### ISSUE TITLE
How to display WeekNumbers in md-datepicker?

### ISSUE THREAD

**Issue by tahaerden** [angular/material#10003]
I'm using the following config:

```js
app.config(function($mdDateLocaleProvider) {
    // Can change week display to start on Monday.
    $mdDateLocaleProvider.firstDayOfWeek = 1;

    $mdDateLocaleProvider.parseDate = function(dateString) {
      var m = moment(dateString, 'DD.MM.YYYY', true);
      return m.isValid() ? m.toDate() : new Date(NaN);
    };

    $mdDateLocaleProvider.formatDate = function(date) {
      return moment(date).format('DD.MM.YYYY');
    };

    $mdDateLocaleProvider.weekNumberFormatter = function(weekNumber) {
      return 'Week' + weekNumber;
    };
  });
```

And here is my datepicker:

```html
 <md-input-container>
                  <md-datepicker name="startDate" ng-model="startDate" placeholder="{{'startDate' | translate}}"  required></md-datepicker>
                  <div class="help-block" ng-messages="startDate.$error">
                    <div ng-messages-include="/components/error-messages.html"></div>
                  </div>
 </md-input-container>
```

Now I can see the weekNumber variable is working on my console. But how can I display it inside the calendar? I couldn't find an option for this on the doc.

**Comment by topherfangio** [comment]
Any chance you can turn this into a Codepen so we can play with it and try to provide a solution?

**Comment by tahaerden** [comment]
Hello @topherfangio ,

Sorry, it's been 2 months since I asked this as some other questions. I dropped using angular material later on. Unfortunately I don't have time to create a demo for this now.

But maybe if someone else also needs this functionality, this post might be useful.

**Comment by gretschann** [comment]
@topherfangio maybe this can help starting
http://codepen.io/alexwunder/pen/VpGpNN

i am on the same problem now. Trying to show week numbers

**Comment by topherfangio** [comment]
@tahaerden @gretschann The current `<md-datepicker>` does not have an option for showing the week number within the calendar itself. The `weekNumberFormatter` is used only for ARIA and screen reader support.

Since it's not in the [spec](https://material.io/guidelines/components/pickers.html#pickers-time-pickers), do you have a screenshot of what you're attempting to accomplish?

**Comment by gretschann** [comment]
@tahaerden sure, here is the my first attempt

![week-datepicker](https://cloud.githubusercontent.com/assets/12372687/24537734/c503518a-15e4-11e7-9af3-b6e21e7b6832.jpg)

**Comment by GauSim** [comment]
@gretschann looks awesome would like to see that coming with isoWeek support 👍

**Comment by topherfangio** [comment]
So, this is definitely very hacky, but I've created a quick example of how you might achieve this.

http://codepen.io/topherfangio/pen/YZoNVY

Unfortunately, as you can see in the demo, since we're appending these after the fact, it's wider than the virtual repeat is expecting and it's cutting off some of the days on the right. I'm not 100% sure how best to fix that, so if you could somehow absolute position them sortof like what your picture shows (maybe using mdPanel), that might work better so you don't modify the existing calendar object.

**Comment by MoeFahmy** [comment]
+1

**Comment by Splaktar** [comment]
We have no plans to add an option to visually display the week number on the calendar.
