### ISSUE TITLE
mdContactChips: add support for md-add-on-blur

### ISSUE THREAD

**Issue by Frank3K** [angular/material#10008]
**Actual Behavior**:
 -  `What is the issue? *` The `md-contact-chips` component does not have support for `md-add-on-blur`.
 -  `What is the expected behavior?` When using a `md-contact-chips` component with the `md-add-on-blur` attribute, the 'selected' match is added when the component is blurred.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` Demo of the `md-chips` component with `md-add-on-blur`: [codepen](https://codepen.io/anon/pen/woGzBv). Demo of the `md-contact-chips` component lacking the `md-add-on-blur` functionality: [codepen](https://codepen.io/anon/pen/xRVEbW).
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chromium
 -  `Browser Version: *` 53
 -  `OS: *` Ubuntu
 -  `Stack Traces:`

Related issues: 

- issue for `md-chips` component: #3364 
- PR implementing the feature for `md-chips` component: #9095. 
- the need for support for the `md-contact-chips` was raised [earlier](https://github.com/angular/material/pull/9095#issuecomment-240880260).

**Comment by Splaktar** [comment]
I have done some testing and reviewed the proposed behavior here. Currently typing the first part of a contact, using arrow keys to select a contact, and hitting tab will add that contact card.

It's not clear to me that, when using the mouse, clicking away from the menu should cause the currently focused contact to be added as a chip. This behavior makes a little more sense with basic chips, but it's not clear to me that this is good UX when used with autocomplete (like contact chips).

I have not been able to find this add on blur functionality detailed in the Material Design spec. The [Search Pattern](https://material.io/guidelines/patterns/search.html) guidelines discuss focus but never indicate any case where removing focus would cause a search to be run. The [Chips Guidelines](https://material.io/guidelines/components/chips.html) briefly cover focus, but never blur.

For now, I am going to close this as "not core" since it doesn't seem to be part of the spec. I am open to re-opening this should someone be able to put together a solid argument describing a use case for this where the UX is of high quality or if someone can find this add on blur behavior detailed in the Material Design spec.
