### ISSUE TITLE
input: no error shown for ng-messages until blur

### ISSUE THREAD

**Issue by nmichaud2** [angular/material#10020]
**Actual Behavior**:
 -  No error shown for an input until the input is touched
 -  The error should be shown even when it is not yet touched

**CodePen** (or steps to reproduce the issue): *
https://material.angularjs.org/latest/demo/input

In the error section, click on the description input and erase the content. No error is shown until I blur out of the field. I don't have any indication that the field is required until it is touched, which seems weird to me from an ux standpoint. 

**Angular Versions**: *
 -  Angular Version:
 -  Angular Material Version: 1.1.1

**Additional Information**:
 -  Browser Type: Chrome
 -  Browser Version: 54
 -  OS: Ubuntu
 -  Stack Traces:

**Comment by manish2535** [comment]
- Shouldn't your title be "No error shown for md-input-container/input until they un-selected"?
- The reason that particular input field is not showing a required symbol or an '*' is because it has the md-no-asterisk directive being used.
- I think what we have is good from a UI perspective because if what you are saying is done then you will see an error message as soon as you tab into or click on an empty input field that is required. The current implementation allows the user to do something with the input before an error is displayed. The blur event is one such event that will tell Angular Material for sure that the user had a chance to input something but opted not to.

**Comment by nmichaud2** [comment]
I agree with your last point when we are talking about a form that the user has not completed yet. 

However, if the form is already completed when entering the page, we don't want the user to start deleting the content of a field that is required. You are also right that the '*' would help understand that the field is required, but it is not as clear an error message.

**Comment by Splaktar** [comment]
There are differences between how `ng-messages` are triggered between AngularJS (input invalid) and AngularJS Material (touched and invalid). 

You can change `md-input-container` to work like AngularJS by using `md-is-error` (i.e. ` md-is-error="projectForm.description.$invalid"`). [This demo](https://codepen.io/Splaktar/pen/pZjQvm?editors=1010#0) demonstrates this.

The docs for this are found [here](https://material.angularjs.org/latest/api/directive/mdInputContainer#attributes).
