### ISSUE TITLE
Is there a way to show dots in md-slider by default?

### ISSUE THREAD

**Issue by alexliubj** [angular/material#10057]
I want to show dots even before I slide them, I mean the unit indicators.

`<md-slider flex md-discrete ng-model="tool.ToolComplexity" 
                                   step="1" 
                                   min="1" 
                                   max="5" 
                                   aria-label="rating">
                        </md-slider>`

**Comment by Splaktar** [comment]
Showing the `ticks` all of the time isn't part of the [Material Design Spec](https://material.io/guidelines/components/sliders.html#sliders-discrete-slider).

This isn't possible to do with CSS since we use Canvas for drawing the ticks to avoid performance issues when there are hundreds of ticks. 

I think that you could use a directive to override some of the `md-slider` behavior to call `redrawTicks()` on initialization and avoid calling `clearTicks()` on blur.
