### ISSUE TITLE
mdSelect: items duplicates when using ng-selected

### ISSUE THREAD

**Issue by rozkerim** [angular/material#10068]
**Actual Behavior**:
 -  `What is the issue? *`
When i used md-select with ng-selected, object items duplicates. i couldn't reproduce this issue for string type. I took data from network and i tried to give this data to md-select initially. And if i remove the object from selectbox ,the initial data remains forever.
 -  `What is the expected behavior?`
I expect the model array contains each object at most 1 times.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
http://codepen.io/rozkerim/pen/PbJVbW?editors=1011
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` v1.5.8
 -  `Angular Material Version:` v1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *`Version 54.0.2840.99 m
 -  `OS: *`Windows 8
 -  `Stack Traces:`

----
I found this solved issue https://github.com/angular/material/issues/1643 but the code has changed in two years.

**Comment by bradrich** [comment]
In your controller you have created a method called `initiallyExists`. This functionality can actually be controlled via Angular's core. Use the attribute `ng-model-options="{ trackBy: '$value.id' }"` on your `md-select` element. This tells the select to make sure that the `ng-model` values compare themselves accurately to the repeated nested options.

Please see http://codepen.io/bradrich/pen/KNyKYp?editors=1010 in order to get an idea how this works. Also see the `ng-model-options` Angular documentation: https://docs.angularjs.org/api/ng/directive/ngModelOptions.
