### ISSUE TITLE
Do not load theme styles if theming is disabled

### ISSUE THREAD

**Issue by Remco75** [angular/material#10096]
I am building an app where file size does matter. And bundles with AngularJS Material tend to be pretty big, so any decrease is welcome. 
Since I have a pretty limited color set I don't need theming and I disabled it with  `$mdThemingProvider.disableTheming();`

This helps, but there are still a lot of css-theme related rules present in the bundle. I would expect them to be removed.

Or am I missing something?
**CodePen** (or steps to reproduce the issue): *
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.9
 -  `Angular Material Version:`1.1.1

**Additional Information**:
 -  `Browser Type: *` chrome
 -  `Browser Version: *` latest
 -  `OS: *` macOs sierra

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
We have a helper library, [material-tools](https://github.com/angular/material-tools), for helping fine tune your bundle size.

If there are some specific CSS rules that you would expect to be removed via `$mdThemingProvider.disableTheming();`, but they are still there, I would be happy to investigate, given more details.

Additionally, I doubt that this issue is still relevant 1.5 years later, but if file size or load time are critical, then I would suggest moving to [Angular Material](https://material.angular.io/) (instead of this library, AngularJS Material for AngularJS 1.x) at this time.

If you already have an AngularJS Material app and want to migrate via ngUpgradeLite, you can check out my recent post on this topic [here](https://groups.google.com/forum/?pli=1#!topic/ngmaterial/9dgqZG2e13o).

There was also a [recent post](https://blog.angular.io/migrating-to-angular-fc9618d6fb04) on the Angular blog about upgrading from AngularJS to Angular.
