### ISSUE TITLE
input: adding an input to an invalid form, when using with ng-repeat, causes new input to be marked invalid incorrectly

### ISSUE THREAD

**Issue by AbijeetP** [angular/material#10146]
**Actual Behavior**:
 -  `What is the issue? *`
     Adding more md-input when there are md-input's with errors, automatically makes the new input invalid.
 -  `What is the expected behavior?`
    The newly added md-input should not be marked as invalid, even if the previous one has errors.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/PbXoBa?editors=1010
 -  `Details:`  Press submit, then click on add row. You'll notice that the newly added md-inputs also have errors.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Tested on all Chrome versions
 -  `Browser Version: *` 52.x
 -  `OS: *` Windows and Linux
 -  `Stack Traces:` ---

**Comment by Splaktar** [comment]
I believe that this is just due to the submitted state of the form. If you reset the form and add inputs, they don't get validated. But when the form is marked as submitted, adding new inputs causes them to get immediately validated. [This updated CodePen](https://codepen.io/Splaktar/pen/gOarmyv?editors=1010) includes a reset button to demonstrate this.
