### ISSUE TITLE
tabs: rtl/ltr support not working

### ISSUE THREAD

**Issue by Avishaidev** [angular/material#10156]
What the right way to config rtl support for md-tabs
Please provide an answer with example code.
I am already tried any solution i found around the web
Please H-E-L-P

**Comment by mrhammadasif** [comment]
+1

**Comment by ThomasBurleson** [comment]
We will have much broader support for LTR features after the v1.1.2 release.

**Comment by anilk533** [comment]
**RTL direction for material tabs not working.**
here is the issue.
https://codepen.io/djidel/pen/NpMpmY

please let me know how to solve

thank you

**Comment by marosoft** [comment]
Please find more info and a workaround in #11016

**Comment by Splaktar** [comment]
I've updated @anilk533's [CodePen](https://codepen.io/Splaktar/pen/MBrMeQ?editors=1010#0) to show the supported way to do this with AngularJS Material. We only support applying `dir` to the body element, i.e. `<body dir="rtl">`.

https://github.com/angular/material/issues/11016#issuecomment-402551370 has some details about valid ways to configure `dir`, but that issue is currently waiting for more feedback from the community before any implementation is started.
