### ISSUE TITLE
md-list-item: Text with opacity < 1 within md-list-item does not fire ng-click.

### ISSUE THREAD

**Issue by Grantismo** [angular/material#10169]
**Actual Behavior**:
 -  `What is the issue? *`Clicking on text with opacity < 1 in md-list-item does not fire ng-click.
 -  `What is the expected behavior?` Clicking on text with opacity < 1 should fire click event.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`http://jsfiddle.net/2f6qscrp/215/
 -  `Details:`Clicking directly on text (within the bordered box in this demo) with opacity < 1 within md-list-item doesn't trigger ng-click. Clicking outside the text will still fire the ng-click. Changing the opacity to 1 returns to standard behavior.

**Angular Versions**: *
 -  `Angular Version:` 1.X
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *`Chrome
 -  `Browser Version: *`Version 55.0.2883.87 (64-bit)
 -  `OS: *`Goobuntu
 -  `Stack Traces:`

**Comment by clshortfuse** [comment]
Wow, this is a weird one!

http://jsfiddle.net/2f6qscrp/221/

It seems any opacity value change allows the inner item to be clicked.

**Comment by clshortfuse** [comment]
This actually isn't an error on our code but one of the many joys of CSS. When you change an element's opacity it pops it to a different display stack (aka 3D rendering). Use `pointer-events: none` when you change the object's opacity. 

For this reason, it's sometimes better to color's alpha value instead of an element's opacity (ie: `color: rgba(0,0,0,0.20);`)
