### ISSUE TITLE
md-autocomplete > md-input-maxlength > user input restriction

### ISSUE THREAD

**Issue by shreeshkatyayan** [angular/material#10173]
**Actual Behavior**:
 -  `md-input-maxlength doesn't restrict user input`
md-input-maxlength currently sets $valid as false. It should be restricting user input to the <integer> value as well to avoid additional workarounds.

**Angular Versions**: *

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
`md-input` with `md-maxlength` does not restrict input when it goes beyond the `maxlength` specified. It just marks the form as invalid and displays the character count (I.e. 5/3) plus any `ng-messages` that you have setup. 

Here's an example [CodePen](https://codepen.io/Splaktar/pen/zRMBwP?editors=1010).
Note that `md-char-count` doesn't show currently for autocomplete due to https://github.com/angular/material/issues/9419.

We have no plans to block user input after `maxlength` is reached.
