### ISSUE TITLE
select(multiple): not working with ng-if

### ISSUE THREAD

**Issue by hishamkaram** [angular/material#10214]
**Actual Behavior**:
 -  `What is the issue? *`
md-select not working with ng-if 
 -  `What is the expected behavior?`
ng-model containing selected values
**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
[Code](http://codepen.io/anon/pen/rjNggb#anon-login)
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
`v 1.5.9`

 -  `Angular Material Version:`
`v 1.1.1`
**Additional Information**:
 -  `Browser Type: *`
chrome
 -  `Browser Version: *``55.0.2883.87 m (64-bit)`
 -  `OS: *` `windows 10`
 -  `Stack Traces:`

----

**Comment by hishamkaram** [comment]
i tested it with angular v1.6.1 too

**Comment by hishamkaram** [comment]
@ThomasBurleson

**Comment by Splaktar** [comment]
It was hard to figure out what "not working" meant and which `ng-if` was in question since the CodePen had two. However, this appears to have just been an issue with [ng-if](https://docs.angularjs.org/api/ng/directive/ngIf) creating a new scope. I updated [the CodePen](https://codepen.io/Splaktar/pen/JjYRmzb?editors=1010) to use Controller as syntax and the issue was resolved.
