### ISSUE TITLE
Support for Hijri or Jalali or other international calendar in datepicker

### ISSUE THREAD

**Issue by araselahi** [angular/material#10211]
I think making dateUtil.js injectable, would provide calendar support functionality for Hijri or Jalali or other international calendars in datepicker. Adding fromGregorian and toGregorian date functions to $mdDateLocale service may provide more abstract solution. These functions could be consequently used in dateUtil.js to provide localized date calculation. Currently $mdDateLocale just provide messages, formatters, and parsers for date internationalization but not date conversion.

I volunteer to produce dateUtil or $mdDateLocale for Hijri or Jalali. Please help me how.

**Comment by araselahi** [comment]
angular/material2#2519
Support for Hijri or Jalali or other international calendar in datepicker #2519

**Comment by Splaktar** [comment]
It looks like there is some support for this in Angular Material. We don't have the resources to investigate or support this in AngularJS Material.

**Comment by kasun90** [comment]
Can you please direct me to the api where we can input a custom calendar?

**Comment by araselahi** [comment]
@kasun90 it is on AngularMaterial branch not AgularJsMaterial:
[https://github.com/angular/components/issues/2519](url)

**Comment by Batoul-Ammar** [comment]
It was surprisingly supported by angular material since they support localization you can find that on their documentation 
[datepicker-locale](https://material.angular.io/components/datepicker/examples#datepicker-locale)

The only issue I have faced is that I have to discover the right local to generate **Hijri dates** 'ar-sa'

`this._adapter.setLocale('ar-sa');`
