### ISSUE TITLE
mdPanel vertical boundaries

### ISSUE THREAD

**Issue by scriptsure** [angular/material#10225]
**Actual Behavior**:
 -  `What is the issue? *`
IF THE PANEL IF VERY LARGE IT WILL BE CONTAINED ON THE BOTTOM OF THE Y AXIS... BUT AT THE TOP IT RUNS OFF THE PAGE. IT DOES NOT RESPECT THE PARENT CONTAINER SIZE AT THE TOP.

IF THIS IS EXPECTED BEHAVIOR, THEN HOW CAN WE OVERRIDE AND HAVE THE TOP OF Y AXIS RENDER JUST AS THE BOTTOM OF THE Y AXIS?
 

**CodePen** (or steps to reproduce the issue): *
 http://codepen.io/scriptsure/pen/vydYGK 

CLICK SELECT MENU BUTTON

**Angular Versions**: *
 -  `Angular Version:` 1.5
 -  `Angular Material Version:` MASTER

**Additional Information**:
 -  `Browser Type: *` CHROME
 -  `Browser Version: *`
 -  `OS: *`  WINDOWS
 -  `Stack Traces:`

**Comment by ThomasBurleson** [comment]
@scriptsure - I just realized that this appears to be the same issue that you filed with #8636.
And I believe @ErinCoughlan  provided reasonable workarounds. How is this issue different from that one?

**Comment by scriptsure** [comment]
@thomasburleson yeah very different case. That one was really around mobile issue where I opened the panel and wanted it to open full screen with margin and a scrollbar. This case is causing an issue on desktop where the panel is riding off the top of the page. There have been many changes around placement of the panel. It seems that the changes have resulted in the panel being perfectly placed on the bottom of the parent container. But the top has not been addressed. Just as a use case why would we want that to ever happen?  I can't set a fixed height in our particular case. I of course tried a lot of CSS fixes but none seemed to work. Probably this is due to the recent placement changes that have been added to MD. Does this make sense?

**Comment by ErinCoughlan** [comment]
@scriptsure I believe the key issue here is that the height of your list is larger than the height of the viewport, which causes it to be rendered off screen (either on the top or the bottom). In order to calculate position, the panel needs to know the height and width of what it is rendering.

For some technical background, the panel uses `position:fixed`. It was not possible to use `position:relative` or `position:absolute` as it would require moving through the entire DOM to find the chain of parent containers and their offsets, then keeping track of that to find the correct offset from the component that opened the panel. As you can imagine, this would be incredible intensive calculations and would hurt performance to the point of being unusable as it's very possible and common for the closest parent to be document.body and for either to be deeply nested. (Removing relative positioning entirely would be the only solution to this, but that would mean panel wouldn't fit your use case or many others in ngMaterial.)

The reason it's on the bottom and not the top is simply because the panel tries to fit in the viewport, and upon failing in all positions, just goes with the last choice (bottom in this case). 

As long as the panel height is less than the viewport, you can position it however you want and then scroll the content. If this is true, the extra checks for positioning can be performed successfully and the panel will always be on screen, which solved some other issues users were having.

The panel API should not be responsible for changing the height of what it is rendering. That's too specific for such a low-level service and could have unwanted side effects for users who perhaps didn't want their content cut in half. We also don't know how to add scroll bars to arbitrary content, again without side effects. That's why both of these are left up to the user.

**Comment by bradrich** [comment]
@scriptsure With all of that being said, I think that your best bet would be to confine your list to an element that has max-height constraint and a scrollable overflow. This would allow you to keep it from interfering with the height of viewport. It would also not be difficult to determine the viewport height and set the max-height of your list to something just shy of it. 

Since this has been determined to be the proper functionality for the mdPanel API, I am going to close this issue.
