### ISSUE TITLE
Grid List View Rendering Problem  (PLEASE HELP!!!)

### ISSUE THREAD

**Issue by beaubarbour** [angular/material#10316]
We are using the Grid-list to display an infinite-scroll array of cards.

The problem occurs, at load, before the list is rendered correctly, it displays all the cards in a 'pile' in the top left corner for a split second.

All of the feedback we've received, notes that this makes the whole system seem flimsy.

Is there any fix for this? 

Thanks in advance!  It's a great framework!

**Comment by beaubarbour** [comment]
Apparently this problem only exists in Chrome and is not present in Safari.

**Comment by graphefruit** [comment]
As a work arround maybe try to display the cards as "visible:hidden"?
After that:
```
setTimeout(function()
{
setvisible()
},50);
```
Maybe it helps so far.

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'will not support' category for one or more of the following reasons:

*  Issue has a reasonable workaround
*  Issue doesn't have a demo or reproducible case available
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests to resolve this issue are encouraged! Note, however, that Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
