### ISSUE TITLE
datepicker: with a 'required' attr triggers incorrect error state when setting date

### ISSUE THREAD

**Issue by Phr33d0m** [angular/material#10360]
**Actual Behavior**:
 -  `What is the issue? *` Appending `required` to mdDatepicker and setting the date dynamically triggers an incorrect error state, if you set the date again the error state is removed.
 -  `What is the expected behavior?` Not to trigger the 'red line' when setting a valid date on a `required` mdDatepicker

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/KaRzNX
 -  `Details:` Click the button once to show the issue, click it again and the issue disappears - this happens only the first time, ever after if you click the button 100 times the error doesn't show up.

**Angular Versions**: *
 -  `Angular Version:` 1.6.1
 -  `Angular Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

**Comment by Splaktar** [comment]
I can [reproduce this](https://codepen.io/Splaktar/pen/WNQBZJp?editors=1010) in `1.1.22`. This is also an issue on [master](https://codepen.io/Splaktar/pen/pojmWxp?editors=1010).

It appears that the `md-datepicker-invalid` class is getting applied to the `<div>` with the `md-datepicker-input-container` class. This is what causes the red line. 

However, all of the classes `ng-pristine _md-datepicker-has-triangle-icon ng-isolate-scope ng-valid-mindate ng-valid-maxdate ng-valid-filtered ng-valid-valid ng-touched ng-not-empty ng-valid ng-valid-required` on the `md-datepicker` appear to be correct.

The problem appears to be caused by this line
https://github.com/angular/material/blob/3d5ff5db56d3b84b2c7d813886d13ef831b7a295/src/components/datepicker/js/datepickerDirective.js#L667

Where `this.ngModelCtrl.$valid` is false on the first update of the `ng-model`.

This is because `DatePickerCtrl.onExternalChange` is called from `ngModelCtrl.$formatters` prior to `$render` and `$validate` being called.
