### ISSUE TITLE
$mdSticky: optional browserStickySupport

### ISSUE THREAD

**Issue by vladimir-barsuchenko** [angular/material#10383]
My goal is different styles for `.md-sticky-clone`. Plus I need to hide it and show on scroll event without touching original sticky element.

My idea is to make `browserStickySupport` optional

and change 

https://github.com/angular/material/blob/master/src/components/sticky/sticky.js#L74-L81

to

```
function MdSticky($mdConstant, $$rAF, $mdUtil, $compile) {
  
  /**
   * Registers an element as sticky, used internally by directives to register themselves
   */
  return function registerStickyElement(scope, element, stickyClone, stickySupport) {
    var browserStickySupport = angular.isBoolean(stickySupport) 
      ? stickySupport && $mdUtil.checkStickySupport()
      : $mdUtil.checkStickySupport();
```

Can provide PR

My current workaround is `$mdUtil.checkStickySupport = () => false;` in `.run()`

**Comment by Splaktar** [comment]
If I understand this properly, you want to leverage the `$mdSticky` sticky capabilities even when the browser supports `sticky` positioning and the reason is that you want to use this to create some custom sticky behaviors.

If we ever [redesign the $mdSticky service](https://github.com/angular/material/issues/9361), then we plan to depend even more upon the native browser capabilities and remove move of our custom implementation. That might conflict with these proposed changes.

I don't think that this is a common use case, so I'm hesitant to add support for this. It's likely best if you just forked or created a custom implementation of the `$mdSticky` service for your project.
