### ISSUE TITLE
list: list-item containing md-icon does not consistently align contents 

### ISSUE THREAD

**Issue by AmandaFoster** [angular/material#10382]
**Actual Behavior**:
 -  `What is the issue? *` When a plain `md-list-item` contains an `md-icon` followed by a `span` or a `div` (even if marked with `md-list-item-text`), there is no flex sizing applied to the text element which causes it not to take up the full width. The list items end up aligned to the center for most cases, and the right for clickable list-items.
 -  `What is the expected behavior?` Plain `md-list-item`s should behave consistently with those marked with `md-2-line` or `md-3-line` as well as those whose icon is marked with `md-avatar`.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/amandabot/pen/mRGRrJ
 -  `Details:` Shows a working example, non-working examples, and some potential fixes/workarounds

**Angular Versions**: *
 -  `Angular Version:` 1.5.10
 -  `Angular Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 55.0.2883.87
 -  `OS: *` Windows 10
 -  `Stack Traces:` N/A

----
This is related to this [issue](https://github.com/angular/material/issues/6084), but it is closed and the title inaccurate.

```js
//aligns properly
<md-list-item>
  <img src="my-avatar.png" class="md-avatar">
  <span>Alan Turing</span>
</md-list-item>

//does not align properly (this is from the docs)
<md-list-item>
  <md-icon class="md-avatar-icon" md-svg-icon="avatars:timothy"></md-icon>
  <span>Timothy Kopra</span>
</md-list-item>

//aligns properly
<md-list-item class="md-2-line">
  <md-icon md-font-icon="fa-search" class="fa" aria-hidden="true">
  </md-icon>
  <div class="md-list-item-text">
    <h3>single line in div</h3>
    <p>second line</p>
  </div>
</md-list-item>

//does not align properly
<md-list-item>
  <md-icon md-font-icon="fa-search" class="fa" aria-hidden="true">
  </md-icon>
  <div class="md-list-item-text">
    <h3>single line in div</h3>
  </div>
</md-list-item>
```

Adding these CSS classes fixes the issue, but there appear to be several variations that might need to be updated in the stylesheet:

```css
md-list-item md-icon ~ span,
md-list-item .md-list-item-text, 
md-list-item > .md-no-style .md-list-item-text {
      -webkit-box-flex: 1;
      -webkit-flex: 1 1 auto;
              flex: 1 1 auto;
      margin: auto;
      text-overflow: ellipsis;
      overflow: hidden; }
```

Alternatively, there are a couple of workarounds that produce the desired effect without changing the library. Maybe the docs could be updated to reflect this?
```js
<md-list-item>
  <md-icon md-font-icon="fa-search" class="fa" aria-hidden="true">
  </md-icon>
  <p class="md-list-item-text">
    single line in p
  </p>
</md-list-item>
```
```js
<md-list-item>
  <md-icon md-font-icon="fa-search" class="fa" aria-hidden="true">
  </md-icon>
  //the flex=100 could be applied to a sole span as well
  <div class="md-list-item-text" flex=100>
    <span>single line in div with flex 100</span>
  </div>
</md-list-item>
```

**Comment by Splaktar** [comment]
Here's an [updated CodePen](https://codepen.io/Splaktar/pen/xJjjKm?editors=1100#0) with the proper layout and alignment.

### Please note the following
- As described in [the md-list-item docs](https://material.angularjs.org/latest/api/directive/mdListItem) single line list items should contain `p` and `span` elements. `div` is only used for the 2 and 3 line list items. If you use a `div` in a single line list item, the layout won't work well.
- At the bottom of the page, there is a section on [DOM modification](https://material.angularjs.org/latest/api/directive/mdListItem#dom-modification) that describes what happens when a list item is clickable.
- Please use CSS to style instead of wrapping list item text in `h3` tags

The [list demo page](https://material.angularjs.org/latest/demo/list) contains a wide variety of different options for icons, checkboxes, etc.

You do call out one issue in the docs that we need to fix. `md-avatar-icon` is meant to be used with icons, not images. So the following
```html
   <md-list-item>
     <md-icon class="md-avatar-icon" md-svg-icon="avatars:timothy"></md-icon>
     <span>Timothy Kopra</span>
   </md-list-item>
```
Should be
```html
   <md-list-item>
     <md-icon class="md-avatar-icon" md-svg-icon="social:person"></md-icon>
     <span>Timothy Kopra</span>
   </md-list-item>
```
and I'll fix that.

The [updated CodePen](https://codepen.io/Splaktar/pen/xJjjKm?editors=1100#0) includes the use of both `md-avatar` and `md-avatar-icon`.
