### ISSUE TITLE
md-con

### ISSUE THREAD

**Issue by darxx** [angular/material#10397]
**Actual Behavior**:
 -  `What is the issue? *` - Can`t load svg from server response
 -  `What is the expected behavior?` not using #.svg to be able load dynamic icon from back end

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` Can`t use code pen for this example
 -  `Details:`

Not working

```
 <md-icon md-svg-src="api/collaborator/category
/d7069958-6717-402e-bdde-af5d5ebc7246/document
/ec63cde3-8c8c-4ed4-8710-c6ff679b1a6b/icon/ad857acc-2b1b-452d-8202-01703f2fe2d3"></md-icon>
01703f2fe2d3"></md-icon>
```
Working
```
 <md-icon md-svg-src="api/collaborator/category
/d7069958-6717-402e-bdde-af5d5ebc7246/document
/ec63cde3-8c8c-4ed4-8710-c6ff679b1a6b/icon/ad857acc-2b1b-452d-8202-01703f2fe2d3#.svg"></md-icon>
```

**Angular Versions**: *
 -  `Angular Version:` 1.5.6
 -  `Angular Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` all
 -  `Browser Version: *` 
 -  `OS: *` all
 -  `Stack Traces:`

Issue related to 
```
  var urlRegex = /[-\w@:%\+.~#?&//=]{2,}\.[a-z]{2,4}\b(\/[-\w@:%\+.~#?&//=]*)?/i;
```

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'will not support' category for one or more of the following reasons:

*  Issue has a reasonable workaround
*  Issue doesn't have a demo or reproducible case available
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests to resolve this issue are encouraged! Note, however, that Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
