### ISSUE TITLE
md-button IOS double Click | Angular 1.5.7

### ISSUE THREAD

**Issue by swapnil001** [angular/material#10416]
**Actual Behavior**:
 
I am using md-button `<md-button md-no-ink ng-click="showSignUpModal('signup1');" class="md-button md-primary md-raised btn-signup"> TEST </md-button>`. On iOS devices I have to tap twice to get ng-click function work. What is the work around for this to fire in 1 tap only? Thanks.

**Angular Versions**: *
 1.5.7

**Comment by supportQuadra** [comment]
+1

**Comment by LarsSaalbach** [comment]
@swapnil001 
This is a common IOS-Problem, the problem is that first the :focus/:hover event is fired in CSS, that cancels the click event, and the second click actual fires the click event.

What can you do?
- Disable :focus/:hover other css selectors.
- Write a custom directive (like I did) which handels the click event yourself `own-click-event=showSignUpModal()` e.g.

**Comment by enri90** [comment]
+1

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. A CodePen demo of the issue is **required**.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.

This could be a number of different things, but there isn't enough detail here to determine which. You may want to skip click hijacking on mobile, [details here](https://material.angularjs.org/latest/api/service/$mdGestureProvider).
