### ISSUE TITLE
toolbar: md-scroll-shrink does not work if content is scrolled too soon after page load

### ISSUE THREAD

**Issue by marshall007** [angular/material#10413]
**Actual Behavior**:
 -  `What is the issue?` Specifically in conjunction with `ng-cloak`, but also in many other cases, `md-scroll-shrink` does not work if the sibling `md-content` is scrolled within 5 seconds of loading the page.
 -  `What is the expected behavior?` It should work as soon as the DOM is loaded.

**CodePen** (or steps to reproduce the issue):
 -  The existing toolbar [Scroll Shrink demo](https://material.angularjs.org/1.1.3/demo/toolbar) reproduces this behavior so long as you attempt to scroll the `md-content` within 5 seconds.

**Angular Versions**: 
 -  `Angular Version:` 1.6.1
 -  `Angular Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type:` Chrome
 -  `Browser Version:` 56
 -  `OS:` MacOS 10.12.2

**Comment by mahmoud-kayali** [comment]
I have faced the same issue with ng-cloak, I have managed to solve it by doing the following:

1. Remove `ng-cloak`
2. Set the style to `display:none`
3. added a class to my css called force display 
`.force-display {
    display: block !important;
}`
4. on the same element add the attribute `ng-class="{'force-display':true}"`

What this does is that it will hide the element by default, once angular is loaded and initialized it will set the class force-display to the element which will override the display:none style because !important exists

hope this workaround helps anyone facing the same issue

**Comment by Splaktar** [comment]
I can reproduce this in 1.1.5 as well: https://material.angularjs.org/1.1.5/demo/toolbar

**Comment by mckenzielong** [comment]
When the scroll shrink is first enabled, it invokes updateToolbarHeight using _$mdUtil.nextTick_ (L226):

`$mdUtil.nextTick(updateToolbarHeight, false);`

This actually sets the toolbar height to _zero_.  This causes the _y_ calculation in onContentScroll to be incorrect, always returning zero until the first debounced call to updateToolbarHeight triggers.  It seems like _nextTick_ was used to allow the toolbar time to be rendered / laid-out / have dimensions.

One work around would be to reduce the debounce time at L114 to something smaller than 5000:

`var debouncedUpdateHeight = $mdUtil.debounce(updateToolbarHeight, 5 * 1000);`

I am wondering if something changed in AngularJS related to _timeout_ that has broken _nextTick_?

**Comment by Splaktar** [comment]
@mckenzielong does something like `$timeout(updateToolbarHeight, 10)` or `$timeout(updateToolbarHeight, 100)` fix this as well? 

I've seen cases in the past where `$mdUtil.nextTick` was used but wasn't a good fit since it both defaults to `0ms` and it can be bundled and delayed with other "on tick" changes that the change depends on happening first (then they happen at the same time and issues occur).

**Comment by mckenzielong** [comment]
@Splaktar yes, changing the check in _enableScrollShrink()_ to:

```js
$timeout(updateToolbarHeight, 10, false);
```
does the trick.
