### ISSUE TITLE
backdrop animation does not work if `$rootElement` is `html` tag

### ISSUE THREAD

**Issue by ilovett** [angular/material#10439]
**CodePen** (or steps to reproduce the issue): *

ng-app is defined on the body, backdrop animation is working
https://embed.plnkr.co/AsA8ydhifyVl9kfGZceo/

ng-app is deifned on html, backdrop animation NOT working
https://embed.plnkr.co/PLhfbWJUyvVpijfx5rlp/

I had originally opened this up thinking it was an issue with angular `ngAnimate` over [here](https://github.com/angular/angular.js/issues/15738)

**Angular Versions**: *
 -  `Angular Version:` 1.5.11, 1.6.1
 -  `Angular Material Version:` 1.1.1, 1.1.3

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'will not support' category for one or more of the following reasons:

*  Issue has a reasonable workaround
*  Issue doesn't have a demo or reproducible case available
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests to resolve this issue are encouraged! Note, however, that Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].

**Comment by maxprin** [comment]
Hi there, I'm having this issue and while not a huge deal, it's a bit annoying :) 
Is there a workaround? I need ng-app in the <html> tag.
Thanks in advance!

**Comment by Splaktar** [comment]
@maxprin please open a new issue with a CodePen reproduction.
