### ISSUE TITLE
Two md-tab on the same page..

### ISSUE THREAD

**Issue by anooppvkeloth** [angular/material#10487]
parant tab and child tab must be scrollable with no issues as expected

But child tab is not scrolling its contents..but with mouse its scrolling..but with swipe its not scrolling..

**Comment by henrymana** [comment]
It might be good to follow the requested template if it is an issue... for questions use the google group...

**Actual Behavior**:
 -  `What is the issue? *`
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:`
 -  `AngularJS Material Version:`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by EladBezalel** [comment]
@anooppvkeloth as @henrymana said, this issue doesn't meet our issue standards and completely ignores our template. please in any case this issue is still happens on HEAD open a new issue and provide a codepen with your problem.
