### ISSUE TITLE
Collapsible horizontal navbar on mobile?

### ISSUE THREAD

**Issue by demisx** [angular/material#1050]
Hi. The project looks amazing. I am considering using it for our next product. However, I am having hard time locating some components that are available in Bootstrap. For example, how would I go about implementing the horizontal navbar that self-collapses at given mobile breakpoint? Similar to how your navbar works here https://material.angularjs.org/#/demo/material.components.toolbar when you resize the browser window. I've gone through demos, but couldn't locate this functionality. Thank you.

**Comment by bastienJS** [comment]
@EladBezalel What I do not understand about material design then is why is this guy following google material design and he created something @demisx and I want: http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

But why does angular material design not create something like the above?
I mean the link`s author follows material design by google?!

**Comment by EladBezalel** [comment]
@bastienJS @demisx, google material design spec has been updated two month ago with more components and specs, one of their changes was to define a proper way of menus,
as you can see [here](http://www.google.com/design/spec/components/menus.html), this is what you're looking for
![menu](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7VW5LS2JTQ2puOUE/components_menus_usage3do.png)

that components is called 'phase two of menu' as you can read in #78 which will be on 0.11.

the guy who themed bootstrap to 'material design' has succeeded in his vision of how this should be implemented.

**Comment by bastienJS** [comment]
@EladBezalel  very cool! Ok 0.11 will be after Summer I guess in 3 months :P Anyway it looks promising if its the same as my pasted link I can wait :-)

**Comment by amritanjali** [comment]
i have same issue like @demisx   , i want collaps my tabs in mobile view but i did'nt find any way in angular material design . i am using angular material design in my project. please give some suggetion

**Comment by danger89** [comment]
It's indeed unbelievable that a simple collapsible responsive menu is so difficult to make with Angular 6 + Angular Materials 6.0.1 (in 2018)... [This example on Stackoverflow](https://stackoverflow.com/a/47969586/518879) looks like the best attempt to far.

**Comment by Splaktar** [comment]
@amritanjali http://gdg-x.github.io/boomerang/ demonstrates using the Transform Pattern to change from tabs on desktop to sidenav on mobile. The related source code can be found [here](https://github.com/gdg-x/boomerang/blob/master/index.html). If you want to use the overflow pattern instead of the Transform Pattern, then you can do something similar to what is doing in the overflow example in the slides linked below.

@danger89 this repo and issue is for AngularJS Material, not Angular Material. That said, my presentation on [Create Enterprise UIs That Your Users Will Love](https://docs.google.com/presentation/d/1yXMuzIqlWcF2RRkBgg8B7crQSN4CMtW91d6wBt_QeuE/edit?usp=sharing) covers some of these patterns for Angular Material. The links to the StackBlitz examples are in the speaker notes.
