### ISSUE TITLE
datepicker: cannot set current date in calendar

### ISSUE THREAD

**Issue by sameershaik90** [angular/material#10533]
Actual Behavior:
Not able to set current date. Current date is always set to system's date. Example- If today's date in my system is March 27 2017, this date is circled as today's date in md-datepicker's calendar. I am looking for a way to set current date based on user's time zone.

Expected Behavior:
There should be a way to set current date as per user's preference. 
![datepicker](https://cloud.githubusercontent.com/assets/26721594/24370681/e95dce62-1345-11e7-9d9f-45f0b317c886.PNG)

AngularJS Versions: 
 -  AngularJS Version: 1.6
 -  AngularJS Material Version: 1.1.3

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

It's not clear what you were trying to do without a demo reproducing the issue, but you can take a look at https://material.angularjs.org/latest/api/service/$mdDateLocaleProvider for some guidance.

There were also some issues with `md-datepicker` and `md-calendar` not accepting `ng-model-options` with a timezone defined. The datepicker part of that was solved about a year ago. The calendar part of that should be fixed in `1.1.23`.
