### ISSUE TITLE
radio-button: binding object with ng-model not working with zone.js

### ISSUE THREAD

**Issue by rahulrsingh09** [angular/material#10558]
I am trying to bind radio buttons using ngmodel but it dosen't seem to work.

Template

```
  <md-radio-group>
    <md-radio-button *ngFor="let gender of genders" [(ngModel)]="user.gender"
                     name = "gender" [value]="gender.value"> {{gender.display}} </md-radio-button>
  </md-radio-group>
```

```
public genders = [
    {value:'F',display:'Female'},
    {value:'M',display:'Male'},
  ];

  ngOnInit() {
    this.user = {
      name:'',
      gender:this.genders[0].value,
      role:null,
      theme:this.themes[0],
      isActive:false,
      toggle:this.toggles[1].value,
      topics:[this.topics[1].value]
    }
  }
```
The binding is just now working getting this error in console.

```
ERROR ZoneAwareError {__zone_symbol__error: Error: Uncaught (in promise): Error: No value accessor for form control with name: 'gender'
Error: N…, rejection: ZoneAwareError, promise: ZoneAwarePromise, zone: Zone, task: ZoneTask}
```

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template and includes a CodePen/StackBlitz/GitHub reproduction. This gives the team the information needed to investigate the bug or prioritize the enhancement.

It looks like you were doing something with ng-upgrade since you are using zone.js and Angular Forms with AngularJS Material, but there isn't enough information provided here to investigate the issue.
