### ISSUE TITLE
autocomplete(chips): popup selection list has an invalid default selection when opened the second time

### ISSUE THREAD

**Issue by p4pramod** [angular/material#10573]
**Actual Behavior**:
 -  The md-autocomplete in chips selection is not showing selected index in the auto complete after one chip is added. 

 -  After adding the first chip through autocomplete, when we search another text the suggestion should show nothing as selected unless user uses down arrow on keyboard.

**CodePen** (or steps to reproduce the issue): *
 - this issue can be replicable in the demo of chips page
       https://material.angularjs.org/latest/demo/chips

 -  Go to -Custom Inputs

   then go to "Use md-autocomplete to build an ordered set of chips." section. add Broccoli and then type "C". If possible try adding and deleting the chips. Please verify the selected index of the suggestion box provided by autocomplete.

**Comment by JJTheo** [comment]
I've had the same problem, and I can't find any solutions.
I made this jsFiddle to try a few things : [https://jsfiddle.net/JJTheo/9z34r9rc/2/](url)

**Comment by Splaktar** [comment]
It was a little hard to understand this, but I was finally able to reproduce it. On the appearance of the second popup, an item is selected by default when it should not be.

**Comment by Splaktar** [comment]
I looked into this some more. The item wasn't actually selected. The issue was that `ng-class` was marking it with the `selected` class. It was doing this when evaluating `-1 === 1` and `-1 === 0`, etc to `true`, which appears to be a bug in how `md-virtual-repeat` works with `ng-class`.

I've changed the theming to target the `#selected_option` class instead (new in 1.1.11) and this seems to be working consistently. The PR is #11529.
