### ISSUE TITLE
virtual-repeat: fails to remove conditional class on first render

### ISSUE THREAD

**Issue by marius-klimantavicius** [angular/material#10609]
**Actual Behavior**:
 -  `What is the issue? *`
The rendered elements have incorrect class applied from ngClass. All elements have the same class

 -  `What is the expected behavior?`
ngClass applies (removes) the conditional class.
Only even elements have the class, odd elements have the class removed.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
http://codepen.io/anon/pen/JNKyGv
 
-  `Details:`
Had to use $timeout, because otherwise md-top-index was ignored on codepen. In my production code I use md-start-index with $mdPanel to display the virtual list.

Not sure if Angular.js (ngAnimate) or Angular Material issue:
1. Initial elements (blocks) are created, each run a $digest
1. During the digest ngAnimate invokes addClass to add/remove conditional classes (item-even in my case)
1. ngAnimate adds animation class item-even-add class first
1. Due to specified md-start-index or md-top-index a scroll is performed
1. The index is selected so that when blocks are reused they would have to remove the class
1. An updateBlock_ will do additional digest for the reused blocks
1. A removeClass should be placed into animation queue, however this does not happen because there is already an animation for the node, however it is not connected to $rootNode or body (see https://github.com/angular/angular.js/blob/master/src/ngAnimate/animateQueue.js#L378)
1. The removeClass animation is skipped and the item-even class is not removed.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.4
 -  `AngularJS Material Version:` 1.1.1, 1.13 (haven't tested other)
 
**Additional Information**:
 -  `Browser Type: *` 
Google Chrome and Internet explorer
 -  `Browser Version: *` 
Chrome: 57.0.2987.133
Internet Explorer: 11.0.9600.18618 

Mozilla Firefox (52.0.2) seems to work correctly.
 -  `OS: *` Windows 8
 -  `Stack Traces:`

**Comment by marius-klimantavicius** [comment]
Even/odd styling by using css3 (nth-child) works only to a point - it works but looks visually strange when scrolling.

**Comment by Splaktar** [comment]
I was able to reproduce this on macOS + Chrome with the AngularJS 1.6.6 and AngularJS Material 1.1.5: https://codepen.io/Splaktar/pen/jagJrz

**Comment by Splaktar** [comment]
I verified that changing https://github.com/angular/material/blob/v1.1.10/src/components/virtualRepeat/virtual-repeater.js#L836-L841 to use a `$timeout` of `100` (instead of `$mdUtil.nextTick`) seemed to fix this, but it seemed a little hacky. Using a value of `0` does the same general thing as the existing code and a low value like `1` didn't seem to help.

I looked around for some way to trigger it in a way that was less likely to result in another race condition, but I wasn't able to find anything that would work well.

I'm looking for some feedback on how to move forward with this. 

- Is the workaround to just define the `md-top-index` value after the virtual repeat is visible sufficient?
- Is it worth adding this `100` ms `$timeout` that would affect (in a minor way) all users or virtual repeat?

**Comment by MusicCog** [comment]
> I'm looking for some feedback on how to move forward with this.
> 
>     * Is the workaround to just define the `md-top-index` value after the virtual repeat is visible sufficient?
> 
>     * Is it worth adding this `100` ms `$timeout` that would affect (in a minor way) all users of virtual repeat?

I think that we need a way of reacting to 'actually-has-rendered-this-list' rather than assuming $timeout values - that would then either call scrollToIndex or allow us to.

My data-ng-class (active) gets set multiple times when switching between different lists, which I suspect is exactly the same issue that marius reported.

**Comment by MusicCog** [comment]
Splaktar, can you give us your patch please ?
> Splaktar to use a $timeout of 100 (instead of $mdUtil.nextTick)

I know it's a hack, but might get me started.

**Comment by Splaktar** [comment]
@MusicCog here's a [CodePen](https://codepen.io/Splaktar/pen/JmdoXp) with the `$timeout` patch. Please try this [angular-material-10609.js](https://drive.google.com/uc?export=download&id=19GBfiVyUq0SmUoA_hnjCoA79r8Zx4ZCW) file and let me know if it resolves the issue for you. If it does, I can open a PR.

**Comment by Splaktar** [comment]
@MusicCog was that patch effective? If so, please let me know so that I can create a PR to fix this permanently.

**Comment by Splaktar** [comment]
@MusicCog I'm not sure if you are still interested in or using the above patch, but I never got any feedback about it working or not. I'm going to close this issue, but if you do let me know soon that it was effective then I can re-open and send a PR for the fix.
