### ISSUE TITLE
datepicker: exception when ng-model and md-max-date or md-min-date are the same string

### ISSUE THREAD

**Issue by wcmboy** [angular/material#10627]
**Actual Behavior**:
 -  `What is the issue? *`
md-datepicker directive
ng-model and md-max-date are the same and both are string
when open the month view,it throw error.
 -  `What is the expected behavior?`
throw the exception:TypeError: maxDate.getFullYear is not a function
**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`https://codepen.io/wcmboy/pen/gWmwLv
 -  `Details:`
when you open the day view,you can select a month,and then you will open the month view,you will see nothing.And you open the developer tool,you will see the exception message.

**AngularJS Versions**: *
 -  `AngularJS Version:`1.5.5
 -  `AngularJS Material Version:`1.1.4

**Additional Information**:
 -  `Browser Type: *`chome
 -  `Browser Version: *`57.0.2987.133
 -  `OS: *`macOs Sierra 10.12.4
 -  `Stack Traces:`
TypeError: maxDate.getFullYear is not a function
    at Object.isMonthWithinRange (angular-material.js:30598)
    at CalendarYearBodyCtrl.buildMonthCell (angular-material.js:29911)
    at CalendarYearBodyCtrl.buildCalendarForYear (angular-material.js:29963)
    at CalendarYearBodyCtrl.generateContent (angular-material.js:29871)
    at angular-material.js:29824
    at ChildScope.$digest (angular.js:17073)
    at VirtualRepeatController.updateBlock_ (angular-material.js:24777)
    at VirtualRepeatController.virtualRepeatUpdate_ (angular-material.js:24691)
    at VirtualRepeatController.containerUpdated (angular-material.js:24595)
    at VirtualRepeatContainerController.updateSize (angular-material.js:24122)
----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by adoris** [comment]
same issue here. 
Win10, Chrome 59.0.3071.115
any solution?

**Comment by mhmo91** [comment]
same issue here

**Comment by Splaktar** [comment]
This appears to be caused by just not following the [API documentation](https://material.angularjs.org/latest/api/directive/mdDatepicker).

Parameter | Type | Description
-- | -- | --
*ng-model | Date | The component's model. Expects either a JavaScript Date object or a value that can be parsed into one (e.g. a ISO 8601 string).
md-max-date | Date | Expression representing a max date (inclusive).

While the expression passed into `ng-model` will attempt to be parsed into a `Date` if it is not already a `Date` object, this isn't true for `md-max-date` or `md-min-date`. They require `Date` objects as arguments.

I was able to update the [CodePen](https://codepen.io/Splaktar/pen/wjRORQ?editors=1010#0) to 1.1.9 and pass in a `Date` object for `md-max-date`. This works as expected.
