### ISSUE TITLE
datepicker: fails validation but doesn't update error state (root cause identified)

### ISSUE THREAD

**Issue by zNegative** [angular/material#10646]
`DatePickerCtrl.prototype.handleInputEvent` applies the test `isDateComplete()` against the input string and uses the result to skip model updates, but then updates the error state based solely on the parsed date.

If the `locale.parseDate()` call is customized via `$mdDateLocaleProvider` then it's possible to return a valid date for an input string that doesn't pass `isDateComplete()`, resulting in a silent error and lost data.

Found this by accidentally custom parsing "Dec 2017" into `Date(2017, 11, 1);`

https://github.com/angular/material/blob/e06284aa4745dd7323a872a0a9290fd026747e30/src/components/datepicker/js/datepickerDirective.js#L639

**Comment by 0x4C4A** [comment]
Just hit this too. Can be fixed by adding a custom isDateComplete in the $mdDateLocaleProvider config. This really only needs to be added to the docs, no underlying fixes needed.

**Comment by zNegative** [comment]
I think it's still worth being fixed, it should be a very safe change and may save others from spending time on it in the future.

**Comment by Splaktar** [comment]
We provide an example of customizing this in the [$mdDateLocaleProvider docs](https://material.angularjs.org/latest/api/service/$mdDateLocaleProvider).

The `defaultIsDateComplete` is very naive and it certainly should be overridden if you are using custom parsing:
https://github.com/angular/material/blob/ee7d3faf6c78bfef5c04f3d1aa2809a6d5666d94/src/components/datepicker/js/dateLocaleProvider.js#L224-L240

I'll close this as it appears to be a misconfiguration rather than a bug (and there is no reproduction to demonstrate a bug).
