### ISSUE TITLE
select: update options

### ISSUE THREAD

**Issue by tangb** [angular/material#10645]
Hi

I think I found an issue with md-select when options are refreshed.

Steps to reproduce the issue:
- At loading md-select is filled with options
- A button launches ajax request
- At promise resolving the function refresh all options
Finally md-select seems not updated, user needs to click on it to see changes.

Here a codepen of problem:
https://codepen.io/Tangb/pen/aWLdge
Click on change button, wait at least 3 seconds and click on md-select.

Thank you for all your work :smiley:

**Comment by peio72** [comment]
Answer here:

https://material.angularjs.org/latest/api/directive/mdSelect

"At first one might expect that the select should be populated with "Bob" as the selected user. However, this is not true. To determine whether something is selected, ngModelController is looking at whether $scope.selectedUser == (any user in $scope.users);;

Javascript's == operator does not check for deep equality (ie. that all properties on the object are the same), but instead whether the objects are the same object in memory. In this case, we have two instances of identical objects, but they exist in memory as unique entities. Because of this, the select will have no value populated for a selected user.

To get around this, ngModelController provides a track by option that allows us to specify a different expression which will be used for the equality operator. As such, we can update our html to make use of this by specifying the ng-model-options="{trackBy: '$value.id'}" on the md-select element. This converts our equality expression to be $scope.selectedUser.id == (any id in $scope.users.map(function(u) { return u.id; })); which results in Bob being selected as desired."

**Comment by tangb** [comment]
@peio72 
Dammit I already read that doc before but I could not remember :simple_smile:
Thank you very much for your answer.
