### ISSUE TITLE
content: auto-hiding of address bar on chrome mobile does not work when using md-content

### ISSUE THREAD

**Issue by Remco75** [angular/material#10659]
**Actual Behavior**:
 -  `What is the issue? *`
When using md-content to scroll through content Chrome for android mobile does not hide the adressbar
 -  `What is the expected behavior?`
It should hide the adress bar to create more room.

**CodePen** (or steps to reproduce the issue): *
Create a page with:

- some content on top,
- an md-content element with few 100 rows of content
- if you want, a sticky footer
Open in chrome on android, scroll the page. Basic UX function broken.

**AngularJS Versions**: *
 -  `AngularJS Version:`: 1.5.9
 -  `AngularJS Material Version:`.1.1.4

**Additional Information**:
 -  `Browser Type: *`Chrome
 -  `Browser Version: *`latest
 -  `OS: *`Android
 -  `Stack Traces:`

**Comment by Splaktar** [comment]
If you need this functionality, then I would recommend putting your main content in `<main>` element rather than an `md-content`. `md-content` would be better used for sub-page level scrollable areas in that case.

`md-content` for the main page area should work well with app-like experiences like those provided by PWAs, Ionic, or Cordova apps where you have no address bar.
