### ISSUE TITLE
chips: md-enable-chip-edit no longer accepts an expression

### ISSUE THREAD

**Issue by DeneroWatz** [angular/material#10657]
md-enable-chip-edit works only with static values

We are seeing a regression after upgrading from material 1.1.0 to 1.1.3.

We have a configuration(_$scope.config.modify_) that tells whether the chips should be editable.

In my md-chips, I use _md-enable-chip-edit="{{::config.modify}}"_ but the chips are still editable even if the value is false. If I change it to literal "false", it works.

This is easily reproduceable with the 'Make chips editable' sample provided here - https://material.angularjs.org/latest/demo/chips

In the codepen, when I add _self.editable= false;_ in the controller and mofiy:

_<md-chips ng-model="ctrl.editableFruitNames" readonly="ctrl.readonly" md-removable="ctrl.removable" md-enable-chip-edit=**"true"**></md-chips>_

to

_<md-chips ng-model="ctrl.editableFruitNames" readonly="ctrl.readonly" md-removable="ctrl.removable" md-enable-chip-edit=**"{{ctrl.editable}}"**></md-chips>_

the chips are still editable. Best explained by the below snapshot.

Is there a workaround if it is a bug?

![image](https://cloud.githubusercontent.com/assets/18241620/25911448/821d5c6e-35d1-11e7-906c-2e3214b650b9.png)

**Comment by Splaktar** [comment]
This was due to the change in PR https://github.com/angular/material/pull/9095 that went in 1.1.1. There was an intentional change to only check the editable state once and to change it from a scope binding to an attribute check (which just evaluates if the string is truthy or not).

I can see how this is certainly a breaking change though. Is this something that you would still like to see addressed?
