### ISSUE TITLE
Sowing confusion with the name "angular"

### ISSUE THREAD

**Issue by cogitaria-admin** [angular/material#10766]
This package name should be retired and replaced with an **AngularJS** version.  Likewise the now-incorrect material/angular2 should be simply **angular**.  Seems like some of the core libraries aren't aligned with the recommended naming scheme for Angular packages.  You can imagine that does create a little confusion. 

Thanks!

**Comment by Splaktar** [comment]
Thank you for the feedback. I realize that naming has been a problem for some time now. We've done our best to call out the differences and link to the other repos to help people find the right repo to post their issues.

However, changing this repo's name or the package name is not something that we want to do at this time due to the disruption it would cause to our documentation and users.
