### ISSUE TITLE
How to force the re-flow / re-render of md-grid-list ?

### ISSUE THREAD

**Issue by mikeabeln** [angular/material#10774]
Hi there,

I'm wondering how to force the re-flow or re-rendering of a md-grid-list?

I'm trying to remove a tile in a grid based on breakpoint by changing the colSpan and rowSpan to 0, but the grid still leaves a blank space. I've also tried adding a display:none class to the tile itself but that also leaves a blank space.

There seems to be no method available to re-draw the grid, please explain?

Thanks in advance!

**Comment by henrymana** [comment]
I would post questions on the mailing list... https://groups.google.com/forum/#!forum/ngmaterial

I haven't used it but the "dynamic tiles" example in the demos might be relevant:

https://material.angularjs.org/latest/demo/gridList

One thing you could do is to either remove or filter the tile from your model so that it is not displayed (instead of filtering by doing something custom).

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.

There may be better avenues for troubleshooting or asking for help with your app. These include [Stack Overflow](https://stackoverflow.com/), [Gitter](https://gitter.im/), this project's mailing list or forums, etc.

Please limit GitHub issues to bug reports and feature requests.
