### ISSUE TITLE
md-autocomplete show dropdown only when query is completed

### ISSUE THREAD

**Issue by HimanDev** [angular/material#10787]
My md-autocomplete is dependent on another md-autocomplete. for example my first dropdown is of country and second is states . for the first time when select the country then the second dropdown is populated with corresponding states. 

but the problems starts when i change the country and moves to states dropdown ,initially it shows the previous results and then after http response it refreshes the result.

i want to show the suggestions only when my http call is completed .
can you guys please help me with this

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.5
 -  `AngularJS Material Version:` 1.1.0

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. A CodePen demo of the issue is required. This gives the team the information needed to investigate the bug or prioritize the feature.

There are better avenues for troubleshooting or asking for help with your app. These include [Stack Overflow](https://stackoverflow.com/), [Gitter](https://gitter.im/), the [AngularJS Material forums](https://groups.google.com/forum/?pli=1#!forum/ngmaterial), etc.
