### ISSUE TITLE
ngUpgrade: Angular 4 / zone.js / mdTabs infinite $digest when in hidden container

### ISSUE THREAD

**Issue by ampled** [angular/material#10847]
**Actual Behavior**:
 -  `What is the issue? *`
After setting up hybrid angular 4 / angularjs-development for an application, I noticed that hundreds of timers were being fired every second, triggering $digests with every timer. I managed to find out that the function handleResizeWhenVisible ([tabsController.js](https://github.com/angular/material/blob/master/src/components/tabs/js/tabsController.js#L280)) was being run a whole lot and tried removing md-tabs from the template of an mdSideNav that is hidden (display: none) by default when the application starts, and that caused the inifite timers and $digest-cycles to stop. The timers also stop firing when the tabs are displayed, leaving me to think that somewhere in Angular 4 / zone.js patching of setTimeout causes the tabsController's resizing function to cause an infinite loop of $digests and setTimeouts being fired. Note that this doesn't trigger an angularjs infinite digest error, and the problem only occurs when the application is run as a hybrid.

 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
Plunker:  https://plnkr.co/edit/OtYR2o?p=preview

 -  `Details:`
In this demo the tabs are contained in a hidden div, causing $digests to trigger in a loop. The console outputs every 100th $digest cycle. The timers / $digests stop triggering as soon as the tabsContainer div is shown. In my application the $digests start again when the container is hidden again, but in the demo they don't. Note that for some reason this demo also triggers $digests when moving the mouse around.

**AngularJS Versions**: *
 -  `AngularJS Version:`
1.5.11
 -  `AngularJS Material Version:`
1.1.4
**Additional Information**:
 -  `Browser Type: *`
Chrome
 -  `Browser Version: *`
Version 60.0.3112.90 (Official Build) (64-bit)
 -  `OS: *`
Windows 10 Professional
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ampled** [comment]
I think adding and removing tabs dynamically while the tabs are hidden is what causes the timeout/$digest loop to restart in our application.

**Comment by Hintalo** [comment]
Hi
Is there any update on this issue? Or any workaround?
We have the same problem in our hybrid ng1/ng5 app, we are getting massive, infinite digest cycles, causing a huge memory-leak issue and crash of the browser.
We don't even have our md-tabs hidden and we are not adding tabs dynamically.
Thanks in advance for any help.

**Comment by ampled** [comment]
@Hintalo There's a lot to cover to keep material1 from keeping zonejs busy, including mouse movement. I'd start here: https://github.com/angular/material/issues/10636#issuecomment-301128015 to run certain DOM events outside of the Angular Zone. As for tabs, my solution was to rewrite the heaviest components with material1 tabs to use material2 tabs. Good luck 😄

**Comment by Hintalo** [comment]
Thank you for the quick reply. Yes, I think, migrating the corresponding components to material2 is the cleanest solution.

**Comment by Hintalo** [comment]
Just a quick update: in the last days I've learnt about the new "downgradeModule()" in NG5+
(see [here ](http://www.syntaxsuccess.com/viewarticle/angular-ngupgrade-with-downgrademodule) and [here](https://github.com/JoeyXXX18/ng2_upgrade_downgrademodule) and [here](https://stackoverflow.com/questions/47189917/using-downgrademodule-in-conjunction-with-downgradeinjectable-in-an-angular-an)).
DowngradeModule allows separating the NG1 zone from the NG2+ zone, actually the NG2+ part will be added as a downgraded module to the hybrid app.
Using downgradeModule instead of UpgradeModule has solved the infinite-digest-loop issue in our application and normalized the CPU and memory-usage in the browser, allowing a stabile temporary solution until the Angular migration work is fully done.

**Comment by Splaktar** [comment]
@Hintalo Yes, ngUpgradeLite (or `downgradeModule()`) in Angular v5 is the recommended way to do upgrades when AngularJS Material is involved. We're planning to add an ngUpgrade guide that will help point people in the right direction.

We don't plan to support the full ngUpgrade (and thus Angular v2 or v4 hybrid mode) for AngularJS Material due to a number of issues.

Can you confirm that this issue does not exist when using ngUpgradeLite/`downgradeModule()` with Angular v5+?

**Comment by Hintalo** [comment]
@Splaktar Yes, in our hybrid NG1/NG6 application (where we are using both Angular and AngularJS Material), the infinite digest issue has disappeared since we're using the downgradeModule() feature at bootstrap.
In our app, one separate workaround was needed to solve the missing-dependency-issue due to lazy-bootstrapping of the Angular-part, see [here](https://stackoverflow.com/questions/47189917/using-downgrademodule-in-conjunction-with-downgradeinjectable-in-an-angular-an). Using a "ServiceBootstrapComponent" as recommended in that stack-overflow answer has solved this missing-dependency-issue.

**Comment by Splaktar** [comment]
I had problems with [updating the Plunker](https://plnkr.co/edit/Ip8Ilx?p=preview), so I migrated it to StackBlitz:
[AngularJS Material ngUpgradeLite Demo](https://stackblitz.com/edit/ngupgrade-tabs-digest-10847?file=ng1/tabs.component.html)

It uses AngularJS Material 1.1.9, AngularJS 1.7.2, and Angular 6.0.6.

Everything seems to be working as far as showing Angular and AngularJS Material components. I'm also not seeing any major `$digest` issues where it's being triggered hundreds of times.
