### ISSUE TITLE
Can multiple md-autocomplete be used within a single chip?

### ISSUE THREAD

**Issue by kamal2311** [angular/material#10856]
**Actual Behavior**: 
 -  `What is the issue? * Currently there seems to be no straightforward way of having multiple autocompletable parts within a single chip.
 -  `What is the expected behavior?`I am looking for implementing a search box similar to [https://rawgit.com/hirokiosame/search.js/master/index.html](url) using md-chips and md-autocomplete.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:`
 -  `AngularJS Material Version:`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
The linked example above gives a 404.

**Comment by Splaktar** [comment]
If you want to open a feature request, please open a new issue and complete the issue template so that we can have more information on the use case.

**Comment by kamal2311** [comment]
Apologies for the link. Updated the link. Does that help?

**Comment by Splaktar** [comment]
Thanks, that's quite an interesting component! 

We don't currently have any plans to create or support something like that. It seems complex enough that the whole component should be a library rather than being just one component in a larger library.

We're currently overloaded with a11y issues related to our current implementation of chips and autocomplete. Sorting those out is going to take all of our focus, leaving very little time for minor enhancements, and almost no time for new features.
