### ISSUE TITLE
chips: mdIcon in mdChipRemove has aria-hidden set to true

### ISSUE THREAD

**Issue by EamonKavanagh** [angular/material#10861]
**Actual Behavior**:
- When inspecting the default md-chip-remove button on an md-chip, aria-hidden is set to true. This causes it to not be voiced by screen readers when focused (typically in sticky mode).

**CodePen** (or steps to reproduce the issue): *
- See the demo on the Angular Material page here: https://material.angularjs.org/latest/demo/chips

**AngularJS Versions**: *
1.6.4-local+sha.617b36117

**Additional Information**:
- Chrome 59.0.3071.115

**Comment by Splaktar** [comment]
This was fixed in `1.1.11`.

Previously:
![screen shot 2019-01-08 at 5 15 50 pm](https://user-images.githubusercontent.com/3506071/50862271-3dc00900-1369-11e9-822f-c7640bb67ed1.png)

After:
![screen shot 2019-01-08 at 5 16 09 pm](https://user-images.githubusercontent.com/3506071/50862252-3436a100-1369-11e9-9e1e-587705d35813.png)
The wrapping button gets a useful and customizable `aria-label` which the screen reader announces.
