### ISSUE TITLE
$mdSidenav onClose isn't working

### ISSUE THREAD

**Issue by leosco** [angular/material#10863]
Per the behavior documented [here](https://material.angularjs.org/latest/api/service/$mdSidenav) you should be able to set an onClose event callback using the following form: `$mdSidenav('left').onClose(() => {})`. However, it appears that only the per call promise syntax actually does the job: `$mdSidenav('left').close().then(() => {})`.

For me, personally, it'd be more convenient to set a global onClose event callback for a particular sidenav. Also, the lack of this feature gives us no easy way of working around the sidenav closing by clicking on the backdrop, pressing the esc key, etc. Here's a reproduction:

https://codepen.io/leosco/pen/wqjwXb

**Comment by DollarAkshay** [comment]
I changed your code to a bit more readable and standard js format : https://codepen.io/DollarAkshay/pen/QqgNwe

So if you open the console log you can see that it is throwing an error.

`SideNav 'left' is not available! Did you use md-component-id='left'?`

This is actually being thrown by `$mdSidenav('left').onClose(...)`

I guess the docs are wrong because I did a look up on the git hub issues and found 
1. https://github.com/angular/material/issues/1501
2. https://github.com/angular/material/issues/1311

These two issues are similar to your issue. and it looks like using `.then()` is the proper way of doing it even though the docs say otherwise.

**Comment by leosco** [comment]
@DollarAkshay yep. Basically what's happening is that on page load, the md-component isn't registered yet, so the onClose property can't be set. If you do it on an individual click event after the page has loaded, there's no problem.

Also, my code was totally readable ;) it was just such a simple example that I put it all in the `<script>` tag, instead of in a separate JS file.

**Comment by Splaktar** [comment]
Here's a working [CodePen](https://codepen.io/Splaktar/pen/bvbgYw?editors=1011) that shows how this is supposed to be used.

I'll update the docs to show this:
```javascript
      $mdSidenav('left', true).then(function(instance) {
        instance.onClose(function() {
          console.log('closed!');
        });
      });
```
