### ISSUE TITLE
Demos on the material website open a new CodePen session

### ISSUE THREAD

**Issue by corzani** [angular/material#10881]
If I click on any CodePen links on https://material.angularjs.org/latest/demo/autocomplete
I am redirected to a new CodePen session.

**Comment by cji03** [comment]
looks like their examples are gone.

**Comment by LoganDupont** [comment]
It's already solved in #10692. Just go to the master branch https://material.angularjs.org/HEAD/demo/autocomplete

**Comment by IMM0rtalis** [comment]
Why is there a thing solved in the end of May still not released? This is not the only bugfix which should be released already. :/

**Comment by LoganDupont** [comment]
Because they only put their focus on Material 2 at the moment which shouldn't be the case as long it's in beta. So this project is totally outdated as you don't know when a new release will happen and when certain bugs will be fixed. They also promised things on this project that weren't realistic after all #10430 and this is the case for quite some time now.

**Comment by ThomasBurleson** [comment]
Fixed with SHA f859507. 

> We are hoping to release AngularJS Material v1.1.5 **this** week.
