### ISSUE TITLE
dialog: with parent + angular-ui-router can break all future dialogs

### ISSUE THREAD

**Issue by chadjaros** [angular/material#10899]
**Actual Behavior**:
 -  `What is the issue? *`

UI-Router + improper order of events around showing/hiding a $mdDialog which is attached to a parent view can cause all future dialogs to silently fail until the site is reloaded.

Repro:
1. Create a $mdDialog with `parent` set to an <md-content> element
1. Call $mdDialog.cancel()
1. Navigate to a new angular-ui-router state before the cancel() promise/animation completes
1. Try to open another $mdDialog of any type
[observe] All further dialogs are borked, and fail silently

 -  `What is the expected behavior?`

Further dialogs continue to function normally

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`

https://codepen.io/anon/pen/rGNMeL

 -  `Details:`

- Test Dialog button creates a simple alert 
- Break Dialogs button reproduces the issue, any further attempted dialogs fail silently

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.8
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 60
 -  `OS: *` Mac OSX 10.12
 -  `Stack Traces:` none

**Comment by bogdan-panteleev-mifort** [comment]
Yes, I also faced the issue

**Comment by Splaktar** [comment]
If you check the [$mdDialog docs](https://material.angularjs.org/latest/api/service/$mdDialog) for `parent`, it specifies that the parent must be of type `element`, this means `angular.element`.

Note this code from the example:
```js
       var parentEl = angular.element(document.body);
       $mdDialog.show({
         parent: parentEl,
```
I updated the [CodePen](https://codepen.io/Splaktar/pen/qMaOPj) to do this instead of passing the string `".target"` and it seems to work a lot better.
