### ISSUE TITLE
card: content spilling over despite having layout-wrap in its parent tag

### ISSUE THREAD

**Issue by fullstackguyhere** [angular/material#10919]
**Actual Behavior**:
 - Despite having `layout-wrap` in my `md-content` tag, I have some content of the card spilling over when I click on an expanding button inside it
-  Card should expand to fit content.
-  see the distortion snapshot : https://i.stack.imgur.com/k52sj.png

my code:- https://gist.github.com/fullstackguyhere/883dd58f38cbb1f7b3c741b6a88a115e
see from line number 80 to 112

**AngularJS Versions**: *
 -  `AngularJS Version:1.6.6`
 -  `AngularJS Material Version:1.1.5`

**Comment by DollarAkshay** [comment]
Could you provide a minimalistic code pen demo ?

**Comment by fullstackguyhere** [comment]
I have provide code in the gist linke above. @DollarAkshay

**Comment by Splaktar** [comment]
I tried to load up the provided code in our blank StackBlitz demo, but it doesn't appear to display a card without the JavaScript from your app: [demo](https://stackblitz.com/edit/angularjs-material-blank-ynbv8d?file=app%2Fapp.template.html).

Based on the screenshot, it appears to just be an issue with the sizing, padding, margins, etc. It would be pretty easy to sort out with an actual demo.

Since there is no demo here and there does not appear to be a bug, I'm going to close this. We suggest using StackOverflow when looking for help fixing things in your app. Please use our GitHub issues for demonstratable bug reports only.
