### ISSUE TITLE
tabs: rounding issue when calculating tabs width causing pagination to appear unnecessarily

### ISSUE THREAD

**Issue by agale123** [angular/material#10911]
**Actual Behavior**:
 -  `What is the issue? *` For certain widths of tabs and structures for the parent, the pagination indicators are appearing when they are not necessary due to rounding of the tab widths when determining whether they fit within the parent.
 -  `What is the expected behavior?` The pagination indicators should not appear unless the content won't fit within the parent element

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/agale/pen/mwyGob
 -  `Details:` There are two tabs, each with a width of 106.5px. So the parent must be at least 213px for these tabs to show without pagination. But, the pagination shows when the parent is 213.4px (see codepen).

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.5
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 61
 -  `OS: *` Linux
 -  `Stack Traces:`

**Comment by Splaktar** [comment]
There were some changes in recent releases to align the `md-tab` `min-width` with the Material Design spec. That means that for this demo, due to the small sizing of the tabs, you will need to be running it under `600px` of width. 

In that case, with an [updated demo](https://codepen.io/Splaktar/pen/qBNJRpz?editors=1100) this pagination rounding issue is no longer reproducible. So this appears to have been fixed sometime recently.
