### ISSUE TITLE
select: trackBy - preset object, with property not in matching options, makes select dirty

### ISSUE THREAD

**Issue by jakobadam** [angular/material#10925]
**Actual Behavior**:
 -  `What is the issue? *` `trackBy` on model options for the `mdSelect` doesn't work as expected. Having a preset value with some extra property, that's not in the matching options object makes the form dirty.
 -  `What is the expected behavior?` It shouldn't be dirty.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/jakobadam/pen/mBmdJe
 -  `Details:` Problem stems from the use of `angular.equals` here: https://github.com/angular/material/blob/master/src/components/select/select.js#L897

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.5
 -  `AngularJS Material Version:` 1.1.5

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 61
 -  `OS: *` Windows 10
 -  `Stack Traces:`

best regards,
Jakob

**Comment by Splaktar** [comment]
Thank you for the comprehensive and detailed reproduction!

This appears to have been fixed by PR https://github.com/angular/material/pull/11156 in `1.1.22`. I updated the [CodePen](https://codepen.io/Splaktar/pen/dyXgNEG?editors=1010) to `1.2.1` and the first example appears to be working properly.
