### ISSUE TITLE
toast: z-index isn't working as expected

### ISSUE THREAD

**Issue by rlaPHOENiX** [angular/material#10923]
**Actual Behavior**: 
 -  `What is the issue? *` md-toast z-index isnt working as expected, when setting it to 2147483647 (max) it should go over a fullscreen html5 video, but it doesnt.
 -  `What is the expected behavior?` It should appear infront of a fullscreen video, a regular div with the same properties works but when using it on md-toast it doesnt.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://jsfiddle.net/bw2ytwwb/
 -  `Details:` As you can see, it DOESNT go in front of the video. (the div works but the md-toast doesnt)

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.10
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 61
 -  `OS: *` Windows 10
 -  `Stack Traces:`

**Comment by Splaktar** [comment]
I believe that [this demo](https://jsfiddle.net/splaktar/zmn0q872/33/) shows both the `div` and the `md-toast` on the video. The missing piece that is outside of the scope of AngularJS Material is answered [here](https://stackoverflow.com/a/59900474/633107). This requires you calling full screen on the `.video-container` rather than on the `video`. You would probably need to implement some custom video controls to do this.
