### ISSUE TITLE
md-checkbox(and possibly others): aria-label not created if inside ng-if

### ISSUE THREAD

**Issue by epelc** [angular/material#1094]
If you put an `md-checkbox` (and possibly other elements but I haven't tested it yet) inside of an `ng-if` a default `ariaLabel` is not set from the elements text.

```
you recieve ariaLabel not set errors when using within an ng-if
<div ng-if="editable">
  <md-checkbox ng-model="user.sendEmailUpdates">Receive email updates</md-checkbox>
</div>

works fine with ng-show
<div ng-show="editable">
  <md-checkbox ng-model="user.sendEmailUpdates">Receive email updates</md-checkbox>
</div>
```

**Comment by marcysutton** [comment]
Your example is missing quotes, but here's one theory: 

If `ng-show` behaves differently than `ng-hide` it could be due to the `ariaLabel` utility looking for text content in the checkbox during initialization but it being in a `display: none` block. There were also issues ([possibly outstanding](https://github.com/angular/material/issues/507), need to test it) with this utility in `ng-repeat` and plans for refactor: https://github.com/angular/material/issues/608

**Comment by epelc** [comment]
@marcysutton The quotes was just in my above example the problem still persists.

I figured it was related to #507 but I just wanted to document this since it was with `ng-if`.

**Comment by marcysutton** [comment]
@epelc is there no label inside the checkbox component? I thought `md-checkbox` had a child label element now, which wouldn't require `aria-label` to be copied to `md-checkbox`.

**Comment by marcysutton** [comment]
I thought for a second `<md-checkbox>` had a nested `<label>`, but it doesn't. It relies on the `aria-label` attribute to give it an accessible name as an input. I noticed a similar limitation with the `$mdAria` utility when the content was delivered from `ng-bind`. After I'm done with the docs redesign I'd love to revisit this issue, since it's an important one.

**Comment by epelc** [comment]
@marcysutton Essentially the `aria-label` attribute isn't being set when there is text content in the checkbox which it should be. So it's throwing the missing aria-label warning that you would get if you had an empty checkbox or one with no text and no `aria-label` set.
