### ISSUE TITLE
datepicker: md-debounce-interval = 0?

### ISSUE THREAD

**Issue by desfarik** [angular/material#10941]
Can I set the md-debounce interval to 0?
For what purpose is the md-debounce-interval created?
Why default 500?

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However there are better avenues for troubleshooting or asking for help with your app. These include [Stack Overflow](https://stackoverflow.com/), [Gitter](https://gitter.im/angular/material), the [AngularJS Material forums](https://groups.google.com/forum/?pli=1#!forum/ngmaterial), etc.

Please limit GitHub issues to bug reports and enhancement requests.

I guess that you are referring to [md-datepicker](https://material.angularjs.org/1.1.12/api/directive/mdDatepicker). Yes, you can set the value to `0`. The purpose is so that typing into the datepicker's input won't cause excessive calls to code that triggers an API request.
