### ISSUE TITLE
md-chip inside md-dialog, enter key won't register

### ISSUE THREAD

**Issue by tsanjoto** [angular/material#10996]
**Actual Behavior**:
 -  `What is the issue? *`
putting md-chips inside md-dialog won't register enter key and makes a new chip
 -  `What is the expected behavior?`
a new chip is created inside the md-chips thats inside the md-dialog

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`
https://codepen.io/tsanjoto/pen/POaLme
i have a normal md-chips
and a md-chips inside md-dialog

**AngularJS Versions**: *
 -  `AngularJS Version:`
1.5.5
 -  `AngularJS Material Version:`
1.1.0

**Additional Information**:
 -  `Browser Type: *`
chrome
 -  `Browser Version: *`
61.0.3163.91
 -  `OS: *`
macOS sierra 10.12.6
 -  `Stack Traces:`
invalid
----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
That is because you told it use invalid separators as part of `md-separator-keys`. They need to be keycodes and not strings like `md-separator-keys="[',',';']"`. Please take a look at my [example CodePen](https://codepen.io/Splaktar/pen/bYjJjG?editors=1010#0) that is working with both the enter key and comma in the dialog.

There is also an example in the [chips demo](https://material.angularjs.org/latest/demo/chips) where it uses a custom key:
```javascript
    // Any key code can be used to create a custom separator
    var semicolon = 186;
    this.customKeys = [$mdConstant.KEY_CODE.ENTER, $mdConstant.KEY_CODE.COMMA, semicolon];
```
