### ISSUE TITLE
md-tab header scroll not working n mousewheel event

### ISSUE THREAD

**Issue by ShankzPatil** [angular/material#11032]
**Actual Behavior**:
 -  `What is the issue? *` mousewheel event.wheelDelta is undefined
 -  `What is the expected behavior?` so 
```
 function scroll(event) {
                if (!ctrl.shouldPaginate) return;
                event.preventDefault();
              if(angular.isDefined(event.originalEvent))
                event = event.originalEvent; // add this line if  event.originalEvent is present

                ctrl.offsetLeft = fixOffset(ctrl.offsetLeft - event.wheelDelta);
            }
```

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.7
 -  `AngularJS Material Version:` 1.5.5

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *`
 -  `OS: *` Win 64 bit
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. A CodePen example of the issue is required.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.

Scrolling with the mouse wheel is working fine in the demo here: https://material.angularjs.org/latest/demo/tabs
