### ISSUE TITLE
Request: Responsive gutters (padding/margins)

### ISSUE THREAD

**Issue by jaminroe** [angular/material#11055]
### Bug, feature request, or proposal:
I'd like to be able to have responsive gutters based on the viewport/breakpoint size, just like the [MD breakpoints infographic](https://material.io/guidelines/layout/responsive-ui.html#responsive-ui-breakpoints), you highlight in your docs.

### What is the expected behavior?
I'd like to see: 16px gutters on mobile, 24px gutters on tablet, 32px gutters on desktop, 40px on large desktop

### What is the current behavior?
To my understanding, it doesn't look like there's a way to do this. Currently, you have to be fixed to one size of gutters for all viewports/breakpoints.

### What is the use-case or motivation for changing an existing behavior?
Would like to better support responsive layout for various device sizes

### Which versions of AngularJS, Material, OS, and browsers are affected?
All

### Is there anything else we should know? Stack Traces, Screenshots, etc.
Please fill me in or help me understand if there's a way to do this with the current version. Thank you!

**Comment by jaminroe** [comment]
Not sure, but this may be related to issue #6537

**Comment by Splaktar** [comment]
There is some support for this in the [SCSS layout styles here](https://cdn.gitcdn.link/cdn/angular/bower-material/v1.1.5/angular-material.css). If you are using a build system like Webpack, then you should be able to work with these SCSS files via the `bower-material` module. Unfortunately, I don't have a good Webpack + SCSS repository for AngularJS Material that I can point you to at this time.

If you are just using [the CSS](https://github.com/angular/bower-material/blob/master/angular-material.css#L7111-L7132), then it's fixed at 4px, 8px, 16px. But you could certainly override those styles as part of some media queries that are specific to your app in order to get them to provide responsive gutters.

**Comment by jaminroe** [comment]
I see, No problem! 👍😊 I just wanted to make sure I wasn't missing something. I'll pass the info along to my developers. Thank you!
