### ISSUE TITLE
md-datepicker not displaying dates/dialog correctly

### ISSUE THREAD

**Issue by b3023630** [angular/material#11112]
### Bug, feature request, or proposal:
Bug

### What is the expected behavior?
To display dates in expected calendar format and to be of reasonable size

### What is the current behavior?
Only one column of dates are showing.
The datepicker dialog is stretching/overflowing in X - I haven't been able to find any conflicting styles
![image](https://user-images.githubusercontent.com/22642985/35913135-a74b1390-0bf6-11e8-962a-155c11169821.png)

### Which versions of AngularJS, Material, OS, and browsers are affected?
Angular 1.5.3
Angular 1.1.1
Windows
Chrome Version 63.0.3239.132 (Official Build) (64-bit) & Firefox 43.0.1

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. The CodePen/Plunker/JSFiddle demo is not optional.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.

Also please verify that your bug isn't fixed in the latest version of AngularJS Material before submitting an issue.

In this case it looks like this may be an issue that is specific to your app, if that is true, then there are better avenues for troubleshooting or asking for help with your app. These include [Stack Overflow](https://stackoverflow.com/), [Gitter](https://gitter.im/), the [AngularJS Material forums](https://groups.google.com/forum/?pli=1#!forum/ngmaterial), etc.
