### ISSUE TITLE
docs(dialog): show resolve property removed?

### ISSUE THREAD

**Issue by korengal** [angular/material#11159]
Great work guys !!! 

I am wondering if this is Bug or feautre?

There was an ability in $mdDialog API Documentation  to send resolve parameters in (release version  1.1.4).

> resolve - {object=}: Similar to locals, except it takes promises as values, and the dialog will not open until all of the promises resolve.

This is still working  (in version 1.1.7),  but i am afraid that it will be removed.

can you tell me why this was removed from $mdDialog API Documentation ?

Thanks!

**Comment by Splaktar** [comment]
Including links to the documentation that you are asking about would be helpful in the future. I'll take a look now though.

**Comment by Splaktar** [comment]
OK, I see that entry in the [1.1.4 docs](https://material.angularjs.org/1.1.4/api/service/$mdDialog) but then it goes away in the [1.1.5 docs](https://material.angularjs.org/1.1.5/api/service/$mdDialog).

**Comment by Splaktar** [comment]
Here's [the commit](https://github.com/angular/material/commit/f94484fe9f10f6cd394bc8f8061dd440bfdfad27#diff-58cbee594b2fabf2c78b6d283750e535) that removed this. 

The original issue is https://github.com/angular/material/issues/7400 and the docs were removed because the functionality appeared to not be working. 

However later [comments](https://github.com/angular/material/issues/7400#issuecomment-289870601) explained how to properly pass a function that returns a Promise, rather than a Promise, in order to make this work. This comment has a CodePen example too.

**Comment by Splaktar** [comment]
We would welcome a PR that added this documentation back in and provided an example of how to properly provide the value as explained in the comment linked above.

**Comment by korengal** [comment]
Thanks !!! :)
