### ISSUE TITLE
bug(md-nav-bar): disabled attribute doesn't work as expected

### ISSUE THREAD

**Issue by ferc** [angular/material#11172]
### Bug, feature request, or proposal:
It's not working appropriately, if I initialize the md-nav-item with the disabled attribute in true, it doesn't disable anything (just the first time)

### What is the expected behavior?
The disabled attribute should work the first time and every time the ng-disabled value changes

### What is the current behavior?
If I initialize the md-nav-item with the disabled attribute in true, it doesn't disable anything

If you change the value of ng-disabled, the second time it will work

##### Detailed Reproduction Steps: 
It's the same nav-bar codepen demo from the Angular Material docs, I've only changed the "disable second tab" checkbox to start as checked and the disable nav-item doesn't work the first time.

### Which versions of AngularJS, Material, OS, and browsers are affected?
AngularJS 1.6.9, Angular Material 1.1.8, all OS and browsers

**Comment by Splaktar** [comment]
[This comment](https://github.com/angular/material/pull/10992#issuecomment-373980346) seems to cover the root cause. I believe that we just need to add an extra `mdNavItem.disabled = $mdUtil.parseAttributeBoolean(value, false);` above the `if('MutationObserver' in $window) {` to handle the initialization of the value.
