### ISSUE TITLE
pull to refresh http://git.aaronlumsden.com/material/ 

### ISSUE THREAD

**Issue by rakesh06081989** [angular/material#1117]
i think material design should have pull to refresh like Google Inbox.
like this jquery plugin http://git.aaronlumsden.com/material/ 
if we create this in angular material it will be more effective

**Comment by EladBezalel** [comment]
related #1060

**Comment by ThomasBurleson** [comment]
To refresh your Angular Material library, you should use `bower update`.

**Comment by PaulMougel** [comment]
@ThomasBurleson That's not what the issue is about ;)

Looks like OP talks about a specific visual component (loading bar as displayed in the linked jQuery plugin) and behavior (pull with finger to refresh a list, as in the native Inbox app).

![image](https://cloud.githubusercontent.com/assets/1788596/5631176/bce73658-95c4-11e4-95dc-56cfa8607e60.png)

@rakesh06081989 This question seems best fitted for the [ngMaterial forum](https://groups.google.com/forum/#!forum/ngmaterial).

**Comment by ThomasBurleson** [comment]
@Paul - I also closed this issue since we have issue #1060. But agreed an ngMaterial forum conversation is better suited for custom loaders.

**Comment by rakesh06081989** [comment]
@ThomasBurleson <https://github.com/ThomasBurleson> you are correct..


my thought is that only.

Looks like OP talks about a specific visual component (loading bar as
displayed in the linked jQuery plugin) and behavior (pull with finger to
refresh a list, as in the native Inbox app).

[image: image]
<https://cloud.githubusercontent.com/assets/1788596/5631176/bce73658-95c4-11e4-95dc-56cfa8607e60.png>

@rakesh06081989 <https://github.com/rakesh06081989> This question seems
best fitted for the ngMaterial forum
<https://groups.google.com/forum/#!forum/ngmaterial>.

On Tue, Jan 6, 2015 at 9:31 PM, Thomas Burleson <notifications@github.com>
wrote:

> @Paul <https://github.com/Paul> - I also closed this issue since we have
> issue #1060 <https://github.com/angular/material/issues/1060>. But agreed
> an ngMaterial forum conversation is better suited for custom loaders.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/1117#issuecomment-68884723>.
>



-- 
Thanks & Regards,
Rakesh R,
Cell: 9177807762.
