### ISSUE TITLE
[DOC] Every versions have same Getting Started

### ISSUE THREAD

**Issue by HZooly** [angular/material#11222]
### Bug, feature request, or proposal:

When selecting an old version of AngularJS Material, going on Getting Started page, I got the same code than on HEAD version (currently 1.1.8).

### What is the expected behavior?

Have Getting Started page for selected version.

### What is the current behavior?

Have most recent version.

See here for example: https://material.angularjs.org/1.1.0/getting-started

Version 1.1.0, you will see get started for 1.1.8.

**Comment by Splaktar** [comment]
That's not quite accurate. Each getting started page is different, but they don't contain version-specific details. Only the embedded CodePen includes versions and those are the versions of the latest recommended release (1.1.8).

All Getting Started Guides since 1.0 use that same CodePen. Only [prior to 1.0](https://material.angularjs.org/0.11.4/getting-started) did we use another CodePen. But in general, we never create a new CodePen with specific version numbers to match up with each Getting Started Guide.
