### ISSUE TITLE
Scale down every components

### ISSUE THREAD

**Issue by gflowgithub** [angular/material#11242]
Hello,

Is there any way to scale down EVERY components?

In some cases I'd like these components a little closest, input containers, toolbars, menu items..., but there are too many css properties like height, min-height, padding, margin... that works different depending of the component.

Thank you very much!!

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However the [AngularJS Material forums](https://groups.google.com/forum/?pli=1#!forum/ngmaterial) are better for Q&A and discussions.

Please limit GitHub issues to bug reports and feature requests.

That said, the [CSS Density Project](https://github.com/angular/material/projects/3) is targeted at addressing this. For some of the components, like [md-list](https://material.angularjs.org/latest/demo/list) you can use `md-dense` (i.e. `<md-list class="md-dense">`) to enable a mode where there is less padding and margin and generally a better layout for desktop.

But this project is not complete, so only `md-list` and `md-menu` are currently supported. https://github.com/angular/material/issues/9201 discusses the idea of having a way to set dense mode globally or on a DOM tree, but that issue is waiting for dense mode support in most all of the components. I think that this question is close enough to that one, that I am going to close it and let discussion continue over there.

Also please note that the main champion of this CSS Density Project is no longer with the team and CSS Density is a lower priority than addressing our a11y bugs (see the 3 open projects for a11y).
