### ISSUE TITLE
mdDatepicker: is one day off when typing

### ISSUE THREAD

**Issue by luninroman** [angular/material#11250]
### Bug, feature request, or proposal:
Bug

### What is the expected behavior?
Date when typing should not be one day off

### What is the current behavior?
 So when I select a date via calendar pop-up and pick a day it gives me a correct day, but when I type a date - it gives me one day off, e.g. typing _2012-12-12_ gives me Tue _Dec 11 2012 00:00:00 GMT-0500 (EST)_

##### Detailed Reproduction Steps: 
Pick a date via input field, but not a calendar

### Which versions of AngularJS, Material, OS, and browsers are affected? 
AngularJS 1.6.9
Chrome 66.0.3359.117

### Is there anything else we should know? Stack Traces, Screenshots, etc.
![download](https://user-images.githubusercontent.com/16228200/39086953-f49a6e1c-4566-11e8-96dc-480cbcd4f78f.png)
As you may see date is different from the one I typed 
My current timezone Easter, not sure if it matters

**Comment by Splaktar** [comment]
I believe that this is the same general issue that is tracked in, even though `ng-model-options` is not used:
https://github.com/angular/material/issues/10431
https://github.com/angular/material/issues/10598

**Comment by codymikol** [comment]
Looks like this occurs only if the $mdDateLocaleProvider.formatDate is set. If the config block is removed, everything works fine.

**Comment by codymikol** [comment]
Can confirm this is actually not a bug. 

What happened here is you overwrote $mdDateLocaleProvider.formatDate which tells angular material how to convert a date object into a string. You also need to overwrite the $mdDateLocaleProvider.parseDate functionality in order to tell angular material how to parse your date string back into a date object.

Here is a fixed pen: https://codepen.io/codymikol/pen/JBpzpz

**Comment by Splaktar** [comment]
@codymikol thank you for looking into this! Your suggestion looks good.
