### ISSUE TITLE
feat(button): add new stroked (outlined) button type

### ISSUE THREAD

**Issue by HZooly** [angular/material#11413]
Is it planned to add stroked/outlined button styles in Material v1 ? It has been done in Material v2.

I'd glad to help the team to implement it in the library 😃

**Comment by Splaktar** [comment]
At this point, we don't plan to add any of the Material Design 2018 updates to AngularJS Material. The team is hard at work adding these to Angular Material (as you noted).

As I mention in https://github.com/angular/material/issues/11415, we're going to be clarifying this in the 1.1.11 release via pointing all of our links to the [Material Design 2017 spec](https://material.io/archive/guidelines/).

For AngularJS Material, we're focusing our limited resources on fixing bugs, perf, and a11y issues so that this library is more stable and reliable rather than adding new features.

That said, we would consider this specific item to be an enhancement that doesn't seem overly difficult to implement or maintain. If a community member wanted to put together a well crafted PR w/ tests and full functionality, we would try to get it in.

**Comment by Splaktar** [comment]
PR https://github.com/angular/material/issues/11415 has been merged and released in `1.1.11` to point all of our docs to the Material Design 2014-2017 spec.

After discussion with the team, we are going to keep AngularJS Material focused on this spec and not add support for the MD 2018 spec. For the latest Material Design features, [Angular Material](https://material.angular.io/) will be the place to look.

**Comment by HZooly** [comment]
Thanks for keeping us updated @Splaktar !
