### ISSUE TITLE
Deprecated text floats, but no docs page

### ISSUE THREAD

**Issue by MarcosPortugal** [angular/material#1146]
Just a heads up. This https://github.com/angular/material/commit/60fcd6f4d8b895162b37a940c3f33164d8044382 change made the use of text floats throw this warning:

/!\ md-text-float is deprecated. Please use `<md-input-container>` and `<input>`.More information at http://material.angularjs.org/#/api/material.components.input/directive/mdInputContainer

 But the link provided doesn't lead anywhere.

**Comment by mzbyszynski** [comment]
Isn't this just because material.angular.org is still built from 0.7.0-rc1 and not 0.7.0-rc2?

**Comment by marcysutton** [comment]
Sounds like it to me.

**Comment by mzbyszynski** [comment]
So could someone with the powers to do so regenerate the docs on https://material.angularjs.org based on 0.7.0-rc2? I know the docs used be updated automagically when changes were pushed to the master branch but you decided to switch them from master to the last numbered release. I guess that is a manual process for now (re #988 )?

I think keeping the published docs from 0.7.0-rc1 online will cause a lot of needless confusion and generate more bogus issues here so if it is not too much work I think it would make sense to do it ASAP, instead of waiting until development on 0.7.1 starts.

Really I just want to be able to play with the demos and fixes in the new version without having to build the docs myself :wink:

**Comment by ThomasBurleson** [comment]
@mzbyszynski - we have asked the server team to rebuild http://material.angularjs.org to be sync'd with 0.7.0-rc2

**Comment by MarcosPortugal** [comment]
Thanks a lot!

**Comment by mzbyszynski** [comment]
Yes! 0.7.0-rc2 docs are live
