### ISSUE TITLE
switch: clicking on empty space triggers the switch

### ISSUE THREAD

**Issue by Oneril** [angular/material#11534]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
https://codepen.io/anon/pen/JeVgWP

### What is the expected behavior?
Switch should be clickable only on label and on the switch and not on the empty left after.

### What is the current behavior?
Switch is clickable on label, on the switch and on the empty left after.

### What is the use-case or motivation for changing an existing behavior?
In a form client can missing click on a empty and will expect no changes on there form. But here it's miss leading the user.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.6.7
- AngularJS Material: 1.1.10
- OS: Windows
- Browsers: Chrome

**Comment by Splaktar** [comment]
The whole switch is clickable. In the first case, due to the layout the switch extends to the full width of the page.
![screen shot 2018-12-04 at 7 55 21 pm](https://user-images.githubusercontent.com/3506071/49482912-15d80580-f7ff-11e8-8ed4-03347e7246ec.png)
If you don't want this, then you need to adjust your layout as you did in the second example.
![screen shot 2018-12-04 at 7 58 59 pm](https://user-images.githubusercontent.com/3506071/49482913-15d80580-f7ff-11e8-9701-4ae5983424e0.png)
