### ISSUE TITLE
bug(docs) relative anchor links not working in docs

### ISSUE THREAD

**Issue by codymikol** [angular/material#11644]
## Bug, enhancement request, or proposal: bug

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. go to https://material.angularjs.org/latest/Theming/01_introduction
1. click on the  "$mdThemingProvider.setNonce()"link
1. you will be brought to a 404 page.

This also happens for all of the card header links on a HEAD branch

1. go to https://material.angularjs.org/HEAD/demo/autocomplete
1. click on the header of the first card
1. you'll end up on a 404 page

This seems to work fine on release pages though

### What is the expected behavior?

The links should work properly.

### What is the current behavior?

They don't 😉 

### What is the use-case or motivation for changing an existing behavior?

Better documentation. The header links aren't a big deal but the theming one may cause confusion. I also suspect there are more cases like it.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.1.7
- AngularJS Material: 1.1.13 
- OS: OS
- Browsers: Chrome 
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.

N/A

**Comment by Splaktar** [comment]
Related to PR https://github.com/angular/material/pull/11634.

**Comment by Splaktar** [comment]
This is also an issue on the main home page.

https://material.angularjs.org/1.1.12/#the-latest-material-design works, but https://material.angularjs.org/latest/#the-latest-material-design doesn't. This appears to be due to the following change:

1.1.12:
```html
<a class="docs-anchor ng-scope" ng-href="#the-latest-material-design" name="the-latest-material-design" href="#the-latest-material-design">The Latest Material Design</a>
```

1.1.13:
```html
<a class="docs-anchor ng-scope" name="/#the-latest-material-design" ng-href="/#the-latest-material-design" href="/#the-latest-material-design">The Latest Material Design</a>
```

In this case, the `/` in `/#anchor` breaks the ability to scroll down to the anchor.

**Comment by Splaktar** [comment]
I'm not seeing any difference with the anchor behavior on the home page (on `localhost`) when the `/` is removed.

When the site is deployed, `$location.path()` is not giving us the full path with the Base URL. It gives `/demo/autocomplete` instead of `/latest/demo/autocomplete`. To get the full path with the Base URL, we need to use `$window.location.pathname`.

**Comment by Splaktar** [comment]
Ah, the home page issue is due to the `name` attribute needing to not include any path information or `#`, just the name of the anchor. PR coming soon...
