### ISSUE TITLE
datepicker: error validation of formatting with custom locale

### ISSUE THREAD

**Issue by Miqueliu** [angular/material#11677]
I need datepicker to show date in non-English format. Therefore, I loaded a `$locale` value for AngularJS and overwrote `formatDate` function of `$mdDateLocale` service to do it.

Well, recently an error has appeared: A validation error is applied in date inputs.

[Here](https://codepen.io/anon/pen/pYayvR) is a CodePen testing. You can see that the input is detected as wrong. It is because of month-day position permutation: The system detects that month (first number) obviously cannot to be greater than 12.

This occurs since the new release 1.1.13 and it seems to be caused by [a commit of January 5](https://github.com/angular/material/commit/57c81c890fc33e586dd38add2a0b4899f62e1a4e).

Is it a real issue or there is a way to output string dates avoiding this trouble?

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. This gives the team the information needed to investigate the bug or prioritize the feature.

**Comment by Splaktar** [comment]
A couple of notes, this CodePen is using AngularJS `1.7.8` which isn't fully released yet AFAIK (it's not listed on angularjs.org). But changing it to `1.7.6` doesn't solve this.

I'm not sure where you saw that overriding `$mdDateLocale.formatDate` in the `run()` function was the correct approach. But our [`$mdDateLocaleProvider
 docs`](https://material.angularjs.org/latest/api/service/$mdDateLocaleProvider) show you the proper way of working with custom date locales in the `config()` function.

If you want validation to work with your custom locale, you will need to implement a `$mdDateLocaleProvider.parseDate()` function that properly validates dates in your locale.

The change from https://github.com/angular/material/commit/57c81c890fc33e586dd38add2a0b4899f62e1a4e is just showing you the validation error now since that code has been changed to work properly. Previously it would not show validation for invalid dates.

**Comment by Splaktar** [comment]
If you have more questions about how to configure `$mdDateLocaleProvider` please post them on the [AngularJS Material forums](https://groups.google.com/forum/?pli=1#!forum/ngmaterial) or [Stack Overflow](https://stackoverflow.com/questions/tagged/angularjs-material).

**Comment by Miqueliu** [comment]
Thank you, @Splaktar.

I put in run block because of date filter.

You're right. Yesterday I noticed the `parseDate` function is necessary. Anyway, I think it would have to be a automatic mechanism.
