### ISSUE TITLE
select: want to display options with custom formatted html

### ISSUE THREAD

**Issue by true-doc** [angular/material#11765]
I have a select box which I want its text to be edited into this specific format.
	<md-option ng-repeat="staff in staffs" 
			ng-value="employee_id">
		pix		**Staff Name**
		<i>Dept</i>					<i>employe_id</i>
	</md-option>
	
so the result would be 

		passpt		**Staff Name1**
		<i>Dept</i>					<i>employe_id</i>

		passpt		**Staff Name2**
		<i>Dept</i>					<i>employe_id</i>
		
		passpt		**Staff Name3**
		<i>Dept</i>					<i>employe_id</i>

What I have done so far is 
	
	<md-option ng-repeat="staff in staffs" 
			ng-value="employee_id">
		<h4>{{staff.name}}</h4>
	</md-option>
	
This is not working. I have been confused as to how to go about it.

I have looked at md-autocomplete but I do not want the search field. 
I want to be able to display all the items, autocomplete does show all the items

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

In the future, please provide a CodePen Demo that reproduces a bug if you have identified one, otherwise there are better avenues for troubleshooting or asking for help with your app. These include [Stack Overflow](https://stackoverflow.com/questions/tagged/angularjs-material), [Gitter](https://gitter.im/angular/material), the [AngularJS Material forums](https://groups.google.com/forum/?pli=1#!forum/ngmaterial), etc.

Please limit GitHub issues to bug reports and enhancement requests.

Here's a [CodePen example](https://codepen.io/Splaktar/pen/ymgXmg?editors=1010#0) that shows that you can add all kinds of styling to `md-options`. Also tags like `<i>` and `<b>` will work. `<h4>` also works fine but it isn't very noticeable. I've used a `<h1>` in the example to make it obvious.
