### ISSUE TITLE
$mdToast does not work when the module container contains the ng-include directive

### ISSUE THREAD

**Issue by fabito** [angular/material#1192]
Check the plunker below for more details:

http://plnkr.co/edit/X0l2VnKCnM6Fhikos7QP

**Comment by rschmukler** [comment]
The issue is that `ng-include` replaces the element with the content. Since you're bootstrapping that element, `$rootElement` (where the toast inserts itself) is no longer in the DOM.

You can manually specify `options.parent` if you really need to do this, but I wouldn't recommend bootstrapping a DOM node that's getting swapped out of the DOM anyway as lots of things can depend on `$rootElement` (not just angular-material).

**Comment by fabito** [comment]
Thank you for clarifying.
