### ISSUE TITLE
checkbox: label text not centered with non-default font-size

### ISSUE THREAD

**Issue by oliversalzburg** [angular/material#11995]
## Bug, enhancement request, or proposal
Text on checkboxes is not aligned as expected.

# Demo and steps to reproduce the issue
**Demo URL (required)***:  https://stackblitz.com/edit/angularjs-material-blank-jdioxn

#### Detailed Reproduction Steps
1. Change the font-size on your page to `10px` or some other unexpected value.

### Explain the expected behavior
The text is vertically centered next to the box icon.

### Explain the current behavior
The text appears to be aligned to the top of the bounding box.

### Discuss the use-case or motivation for changing the existing behavior
This used to behave as expected in previous versions and should result in an experience more aligned with expectations.

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 1.7
- AngularJS Material: 1.2.0
- OS: Windows 10
- Browsers: Edge

#### Screenshots
![image](https://user-images.githubusercontent.com/1658949/89532935-e1e28e00-d7f2-11ea-9d91-102546b68d70.png)

**Comment by Splaktar** [comment]
OK, I've dug into this a good deal more. Here's an updated [demo](https://stackblitz.com/edit/angularjs-material-blank-9ygmhu?file=style.scss) with some options for dealing with this breaking change in `1.2.0`. This change was made to align `md-checkbox` with the final version of the Material Design 2017 guidelines and to provide some more flexible Sass variables for advanced usage.

Here are the highlights
1. This vertical alignment is now done via Sass margin calculations related to [`$checkbox-text-margin-top`](https://github.com/angular/material/blob/c60938552c1a007b24b0cd2de5248453161ae012/src/components/checkbox/checkbox.scss#L8)
1. You can now override the value of `$checkbox-text-margin-top` across your app
    1. Note that this is also part of the [`$md-inline-alignment` calculation](https://github.com/angular/material/blob/c60938552c1a007b24b0cd2de5248453161ae012/src/components/checkbox/checkbox.scss#L15-L17) which is used for [inline form elements](https://material.angularjs.org/latest/demo/input#inline-form), which are inside of a container with the `md-inline-form` class.
1. If you are using CSS-only, you can just override the `margin-top` of `md-checkbox .md-label`

Should we have a default font-size in `md-checkbox`'s styling so that it is harder for this to break due to inherited font-sizes? 
- My thoughts: probably not
- What do you think?

Is there some way to make these calculations able to work with any font-size without breaking `.md-inline-form` alignment or just breaking [general checkbox alignment](https://github.com/angular/material/pull/12017#pullrequestreview-493918459)?
- I'm open for suggestions on this.

**Comment by oliversalzburg** [comment]
Sorry, I don't think I can be of much use on this anymore. We've put our AngularJS frontend into maintenance mode and this is just too minor of a detail 😥
