### ISSUE TITLE
md-input-container: Textarea problems with model initialization when element not visible on view load

### ISSUE THREAD

**Issue by Splaktar** [angular/material#1202]
Overview of the Issue:
There are some issues with updating the model for textareas contained in md-input-containers. The view model is probably not getting updated since the view isn't visible upon initialization of the page. 

We've seen this same thing a lot with different libraries since updating to AngularJS 1.3.x. Here's a similar issue with angular-bootstrap-switch (https://github.com/frapontillo/angular-bootstrap-switch/issues/52). We've also seen it with ui-select2.

We were able to solve both issues using $intervals that just sit and wait for the view to become visible and then initialize the model properly. But this seems like a horrible hack, so we're hoping to hear about a better fix for this.

Angular Material Version: master, 0.7.0-rc2, 0.7.0-rc3
Browsers and Operating System: Chrome 39 and 42
Reproduce the Error: http://plnkr.co/edit/cV2xejsabJIhM70IC6Zg?p=preview
Related Issues: #559 #565

**Comment by frapontillo** [comment]
:+1: to get updates on this.

**Comment by marcysutton** [comment]
Hi @Splaktar, can you check your use case with the latest code on master and see if it's still an issue? Thanks!

**Comment by JayQuid** [comment]
Hi @marcysutton (and @Splaktar), I'm having the same issue, I'm currently using material on master.

The height of the textarea is set on auto when it should be fitted to content.

It happens when the textarea isn't visible at first. For instance, I have an editable div which transforms to a textarea when clicked, so the textarea isn't there at first (it's hidden via ng-hide).

**Comment by Polyethylene** [comment]
Hi @marcysutton (and @Splaktar), I'm having the same issue, I'm currently using material on master.

The height of the textarea is set on auto when it should be fitted to content.

It happens when the textarea isn't visible at first. For instance, I have an editable div which transforms to a textarea when clicked, so the textarea isn't there at first (it's hidden via ng-hide).

**Comment by Splaktar** [comment]
@marcysutton I've updated the Plunker to Angular 1.3.15 and removed hammer.js. It is still using angular-material `master` as it was previously. This last test was done with against cbbdf744f8dc08243ee0fbe44e0751606666afa7 which includes 0.9.0rc3.

The textarea is no longer completely empty, so the model appears to be updating now. But as @Polyethylene mentioned, the textarea's size is not properly initialized and it uses the default size without giving any indication that there is more text that is not displayed (no scrollbar).

Interacting with the textarea seems to make the size update properly.

**Comment by Polyethylene** [comment]
Yes, as @Splaktar said :

> Interacting with the textarea seems to make the size update properly.

Such as selecting text inside the input with the mouse. Just getting the focus isn't enough to resize it properly.
