### ISSUE TITLE
md-slider: Appearance not updated properly when bound value changes

### ISSUE THREAD

**Issue by maxee** [angular/material#1210]
I got some strange behavior with the md-slider component. If the bound value changes, the slider position doesn't get updated immediatly. Bizzarely, if I open the GoogleChrome-Dev-Tools and close them again, the value updates instantly.

Unlike the md-slider, the input field which is bound to the same value, updates properly.

```
<md-input-container>
  <label>Input</label>
  <input type="text" ng-change="myfunc()" ng-model="devices[key].Properties.MyProp" />
</md-input-container>

<md-slider ng-change="myfunc()" ng-model="devices[key].Properties.MyProp" min="0" max="100" aria-label="lbl"></md-slider>
```

**Update:**
~~It seems that the above issue occures if the bound value is not a number but a string.~~
However its the question why a string value works as well after some time or by opening the Dev-Console and closing it afterwards.

**Comment by maxee** [comment]
After looking into it another time, I found out that the binding indeed updates correctly. 
The correct value gets assigned, but the slider fails to adapt its appearance, as you can see in this screenshot:
![material-slider](https://cloud.githubusercontent.com/assets/408498/5793923/64f80c2c-9f58-11e4-8bd6-e8a7f6864373.png)

The small **blue strip** is at its correct location (100), but the circle isn't. By opening and closing the Chrome-Dev-Tools the circle updates it's position to position 100.

**Comment by medaamarnadh** [comment]
Yes . I have the same problem .
It is working fine in browser. When i was build as a cordova application .
The slider has the same problem in android tablet

**Comment by PaulMougel** [comment]
Same issue here: the `md-track` component is displayed correctly, but not the `md-thumb`.
 From my experience, this happens when the slider is in a `<md-tab>` component, but only when the tab where the slider belongs is not displayed on the first render. Here is a [Plunker](http://plnkr.co/edit/kyW8KdCPOHk3umzW1wZl?p=preview). If the page is resized, then the `md-thumb` is repositioned correctly.

![untitled](https://cloud.githubusercontent.com/assets/1788596/5834207/6f792384-a15b-11e4-8f11-46949edc55c8.gif)
(Please excuse me for the flicker)

**Comment by ThomasBurleson** [comment]
I added 
```css
.md-tab-content   {
  
  padding:30px;
}
``` 
to improve the plunkr. I see two (2) issues:

1.  No discrete step indicators
2.  Thumb position is wrong... (I think this has to due with content $scope disconnects, btw).

**Comment by PaulMougel** [comment]
Confirming the fix, thanks!
