### ISSUE TITLE
We're moving away from positioning the dropdown on top of the select. You can try our new select based on top of MDC's styles. The API and behavior is exactly the same since it shares the same base class as the current select, but the CSS will be slightly different and the dropdown is only positioned above/below. You can try it by importing `MatSelectModule` from `@angular/material-experimental/mdc-select` instead of `@angular/material/select`.

### ISSUE THREAD

**Issue by khepf** [angular/material#12145]
Hello,

Any update on when the corrections to the mat-select dropdown positioning might be ready for production? I have a few teams holding off on updating from Angular Material 11 for this reason alone.

Thank you!
Jeremy

We're moving away from positioning the dropdown on top of the select. You can try our new select based on top of MDC's styles. The API and behavior is exactly the same since it shares the same base class as the current select, but the CSS will be slightly different and the dropdown is only positioned above/below. You can try it by importing `MatSelectModule` from `@angular/material-experimental/mdc-select` instead of `@angular/material/select`.

_Originally posted by @crisbeto in https://github.com/angular/components/issues/23625#issuecomment-931448386_

**Comment by crisbeto** [comment]
The component in `material-experimental` should be usable as it is right now. As I mentioned, it inherits all of its logic from the existing `mat-select`, except for the dropdown positioning and CSS styles. I can't say when it'll be made the default, because we are blocked on some external dependencies, but when that happens, we'll have an automated migration to change your import back to `@angular/material/select`.

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.

I have transferred this issue to the correct repository for you.
