### ISSUE TITLE
Angular Material along with angular-ui

### ISSUE THREAD

**Issue by amolghotankar** [angular/material#1231]
FAQ?

Can we use angular material design with another component library like angular-ui together as both are complimentary in one way but have some mutually exclusive features also, like Accordion, Carousel, Typeahead. Also this question goes as a extension to use of other plugin libs like bootstrap calendar etc. 

Same is the case with bootstrap.css & bootstrap.js?

Will angular material design gel well with all of them?

Please suggest..

**Comment by epelc** [comment]
@amolghotankar Please move this to the [forums](https://groups.google.com/forum/#!forum/ngmaterial)

But you can generally use angular material with any library that allows you to specify your own template. Since most assume you are using bootstrap they give a bootstrap template but if they let you specify your own you can usually make it work. However I haven't used ui-bootstrap with angular-material which is what I think you mean by angular-ui. But you should be able to use their components.
