### ISSUE TITLE
Clarify Theming Docs

### ISSUE THREAD

**Issue by rschmukler** [angular/material#1253]

**Comment by ThomasBurleson** [comment]
Theme represents a collection of palettes associated to intentions within the application. Palettes represents set of hues to a base color  (ala swatches).

[Primary = blue, accent = cyan](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7S1dwdXNVa1B1OHc/components_cards6.png)

[Primary = pink, accent = orange](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7ZnNIdWJFUEpFNkU/components_cards10.png)

[Primary = pink, accent = cyan](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7MVF2bUpGcWhlUVE/components_chips_contact2.png)

[Primary = teal, accent = cyan](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7UFJNRWt4MlVVMVE/components_dividers_type6.png)

**Comment by amedeomar** [comment]
It is not clear (to me) if there are some predefined themes and if so what are their names

**Comment by rschmukler** [comment]
@amedeomar There aren't any pre-defined themes, instead you should configure your application's default theme with the `$mdThemingProvider`...

```js
angular.module('myApp', [])
.config(function($mdThemingProvider) {
  $mdThemingProvider.theme('default')
    .primaryPalette('blue')
    .accentPalette('pink');
});
```

Expect the docs to be improved shortly, which will hopefully help alleviate some of the confusion.

**Comment by amedeomar** [comment]
So the string 'default' indicates that i'm creating\overriding the 'default' theme?

**Comment by rschmukler** [comment]
That is correct. `$mdThemingProvider.theme` will either grab or create a new theme with the name specified.

**Comment by amedeomar** [comment]
Ok..thank you

**Comment by richardaum** [comment]
Well. The documentation doesn't specify what is the relation between tones (100,200,300..) with its usage with components. For instance, what is the tones used for `md-toolbar` by default. What hue should I overwrite to achieve that color? And what about other 30 material components?

It would be very useful if we could set "blue" as just a few tones of blue (maybe just one), instead of many, like md-theme requires.

![screenshot from 2017-02-25 03-16-16](https://cloud.githubusercontent.com/assets/2018161/23329173/d456e562-fb08-11e6-807d-dcf2cfc91176.png)
