### ISSUE TITLE
md-input-container not rendering like it should

### ISSUE THREAD

**Issue by cabey** [angular/material#1265]
This plunker has the code I'm working on.  On my local machine I have the bower_components folder and angular-messages.js file. The input box does not display like the demo on the angular material design site.  Any help is appreciated.  Thanks,

http://plnkr.co/edit/o9oa2A5LnqwOYBspSFTm?p=preview

**Comment by marcysutton** [comment]
Hi! Your dependencies must be loaded in the Plunker for us to be able to help you debug. It's a bit hard to tell when it won't render at all. :)

**Comment by cabey** [comment]
Hi, I've added the dependencies to the plunker and am able to show the behavior I was talking about.  Thanks,

http://plnkr.co/edit/o9oa2A5LnqwOYBspSFTm?p=preview

**Comment by marcysutton** [comment]
Ok, the reason is because there's a mismatch in here: the angular-material.js source you've included is 0.6.1, while the markup for `<md-input-container>` was introduced in 0.7.0. We have an update coming next week that should get our CDN up to date, since it's stuck back on 0.6.1. I would recommend doing a build from the master branch or the [0.7.0-rc3 tag](https://github.com/angular/material/tree/v0.7.0-rc3) the meantime.
