### ISSUE TITLE
Problem with Leaflet / Mapbox.js

### ISSUE THREAD

**Issue by deviloperz** [angular/material#1300]
I have a problem building an app with a leaflet map.

There is no click-event fired when clicking on a marker on the map. This is because angular-material is catching all click-events that are not from material itself.

Any idea how i could fix this?

**Comment by marcysutton** [comment]
Can you provide a Codepen or Plunker so we can help you debug?

**Comment by deviloperz** [comment]
Hi, I have made a small Codepen showing the problem.
http://codepen.io/anon/pen/QwMEdq

It doesn't work because of this piece of code, but if i remove it every other click gets fired twice.
```javascript
document.addEventListener('click', function(ev) {
  // Prevent clicks unless they're sent by material
  if (!ev.$material) {
    ev.preventDefault();
    ev.stopPropagation();
  }
}, true);
```

**Comment by marcysutton** [comment]
Are you intending to use a Leaflet map as part of a larger Angular Material interface, and that's why the CSS/JS resources are included? There aren't any Angular Material components in your example, so I'm curious why interference would be happening. 

I'm not seeing that event listener anywhere in your example to inspect click behavior, but right off the bat I see a few issues with it:
 * It should use the jqLite wrapper and event binding syntax (or `ng-click`): `$document.on('click', function(ev){});`
 * You might want to scope your event handler to the map element, so that it doesn't propagate through the whole DOM.

I forked your Codepen to use the last release of Angular Material that didn't include `mdGestures` (the only thing that would have been bound to the document) instead of rawgit, which pulls from master: http://codepen.io/marcysutton/pen/pvrrVX Can you see if the issue persists?

**Comment by marcysutton** [comment]
This issue popped up with `mdGestures`, and is the same issue as https://github.com/angular/material/issues/1326. Reviewing it with @ajoslin.

**Comment by ajoslin** [comment]
There are several ways to fix this, I'll have to think about it.

**Comment by ajoslin** [comment]
Leaflet will work on desktop now.

**Comment by ajoslin** [comment]
It may also work on mobile. Could you test it and report back your results?

**Comment by deviloperz** [comment]
I've tested on desktop and on mobile and everything is working perfectly.
Thanks for your help

**Comment by marcysutton** [comment]
Closing for now, let us know if there is still an issue.

**Comment by dg1202** [comment]
I have this issue on both chrome and safari for iOS.

Firmware: iOS 8.3
Safari: 8
Chrome: v42.0.2311.47

Leaflet click events are firing on desktop, but nothing on mobile.

**Comment by ThomasBurleson** [comment]
For mobile solutions that are also using jQuery, you can now use $mdGestureProvider in 
```js
   app = angular.module('MyApp', ['ngMaterial'])
      .config(function( $mdGestureProvider ) {
          $mdGestureProvider.skipClickHijack();
      });
```
This will configure $mdGesture to **not** intercept clicks (stop propagation and prevent defaults).

If your issues persists, please open a **new** issue. Do not comment on this one.

**Comment by dg1202** [comment]
That did the trick! Thanks a mil

**Comment by ThomasBurleson** [comment]
@dg1202 - #ftw, excellent. Thanks for using Angular Material.

**Comment by chriseyhorn** [comment]
I had the same issue with Leaflet maps.  This fix worked for me.

**Comment by magnolo** [comment]
thx a ton...

**Comment by adam-s** [comment]
I'm using Angular Leaflet Directive with Angular Material Design. The controls on the map on mobile devices don't work. If I use `$mdGestureProvider.skipClickHijack();`, what features of Material Design do I lose? Am I making a sacrifice?

**Comment by johnedvard** [comment]
@adam-s I just tried to use one of the `md-swipe` directives e.g `md-swipe-right`, and they do not work if I use the `$mdGestureProvider.skipClickHijack();`-call. I ended up using angular's `ng-touch` directive instead.
