### ISSUE TITLE
TypeScript Definition (.d.ts) File

### ISSUE THREAD

**Issue by rdesimone** [angular/material#1323]
It would be a good idea to provide a TypeScript definition (.d.ts) file for Angular Material.

**Comment by marcysutton** [comment]
PRs welcome :smile:

**Comment by rdesimone** [comment]
@ThomasBurleson maybe a good idea to reopen (after watching ng-conf)

**Comment by juanfranblanco** [comment]
Please reopen

**Comment by PrashantAshok** [comment]
@rdesimone : it has been created https://github.com/borisyankov/DefinitelyTyped/tree/master/angular-material

**Comment by rdesimone** [comment]
@PrashantAshok Thanks, will look at it!

**Comment by ThomasBurleson** [comment]
@jelbourn - do you have time to review [angular-material.d.ts](https://github.com/borisyankov/DefinitelyTyped/blob/master/angular-material/angular-material.d.ts) and perhaps build a full, complete, correct version?

**Comment by jelbourn** [comment]
@ThomasBurleson I might have some time over the next few weeks, but I think this is something where it would be much better for someone from the community to add via PR.

**Comment by rdesimone** [comment]
@ThomasBurleson IMO should be created and maintained by the core team.

**Comment by mtraynham** [comment]
I didn't realize there was PR for this...

@ThomasBurleson @jelbourn I wrote the definition for DefinitelyTyped based on the documentation.  The theme-ing definitions were a result of debugging the theming service... Even though it's worked for me without error, I encourage someone to validate them or angular-material provide their own.

**Comment by ThomasBurleson** [comment]
Also consider this partial TypeScript definition file: https://github.com/borisyankov/DefinitelyTyped/blob/master/angular-material/angular-material.d.ts

**Comment by rdesimone** [comment]
@ThomasBurleson build a TypeScript AM sample today, found some issues which IMO should be changed or discussed. Where to discuss this?

**Comment by ThomasBurleson** [comment]
@rdesimone - let's discuss this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial). I will track and contribute...

**Comment by alexeagle** [comment]
Note that for Angular 2 (and any material components for Angular 2), we will ship .d.ts files for TypeScript users to compile against. That's convenient because we'll use TypeScript compiler on our code, and should be able to mark the public API and machine-generate the .d.ts file.

For project which aren't authored in TypeScript (Angular 1 and current Angular Material) it's a manual, error-prone task to maintain the .d.ts files. So I agree with @jelbourn that we follow the current community contribution process in DefinitelyTyped for these projects.
