### ISSUE TITLE
Required attribute doesn't prevent form from submitting

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1360]
I have an input in a form and the form still submits even though I have the `required` attribute and the input is empty. The class `ng-invalid-required` is present, but the functionality it seems isn't.

**Comment by gustavohenke** [comment]
This is not a problem of the Angular Material team.

If your form have the attribute `novalidate`, then the DOM `submit` event will occur normally. It'll be your task to verify if your form is valid in your call inside `ng-submit` directive.
This is likely the case when using a framework that does provide form validation styles, like Angular Material. because their styles are beautiful, unlike the browser defaults.

**Comment by ilanbiala** [comment]
@gustavohenke I don't have the attribute `novalidate`...I want the form to be validated and it isn't as of now.

**Comment by rschmukler** [comment]
@ilanbiala can you submit a codepen / jsfiddle demoing this?

**Comment by gkalpak** [comment]
BTW, a form **should** get submitted normally (by default) even if the fields are invalid. There are legitimate cases, where one might want that. If not you can handle the logic yourself.

**Comment by ilanbiala** [comment]
@gkalpak that should be the case when there are not `required` attributes set on inputs.

**Comment by ilanbiala** [comment]
Seems like I just had to tweak the form container placement to surround the buttons in the md-dialog.
