### ISSUE TITLE
$mdThemingProvider backgroundPalette does not theme the background

### ISSUE THREAD

**Issue by jaderabbit** [angular/material#1450]
I configure the theme provider as follows: 
```
$mdThemingProvider
            .theme('default')
            .primaryPalette('deep-orange', {
                'default': '900',
                'hue-2': '500'
            })
            .backgroundPalette('grey', {
                'default': '200'
            })
            .accentPalette('orange');
```

But the background remain's white

**Comment by nicbon** [comment]
It would be really great to have this working.

**Comment by ThomasBurleson** [comment]
@rschmukler - any interim thoughts while we resolve this for 0.9.x ?

**Comment by blackendstudios** [comment]
it takes the '50' value when you set the backgroundPalette, so maybe an easy workaround will be that you can put the background color on the '50' while this get fix... what do u think?

**Comment by gustavohenke** [comment]
@blackendstudios that trick helped me, but I rather use something less "hacky", so I'll just :+1: this issue.

**Comment by blackendstudios** [comment]
ohhhh glad that helped...it was my firts contribution on git hubjajajaja ...great...hope to help more in the future

**Comment by Hendrixer** [comment]
:+1:

**Comment by arshabh** [comment]
This issue is similar to #1321 . The reason why it takes the 'A100' value always is because it is the default color for 'hue-3'. And after digging in the code i found that the theme sass files for components have hard coded background color as:

```javascript
md-content.md-THEME_NAME-theme {
  background-color: '{{background-hue-3}}';
}
```
The above example is from `content-theme.scss`. Similar mention is also found in other theme files like `dialog-theme.scss`, `sidenav-theme.scss`, `slider-theme.scss` and `subheader-theme.scss`.

The solution that i propose for this is something like this

```javascript
md-content.md-THEME_NAME-theme {
  background-color: '{{background-color}}';
}
```

This has started working for me in my local build. But i guess the solution would be more comprehensive - providing background capabilities in a more generic manner. Just putting it out there. Hope it helps

**Comment by dpipkin** [comment]
@blackendstudios Do you change the 'A100' value on `primaryPalette` or `accentPalette`?

**Comment by arshabh** [comment]
@dpipkin it  is on `backgroundPalette`

**Comment by blackendstudios** [comment]
backgroundPalette :)

**Comment by dpipkin** [comment]
Awesome! Thank you.  
The hacky way that I made it work:
```
var background = $mdThemingProvider.extendPalette('grey', {
  'A100': 'f2f2f2'
});
$mdThemingProvider.definePalette('background', background);
$mdThemingProvider.theme('default')
 
...

  .backgroundPalette('background');
```
I hope that isn't too roundabout.

**Comment by rschmukler** [comment]
@dpipkin that is the proper way to achieve this. Waiting on #1950 to see if a clearer way emerges from it.

Closing this issue for now, but follow #1950 to see a potential enhancement
