### ISSUE TITLE
md-dialog: support `.hmtl()` for alert and confirm dialog?

### ISSUE THREAD

**Issue by SummerWish** [angular/material#1495]
I don't want to clone an alert / confirm dialog template & controller only to add newlines.
I prefer adding `html()` method or adding `newline` filter to alert & confirm dialog.

What do you think?

**Comment by marcysutton** [comment]
Can't you use a custom template to create your own HTML? Alert and Confirm dialogs are meant to be presets.

**Comment by breeswish** [comment]
Yeah, but I think alert and confirm should be 'behavioural presets' mainly, leave the content customizable (text or html).

**Comment by ilanbiala** [comment]
@marcysutton what about allowing `\n` and `\t` to be parsed in the `.title()` and `.content()` strings?

**Comment by ThomasBurleson** [comment]
Since the $mdDialog uses  `<md-content>... </md-content>`, I think the `$mdDialog.alert().content( )` API  should be used to insert **any** innerHTML content.  Currently that method is used to inject text into a `<p>` area... which is not an intuitive API. 

*  `.content( ref )` should accept any unescaped string value (HTML) and inject as a child of the `<md-content>` container
*  `.message( ref )` should accept any simple text and inject as the body of the of the `<md-content><p>{ref}</p></md-content>`

**Comment by kamarouski** [comment]
+1. Was thinking to implement my own version of confirm dialog as I need to bold some text in a message. As 0.10 milestone is in rc stage now I'll wait for this issue to be fixed.

**Comment by houmark** [comment]
Any news here?

**Comment by ThomasBurleson** [comment]
`.content()` will support simple strings or strings with HTML markup.

**Comment by houmark** [comment]
:+1: Nice work! I'll be testing soon :)

**Comment by metamatt** [comment]
In case anyone else wonders why they had this working in 0.111 and then it stopped working in 1.0: see 6a564508567cf1e352495bdf803f6db94334c601.

**Comment by rodwin** [comment]
Is there any specific reason why this has been removed?

**Comment by SummerWish** [comment]
You can use htmlContent

**Comment by rodwin** [comment]
@SummerWish You are right. Thanks
