### ISSUE TITLE
cant deselect all md-tab

### ISSUE THREAD

**Issue by djindjic** [angular/material#1508]
one of tabs is always selected. I have tried to set selectedIndex to -1 but last selected tab is still underlined.

**Comment by marcysutton** [comment]
Why would you deselect a tab? Every tab interface I've ever seen has one selected always.

**Comment by djindjic** [comment]
interesting point, maybe you are right. my idea was to have two tabs as two different routes (/route1 and route2), but if I go to home (/) route I want those two to be deselected.

**Comment by marcysutton** [comment]
What do you plan on showing in the tabs content area when there isn't a tab selected? The component isn't really intended to be used that way–there is always at least one tab selected. I think if you're running into this kind of limitation, the tabs component might not be the right pattern for your content.

**Comment by djindjic** [comment]
I agree, thanks.

**Comment by whijasn** [comment]
@marcysutton  We recently switched to 0.10.1. We have found that when a button on a page with md-tabs pops up a dialog with a form in it, the inputs are disabled and appear to be read only. The same dialog works just fine on pages without tabs. We are wondering whether the cause is due to the tabIndex/Focus being stuck in the tabs, rather than being passed to the form in the dialog. What is causing the inputs to be unclickable on the tabs pages? If it has to do with the tabIndex/SelectedIndex/ Focus then maybe this is a reason to be able to de-select all tabs and move the focus to the input tags making them clickable? From our point of view it seems that the presence of the tabs are related to our problem. Do you think they are related? What else may cause the input to work correctly on certain pages, but not on others(The ones with the tabs)? Certainly feel free to answer the question related to this post, and any info you can give us would be wonderful. Is this issue addressed in a different post somewhere? Thank you so much

**Comment by marcysutton** [comment]
@whijasn this is a closed issue, and that is way too much detail for a comment. Please post in the [Angular Material forum](https://groups.google.com/forum/#!forum/ngmaterial) with a Codepen or other demo showing your issue, or open a new bug on Github if appropriate.
