### ISSUE TITLE
Input type="file" not working on mobile devices.

### ISSUE THREAD

**Issue by douwevdijk** [angular/material#1545]
Hi All,

When I add a regular <input> tag with type="file" the element is disabled or at least I am not able to select it and no dialog appears. 

FYI: I am using master.

How can I fix it?

Rgds, Douwe.

**Comment by marcysutton** [comment]
I wonder if `$mdGesture` is preventing access to the input. @rschmukler what do you think?

**Comment by douwevdijk** [comment]
Hi, it is a lot to put my code on plunkr. The issue is only occuring when using #master. No issue on 0.7.0 or 0.7.1.

**Comment by marcysutton** [comment]
Definitely mdGesture then, sounds like.

**Comment by demisx** [comment]
We are experiencing this issue as well. Loading angular material JS file, stops `input="file"` selector working on iPad and iPhone (iOS 8 and 7). Not sure if this also affects Android. 

Here is the plunkr: http://plnkr.co/edit/cddmqDqDv6qLiw2RqyKT?p=preview. Removing this line makes it work again:

```js
<script src="https://rawgit.com/angular/bower-material/master/angular-material.min.js"></script>
```

**Comment by zasied** [comment]
Can confirm - it doesn't work on iPad/iPhone iOS 7&8. But it does work on iOS 6 (iPod Touch OS 6.1.3). It also does work on Android (Xoom Tablet really old OS: 4.0.3). Hope it helps to narrow it down.

**Comment by firmcontact** [comment]
I have the same issue with submit buttons, works if I add ng-click. Submit button works on iPad and Galaxy 4S but not iPhone 6.

**Comment by rgolea** [comment]
Isn't there a stylish input type="file"?

**Comment by rgolea** [comment]
Just got it

```
input[type="file"] {
    display: block !important;
    width: 100% !important;
    height: 100% !important;
    opacity: 0 !important;
    overflow: hidden !important;
    z-index: 100 !important;
    margin-top: -20px;
    padding-top: -20px;
    top: -20px;
}
````

Use the css above like the example below:

```
<md-button>
                Select file
                <input type="file" />
</md-button>
````

**Comment by demisx** [comment]
I see this works in Safari iOS on iPad at least, but CSS kills all of the
Material Design. Looks just like a plain static button on my end.

**Comment by demisx** [comment]
Here is some more details on @Rares Golea's solution.

* The ripple effect doesn't appear on Chrome Mac
* Attach file popup is not triggered on Windows Firefox and IE11
* Button dimensions are different from the original <md-button>. Would be
great if they could stay the same.

Perhaps these could be fixed with CSS?

**Comment by rgolea** [comment]
Maybe... I really don't know what to say. It really surprises me that the ripple effect doesn't work on your Chrome. On mine does and I'm developing on Mac.
The third issue I did notice. I don't know how to fix it. If someone comes up with a solution please let me know. For now I'm making my md-button 100% wide.
The second issue I really didn't know about it.

If someone comes up with an idea... please post it here for the benefit of the entire community.

**Comment by demisx** [comment]
@rgolea Thank you for taking a stab at it. You button does work on mobile and it's a great improvement already!

**Comment by rgolea** [comment]
@demisx Thanks!

**Comment by ajoslin** [comment]
Looks like input type="file" can't be opened my a fake MouseEvent either, and our block of the normal click on iOS is stopping this.  We should add an exception to our click blocking for certain elements.

**Comment by demisx** [comment]
@ajoslin :+1: please. None of our upload input elements currently work on iOS. Also, what do you think about @rgolea approach of passing `<input type="file">` inside `<md-button>`. Does this look like a proper approach or will there be a dedicated file upload button in future releases?

**Comment by zasied** [comment]
Downloaded latest angular-material (v0.8.3) and it works a bit better but still fails on iOS (iPad iOS 8.1.3) - now the event to render file dialog is fired so that I can either choose existing photo or take snapshot - but "change" event is not propagated. So my javascript function that is registered with "change" event of input file is never called... Prior to this version I couldn't even get the file dialog to appear. Actually what is weird, my function got called like once, but then never again (on dozens of tests). Really bizarre...

**Comment by jeroenvheel** [comment]
i have the same issue (iphone 5s, iOS 8.2.0)
the fix @rgolea did not work for me.

**Comment by marcysutton** [comment]
@demisx it's actually undesirable to put the file input inside of a button, because they have contradicting semantics (inputs can't be nested in buttons). The fact that you can't tap on it on mobile devices is an shortcoming of the library (which we are working on), but embedding it into a button just compounds the problem. 

Additionally, the design spec outlines the FAB with a plus sign in it as the correct way to signal file upload. http://www.google.com/design/spec/components/buttons.html#buttons-floating-action-button
This is really a new component, which we'll have to build support for. In the meantime, allowing taps to be registered on the native file input makes sense.

**Comment by marcysutton** [comment]
In my latest testing, I found that the Angular Material library does not interfere with the native behavior of `<input type="file">` on iOS. On an iPhone, tapping the input brings up "Take Photo or Video" and "Photo Library". 

@zasied can you post a Codepen or Plunker showing your change issue, so we can debug that? Otherwise I will mark this issue as fixed.

**Comment by demisx** [comment]
@marcysutton Understood. I am actually keeping the input outside of the button in my code. I just need a way to convert an md-button to a file upload button. I can't use FAB, since the file upload in my form is not a promoted action per se--it has same weight/importance as other form fields. 

I've tried to test my form against the master, but the form doesn't even render completely. Either there is a bug in master, or it had some serious breaking changes. I had to roll back to latest 0.8.3 release where the form renders properlhy, but the file upload input doesn't work.

Here are the plunkers for the plain `<input type="file">` form element + ngMaterial: 
Against 0.8.3: http://plnkr.co/edit/cddmqDqDv6qLiw2RqyKT (doesn't work)
Against master: http://plnkr.co/edit/IyGRAiMWbJYqOdd4QqYU (works)

**Comment by ThomasBurleson** [comment]
@demisx - 

*  In 0.8.3, Angular Material Gestures would activate upon script load
*  In master, mdGestures will activate only during the run phase of the ngMaterial.core module.

This means, if you do not use ngMaterial (within an AngularJS app), then Gestures will **not** activate; which is the expected functionality.

> Please note that your Plunkrs will never work .... you did not include the full dependencies for Angular Material nor create an ng-app or bootstrapper.

**Comment by ThomasBurleson** [comment]
To get `<input type="file">` to work with mdButton, you must use a `<label for="<link id>" />`. See below for working sample:


```html
<html>
  <head>
    <link rel="stylesheet" href="https://rawgit.com/angular/bower-material/master/angular-material.css">
    <style>
      #file-input { display: none; }
    </style>
    
    <script src="https://code.angularjs.org/1.4.0-beta.6/angular.js"></script>
    <script src="https://code.angularjs.org/1.4.0-beta.6/angular-animate.js"></script>
    <script src="https://code.angularjs.org/1.4.0-beta.6/angular-aria.js"></script>
    
    <script src="https://rawgit.com/angular/bower-material/master/angular-material.min.js"></script>
  </head>

  <body ng-app="app" >
    
    <div>
      <h2>File Upload with Material:</h2>
  
      <md-button>
        <label for="file-input">Select</label>  
      </md-button>
      <input id="file-input" type="file">
      
    </div>

    <script>
      angular.module('app', ['ngMaterial']);
    </script>
  
  </body>
</html>
```

@see [Plunkr](http://plnkr.co/edit/tX1BkAYEgdvRCWib0ZA0?p=preview)

Use of the latest Angular Material now shows this **Input type="file"** is working.

**Comment by ThomasBurleson** [comment]
I will close this issue as resolved. But I will also open a new issue (as suggested by @marcysutton) for **mdButton and FABs with input types**. @see #2151

**Comment by demisx** [comment]
@ThomasBurleson Thank you for sharing your example. I've intentionally excluded all dependencies from the previous plunkers to show that just simply including 0.8.3 ngMaterials JS file breaks plain `<input type="file">` functionality in iOS. I've tested your plunker in Safari iOS 8 (iPad) and unfortunately, it still doesn't work. Clicking `SELECT` triggers nothing.

**Comment by ThomasBurleson** [comment]
@demisx - thx for the alert. I will reopen and investigate.

**Comment by rgolea** [comment]
Wow people! Really nice work! Keep it up!

**Comment by zasied** [comment]
Yes, user demisx is correct - still doesn't work. I'd encourage you guys to please test it from iOS, including anything you throw on Plunkr, before you come back and attempt to bless any potential "fix". Tried with iPad, iPhone versions 8.1.3 and 8.1.2 respectively

**Comment by jeroenvheel** [comment]
this one is fixed with this commit : https://github.com/angular/material/commit/2c57a8289f73265ca41fc8b2fbbe173a80073caa

**Comment by infacq** [comment]
Ive tried this

````html
<md-button>
        <label for="file-input">Select</label>  
</md-button>
<input id="file-input" type="file">
````
but if `<md-button>` is surrounded by `<form>` tag, it actually will trigger form submit. What do you guys think? should I wrap it inside form tag?

**Comment by davemerwin** [comment]
If you add type="button" to the button it shouldn't submit it unless you bypassed that somewhere else.

**Comment by codeFire97** [comment]
hi, this work for me 
add to info.plist :
privacy - Photo Library Usage Description
privacy - Camera Library Usage Description

The problem was in the security of the xcode that does not allow the access to the camera and gallery if you do not specify so that you use them

**Comment by nehapraksh** [comment]
We had the same problem while working on one of our projects. After exploring a lot we found some solutions and able to run it on android. But, there is still some issues with the android version 4.4-4.4.2 because these versions do not support it. For more details of the problem and its solution, visit the below link:
http://www.ipragmatech.com/fix-html5-file-input-cordova-android/

**Comment by IgorKurkov** [comment]
I haven't material lib in the angular 7 project but input[type=file] not showed on mobile anyway. The fastest solution is - make custom upload button...
