### ISSUE TITLE
$mdGesture public API

### ISSUE THREAD

**Issue by mprokopowicz** [angular/material#1546]
Will the $mdGesture service be public? For now we have some problems with adding custom events to our app. We will be happy to rewrite some parts of our code to use $mdGesture but it is unclear if it is designed to be used "outside" of ngMaterial.

**Comment by gustavohenke** [comment]
I'm also interested to know.
I have kicked Hammer.js from my app when it was kicked from ngMaterial, mainly because of [the answer to this commentary](https://github.com/angular/material/pull/1257#issuecomment-71038421).
As a result, I've been hacking around the `$mdGesture` API so I could keep the same custom events I had with Hammer.

**Comment by ThomasBurleson** [comment]
@rschmukler - any objections or concerns ?

**Comment by rschmukler** [comment]
Nope. I think it'd be good to be a public API. We just have to document it better.

**Comment by karolkochan** [comment]
Any updates or plans when we could expect public API for $mdGesture?
