### ISSUE TITLE
feat(icon): Replace SVG icon cache with embedded SVG document <defs>

### ISSUE THREAD

**Issue by programmist** [angular/material#1548]
## Overview
Our current md-icon caching solution involves keeping a JavaScript object map of ID to DOM element. When a cached icon is referenced, it is pulled from the cache, cloned, and appended to the md-icon element. 

So, this:

    <md-icon md-svg-icon="action:android"></md-icon>

produces something like this

    <md-icon md-svg-icon="action:android">
      <svg><g id="android" path d="..."></g></svg>
    </md-icon>

Instead of maintaining this mapping we could instead create an embedded SVG document, appended to the ```<body>``` element, and add SVG definitions to the ```<defs>``` section.  This would enable referencing icons by id using ```xlink:href``` instead of creating copies of the SVG.

So, this

    <md-icon md-svg-icon="action:android"></md-icon>

could produce this

    <md-icon md-svg-icon="action:android">
      <svg><use xlink:href="#action-android"></use></svg>
    </md-icon>

And our embedded document might look something like this

    <body>
      <svg xmlns="http://www.w3.org/2000/svg" id="md-icon-embedded" style="display: none;">
        <defs>
          <g id="action-android" path d="..."></g>
          <g id="action-alert" path d="..."></g>
          ...
          
          <symbol id="social-cake" path d="..."></symbol>
        </defs>
      </svg>
      ...
    </body>

## Considerations
* How will this work with projects like [grunt-svgstore](https://github.com/FWeinb/grunt-svgstore)?
* Should we offer a config option that eager loads all configured icons into this document on start-up?

**Comment by Frank3K** [comment]
I like your idea, it is a better way of using SVG-icons than the way they are used now. It makes use of specific SVG-features which are intended for this (and similar) purpose(s). Furthermore I think this solution performs better since you do not need to inject a partial DOM every time a given icon is used.

The solution is way better than the one I provided for a related issue (#1514) on SVG symbols.

> How will this work with projects like [grunt-svgstore](https://github.com/FWeinb/grunt-svgstore)?

As far as I can see, what you describe is exactly what [grunt-svgstore](https://github.com/FWeinb/grunt-svgstore) is made for.

> Should we offer a config option that eager loads all configured icons into this document on start-up?

I'm not sure what you mean. Do you want to construct the SVG sprite-map client side? 

#### Notes:

You can even add the complete URL in the `xlink:href` and let the browser handle everything. Unfortunately, this does not work in Internet Explorer, where you need to resort to polyfills like [svg4everybody](https://github.com/jonathantneal/svg4everybody).

#### References:
* [Icon System with SVG Sprites](http://css-tricks.com/svg-sprites-use-better-icon-fonts/)
* [SVG `symbol` a Good Choice for Icons](http://css-tricks.com/svg-symbol-good-choice-icons/)

Both by Chris Coyier from css-tricks.
