### ISSUE TITLE
md-tabs: Single tab w/ stretch is not centered

### ISSUE THREAD

**Issue by rgthree** [angular/material#1570]
`<md-tabs md-stretch-tabs="always">` does not center a single-tab correctly (see that last example below, which should have the label "one" directly below the title):
![dy2jkvpzwk 2](https://cloud.githubusercontent.com/assets/476360/6271714/a2b9143e-b830-11e4-9a5e-ff093d57afc7.png)
_(#1506 has the scrollbar issue)_

Looks like it has a `width` style _that is correct_ but also a `min-width` that keeps it shorter. Here's a live jsbin: http://jsbin.com/guweto/2/

**Comment by mckenzielong** [comment]
This is caused by max-width being set smaller than the stretched width of the tab.  
In TabPaginationDirective, max width is calculated with this in calculateTabData:
```javascript
var tabsWidth = clientWidth - PAGINATORS_WIDTH - 1;
```

After the style is applied there is an adjustment done for stretched tabs:
```javascript
function adjustForStretchedTabs() {
     var canvasWidth = pages.length === 1 ? clientWidth : tabsWidth;
     var tabsPerPage = Math.min(Math.floor(canvasWidth / max), tabs.length);
     var tabWidth    = Math.floor((canvasWidth / tabsPerPage));
     $tabs.css('width', tabWidth + 'px');
     return calculateTabData(true);
}
```

Which sets the width to a value 65px larger than max-width (or PAGINATORS_WIDTH+1 px)
