### ISSUE TITLE
What is the distinction between docs and core?

### ISSUE THREAD

**Issue by DavidSouther** [angular/material#1718]
For instance, when using `md-toolbar` with an h2 class `md-toolbar-tools`, I expect my code to look "exactly" like the demo. However, the 16px padding left on `h2.md-toolbar-tools` is in the docs.css, not a part of the core. As a user, I expect the demos to be copy/paste and "just work"; instead, I need to dig into the docs.css to get the same visual styles.

Please add (or point me to) a task that covers untangling these on the release milestones. Thank you!

(PS I love watching the features as they keep rolling in!)

**Comment by ThomasBurleson** [comment]
Related to #594

**Comment by marcysutton** [comment]
The CSS API (#594) and Typography defaults in #1128 will definitely help this. 

However, I looked at the docs CSS file (`docs/app/css/style.css`) to make sure there weren't any styles included that should have been in `toolbar.scss` or elsewhere. There are some changes coming for this, but I found that there were no padding styles for `.md-toolbar-tools` in the docs CSS. Rather, you are seeing that the docs build system packages Angular Material along with the docs CSS, so in the browser it looks like the styles are attributed to the docs CSS, rather than the framework. @ThomasBurleson I bet it would help to separate `docs.css` from `angular-material.css` in our build system to clarify where the styles are coming from. 

In any case, I'm working on the toolbar style defaults so that they work with headings out of the box, as I ran into the same issue when I created the [Hello World Codepen](http://codepen.io/marcysutton/pen/OPbpKm).
