### ISSUE TITLE
md-subheader ng-view

### ISSUE THREAD

**Issue by rgolea** [angular/material#1772]
Hi there! I've got an issue with md-subheader. Every time I change my route with ng-view the subheader starts behaving wrong. I would like to know if I'm the only one.

**Comment by WhiteAbeLincoln** [comment]
I have the same issue. The subheader moves somewhere to the middle of the page, instead of being the default width of the toolbar from the top. I also have an issue where the subheader gets hidden behind a locked open sidenav, even though the containing element doesn't do this. 
![screenshot from 2015-03-21 17 01 54](https://cloud.githubusercontent.com/assets/7330103/6766818/2cdc9e2e-cfec-11e4-89a0-49f2d5c9a585.png)

**Comment by jelbourn** [comment]
@rgolea @WhiteAbeLincoln can someone provide a demo?
