### ISSUE TITLE
Upon tab reapearing selection is not taken into account

### ISSUE THREAD

**Issue by yccteam** [angular/material#1777]
First of all, I never mentioned how I LOVE this angular-material project.
Here's the codepen example:
http://codepen.io/yccteam/pen/GgGbzO
The issue is this:
1) Tabs are created and work fine.
2) When I click on "Change IF" the tabs are supposed to disappear due to ```ng-if``` - works great.
The problem is:
3) When  "Change IF" is clicked again, the ``ng-if``` is satisfied and shows the tabs again. but ```md-select``` isn't taken into account once the tabs reappear.

I've also added the "ng-show" for sports (just click  "Change SHOW"  to play with it).
It works, but now I need to take care of the ```md-bar```, which is external to the tab itself.

I currently sove this using a hack with a watcher that sorts things out, but using a watcher while I already have a watcher (```ng-if```) seems very... hackish...

Is this behavior intentional? Any way to solve this within the API?

Added later:
I've added another functionality that recreates a bug in the tabs:
1) Click on the "Change SHOW" in order to make the tabs to disappear.
2) Then click on the "Change Tab" until the tab index changes (the number below the button)
3) Click on "Change SHOW" in order to make the tabs reappear.
4) Note the tabs appear wrong

**Comment by tic2000** [comment]
Hello,

I'm not any expert, but...

Regarding your first issue. The index md-selected is taken into account. The problem is that when you remove the tabs from the dom (which is what ng-if does) that index is set to -1, which you can clearly see in your output.

To fix that without a watch you can assign a function to the click instead of doing a x assignation. In that function you store the index before you change the value of x. [Here is a codepen](http://codepen.io/anon/pen/pvZGQw) to see what I'm talking about.

Regarding the second issue. First and foremost I see an error when the index is changed while the tabs are hidden. I changed the [line 191 of paginationDirective.js](https://github.com/angular/material/blob/8364fb57a9ac1b211c09ff564fea6ad0dea94e61/src/components/tabs/js/paginationDirective.js#L191) to
```javascript
          currentPage = currentPage || {};
          currentPage.lastTabIndex = index;
          currentPage.tabs = currentPage.tabs || [];
```
which fixes the error.
Another issue there is that the tab width is not calculated correctly when the tabs are shown again, but I leave that to people which understand this better then me.
