### ISSUE TITLE
md-select: overflow: hidden of parent md-content in mac after open md-select

### ISSUE THREAD

**Issue by pradeepkumarrawat** [angular/material#1778]
There is problem with *md-select* in mac(because in few other OS it works). When a user click on mdSelect it disable the parent mdContent scroll(with *overflow: hidden*) but after closing it didn't back to *overflow: auto* so user is unable to scroll the page after that.

**Comment by pradeepkumarrawat** [comment]
I used overflow: auto !important; for now in parent mdContent to work it correctly.

**Comment by rschmukler** [comment]
@pradeepkumarrawat thanks for the report. Can you try [this demo](http://jsfiddle.net/rschmukler/2dykxg1a/) based on master. I just tried on the latest Safari (8.0.5) and it seems to work correctly. I'm wondering if the issue still exists. If so, please submit a plunkr/codepen/jsfiddle with some example code so that we can track down this issue.

Thanks!

**Comment by pradeepkumarrawat** [comment]
@rschmukler  thanks seems fixed.
