### ISSUE TITLE
md-checkbox with md-no-ink causes ng-change or ng-click to be called twice

### ISSUE THREAD

**Issue by evanshortiss** [angular/material#1813]
Hi, 

Just reporting a small bug I came across. When _ng-click_ or _ng-change_ is used on an _md-checkbox_ with _md-no-ink_ applied the _ng-change_/_ng-click_ will be triggered twice.

No promise on a bug fix as of yet since I haven't looked into it.

With the following markup I can reproduce it:

```html
<md-input-container>
	<p>Do you like Material Design?</p>

	<md-checkbox
		ng-model="input.value"
                md-no-ink
		ng-change="save()"
		class="md-primary">
		<span ng-show="input.value == true">
			YES
		</span>
		<span ng-show="input.value == false || input.value == ''">
			NO
		</span>
	</md-checkbox>
</md-input-container>
```

**Comment by marcysutton** [comment]
Hi, can you provide a live demo using Codepen or Plunker so we can see the bug in action? 

Also, there are labeling problems with your example. The child `<span>` elements are incorrectly being copied to an `aria-label` attribute and making the checkbox unclear to screen readers ("Yes"/"No" instead of "Do you like Material Design"). The simplest fix for preserving the existing style would be to use `aria-labelledby` on the checkbox and an `id` on the paragraph tag:
```html
<md-input-container>
    <p id="some-input-label">Do you like Material Design?</p>

    <md-checkbox aria-labelledby="some-input-label"></md-checkbox>
</md-input-container>
```

**Comment by evanshortiss** [comment]
Hi @marcysutton I'll try to get this recreated in a Plunker asap

**Comment by robertmesserle** [comment]
I am closing this issue for now.  I am unable to recreate this issue with the latest code from master.
