### ISSUE TITLE
Fix peerDependency

### ISSUE THREAD

**Issue by kentcdodds** [angular/material#1848]
Thanks for using `peerDependencies`. That's awesome. However, when I try to install this via `npm` with the beta version of angular, it fails the `peerDependencies`. I actually don't know of a good solution to this as I'm also having issues with it in [my library](https://github.com/formly-js/angular-formly)... Would love it if we could come up with a solution.

**Comment by ThomasBurleson** [comment]
@kentcdodds - I think the semver (semantic versioning) ignores any   `1.x.x-SomeText` versions.

**Comment by kentcdodds** [comment]
So, are you saying that there's no way to solve this? :crying_cat_face:

**Comment by linclark** [comment]
I think this should work:

```
1.3.x || >1.4.0-beta.1
```

I'll put in a PR.

**Comment by ThomasBurleson** [comment]
@linclark - 

I did not know you could do use `||` to make combinations. Nevertheless, for Bower-Material I think trying to force bower support for **un-released** Angular builds should be avoided. You can always load newer, unreleased version explicitly with local bower overrides.


> Examples of unreleased builds: v1.4.0-build.3897+sha.1fc87e2

**Comment by linclark** [comment]
I'm not sure how/whether that would work in bower. The reason I was making the change to `bower.json` is because the `package.json` doesn't have the `peerDependencies` listed in it. IIRC, the way the Angular team does it, the versions are automatically copied from `bower.json` to `package.json` as part of the publishing process (but correct me if I'm wrong).

The effect the `||` has is to remove this error:

```
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package angular does not satisfy its siblings' peerDependencies requirements!
```

It will not force npm to download the beta. By default, npm will still download `1.3.x`. It will just allow someone who is depending on `angular-material` in their app to choose to use `angular@beta` if they want to.
