### ISSUE TITLE
Gesture update in 0.8.3 breaks sidenav on mobile if jQuery exists

### ISSUE THREAD

**Issue by davidMGS** [angular/material#1909]
http://run.plnkr.co/Lw0WmFqmGGWSvl7W/

Activating the sidenav on mobile will open and then close right away.  I was able to replicate this on Chrome on my One Plus One running Kitkat.  You can also replicate this in the Chrome using mobile emulation selecting any iphones on desktop.

**Comment by kevin-frugier** [comment]
I was going to post something along the same lines.

I'm using jQuery for easy scroll detection because md-subheader (through $mdSticky) is far too shaky on my Android 4.4.4 (the subheader element, when not sticky, shakes like hell during scrolling).
Plugging jQuery allowed me to get a similar behavior without the shakiness but then broke sidenav as you mentioned.

I'm getting a 404 on davidMGS's example  so I have forked the Hello World example of Angular Material.
The problem can be seen on forked code at http://codepen.io/kevin-frugier/full/KwrLWL (however I have a hard time showing it with Chrome emulator, sometimes it works, sometimes in doesn't, my site code (not on CodePen) using both sidenav & jquery indeed shows the problem mentioned by davidMGS.

**Comment by davidMGS** [comment]
Thanks @kevin-frugier for pointing out the plnkr issue.  I guess the live preview expires.  Here are the links to the plnkrs:

Embedded view - http://embed.plnkr.co/PgSHy8ITb9LVhvEcT8Hz/
Edit View - http://plnkr.co/edit/PgSHy8ITb9LVhvEcT8Hz?p=preview

**Comment by kevin-frugier** [comment]
Could this be related to #1842 & #1869 and therefore be fixed by https://github.com/angular/material/commit/81bcf7fd15fd76f054814b34d8a877168fc6225c ?

**Comment by ThomasBurleson** [comment]
Appears resolved with 81bcf7f
