### ISSUE TITLE
Allow card to go over toolbar

### ISSUE THREAD

**Issue by kai23** [angular/material#1943]
As for a minimal example : http://codepen.io/kai23/pen/OPaqXK

I want to make something like here : http://www.google.com/design/spec/layout/structure.html#structure-toolbars

(the 4th exampe)

Any idea how ?

**Comment by Toilal** [comment]
For some reason, it doesn't work when using `md-content`.

Is a working fork : http://codepen.io/Toilal/pen/JoeadV

**Comment by edbentinck** [comment]
After some research it seems to me that the issue here is the `overflow:auto;` property which is set on `md-content`. The `auto` setting doesn't really behave as you'd expect. So, whilst it looks like the `md-card` is being hidden behind the toolbar, the issue is actually that the overflow property on `md-content` is clipping the content.

Explicitly setting `overflow:visible` on `md-content` fixes it, as seen here: http://codepen.io/edbentinck/pen/RWeoaV

In that codepen I also tested the `overflow` issue using standard HTML elements and it's still the same. The `auto` setting doesn't let you offset the child element's position (upwards, at least) without clipping it.

I'd be hesitant to suggest changing the default `overflow` setting of `md-content`. For now it's probably best to stick with a utility class to override it. Thoughts?

**Comment by eshansingh** [comment]
What any of this still doesn't allow is the nice underline and title in the overlap area that's shown in the aforementioned example.
