### ISSUE TITLE
md-maxlength gives error for valid number inputs

### ISSUE THREAD

**Issue by EugeneKostrikov** [angular/material#1960]
See this fiddle for details http://jsfiddle.net/7fj2ad9n/3/ 
Try changing number input to see the error. Works fine for text though.

For sure maxlength doesn't make much sense for numbers :) But it would be better to skip validation if value type is not a string maybe? In my use case for instance there's a wrapper on top of md-input-container that works for both numbers and text.

**Comment by gkalpak** [comment]
Indeed, `mdMaxlength` behaves strangely at times.
IMO, it should follow `ngMaxlength`'s approach and check the `$viewValue`' length (instead of the `$modelValue`'s).

**Comment by brunofin** [comment]
Sometimes it makes sense in number fields, or at least it's just easier to use a length validator instead of a max value validator.

For example, I'm writing a form which one of the fields accepts any number between `0` and `999999`. That's a 6-digits length number. At first I used `min="0" md-maxlength="6"`, but not only it didn't work but it also caused the attached model's value to become `undefined`. When I realized `md-maxlength` was causing this problem, I simply switched to `min="0" max="999999"`. But I had to write down 6 times the number `9`.

In @EugeneKostrikov 's example, the input have `md-maxlength="123"`. Can you imagine to write down the number `9` 123 times in the `max` property, just to make this field work as required?

So there are two problems here: `md-maxlength` shouldn't make the value `undefined` in a number field, if it doesn't work, at least it should gracefully not work =P
And it would be good if it worked in number fields as well, so we have just one way to validate fields' length, even for number fields, after all, number also do have a length.
