### ISSUE TITLE
md-fab on bottom does not update position correctly

### ISSUE THREAD

**Issue by saberlash** [angular/material#1969]
Hello,

i have an angular app that is a step by step survey. At one of the steps, the screen size is bigger than the intial state and the fab button (md-fab-bottom-right) does not stay on the bottom. As you can see, it scrolls up. 
```
<div ng-controller="SurveyCtrl" layout="row" layout-align="center">
     <md-content flex flex-lg="70" flex-gt-lg="60">
           <asp:ContentPlaceHolder ID="MainBody" runat="server">
            </asp:ContentPlaceHolder>        
      </md-content>
      <md-button class="md-button md-fab md-fab-bottom-right" aria-label="Next" ng-click="next()" title="Next">
            <i class="fa fa-arrow-right"></i>
     </md-button>
</div>
```
Is this normal? Can i fix this issue only via design?
![md-fab-issue](https://cloud.githubusercontent.com/assets/6240629/6736507/a89cc794-ce3b-11e4-8f93-a1607de2ee58.png)

**Comment by mckenzielong** [comment]
People might suggest this is a better discussion for the [forums](https://groups.google.com/forum/#!forum/ngmaterial). I think this was done by design.  Like a few of the other elements, the fabs are positioned using position:absolute -- this is where this behavior is coming from.

I believe if you are able to swap out your div for md-content, this problem should just go away.

**Comment by saberlash** [comment]
You are correct. replacing the parent div with md-content fixed the problem. Thank you
