### ISSUE TITLE
$media is deprecated for is-locked-open. Use $mdMedia instead.

### ISSUE THREAD

**Issue by saffabook** [angular/material#1999]
Hi I have just done a bower install of angular-material#master, and implemented the select component. However every time I open the select my console logs out the warning in the title. 

Is this something to be concerned about and to be fixed later?

**Comment by GauravButola** [comment]
After this (https://github.com/angular/material/commit/8afc08d7773a504d7b0ce6fb3511bfb0341fa899) change.

You should be using `$mdMedia` instead of `$media` for `md-is-locked-in`.
So, if you had something like: `md-is-locked-open="$media('gt-md')`, change it to `md-is-locked-open="$mdMedia('gt-md')`.

Hope this helps.

**Comment by saffabook** [comment]
Hi thanks for the reply. 

I don't have any of those lines in, I basically just followed the basic options on this page. :/ 
https://material.angularjs.org/#/demo/material.components.select

It works perfectly, but just throws out that warning.

**Comment by saffabook** [comment]
I worked out what it was in the end. I was the sidenav component. Simple change in the end.

**Comment by brunofin** [comment]
@saffabook Can you please give more details? I also have this warning using a sidenav. What should be changed? Thanks.
