### ISSUE TITLE
Prevent ESC key from closing the menu

### ISSUE THREAD

**Issue by yccteam** [angular/material#2000]
Is there a way to prevent the ESC key to close the side nav menu?
I tried to listen on the document's ```keyup``` event, but to no avail.

**Comment by marcysutton** [comment]
Can you explain your use case? The ESC key is enabled for keyboard accessibility purposes.

**Comment by yccteam** [comment]
Hi,
My use case is quite simple - once the menu is closed, there's no way to get it back (this is the design of my app). I can overcome this by closing the menu (as happens now) and adding some 2em width ```div``` in its stead. Clicking the placeholder ```div``` would reopen the menu. I was hoping to avoid this extra logic by just disabling the ```ESC``` key event...

**Comment by ThomasBurleson** [comment]
Can you not use `md-is-locked-open="true || <expression>"` ?

**Comment by lebbart** [comment]
I have same problem. 
While I open mdDialog, than press Esc and modal closed as mdSidenav closed to! And this is really problem. How can I prevent this function of angular material??

/**
     * Auto-close sideNav when the `escape` key is pressed.
     * @param evt
     */
    function onKeyDown(ev) {
      var isEscape = (ev.keyCode === $mdConstant.KEY_CODE.ESCAPE);
      return isEscape ? close(ev) : $q.when(true);
    }

Thank you for answer!

**Comment by belakm** [comment]
I love angular material but this is very poorly handled.

`md-is-locked-open="true || <expression>"` is a bad solution as it doesn't work as expected (strange twitching and bad response). The only other solution i found is to cut out line 93 of angular-material.js, what seems like an awful solution.

under Services ($mdSidenav)
https://material.angularjs.org/1.1.3/api/service/$mdSidenav
there was a glimmer of hope that onClose handler exists, that turned out to be a document bug or something?

`$mdSidenav(componentId).onClose(function(){}); `
method does not even exist: 
![Uploading Screen Shot 2017-01-31 at 15.27.56.png…]()

overall i don't have an idea how to solve this without going into source.
Using finally is also not a solution as escape doesnt have a trigger.
