### ISSUE TITLE
Docs: "View on Github" links are not correct.

### ISSUE THREAD

**Issue by HenriqueLimas** [angular/material#2005]
The links for the services $mdIcon, $mdIconProvider and $mdMedia are not correct on the documentation.

The correct links are: 
 $mdMedia - https://github.com/angular/material/blob/master/src/core/util/media.js
 $mdIcon and $mdIconProvider - https://github.com/angular/material/blob/master/src/components/icon/iconService.js

**Comment by marcysutton** [comment]
We have a few options here:

* Rename `iconService.js` to `icon.js`
* Split up and rename `dialog.js` and similar components into directive/service files, change Service URL rule in `docs/config/processors/componentsData.js`
* Add a URL metadata to provide components with specific URLs instead of generated ones
* Use redirects
