### ISSUE TITLE
md-checkbox , md-radio-button: with theme set as dark, the labels are with black foreground

### ISSUE THREAD

**Issue by TalPasi** [angular/material#2054]
When the theme is set to dark, the checkbox border color changes and the same goes for the radio button circle , however the label is still black, rendering it very difficult to read 

This is demonstrated in the following link: [plunkr](http://plnkr.co/edit/PWXCXK6L3cpp3838stRK?p=preview)

**Comment by marcysutton** [comment]
The global foreground color on `document.body` is what needs theme support. The `select` and date `input` in your Plunker both suffer from the same problem as the switches/radios. If we add a theme color to the `body`, we can affect a lot of components at once, rather than putting theme colors in one at a time.

**Comment by TalPasi** [comment]
Great, I will try to find the time to submit this myself as a pull request

**Comment by marcysutton** [comment]
Have a look at #1599, it is a service that will make theming outside of components a lot easier.
