### ISSUE TITLE
mdButton: Keyboard pressed state should work similarly to mouse click

### ISSUE THREAD

**Issue by marcysutton** [angular/material#2089]
Although there is a focus state, buttons have no visible `pressed` state when using the keyboard. They should have some visual feedback similar to a mouse click.

**Comment by ThomasBurleson** [comment]
At a minimum, ripple effects should be trigger for spacebar/enter keypresses

**Comment by Aaronaught** [comment]
Enter/space triggering the ripple from the center of the button is exactly how it works in the [Polymer/Paper counterpart](https://www.polymer-project.org/0.5/components/paper-elements/demo.html#paper-button).

Is there a workaround in the meantime - some way to programmatically trigger the ripple? Otherwise it's somewhat of a usability/accessibility problem.
