### ISSUE TITLE
Chips styles inconsistent with spec

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#2098]
http://www.google.com/design/spec/components/chips.html#chips-contact-chips shows:

- [ ] font should be lighter (`color: rgba(0, 0, 0, 0.6)` seems to match a little better)
- [ ] font weight should be normal (just getting rid of the `<strong>` seems to fix it)
- [ ] the background should be darker (`background: rgba(0, 0, 0, 0.1)` seems to match better)
- [ ] vertical padding should be greater in proportion to the font (I'm assuming it's because it's not using rems to go off of the base font-size)
- [ ] focus/hover/click states are missing

A couple other points:

* What's the `transform: translate3d(0, 0, 0)` actually doing that would be useful? This shouldn't require GPU acceleration, and in some cases it can make it worse when you GPU accelerate 100 chips.
* The implementation also lacks the floating picture on the left, which would affect the padding of the chip as well. 
* The implementation is all px-based, so that may cause some issues.
* Why is there a need for `div.md-chip > md-chip`? In my mind, either do one or the other (unless there's no workaround, but I don't see anything that truly requires that outer div), but not both. People will mistakenly create 2 different (possibly conflicting/overriding) rule sets and in general it just crowds the DOM.

**Comment by typotter** [comment]
Thanks for reviewing the style. The current implementation is not going to match the spec at http://www.google.com/design/spec/components/chips.html#, as there is only spec defined for Contact Chips. Contact Chips will be a component built from this more basic implementation of Chips. I have been using a Google-internal spec for 'text chips', and it does appear that the two are somewhat inconsistent. :/

* Font-color: I used background-contrast from the theming pallet. I think I've found a way to get the 60% alpha, but am not sure it's supported
* font-weight: the `<strong>` in the first example is demonstrating use of a custom md-chip template. Perhaps I should change the template more so that it is more obviously a custom template...
* Background: The colour in the spec, `#E7E7E7` is not anywhere in the MD palettes. The colour listed in the internal 'text chips' spec is `#F5F5F5`, which is in the palette.
* Padding: the spec has px listed, so I've used that. 
* Focus/hover/click: I am adding focus styling. I have a larger change coming that adds ink to the chips (will take care of click state). There is no spec for the hover state.
* Transform: not doing anything useful as there are no other transforms on this element to override; removed
* Floating picture: again, this is not contact chips
* px-based styles: yup. Changing to rem where I can...
* div.md-chip > md-chip awkwardness comes from needing an 'md-chip' directive, but also a straightforward way for the caller to specify an md-chip template. I've updated the chips directive now to take only the innerHTML of the user-provided template
