### ISSUE TITLE
site css

### ISSUE THREAD

**Issue by scriptsure** [angular/material#2150]
could we put together a site css that could be delivered with material to give site styling that would not stomp on any material css? Get new projects up and running a lot faster, and a starting point. I am using material in a build now and finding that i am running into a lot of cases where things are looking incorrect (i.e. fonts, blocks, etc) because our site.css is messing things up....

**Comment by ThomasBurleson** [comment]
@daw451-duplicate - We have tried to namespace our CSS so it affects only the **md-** components and some content. Can you provide some examples where your `cite.css` conflicts with Angular Material CSS?

**Comment by daw451-duplicate** [comment]
well I am talking more generally... for instance if i set a line-height across the application or default fonts to be used. Here is a link due to settings in a site.css:

![image](https://cloud.githubusercontent.com/assets/798281/6983230/5ccf3c84-d9e9-11e4-8eac-a9eb155bae67.png)

Very fuzzy... typography much better in material.

All i am saying is to have a site.css, a starter set, to get things going to easily comply with material standards.

**Comment by ThomasBurleson** [comment]
We are planning (post v1.0 release) for a CSS Customization & Template Wizard.

**Comment by daw451-duplicate** [comment]
Tom any news on this? we are starting a new project and will be using v1.
