### ISSUE TITLE
md-select broken

### ISSUE THREAD

**Issue by jgoux** [angular/material#2283]
Hello,
on the master, md-select seems broken on Chrome : https://material.angularjs.org/#/demo/material.components.select
The options aren't aligned with the select input and the window goes crazy.

**Comment by ThomasBurleson** [comment]
With lots of window hiccups when the view is scrolled.
@rschmukler - I did not see these effects/issues before the latest theme changes; but that may be my oversight.

**Comment by kuhnroyal** [comment]
I am encountering 2 issues since 0.9.0-rc1 and on master that might be related to this.
Could you please have a look?

#1 md-toolbar scales to full screen size when md-select-menu is open
http://plnkr.co/edit/jS4jj0XwGxmG3Mos28Jd?p=preview

#2 independent content is resized when md-select-menu is open
http://plnkr.co/edit/WYtzl3xTc0QggCtQqk5y?p=preview
