### ISSUE TITLE
mdList: focus state on primary action never removed.

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#2319]
![screen shot 2015-04-14 at 6 40 08 pm](https://cloud.githubusercontent.com/assets/210413/7149649/b74ea6aa-e2d5-11e4-94f1-69929de3447a.png)

**Comment by nicu** [comment]
@ThomasBurleson did you use the keyboard to reproduce this bug? I just fixed it on my local machine and I'm currently reading the guide on how to submit pull requests.

**Comment by marcysutton** [comment]
Looks like the solution for preventing focus on mouse clicks isn't working with `md-proxy-focus` on mdList. You can reproduce it with the mouse by clicking on the list item part of "Single Action Checkboxes" or "Checkbox with Secondary Action", or by tabbing onto an item and toggling it with the space bar. 

Clicking on the actual checkbox is fine, since the mousedown logic for checkboxes applies to that element.

**Comment by nicu** [comment]
https://github.com/angular/material/pull/2339

**Comment by marcysutton** [comment]
Thanks @nicu!

**Comment by marcysutton** [comment]
Closed with 588e58cf6de9be13f77c820a1582f2d1a2c36cb0.
