### ISSUE TITLE
Support filtering for mdSelect

### ISSUE THREAD

**Issue by kartGoogle** [angular/material#2327]
If there are dozens of items in a list, the user may prefer to filter them rather than have to look through the list to pick the one they want.

Example: A country chooser. I often find it faster to type "Ind" to filter rather than look through the list for "India".

**Comment by erikverheij** [comment]
This would be really great! The LumX framework has this feature implemented already; http://ui.lumapps.com/directives/selects

**Comment by Splaktar** [comment]
This is similar to the ui-select or select2 functionality. One of my projects depends on this and cannot use md-select until both filtering and multi-select are available in a single component like mdSelect/mdAutocomplete. Coming from select2, we would expect this to be part of mdSelect. It might work to use mdAutocomplete, but we would need #1917 in order to only allow users to select items from a pre-defined list (like a select).

This is quite an important use case of enterprise applications.

**Comment by mattdanna** [comment]
+1

**Comment by stefan--** [comment]
+1

**Comment by bluebirdtech** [comment]
+1
