### ISSUE TITLE
md-button: Using buttons for href links inside paragraphs looked better in version 8.3

### ISSUE THREAD

**Issue by birdcw** [angular/material#2372]
Hello, I had previously used md-buttons for links, i.e: 

``` html
<p> this is a <md-button ng-href="#">link</md-button></p>
```

In version 8.3 the links a well-aligned and flow correctly when embeded in text. The attached plunker defaults to the master, and you can see an improvement when you change the CDN to 0.8.3. (typo in the title)

http://embed.plnkr.co/cAUEvSmsSQ7IQLdGqlMj/preview 

Since the buttons give you such nice hover and click animations out of the box, they were a nice way upgrade ordinary anchor text and it would be great to restore the original look of buttons when used in this context.

**Comment by marcysutton** [comment]
Hi, that's because the buttons weren't previously to spec. I haven't seen a Material Design example where they fit inline–flat and raised buttons have margins and specific line heights that don't match paragraph text. I would recommend not using `md-button` inside of a paragraph anymore, as it goes against the Material Design guidelines.
