### ISSUE TITLE
Readd css focus override

### ISSUE THREAD

**Issue by epelc** [angular/material#2404]
Hello I noticed the following in the changelog for `0.9.0-rc1` and I was wondering why.

`CSS Focus outlines not prevented by default`

The css focus outlines tend to be very ugly and go against all other material styles. They also tend to make apps generally look outdated and old. I tried looking for an issue for this but found nothing and I was wondering if there was some reason I missed that someone might want this.

**Comment by ThomasBurleson** [comment]
@marcysutton - care to provide thoughts here?

**Comment by marcysutton** [comment]
As a framework, removing global focus styles is a bad idea because it impacts anyone who includes the stylesheet. For Angular Material components, we replace the default focus style with an alternative, spec-compliant focus style. It's really easy to remove global focus style if developers so choose, and they might. But we are being more selective with how we override it.
