### ISSUE TITLE
md-tooltip: Incorrect positioning with md-content(not taking into account scroll)

### ISSUE THREAD

**Issue by epelc** [angular/material#2406]
It seems with `0.9.0-rc1` `md-tooltip` isn't taking into account `md-content`'s scroll as you can see in the picture below. This was after I scrolled about halfway down the page. My mouse was over the price but the tooltip showed up about where the price would be if I didn't scroll down. Note this worked perfectly fine in `0.8.3`.

![image](https://cloud.githubusercontent.com/assets/5204642/7217715/97e1856c-e60e-11e4-9490-b9cb342d9a23.png)

**Comment by Frank3K** [comment]
Can confirm the issue in Firefox 37.0.1 on Ubuntu 14.10.

**Comment by epelc** [comment]
I've tested on chrome 42 for windows 8.1 and windows 10. I'd guess this is browser independent.

**Comment by AxelTB** [comment]
Same in Chrome 41 and Iceweasel 31.6.0 on Debian 3.16

**Comment by AxelTB** [comment]
Try to put the element to be scrolled and the md-tooltip inside a
`<md-container style="overflow:visible">`

It worked for me...

**Comment by eabovsky** [comment]
I can reproduce on chromium 41 on windows and OSX.

**Comment by ThomasBurleson** [comment]
Solution: auto-hide tooltips upon scroll event detection.

**Comment by kasiarachwal** [comment]
For me, the issue was resolved in Chromium and FF when I hacked md-tooltip's getNearestContentElement() to stop the contained while loop iteration at the nearest ancestor md-content. Judging by a comment inside this function it is supposed to stop the loop there anyway, but it is missing the logic to check for md-content nodeName, and it, therefore, always attaches the tooltip to body, which throws off the positioning for all tooltips below the scroll horizon.

**Comment by Frank3K** [comment]
Can you share your solution / submit a PR? I'm having the same issue. Have you tested your solution in Internet Explorer?

**Comment by kasiarachwal** [comment]
It does work for me in IE.
