### ISSUE TITLE
Dependency on online fonts

### ISSUE THREAD

**Issue by iasandcb** [angular/material#243]
According to https://github.com/angular/material/blob/master/src/theme/_fonts.scss, angular-material requires an internet connection to render fonts properly. It would be good to have an option to provide those fonts locally (i.e. relatively) or on another URLs.

**Comment by rschmukler** [comment]
When possible you should use the web fonts by including the following in the head of your body:

```html
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=RobotoDraft:400,500,700,400italic">
```
This has the advantage that the response will be cached across the browser, allowing multiple pages (across multiple domains) that depend on this font to all load faster.

If you need to include the font manually, you will need to download it and specify the appropriate font-face.

We decided to leave it on the developer to implement offline fonts if they so choose because of both the caching performance above, and not wanting to be opinionated on where the font face is stored? (ie. is it loaded from `/roboto`, or `/styles/fonts/roboto` or `/fonts/roboto` etc).
