### ISSUE TITLE
mdSelect does not inherit theme

### ISSUE THREAD

**Issue by koodzik** [angular/material#2483]
Hi. I have found mdSelect does not inherit theme style. 
See here http://plnkr.co/edit/2ZQMFJzij0MmRdLawaRQ?p=preview

It's similar to https://github.com/angular/material/issues/1399

**Comment by ThomasBurleson** [comment]
See comments from #2628:

---- 

Using a md-select in a md-theme section, does not inherit the theme. For example, using a dark theme based on light-green, md-select is using the default theme (blue) instead of the light-green.

See this codepen: http://codepen.io/anon/pen/RPPoZg

The inputs are using the correct theme, however md-select is using the default theme. This is not expected.
