### ISSUE TITLE
Bug when ng-click is added in 0.9.3

### ISSUE THREAD

**Issue by ekaitzht** [angular/material#2498]
Hi,

I think I have found a bug in the 0.9.0 version. If you add a  ng-click in a element and then you click, the border is colored in blue color.

Here you have a plunker http://plnkr.co/edit/gpjVSui6Gftt7ti1mdnC?p=preview

Thanks

**Comment by vidakovic** [comment]
@ekaitzht I guess you meant version 0.8.3... the version you mention does not exist and I don't see in your Plunker example any special use of Angular Material elements (like md-button etc.). Maybe you should have a look again at the examples...

**Comment by ekaitzht** [comment]
@vidakovic yes, sorry I was using in the wrong way the Angular Material library.

**Comment by ekaitzht** [comment]
I have researched more about the issue and I think the problem is related when I use Data URI in a img tag. Then If you click to the image a blue border color is display when you click the image.

Can I use in Material Angular Data URIs in img tags? Or this is a bug?

Here you have a Plunker updated. http://plnkr.co/edit/gpjVSui6Gftt7ti1mdnC?p=preview

**Comment by vidakovic** [comment]
Where is the code for "MainCtrl" for example? The script.js file for this Plunker:

http://plnkr.co/edit/4J9XmUTRXTXRtp8b1fWr?p=info

Is empty... so no wonder that this doesn't work.

**Comment by sclearion** [comment]
Im using it the right way with the starter project and same thing is happening. REALLY frustrating

**Comment by marcysutton** [comment]
What you're seeing is a result of putting `ng-click` directly on `<img>`, which is not a keyboard-accessible element, so ngAria makes it into one. Angular Material includes ngAria as a dependency, and this module tries to "fix" your accessibility problems by adding `tabindex="0"`, `role="button"` and a keyboard event so that keyboard and screen reader users will be able to interact with your application.

The blue focus outline in your case is due to a non-standard use case. Therefore, if you don't want the outlines you must turn them off in your own CSS. As a framework, we can't put that broad of definitions in our stylesheet–it removes focus styles for EVERYTHING, and is too heavy-handed. We are willing to look into use cases where a Material Design-compliant focus state is available instead of the default browser outline, and there may be a modification to our global focus approach in the future (but it **won't** include `*:focus { outline: none; }`. That said, there's nothing stopping you from overriding global focus styles in your own stylesheet.

**Comment by super-ienien** [comment]
This is a very annoying issue... before i included angular-material everithing was fine. Now i get the outline on every element that have a ng-click directive...

You should realy try to find a solution. You can't expect that every project follow the rules of a the standard html world because some app are very special and uses the HTML standard as their own way...

**Comment by super-ienien** [comment]
Ok, i found a workaround : 

`$ariaProvider.config({
	tabindex: false
});`

This prevent ngAria from automaticaly adding a tabindex attribute to tag that have a ng-click directive.
