### ISSUE TITLE
mdSelect: virtual scroller messes with FB & Google SDKs

### ISSUE THREAD

**Issue by ngraef** [angular/material#2508]
[Demo](http://codepen.io/anon/pen/doyVre?editors=101)

I am using the Facebook and Google login SDKs loaded via javascript. When loaded, they each create a DOM node on `body` (FB creates `<div id="fb-root">` and Google creates `<iframe id="oauth2relayXXXXXXXXX">`).

The [new virtual scroller](https://github.com/angular/material/commit/99b4f2f82aa2923df87131d9d7d527c143d45857#diff-a1919fe5ddcba0e8888df1ee8f3f3727R68) for `mdSelect` moves these nodes into a container when the select is activated, and moves them back to the body when closed. It looks as though this movement triggers something in the SDKs that causes them to reload. This can be observed in the network activity and console output.

The functionality isn't broken; however, in my fully-configured app (i.e. with SDK client IDs added), each open and close of the select triggers 10 network requests: 8 get fulfilled from cache and 2 are ~100ms pings to FB.

@rschmukler - any thoughts on a way around this?

**Comment by rschmukler** [comment]
@ngraef as a temporary work around, you can probably put a root level `md-content` in your body and nest everything inside of that. I'll look into something possibly better....

**Comment by ngraef** [comment]
@rschmukler hmm that only works if the `md-content` has enough content to scroll.

**Comment by ngraef** [comment]
Related: #2456

**Comment by rschmukler** [comment]
@ngraef upon further thinking, I think the wrapper `md-content` is the best approach. The alternative would be some sort of white listing, but I feel like that either requires more work from the user (a call to some sort of provider for every external lib/div id added).

I've made it so that the outer most md-content will be used, provided that the body itself isn't scrolling. Let me know if this doesn't work for you.

**Comment by ngraef** [comment]
Yup, that works. Thanks, @rschmukler !
