### ISSUE TITLE
md-select: Causing stripe.js "CompleteDuplicationError" and "LoadDelayError" on open/close

### ISSUE THREAD

**Issue by epelc** [angular/material#2548]
So this is a werid one. Please take a look at the demo below.

It seems when you open or close an `md-select` it is causing `CompleteDuplicationError` and `LoadDelayError` in stripe js. I looked at the stripe js source and they both seem to be related to iframe dom issues and possibly socket errors. My gusse is that when you open an `md-select` there is an issue with the dom edit's that it does which is either removing stripes iframe or conflicting with it some other way.

I also just noticed that this only happens if the select is outside of `md-content` or in my case in the toolbar.

http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview

It also doesn't happen in `0.8.3` but it does in `0.9.0-rc2` and I'm suspecting it also happens in `0.9.0-rc1`. @rschmukler Maybe you can take a look at this. I asked the stripe people on irc and they didn't know much about it. But I think it is a dom issue with `md-select`.

The unobfuscated stripe js source can also be found below
https://js.stripe.com/v2/stripe-debug.js

**Comment by epelc** [comment]
Also the stripe js can be found [here](https://js.stripe.com/v2/) and [here](https://gist.github.com/epelc/b6cfdd7643ac9d37d2c5) is a formatted version(It's still obfuscated).

**Comment by epelc** [comment]
@rschmukler It seems to be because `md-select` moves everything(including iframes and scripts) into a container element when you open the select outside of `md-content`. Maybe you can add an option to specify a different parent when it's outside of `md-content`. Ie add an `md-select-root-parent` or something similar which we could put on an element just below the body.

![image](https://cloud.githubusercontent.com/assets/5204642/7321667/8d907da4-ea71-11e4-8d85-3b5edb3dc498.png)

**Comment by rschmukler** [comment]
@epelc indeed, wrapping in an `md-content` is the solution to this. But, given you have a toolbar that's not necessarily preferable.

I see a few options....

1) Add an `md-scroll-root` directive (probably an attribute) that makes select stop at that directive if it finds one, and otherwise at the `md-content`.

2) Add a `md-no-disable-scroll` option to the select. This means that it won't render correctly if you do manage to scroll the page, but gives the authors explicit control. In your case, the page doesn't scroll anyway, rather it is the content below the toolbar so it'd be an apt place to use the `md-no-disable-scroll=true`

What're your thoughts? I lean towards option 2, but I fear that people will over-use it and then complain when select doesn't reposition itself when they scroll (which we won't support)

**Comment by ThomasBurleson** [comment]
@epelc - can you send me (via email) your email? Thx,

**Comment by epelc** [comment]
@ThomasBurleson Just sent a hello
