### ISSUE TITLE
md-switch on md-list-item ripple effect and click takes over all item

### ISSUE THREAD

**Issue by forcewill** [angular/material#2579]
In the master branch when using an `md-switch` on a `md-list-item` the ripple effect takes over the entire list item and the switch toggles on click anywhere on the list item.

Check: http://jsfiddle.net/forcewill/mrou30oj/#base

**Comment by marcysutton** [comment]
You need to code your list items to have primary and secondary actions. Right now the secondary action thinks it is a primary one, which is why it takes over the whole row (there's no easy way to anticipate what you're trying to do). I'd take a look at the list controls demo, particularly the "Clickable Items with Secondary Controls":

```html
<md-list-item ng-click="navigateTo(setting.extraScreen, $event)" ng-repeat="setting in settings">
    <md-icon md-svg-icon="{{setting.icon}}"></md-icon>
    <p> {{ setting.name }} </p>
    <md-switch class="md-secondary" ng-model="setting.enabled"></md-switch>
  </md-list-item>
```

Your `lang.name` label and edit button need to become the primary action. Anything else would not align with the Material Design spec.

**Comment by forcewill** [comment]
Thanks i was able to "fix" it by adding the `md-secondary` class, just one question why the different behaviour in having a  single `md-switch` and having a single `md-button` on the list, i.e having a button the ripple doesn't take the entire `md-list` while a switch does

**Comment by riteshjagga** [comment]
As of current date, the correct solution to this issue is to add class like this:

`<md-list-item class="md-no-proxy">`

[md-list-item documentation link](https://material.angularjs.org/latest/api/directive/mdListItem)
