### ISSUE TITLE
Cannot read property '$attrs' of undefined

### ISSUE THREAD

**Issue by dmackerman** [angular/material#2613]
Upgraded to RC3, seems that I'm getting an error with GridList.

`Object.GridListController.layout`

```js
function getTileSpans(tileElements) {
  return [].map.call(tileElements, function(ele) {
    var ctrl = angular.element(ele).controller('mdGridTile');
    return {
      row: parseInt(
        $mdMedia.getResponsiveAttribute(ctrl.$attrs, 'md-rowspan'), 10) || 1,
      col: parseInt(
        $mdMedia.getResponsiveAttribute(ctrl.$attrs, 'md-colspan'), 10) || 1
    };
  });
}
```

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/jgx/pen/JogKrQ. 
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by peter-vbn** [comment]
The error appears when you navigate away from the Grid List demo.

* https://material.angularjs.org/#/demo/material.components.gridList

**Comment by rgolea** [comment]
+1

**Comment by ThomasBurleson** [comment]
@rgolea - This issue has been closed.

**Comment by rgolea** [comment]
Why did that error happened? I'm getting that in another thing I'm working on.

**Comment by ThomasBurleson** [comment]
@rgolea - please open a new issue with full details (and preferrably a demo).

**Comment by Mellbourn** [comment]
Getting this too in 0.10.0

**Comment by voyager1302** [comment]
Hi,
It seems like the issue is not closed.
I'm using Angular material v1.1.1.
Copied the Grid-list sample from angular material site and still get te error:
angular.js:13642 TypeError: Cannot read property '$attrs' of undefined
    at http://macbook-pro-2631.local:5757/assets/js/lib/angular-material.js:11007:51
    at Array.map (native)
    at getTileSpans (http://macbook-pro-2631.local:5757/assets/js/lib/angular-material.js:11003:21)
    at Object.layoutDelegate (http://macbook-pro-2631.local:5757/assets/js/lib/angular-material.js:10811:20)
    at Object.layout (http://macbook-pro-2631.local:5757/assets/js/lib/angular-material.js:11088:12)
    at Object.callback (https://code.angularjs.org/1.5.6/angular.js:1267:18)
    at http://macbook-pro-2631.local:5757/assets/js/lib/angular-material.js:1608:23
    at Array.forEach (native)
    at processQueue (http://macbook-pro-2631.local:5757/assets/js/lib/angular-material.js:1605:15)
    at https://code.angularjs.org/1.5.6/angular.js:19308:31(anonymous function) @ angular.js:13642(anonymous function) @ angular.js:10287(anonymous function) @ angular.js:19311completeOutstandingRequest @ angular.js:5912(anonymous function) @ angular.js:6191
www-embed-player.js:222 GET https://googleads.g.doubleclick.net/pagead/id net::ERR_BLOCKED_BY_CLIENTTd @ www-embed-player.js:222Xd @ www-embed-player.js:225(anonymous function) @ www-embed-player.js:1250Dg @ www-embed-player.js:388yq @ www-embed-player.js:1249(anonymous function) @ www-embed-player.js:1301(anonymous function) @ KANDy6Y_e6w?version=3&loop=1&playlist=KANDy6Y_e6w&autoplay=1&frameborder=0&fs=0&iv_load_policy=3&mo…:10

Thanks for the help,
Yehuda

**Comment by voyager1302** [comment]
Carlos Hi,

As I mentioned I took the sample from Angular material's site. same code.
here is the url for the code pen:
http://codepen.io/anon/pen/WGQVJv?editors=1111

Thanks, Yehuda

**Comment by Jonybang** [comment]
+1

**Comment by jgraygi** [comment]
+1
