### ISSUE TITLE
mdIconProvider overwrites user provided defaultIconSet

### ISSUE THREAD

**Issue by gndn** [angular/material#2621]
It appears that the mdIconProvider.preloadIcons is overwriting the user provided iconset. Given a default icon set:

    <?xml version="1.0" encoding="UTF-8"?>
    <svg>
        <defs>
            <g id="menu">
              <path d="M0 0h24v24H0z" fill="none"/>
              <path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z"/>
            </g>
        </defs>
    </svg>

that is loaded by configuring the iconProvider:

    module.config([
      '$mdIconProvider',
      function($mdIconProvider) {
        $mdIconProvider.defaultIconSet('/images/icons.svg', 24);
      }
    ]);

we instead seeing the angular logo when it is used as follows:

    <md-button aria-label="Open sidebar">
     <md-icon md-svg-icon="menu" class="transparent-icon"/>
    </md-button>

**Comment by ThomasBurleson** [comment]
@programmist - sounds like we should merge the sets (if default already exists)?

**Comment by programmist** [comment]
It looks like code was added to pre-load static icons for other MD components (not sure when):
https://github.com/angular/material/blob/master/src/components/icon/iconService.js#L231

There is one called 'menu', which I guess is colliding with the 'menu' provided by @gndn.  Even if we merged I think we'd still have an issue since hte names are identical.  Our internal, pre-loaded icons should probably be namespaced.  The name 'menu' is too generic.

**Comment by ThomasBurleson** [comment]
Like the namespacing idea for internal componetns.
Also think we should $log a warning for name collisions.

**Comment by gndn** [comment]
As it stands right now, there are about 4 other svg icon paths in my icons.svg file which load just fine (and do not conflict with your preloaded icons.)

Generally, I had assumed that icon sets were namespaces orthogonal to icon names (before reviewing the code.)  Given the current implementation, even having a named iconSet of 'menu' (which would be admittedly horrible) and a registered preloaded icon of 'menu' would lead to a similar conflict with even more surprising consequences, as the iconset itself would be dropped on $get.

**Comment by ThomasBurleson** [comment]
Reopening so @programmist can address name collision warning feature.

**Comment by programmist** [comment]
@ThomasBurleson 
In order to prevent the original problem we would need to scan all icon IDs in the icon group /images/icons.svg (from the original example above) at configuration time and determine if any any icons with those IDs have already been configured in the same group (in this case it was the default group. 

I think name-spacing the angular material static icons is probably sufficient.  I see they've been pre-pended with "md-", but we could go a step further and also put them into their own icon group if we wanted.  Thoughts?
