### ISSUE TITLE
Apply layout-padding on desktop/tablet only

### ISSUE THREAD

**Issue by pjain11** [angular/material#2652]
I want to put "layout-padding" around md-content when the view is rendered on desktop/tablet. I dont want to apply it when the view is rendered on phone. I used to handle such thing which overwriting padding on media query breakpoint in css. How would you suggest handling this with angular material framework?
(one more use case is - I have a list of md-cards. Each card has md-card-content containing text. padding on md-card-content looks perfect for desktop. But on phone it looks too much.)

**Comment by epelc** [comment]
I asked @marcysutton for this before but she said that `layout-padding`/`layout-margin` would automatically get bigger/smaller depending on your screen size. I think this was planned for a future update instead of adding the `-gt-*` style options to `layout-padding`.

I think it's a much better system but I don't think it's been implemented yet. Anyways some custom override styles should work for now.
