### ISSUE TITLE
md-button gets stretched when in the same row with labled input

### ISSUE THREAD

**Issue by uriva** [angular/material#2681]
Plunkr: http://plnkr.co/edit/fPJOEdJAcsbizipXJ6Cz?p=preview

**Comment by grizzm0** [comment]
While the spec doesn't say anything about allowing or disallowing buttons on the same row as a text field I feel like this is not something you're supposed to do.

**Comment by rschmukler** [comment]
Whether you should be able to or not, it's a simple enough use case that I can see other developers doing it.

This has to do with flexbox stretching the div because an explicit margin is set on it. Notice that if we do `margin: auto` on the button it works properly. Waiting to hear what @ThomasBurleson thinks about supporting this use case

**Comment by marcysutton** [comment]
I would also check again with the latest release because the units were changed from `rem` to `px`.

**Comment by uriva** [comment]
Hi,
Is this fixed or closed for another reason?
