### ISSUE TITLE
Deprecate md-select-label

### ISSUE THREAD

**Issue by rschmukler** [angular/material#2684]
We used to allow people to customize what a select would show as the value when it was selected. This is bad UX as it can lead to a user thinking that was is selected is not what they clicked on.

We should follow the HTML native select's behavior of using the `option.textContent` as the display value for the label. `placeholder` can be used for when no value is selected (as it currently, hopefully is).

**Comment by Anthropic** [comment]
In the Material spec there is an option to have additional label text with it's own design rules so that both can be shown without overriding the display of the value.
http://www.google.com/design/spec/components/menus.html#menus-simple-menus

That would be the preferred behavioural outcome for my projects.

**Comment by bshir** [comment]
Hello,
I think that this update has taken away desired functionality from the md-select directive.  There are cases where customizing the select options improves the UX.
Examples...  
a select element containing countries as options with their flag image displayed beside the text.
a select element which formats each option text in a different color (red, yellow, green)

Is there a way to configure this with 10.1?  I'm currently able to do options with custom markup (as before) but unable to maintain consistency with the selected option since md-select-label has been removed.  This creates the inconsistent UX.

It's entirely possible that I'm missing something here.  Let me know if anything here requires clarification.  Thanks

Here's a modification from a demo codepen demonstrating the behavior:  http://codepen.io/anon/pen/rVbLOm

**Comment by ivanhtp** [comment]
Great solution @bshir .
In my experience of a one year old angular material application, users frequently don't understand what that selection is related with. The placeholder soluction is only cool when there is no selected item.

**Comment by JobaDiniz** [comment]
What about when you use `md-optgroup`? The `md-option` can have the same text among different `md-optgroup` and this will confuse users.

```
<md-select ng-model="vm.event.agenda" class="event-agenda">
                        <md-optgroup label="{{group.name}}" ng-repeat="group in vm.groupedAgendas">
                            <md-option ng-value="agenda.id" ng-repeat="agenda in group.agendas">{{agenda.name}}</md-option>
                        </md-optgroup>
                    </md-select>
```

The selected text in my case should be: `group.name - agenda.name`

How to accomplish that?

**Comment by rishabhmhjn** [comment]
+1

`md-select-label` should be included
