### ISSUE TITLE
md-autocomplete search not firing when md-selected-item = md-search-text

### ISSUE THREAD

**Issue by david-gang** [angular/material#2694]
I have the following autocomplete:

```javascript
<md-autocomplete
    md-search-text="searchCtrl.query"
    md-selected-item="searchCtrl.query"
    md-item-text="item"
    md-min-length=3
    md-autofocus=true
    md-items="item in searchCtrl.autocompleteQuery(searchCtrl.searchQuery)">
  <span md-highlight-text="searchCtrl.query">{{item}}</span>
</md-autocomplete>
```

The reason i say that  md-search-text="searchCtrl.query" because i have also a search button and therefore give the user the ability just to fire the search button, instead of selecting an option from the autocomplete.

The problem is that the function searchCtrl.autocompleteQuery is not called.

This is because of the line

```javascript
if (searchText !== getDisplayValue($scope.selectedItem)) $scope.selectedItem = null;
    else return;
```

in the function handleSearchText.

As the code tells it explicitly, I imagine that I don't use the autocomplete as intended.
What is the reason for this?
If this is the case, that it is a wrong usage, there should be somehow a warning either in the documentation or the program not to do so.

**Comment by robertmesserle** [comment]
@david-gang In your example, you are misusing the attributes.  It seems like what you want to do is just remove `md-selected-item` since you are not using it.

The way these are setup is that `md-search-text` is the text being searched for, and `md-selected-item` is an item that the user has selected.  Since this component is based on helping the user fill in a text field, it would not make sense to search even when an exact match for the user's text was already found.  (If there were multiple matches with identical text, there would be no way to visually differentiate these values once selected.)
