### ISSUE TITLE
grid list's md-row-height="fit" results in tile height being 0 even even when md-grid-list has height

### ISSUE THREAD

**Issue by richtier** [angular/material#2741]
I'm having problems making "fit" work for `md-row-height` on `md-grid-list`: when I set "fit" the tiles all have height of 0, resulting in the grid list not displaying.

Simplest way to reproduce is to copy the "Responsive Usage" from the [docs](https://material.angularjs.org/#/demo/material.components.gridList).

```css
<style>

md-grid-list {
  height: 500px;
}

</style>
```
```html
<div
  ng-controller="ribbon.main"
  class="question-deck"
  style="padding-bottom:80px;">
        <md-content
          style="padding: 0; background: transparent;"
          class="md-padding">
            <md-grid-list
                md-cols-gt-md="12" 
                md-cols-sm="3"
                md-cols-md="8"
                md-row-height="fit"
                md-gutter-gt-md="16px"
                md-gutter-gt-sm="8px" 
                md-gutter="4px">
              <md-grid-tile
                  ng-repeat="tile in colorTiles"
                  ng-style="{
                    'background': tile.color
                  }"
                  md-colspan-gt-sm="{{tile.colspan}}"
                  md-rowspan-gt-sm="{{tile.rowspan}}">
              </md-grid-tile>
            </md-grid-list>
        </md-content>
</div>
```

When I change `md-row-height="1:1"` then the grid tiles are >0 which is nice, but the fit is not as desired.

I see in other closed issues we should set the list height, but as you can see that did not solve for me.

**Comment by Tetraib** [comment]
+1 For that. I ended up using 50% or 33% ... (49,9% or 32.8%....) for md-row-height but it is not very neat. Any better workaround ?

**Comment by shyndman** [comment]
I can take this on, unless Ryan is taking on the remaining grid bugs.

**Comment by rschmukler** [comment]
@shyndman Feel free to have at it! Kick it back my way if you end up not having time.

**Comment by Splaktar** [comment]
I was able to reproduce this as well. Have a CodePen handy if needed.

**Comment by tony0918** [comment]
+1

**Comment by simongcc** [comment]
+1

**Comment by obie** [comment]
bump

**Comment by vasiliy0s** [comment]
+1

**Comment by agconti** [comment]
+1

**Comment by mattblang** [comment]
+1

**Comment by itrethan** [comment]
+1

**Comment by simongcc** [comment]
I found that the v0.10.1 is very closed to fix. 
The Master is also NOT working as well. I have tried gridList.js, inside, in `getTileStyle` `fit` case, it said `// noop, as the height is user set`, maybe it change the mechanism? I am not sure because I haven't trace through all master code.

For those who want to make it work quickly, assumed you get the `0.10.1` from bower (mine is the case)
1. open `angular-material.js`
2. search `getTileStyle` (the line with `props.rowCount`)
3. modify `props.rowCount` to `rowCount`

Reason:
Because `rowCount` has not been created in `layoutDelegate()`, instead, it is being put in `function(tilePositions, rowCount) {...}`
so, to use, just change the above variable name can do

Note:
After update, either case is working
eg. specify a `style="height: 100px"` in `md-grid-list` tag
or
specify a `flex` in `md-grid-list` tag and its parent should have a finite height like `layout="column" style="height: 100%"`
as long as a finite height calculation can be made, it should be working fine

Hope this help.

**Comment by yngveo** [comment]
+1 - Hope this gets fixed soon

**Comment by birkskyum** [comment]
+1. @vasiliy0s, thank you. It works like a charm.

**Comment by helzgate** [comment]
This is still an issue with v0.11.0 but the fix is the same, use simongcc's suggestion above.

**Comment by TiagoSousa26** [comment]
But the problem is solved or not?? Because I am in 2016 and have the same problem :(
