### ISSUE TITLE
Autocomplete. Selected item stays on top in mobile chrome

### ISSUE THREAD

**Issue by kamarouski** [angular/material#2755]
Hi guys,

Thanks for the tremendous work you are doing bringing Angular Material to life.

I have the issue with autocomplete when sometimes selected item stays on top of things and only page refresh makes it go away. It constantly reproduces on chrome for iPad/Android, sometimes on desktop.

I use version 0.9.0

**Comment by Tyrannmisu** [comment]
Also happened  to me once in Firefox but I haven't found a way to reproduce it since.

I'm using md-autocomplete in a dialogue and the selected entry stayed on top of the page after the dialogue was closed, only a refresh solved the problem. It happens very rarely and is hard to reproduce (at least for me).

**Comment by robertmesserle** [comment]
Can this still be reproduced with the latest code on https://material.angularjs.org/HEAD/ ?

Closing for now since I'm unable to reproduce, but please comment if it is still an issue and I will reopen.

**Comment by kamarouski** [comment]
I'm on 0.9.7 now and haven't seen this issue for a while.
