### ISSUE TITLE
secondary and primary placeholders switched in md-chips

### ISSUE THREAD

**Issue by typotter** [angular/material#2770]
In the [Chips Basic Usage Demo](https://material.angularjs.org/#/demo/material.components.chips), under 'Use Placeholders and override hint texts'. The placeholder text should be +tag when the collection is non empty, and the longer, "Enter a tag" when the collection is empty.

**Comment by ericgundrum** [comment]
This is caused by a logic error on line 186 of src/components/chips/js/chipsController.js
`return useSecondary ? this.placeholder : this.secondaryPlaceholder;`
should be
`return useSecondary ? this.secondaryPlaceholder : this.placeholder;`

Note that this error appears in production code, not just in the demo. The error is present on branch `master` as well as tag `1.0.0-rc7`.

**Comment by ericgundrum** [comment]
The pull request @dbwhddn10 associated with #3804 will fix this issue.
