### ISSUE TITLE
md-select causes extra HTTP requests on page that uses an iframe

### ISSUE THREAD

**Issue by jelbourn** [angular/material#2783]
When `md-select` is opened, it takes all the elements in `body` and appends them to a virtual scroller. 
(it is ostensibly all element in the closest `md-content`, but the `md-select` menu is always appended directly to the body).

This is problematic because it makes the page fire HTTP requests if any of those elements contain an `iframe`. There are probably other, weirder issues related to wrapping the entire page in an extra div.

Reproduced: http://jsbin.com/mupipa/1/edit?html,js,output

This feature seems really invasive to the rest of the app just to prevent scrolling. 

As far as the behavior itself, some testing shows that the behavior of the native select actually depends on the underlying operating system:
* Linux (Ubuntu): closes the select when scrolling outside
* Mac: Freezes scrolling (actually all interactions outside of the select)
* Window (8): Same as Mac
* ChromeOS: TDB
* Android (Chrome): Opens a fully modal selection list, blocking all interaction w/ underlying page
* iOS: TBD

We need to either figure out a way to make to no-scroll behavior less invasive, or change the behavior to do something simpler (such as closing the select as Linux does).

**Comment by calebegg** [comment]
If the goal is just to keep scrolling on the select from scrolling the whole body, there's a pretty simple technique to do that:

http://codepen.io/calebegg/pen/vOLymN?editors=001

(This also works on two finger scroll touchpads, despite the event being called 'mousewheel'). It doesn't work for touch scrolling (on mobile), but I think this is implemented in a more reasonable way, from what I've seen -- if you don't lift your finger, you only scroll the inner div. If you scroll to the bottom, lift your finger, then scroll again, you can scroll the body, but that's usually what you want anyway.

**Comment by jelbourn** [comment]
@calebegg the original intent of this was to make the page unscrollable whenever a `md-select` was open (which is what happens on Mac / Windows).

**Comment by PrashantAshok** [comment]
@jelbourn - Related issue #2739 with respect to md-select wrapping the entire body in a wrapper. Also mentioned a possible fix.

**Comment by rschmukler** [comment]
@calebegg the problem with the `mousewheel` event solution is that there are many ways that the page could scroll... For example, arrow keys, spacebar, tabbing through elements, etc. Maintaining all of these event listeners / correctly being aware of the context might not be doable. 

Still investigating remedies...

**Comment by calebegg** [comment]
I'm not sure why it's such a big deal if the page scrolls because of the user's intentional actions, like tabbing or scrolling the wheel on the body (arrow keys and spacebar are of course already overridden by md-select). Unless the goal is to maintain rigorous consistency with the OS (which, as @jelbourn showed, is probably impractical).

My proposal was just to override scroll wheel scrolling on the select, as that is probably the best reason to do anything scroll wise, since I think it's pretty unexpected when the scroll wheel on an inner scrollable element starts scrolling the whole page. Other than that, I personally would be fine with other scroll methods staying intact. But that comes down to more of a product decision.

**Comment by jelbourn** [comment]
Another bug that probably has the same root cause: http://plnkr.co/edit/pNCwauATD1SeeTlpHv83?p=preview (scroll down and open the select).

Opening the md-select makes the fab button move.
