### ISSUE TITLE
when md-tabs only contain another md-tabs there will be some odd behavior

### ISSUE THREAD

**Issue by butaixianran** [angular/material#2789]
This is a problem with css of 0.9.0, everything works fine on 0.8.3.

When md-tabs only contain another md-tabs, the contain height is set to 248px even with no content at all.

If I try to fix that by overriding the min-height, a big scrollbar will still be there.

**If I try to add md-dynamic-height to md-tabs, when clicking on a tab, everything following will move up and down.**

check this out:
[http://codepen.io/butaixianran/pen/vOLyaK](http://codepen.io/butaixianran/pen/vOLyaK)

I need a solution for this, thanks!

This is what md-tabs should do ( with css of 0.8.3 ):
[http://codepen.io/butaixianran/pen/ZGQBRm](http://codepen.io/butaixianran/pen/ZGQBRm)

**Comment by robertmesserle** [comment]
This is fixed in 0.9.4.  Updated codepen: http://codepen.io/robertmesserle/pen/pJRvYB

In order to do what you want, you have to:
1. Add the attribute `md-dynamic-height` to the outer tabs
2. Remove any whitespace within your `md-tab`

You could also use the `<md-tab-label>` syntax to specify your label if you don't want to worry about whitespace.
