### ISSUE TITLE
custom dialog backdrop not covering the whole screen in demo

### ISSUE THREAD

**Issue by david-gang** [angular/material#2794]
This is connected to https://groups.google.com/forum/#!topic/ngmaterial/-iOfuBi64U0

When pressing at https://material.angularjs.org/#/demo/material.components.dialog at the custom dialog link just part of the screen is covered by the backdrop.

![capture](https://cloud.githubusercontent.com/assets/1292882/7553394/172d10ec-f6ff-11e4-8de9-dcfa097ea9e4.PNG)

**Comment by EladBezalel** [comment]
As you can see the dialog seems to be a child of its container and therefore it's backdrop covering only his parent.. I don't really know if it's a bug or a feature, but when using md-dialog I've never encountered this kind of issue, I think it happens only (and it's meant to be) on the demo site

**Comment by david-gang** [comment]
Hi @EladBezalel ,

I also was not sure if it is a feature or issue :-)
@marcysutton wrote me at https://groups.google.com/d/msg/ngmaterial/-iOfuBi64U0/3IraePMkPQoJ that: "Dialogs are supposed to cover the whole screen, since interaction is suspended behind it. The custom dialog demo should probably do the same."

**Comment by marcysutton** [comment]
I actually looked into it and things became complicated due to our docs generation setup. The custom dialog stylesheet has dynamically-generated selectors scoped further down the DOM tree, so if you append that dialog to the body it loses its custom styles. There was no easy way to change it without overhauling our docs system. So that's why it is appended where it is.

**Comment by marcysutton** [comment]
Fixed with d360cd22293d9bb5268b4101c0d46bdd96582323.
