### ISSUE TITLE
md-input clear button

### ISSUE THREAD

**Issue by ismarslomic** [angular/material#2802]
I would to have an clear button visible when entering md-input of type search. Button should be displayed to the right and within search field itself

**Comment by marcysutton** [comment]
Have you taken a look at mdAutocomplete? @robertmesserle I wonder if the `input` in autocomplete should have `type="search"`.

**Comment by ThomasBurleson** [comment]
@marcysutton for `<md-autocomplete>` adding a `type="search"` seems like a good idea.

**Comment by robertmesserle** [comment]
Totally agreed.  Will make that change.

**Comment by marcysutton** [comment]
Closing as duplicate of https://github.com/angular/material/issues/2699.

**Comment by EdgarArguelles** [comment]
I have a directive that could hep

http://plnkr.co/edit/Dje0l1?p=preview

**Comment by cmacdonnacha** [comment]
So is the "clear" icon displayed on an input of type search now? Trying to achieve something like this:

![image](https://cloud.githubusercontent.com/assets/9777763/13954386/75ab1c12-f038-11e5-91e8-54a60cdcbd60.png)

**Comment by cmacdonnacha** [comment]
I tried using the **autocomplete** component and it does display the "clear" button. However, I want to have "md-input" styling rather than the autocomplete styling without the floating label. I think there should be an attribute added to determine if the clear icon should be displayed for **md-input** components.
