### ISSUE TITLE
Textarea bouncing

### ISSUE THREAD

**Issue by williamdstuart** [angular/material#2902]
When a text area extends past the screen, sometimes it moves the screen up and down as you type.  Please see the attached video for a demonstration on the Angular Material Demo site.  I'm having this issue on a site I'm working on, but it happens much earlier when typing.

[textareaissue.WMV | uploaded via ZenHub](https://files.zenhub.io/555b3db26777ff675d23f393)

**Comment by orange-buffalo** [comment]
issue #3024 is also about the same

**Comment by WhiteAbeLincoln** [comment]
@ThomasBurleson @mckenzielong has a fix over at issue #3070. I tried it and it worked for me, but did introduce a few minor issues that I'm willing to leave, since the jumping was really aggravating. I think that it would be good to incorporate that fix. In my testing, it hasn't broken anything else, and works on chrome and firefox. I don't have internet explorer or safari to test with, but the code looks like it is pretty standard.

**Comment by ThomasBurleson** [comment]
@WhiteAbeLincoln - I will check it out. Thx

**Comment by EladBezalel** [comment]
@williamdstuart it seems to be fixed in HEAD, closing for now. if it's still happening please write here and i will reopen this issue.

Rel #3024 #3070
