### ISSUE TITLE
input: Placeholder hidden until focused in project spartan

### ISSUE THREAD

**Issue by epelc** [angular/material#2956]
As you can see below the placeholders for floating inputs are hidden until you focus them.
![image](https://cloud.githubusercontent.com/assets/5204642/7775685/40294e06-0083-11e5-8107-510085e8bc20.png)
Try it here https://material.angularjs.org/#/demo/material.components.input

Also do you want bug reports for project spartan/edge yet as they are still pre releases?

Browser: Project sparatan 13.1.01.22.0.0
OS: Windows 10 build 10122

**Comment by Splaktar** [comment]
This is also an issue in IE 11. Can you check if #3582 solves this for Edge please?

**Comment by Splaktar** [comment]
@epelc this has been merged into master. Can you please verify the fix?

**Comment by epelc** [comment]
@Splaktar Sorry I can't check spartan/edge. I'm traveling and won't be back home for 2-3weeks. I might be able to get a windows 10 vm setup on my laptop next week but I'm not 100% if I'll be able to download it or not.

**Comment by Splaktar** [comment]
OK, I've downloaded the latest Win10 ISO and have it running in VirtualBox. I'll use it for a bit of testing this weekend.

**Comment by Splaktar** [comment]
![screen shot 2015-07-21 at 10 30 39 pm](https://cloud.githubusercontent.com/assets/3506071/8816675/464743f2-2ff8-11e5-9b6d-ff1cd0921baa.png)

This appears to be fixed in the latest version of Edge on Win 10. I tested with master, 10.0.0, 0.9.8, and 0.9.0. They all work now. So the fix in #3582 does not appear to be needed anymore for the latest Edge. It is of course still useful for IE 11 and Firefox.
