### ISSUE TITLE
autocomplete (query with promise): delay before results are shown / md-not-found always shown

### ISSUE THREAD

**Issue by r0b-** [angular/material#2976]
http://codepen.io/anon/pen/LVbWLZ
If I use a promise (remote data source) for my items there is a delay between the display of the loading indicator and the result list.
If I use md-not-found with that it is always shown even if results are found.
It seems that the delay and the display of the not-found-contents are somehow connected but it's just a guess ...

btw: The codepen of the "Basic Usage" demo for autocomplete is broken

Thanks in advance

**Comment by ThomasBurleson** [comment]
@rschmukler  - thoughts?
> See #2979 for CodePen issue.

**Comment by robertmesserle** [comment]
This should have been fixed already in master, but it was after 0.9.4 so it isn't in any formal release.

**Comment by robertmesserle** [comment]
@r0b- Using `cdn` links to master with rawgit will cause you to get old versions due to their caching.  If you are just creating a demo on CodePen, you can just remove `cdn` from your links and it should pull the non-cached version from master.

If, however, you're using rawgit for anything on production, you'll want to grab a specific version (or commit) link to rawgit.

**Comment by r0b-** [comment]
Thanks!

**Comment by inaveedahmed** [comment]
@robertmesserle can i get the ref commit. Thanks.
