### ISSUE TITLE
md-tabs accessibility issue - wrong tab count when using screen reader

### ISSUE THREAD

**Issue by mmatheson1** [angular/material#2988]
Tab count is doubled when using a screen reader. For example, in the md-tabs demo (https://material.angularjs.org/latest/#/demo/material.components.tabs), when focusing on tab "One" (first of three), the screen reader will read "Tab selected 4 of 6". 

I'm using Chrome on Linux, with screenreader ChromeVox

**Comment by marcysutton** [comment]
That could be a calculation bug with the tabs since there are essentially two sets. Voiceover had a similar issue at one time if I remember correctly. cc @robertmesserle  

Also note that we prioritize JAWS/IE, NVDA/Firefox and Voiceover/Safari based on usage numbers. Chromevox is a really small segment of the community. More info here: http://webaim.org/projects/screenreadersurvey5/
