### ISSUE TITLE
mdSidenav: md-backdrop wrong place

### ISSUE THREAD

**Issue by ptrenery** [angular/material#2995]
Created a md-toolbar above a md-sidenav so that the nav panel appears below the toolbar when it is locked open. That works fine.

In this configuration, when opening a sidenav that is not locked, it animates into place at the top of the screen, not below the toolbar which is also fine. However, the md-backdrop is created below the toolbar meaning you can still interact with the toolbar. In addition, the offset backdrop goes below the bottom of the page so a scrollbar appears and the page can now be scrolled down.

![screen shot 2015-09-04 at 10 58 31 am](https://cloud.githubusercontent.com/assets/210413/9688201/5737d14a-52f3-11e5-8382-ee7ca30ad583.png)

I added a simple md-toolbar to the standard sidenav codepen demo [here](http://codepen.io/ptrenery/pen/xGRWPm) that shows the issue. Click the "TOGGLE RIGHT" button then scroll down. 

md-backdrop {top: 0} seems to fix it

**Comment by jhogg41** [comment]
An alternative workaround (or perhaps intended approach?) is to trap the sidenav and content in their own div which you then set as position relative (or presumably whatever you like so long as it is explicit). The md-backdrop position:absolute then refers to that div rather than the browser window.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
