### ISSUE TITLE
$window.scrollY is always 0

### ISSUE THREAD

**Issue by pbshop1001** [angular/material#3000]
How can I get a Scroll y position? <md-content> tag wraps main content. Even if I scroll to bottom, it always returns 0

**Comment by rajathms** [comment]
@pbshop1001  you got the solution for this issue, I'm facing the same.
It is something to do with `angular-material` . 
I tried in different projects of angular. This issue is with the project which has Angular material .
To test i uninstalled Angular-material , it works , it gives proper value for `$window.scrollY`
I thought of reopening this issue.
