### ISSUE TITLE
UI Issues when running on Android Device.

### ISSUE THREAD

**Issue by zeeshanjan82** [angular/material#3042]
I have logged a bug in the Ionic Framework but I think its related to angular material design. Please find the issue logged at https://github.com/driftyco/ionic/issues/3858#issuecomment-106865113

**Comment by PDSBGreg** [comment]
From my small amount of testing, anything running in the non-Chrome WebView on Android doesn't layout correctly with Material because it doesn't understand flexbox.

Take a look at the Crosswalk Project (https://crosswalk-project.org/). It is compatible with Cordova 4+. I'm using it in a native application and it solved all of my Material issues.
