### ISSUE TITLE
Video inside md-dialog loads only once.

### ISSUE THREAD

**Issue by alarrosa14** [angular/material#3099]
I have a html5 video embedded inside a md-modal. The first time I open the modal the video loads as it should but when I reopen the modal, the video can't be played. The video frame is dark and controls don't react.

```
<md-dialog flex="70">
<video style="width: 100%" preload='metadata' controls>
            <source src="{{ct.video.video_file}}" type="video/mp4">
</video>
</md-dialog>
```

This happens in chrome only. In Firefox, the video plays normally but there is a problem with the video frame layout when reopening the modal.

**Comment by Schweigi** [comment]
According to a Google search you need to unload the video player first because some browsers do not do that correctly.

For my own project is use [VideoJS](www.videojs.com) which does all that for you with the [dispose](https://github.com/videojs/video.js/blob/master/docs/guides/removing-players.md) function. With this player I hadn't had any issues with md-modals and videos not playing.
