### ISSUE TITLE
Sidenav: slow/odd behaviour on Nokia Lumia 735

### ISSUE THREAD

**Issue by justingrayston** [angular/material#3110]
I was testing the demo site whilst testing an app we are using Angular Material. I noticed this odd behaviour of the sidenav. It seem Internet Explorer on the phone is interpreting touch events slightly differently and the digest that toggles the sidebar seems to take an age.

I don't easily have this phone to hand, but can retest anything specific. I have no idea how to debug a windows phone, Visual Studio? Anyone out there have this all set up who could debug easier than me?

Here is a video of said behaviour.

[![Sidebar issues Video](http://img.youtube.com/vi/ttKn-11BYmQ/0.jpg)](http://www.youtube.com/watch?v=ttKn-11BYmQ)

Relates to #1905

**Comment by fals** [comment]
The sidenav is only one of those issues, and given all the workarround used by Microsoft to simulate touch events using click events in WP It can be forgiven. The major issue that I did notice was the performance for any demo directive. They kill the phone. You almost could see stuff happen in slowmotion. Hoping that the dev team give some care, because Brazil's Lumia market is huge, mainly the enterprise marketing given the low cost and good perfomance of those Lumia phones

**Comment by WhiteAbeLincoln** [comment]
The new sidenav also has issues on chrome and firefox for android. Scrolling and opening the sidenav works just fine, but the dropdowns never open.

**Comment by justingrayston** [comment]
Yup. Confirmed. I have the same issue. This was fine on 0.9.7.
