### ISSUE TITLE
Autocomplete : No longer displays list when md-min-length=0

### ISSUE THREAD

**Issue by Izcalli** [angular/material#3120]
With master version of angular-material:
As you can see on this [codepen v master](http://codepen.io/anon/pen/MwpPLw), the `autocomplete` is set with `md-min-length=0` and when we click on the input, the list isn't displayed anymore meanwhile this feature was available on v0.9.7 : [codepen v0.9.7](http://codepen.io/anon/pen/JdWmzN)

Is it natural ?

**Comment by jgoux** [comment]
+1, I liked the md-min-length=0 behaviour, it gave us an alternative for a filterable select input.

**Comment by fhawkes** [comment]
I noticed this problem as well. I did a little digging to look into the issue and its because the isMinLengthMet function returns an empty string instead of a boolean value. I fixed the issue by changing the isMinLengthMet function in the autocomplete controller as follows: 

``` javascript

function isMinLengthMet () {
    return ($scope.searchText != null && $scope.searchText.length >= getMinLength()) || ($scope.searchText == null && getMinLength() === 0);
}

```

This accounts for the case where searchText has been set to a null value as well when the min length is 0

**Comment by smashercosmo** [comment]
This should be closed. Not relevant for 0.10.0-rc4.
