### ISSUE TITLE
md-dialog custom dialog not working on IE 11

### ISSUE THREAD

**Issue by pove** [angular/material#3187]
To reproduce this issue, open https://material.angularjs.org/latest/#/demo/material.components.dialog on Internet Explorer and click on CUSTOM DIALOG.

IE version used: IE 11.0.9600.17801
ngMaterial: 0.9.8

PS: I wish Chrome was everyone option... ;)

**Comment by Londovir** [comment]
More specifically, the initial opening of the custom dialog appears in IE11 to be initially locked into a non-scrollable panel and you are viewing the bottom portion of the dialog panel only. There is no vertical scrollbar to use to scroll the content, nor does the use of a mouse wheel engage scrolling.

The ironic thing, which I keep encountering with IE11 and the material angular project (which oddly enough, I have not encountered as often with other material frameworks), is that if you do something minimal which forces IE11 to re-render the page layout, it then "wakes up" and renders things properly. In this instance, for me, just hitting the ALT key to pop open the IE11 menu bar is enough to drop down the browser screen, which apparently forces a re-rendering, and IE11 is then able to pick up on the need for the scroll bar and the dialog "appears" to work correctly. I would guess that IE11 is having some trouble recognizing when elements are being dynamically added to the layout and there is no triggering "refresh" of the layout so IE11 expects the content to not need to scroll, and therefore you end up with the odd behavior.

**Comment by DAquilina** [comment]
Not to beat a dead horse, but this issue is still occurring.

Browser: IE11
Angular: 1.5.8
Angular-material: 1.1.3

Using Browserstack to test and seeing the following:
- Have a dialog with an activity feed. The feed uses a poller to periodically contact the API for newer activity.
- Initial load, populate list for the first time, dialog cannot scroll.
- After first iteration of the poll, the list updates and the view re-renders accordingly. Scrollbar appears.
- At this point list can scroll normally -- future iterations of the poller do not affect the layout.
- If the user scrolls to the bottom of the feed, it manually triggers the API to look for older activity. When this happens, the screen glitches out and the scrollbar disappears, forcing the user back to the top of hte dialog.
- After the poller triggers again, the scrollbar reappears.
