### ISSUE TITLE
Speed Dial / Toolbar FAB Accessibility Improvements

### ISSUE THREAD

**Issue by marcysutton** [angular/material#3231]
Great job on these components, they are really solid! To make these them even better for keyboard and screen reader users, I have some interaction suggestions. 

The main goal is to not force keyboard users through the entire menu (mouse/trackpad users have that luxury), but rather to add a single tab stop and use the arrow keys to navigate to the child buttons. Hitting TAB while on the main FAB would skip past the menu and onto the rest of the page.

Broken down into steps:

 * Only keep the main menu button in the tab order. Skip other buttons with `tabindex="-1"`.
 * Add `aria-haspopup="true"` to the main menu button.
 * Open the component on focus of the main menu button, and close on blur.
 * Wire the arrow keys to navigate between buttons.

That should be it! Let me know if you have any questions! cc @topherfangio @robertmesserle

**Comment by topherfangio** [comment]
Hi @marcysutton!

Thanks for pulling this into a new issue. I will try to work on it this week, but I am a bit behind at work due to having family in town this past week, so it may take a bit longer. Please let me know if you have other thoughts in the meantime so I can start thinking about them :-)
