### ISSUE TITLE
Fab Speed Dials with Tooltip

### ISSUE THREAD

**Issue by luclanet** [angular/material#3236]
Oblivious compliments for this relase.

In Speed dial will be great to use tooltip to help users. It works but it made the other bottons unaccessible as you can see on this example:

http://codepen.io/anon/pen/MwoVxe

**Comment by shprink** [comment]
Yes same here, another example: http://codepen.io/shprink/pen/WvEMVy

**Comment by myagoo** [comment]
+1

**Comment by dohomi** [comment]
+1

**Comment by topherfangio** [comment]
Hi all, I think a few things have changed recently regarding the tooltip as it now appears to work. Can you please take a look at the following codepen and see if it works for you? 

http://codepen.io/topherfangio/pen/MwOQPr

_Note: There is currently a bug causing the close/open animation to fire very quickly as you move between action items; it has been fixed in a5807e0._

**Comment by myagoo** [comment]
Works for me :)

2015-06-24 16:26 GMT+02:00 Topher Fangio <notifications@github.com>:
