### ISSUE TITLE
FAB Speed Dial: "Open" state not functional on iOS devices

### ISSUE THREAD

**Issue by BirdInTheCity** [angular/material#3247]
When viewing the demo page on my iPhone 6/iPad Air 2, the open state never occurs.  This is true even when "Open" is selected at the bottom of the demo.

**Comment by topherfangio** [comment]
Thanks for the report! I'll look into this!

**Comment by topherfangio** [comment]
This should now be fixed in master; was an issue with webkit-based browsers. However, we still need to finish #3214 to more properly support touch devices.

Please follow that issue for more updates.

**Comment by daftfox** [comment]
For mobile devices, the listeners should be able to listen to clicks instead of mouseenter/mouseleave.
I have fixed this locally by altering the setupListeners function to:

// Setup our event listeners
      function setupListeners() {
        $element.on('click', function(){
          if(vm.isOpen){
            vm.close();
          } else {
            vm.open();
          }
        });
      }

Again sorry if this is not the proper way of reporting this. I am rather new to reporting issues/fixes.

**Comment by topherfangio** [comment]
@daftfox That is indeed the correct fix, I am attempting to make it a bit more generic though in order to support #3214. A fix should be coming soon :-)

**Comment by daftfox** [comment]
@topherfangio nice. :)

Actually, I'd like to review my previous post.
To make the FAB speeddial compatible with (iOS) touch devices and desktop browsers, I set the listener to 'mousedown'.
