### ISSUE TITLE
md-tabs: Cannot read property 'offsetLeft' of undefined

### ISSUE THREAD

**Issue by jo-me** [angular/material#3264]
Hi,
just upgraded to latest Angular Material 0.10.0-rc4 to check whether the bugfixes for my issues regarding md-tabs are having the expected effects. (I'm referring to  #3169, #3170 , #2730 )

However, I get a new error when the tabs are created:
``'TypeError: Cannot read property 'offsetLeft' of undefined``

The error is easily reproducible if the tabs are created asynchronously (e.g. after timeout).
See here: http://plnkr.co/edit/qpAPFBFOPBs6pnaiR1nH?p=preview

It sounds very similar to #2402. 
Asynchronous loading of tabs also breaks  #3169 again..

Cheers

**Comment by glomotion** [comment]
So this particular bug is blocking us upgrading from ~0.6.0 to 0.10.0 as we heavily rely on md-tabs. 

Another (ultra simple) example of the bug replicated on codepen: http://codepen.io/glomotion/pen/pJrxYO?editors=101. 

I know it's sometimes pretty hard to forecast timelines for stuff like this, but I was just wondering if there is any idea around how long it might take for this bug to be addressed?

**Comment by robertmesserle** [comment]
I'm adding a fix for this, but in the meantime, it should be easily fixable by adding an ng-if to md-tabs that checks the length.  Example:

http://codepen.io/robertmesserle/pen/yNoGJO

**Comment by glomotion** [comment]
Oh nice! 

I should have thought of that. :) 

Thanks Robert, now we can upgrade to 0.10.0! Huzzaaah!

**Comment by matt-d-rat** [comment]
I have the same issue, except my use case comes from using transclusion in my custom parent and child directives that leverage md-tabs and md-tab respectively, so effectively I am "dynamically" adding the md-tab directives in a round about way.

I tried using the ng-if approach on the md-tabs in my directive, but then I have other issues because my child directives are dependent on the parent controller and don't get transcluded as a result.

The temp workaround I have for the time being is putting in a "dummy" temporary tab, and removing it in the parent directive after the transclusion has finished. A bit hacky but works for the time being.
