### ISSUE TITLE
md-selected-item-change called twice

### ISSUE THREAD

**Issue by chr22** [angular/material#3279]
When using mdAutocomplete with mdChips is md-selected-item-change called twice when a chip is chosen, as shown in this [CodePen](http://codepen.io/chr22/pen/ZGJabN?editors=101).

**Comment by saurabh-p** [comment]
+1

**Comment by 526avijitgupta** [comment]
I was also facing the same issue. And here is a solution for the same: [Codepen](http://codepen.io/526avijit/pen/ZGMjQN?editors=101).  
Basically, just declare a variable in your controller which is set to `true` as soon as the `md-selected-item-change`'s function is called. At the end of this function, set the variable to `false` in a timeout. So, whenever the function is called automatically, (on `md-select-item-change`), then check that that variable should be `false`. This is prevent the function from automatically getting called the 2nd time.    

Change function's body to:  
```
$scope.myFunc = function() {  
  $scope.isCalled = true;
  ......  {{ function body }} ....
  $timeout(function() {
    $scope.isCalled = false;
  });
};
```

And in your HTML:  
  `md-selected-item-change="!isCalled &&  ctrl.chipSearch(item)"`  instead of  `md-selected-item-change="ctrl.chipSearch(item)"`

**Comment by typotter** [comment]
Hi there,
The autocomplete on-selected-item-change is fired twice because of the mechanics involved in wiring it up to chips: the user selects an option from autocomplete (first change), then chips snarfs that selection into its model, and clears the autocomplete selection (second change).

If you want to run code when the user selects an item, you can watch the model for changes, and react accordingly. Is there a reason that this would not work for your use case?
