### ISSUE TITLE
Can not load 'ngMessages' in my demo app

### ISSUE THREAD

**Issue by hckhanh** [angular/material#3303]
When I import **'ngMessage'** to my app. It does not work, even does not display the Material theme.
If i remove `'ngMessage'` from the module. It displays the correct theme, but `'ngMessage'` doesn't work
How can I fix it?
![but](https://cloud.githubusercontent.com/assets/6380436/8198290/892bf180-14ce-11e5-87e8-14d28eb00c22.png)

**Comment by hckhanh** [comment]
I follow the example in Material page of Angular
https://material.angularjs.org/latest/#/demo/material.components.input

**Comment by ngraef** [comment]
This is an app-specific question and not an issue with the library. Please ask questions like this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial), not here in the issue tracker.

Regarding your problem, you're not loading `angular-messages.js`, which is why it can't be found.

**Comment by hckhanh** [comment]
Thank you, @ngraef I will remember that :)
