### ISSUE TITLE
Flexbox bug in Firefox

### ISSUE THREAD

**Issue by DaveRevay2** [angular/material#3304]
I did some searching and could not see this listed as a know flex bug.
Not sure if it is specific to the angular material implementation.

Essentially, when there is content greater than the width of the flex box, the box will not flex and will not overflow. It works normally in latest ie and chrome but not working in firefox.

See the pen here for description:
http://codepen.io/anon/pen/vOJVOB

**Comment by gkalpak** [comment]
I believe it is a bug in Firefox's implementation of the Flexbox spec.

The inconsistency boils down to the width of `.container`:

```html
<div layout-align="center" layout="row">   <!-- Has style: display: flex -->
    <div class="container">                <!-- Has style: width: 600px -->
      ...
```

In Chrome/IE, when you shrink the window so that `div[layout="row"]` becomes less than 600px wide, `div.container` shrinks down in order to account for that (thus its content also shrinks).
In Firefox, `div.container` won't shrink below 600px (and thus its content won't have to shrink either).

--
#### Why I think it's a Firefox bug

According to the [Flexbox spec][1], a flex-item (i.e. a child of a flex-container) should shrink according to its `flex-basis` and `flex-shrink` properties and subject to its minimum _main-size_ (in case of `flex-direction: row`, the _main-size_ is the _width_).

Since there are no values set for `flex-basis` and `flex-shrink` on `div.container`, the default values are assumed: `flex-shrink: 1`, `flex-basis: auto` (which means it is determined by the _main-size_ (i.e. _width_))

Since it is the only child of its parent, the base-size shouldn't matter, only that it is allowed to shrink as much as necessary (in order to absorb negative space). This, again, is subject to its [_implied minimum main size_][2]. According to the spec (and since there is no explicit `min-width` set), this is calculated as `min(600px, content-size)`, where _content-size_ is determined as:

> The smallest size a box could take that doesn’t lead to overflow that could be avoided by choosing a larger size.

--
Taking into account all the above, I believe it is indeed an inconsistency in Firefox's implementation of the Flexbox spec.
<sub>Note that setting `min-width: 600px` on `.container` makes Chrome behave like Firefox (i.e. not shrink `.container` below 600px), which is the expected behaviour.</sub>

[1]: http://www.w3.org/TR/css-flexbox-1/
[2]: http://www.w3.org/TR/css-flexbox-1/#min-size-auto

**Comment by ThomasBurleson** [comment]
See fixed demo:  http://codepen.io/team/AngularMaterial/pen/WvMeMQ; where the *outside* `<div>` have a `height: 100%;`
