### ISSUE TITLE
md-icon does not work as specified in documentation

### ISSUE THREAD

**Issue by wlingke** [angular/material#3306]
I followed the exact instructions per the documentation:

- I added `<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">`
- Then, I tried the following: 

`<md-icon md-font-icon="android" aria-label="android"></md-icon>`
`<md-icon class="icon_home" aria-label="Home"></md-icon>`
`<md-icon>home</md-icon>`

However, only the last one worked. The 1st and 2nd html produce nothing.

I am using v0.10.0

**Comment by tinusn** [comment]
Actually, you should have used
```
<md-icon md-font-set="material-icons"> face </md-icon>
```
If you wanted to use the material icons. The first two lines are for another font as per the documentation ("When using Font Icons with classnames:")

**Comment by wlingke** [comment]
I see - I thought that the material icons also had a classnames version. My mistake. Thanks for the clarification.

**Comment by ThomasBurleson** [comment]
@tinusn - To be clear:

*  Use the [deprecated] **md-font-icon** if using font-icons with custom styles matching the md-font-icon value
*  Use **class** if using font-icons a specific custom style
*  Use **md-font-set** if you want to reference an alias to- or specific class style for an entire font-icon set
*  Otherwise, if a **class** is NOT specified then the 'material-icons' class will be auto-added.

**Comment by tinusn** [comment]
@ThomasBurleson You should properly specify that in the mdIcon documentation (https://material.angularjs.org/latest/#/api/material.components.icon/directive/mdIcon), at least that was not clear to me from reading it - especially that md-font-icon is deprecated.

**Comment by tinyfly** [comment]
Agreed, the way it reads isn't very clear. I did the exact same thing as @wlingke and couldn't figure out why it wasn't working.
