### ISSUE TITLE
InkRipple : Intensive clicks can make the element stay dark

### ISSUE THREAD

**Issue by NicolasVargas** [angular/material#3346]
Hi,

Prepare you click skills and try on the [button demo](https://material.angularjs.org/HEAD/#/demo/material.components.button) : If you click intensively on a button, it remains dark.

**Comment by JunedS** [comment]
I have been observing this issue since very long time (either the button becomes dark or completely white depending on the ink) and have observed it mostly in chrome and doesn't seem to be happening in FF if I am not wrong. Also what I have observed is after clicking on button the ripple effect seems to stay without fading away if we do a mouse click else where until we do another click.
