### ISSUE TITLE
Flex Layout Issues with Min-Height / Relative Positioning

### ISSUE THREAD

**Issue by chrismbeckett** [angular/material#3376]
I see a lot of issues being reporting about layouts not working on various devices or browsers, Yesterday I setup a fairly common nested layout:

- outer row layout with a left fixed sidenav and flex content area
- inner column layout with a top-level toolbar and flex content-area

The results across Chrome, IE10, Firebox, Android5 and IOS8 was very inconsistent. Most of the problems were related to scrollbars not showing up for overflow, and flex children not filling their containers. After much tweaking, the following solved all my layout issues:

```css
[layout-fill] {
  height: 100% !important;
  position: absolute;
}
```

a) It seems a lot of the CSS layout in angular material is using min-height instead of height. There are known flex issues in some browsers with min-height not calculating flex children correctly, and I saw this across multiple browsers. Setting height fixed the problem.

b) Particularly in chrome, scrolling was screwed up on flex children when position: relative was used. Switching to absolute for full-height/width solved the scrolling from Chrome browser and Android.

**Comment by jvmccarthy** [comment]
I'm seeing similar issues.  When running in IE11 and using the `flex` attribute, I'm seeing issues with using `layout-fill` on the flex container similar to what @chrismbeckett mentioned in (a).  If I put `height: 100%` on the container, the child elements flex correctly.  Otherwise, they flex to height `0`.  Looks like [Flexbug #3 - min-height on a flex container won't apply to its flex items] (https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items).

**Comment by KingWu** [comment]
Any demo to show how to handle relative positioning?

**Comment by jeson114** [comment]
layout fill kinda screws up my height of flex based grids
