### ISSUE TITLE
md-button should use wrapper div for flexbox support on firefox

### ISSUE THREAD

**Issue by rschmukler** [angular/material#3383]
Right now `md-menu` is broken on firefox. This is because firefox does not allow applying flexbox to elements that defer to OS for rendering, specifically the `button`. See [this stackoverflow](https://stackoverflow.com/questions/24289251/flexbox-not-working-in-buttons-in-firefox) and this [bug tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=984869#c2) for commentary on it. The point is, Mozilla has marked this as "intended" behavior and the solution is to put a `div` inside the button that uses flexbox. Wanted to ping people to see if there is any breakage that comes to immediate mind with this solution...

@jelbourn @robertmesserle @ThomasBurleson. Any objections?

This will also help anyone using ngMaterial who expects the button to behave like a flexbox (which, given our CSS, should be everyone).

**Comment by jelbourn** [comment]
I'm actually of the opinion that none of our components should have `display: flex` or `display: inline-flex` on their outermost element. The problem is that the baseline computation for flex elements is different from `block` / `inline-block`, and this makes it very difficult to do something like putting an `md-button` next to an `input`.

**Comment by ThomasBurleson** [comment]
Concensus with @jelbourn and @rschmukler - outside container for component should be `display:inline-block;`
