### ISSUE TITLE
md-fab-toolbar - strange margin

### ISSUE THREAD

**Issue by Arth95** [angular/material#3390]
Hi!
I've put md-fab-toolbar in my ui-router template and this happens:
![bez tytulu](https://cloud.githubusercontent.com/assets/11191600/8281228/db0133ec-18e5-11e5-9315-03b785f26138.jpg)
Template is in:
md-content
    div layout="column" ui-view
    /div
/md-content
In template md-fab-toolbar is next to table in div.
This happens also when I put this element outside ui-view.

**Comment by topherfangio** [comment]
Any chance you could provide a [Codepen](http://codepen.io/ ) so I can debug the issue a bit further?

**Comment by minhajkk** [comment]
@topherfangio I'm also facing same problem here's the codepen http://codepen.io/anon/pen/GJOwaM

**Comment by EndymionUSA** [comment]
change 
```
ng-class="md-right"
```
to
```
class="md-left"
```

**Comment by topherfangio** [comment]
@EndymionUSA is definitely correct, you should use `class="md-left"` or `class="md-right"` instead of `ng-class`, however, it looks like there may be some other issues with this.

On the example, I'm seeing the house icon appear above the FAB even when the toolbar isn't visible. I'll look into this a bit further, but it's possible it has been fixed with some other recent updates.

**Comment by topherfangio** [comment]
Quick note, in master/0.11.0 we have made some breaking changes to make the fabToolbar better conform with the options in fabSpeedDial. Instead of manually setting the class, you should now use the `md-direction` attribute set to `left` or `right`.

Example:

    <md-fab-toolbar md-direction='left'>
      ...
    </md-fab-toolbar>

This should fix this issue once #4185 gets merged.
