### ISSUE TITLE
md-dialog: Pressing mouse down inside dialog and letting go outside closes it

### ISSUE THREAD

**Issue by blixt** [angular/material#3404]
(Requires option `clickOutsideToClose: true`)

The click position seems to be computed on mouse up rather than mouse down. Intuitively, the mouse down position should be used (so that the dialog doesn't close on failed drag/drop attempts, etc.)

**Comment by topherfangio** [comment]
I believe this has already been fixed as I cannot reproduce it in the latest demos: https://material.angularjs.org/1.0.0-rc2/demo/dialog

It forces both the mousedown/mouseup to be on the dialog to close.

If you are still seeing this issue, please post a comment including a Codepen so that we can investigate and we will reopen.
