### ISSUE TITLE
Error in async tabs

### ISSUE THREAD

**Issue by gio82** [angular/material#3412]
When I create tabs with an async call it gave me this error:

```
TypeError: Cannot read property 'offsetLeft' of undefined
    at adjustOffset (angular-material.js:15025)
    at angular-material.js:14605
```

This because every tab I have is created async so `tab` is undefined.

This error has the following side effect:
![screen shot 2015-06-23 at 10 19 01](https://cloud.githubusercontent.com/assets/3081584/8301762/50b3921e-1991-11e5-934c-201233cfd731.png)

If I add a fake non async tab the issue disappear.

**Comment by jurgenramirez** [comment]
I have the same problem, I'm using latest release (0.10.0) does not work when more tabs arrows added, in the example of the official website, but in this version when I add a new tab brings me to the last and need this effect so I use this version because earlier versions will not work
https://material.angularjs.org/latest/#/demo/material.components.tabs
Example Dynamic Tabs

**Comment by robertmesserle** [comment]
@gio82 @jurgenramirez Is this still an issue?  If so, please reply with a codepen demo.  Closing for now.
