### ISSUE TITLE
I can't use multiple FAB Speed Dial

### ISSUE THREAD

**Issue by mu7amad** [angular/material#3414]
http://codepen.io/anon/pen/rVYLjR

**Comment by topherfangio** [comment]
Can you be a bit more specific about the issue? From the codepen, it looks like the buttons are appearing correctly. The only issue I see is that you've copy/pasted the demo code which means that when you open one, it is automatically opening the other.

**Comment by mu7amad** [comment]
I don't want it to automatically open the other, i want each one just open itself because it's in ng-repeat. If there are 3 or 4 items when i hover on one, all of them will be opened.

**Comment by topherfangio** [comment]
Right, this is because you have copy/pasted the demo code which uses the `md-open` attribute to tie it to a controller property. If you remove this attribute, it should fix your problem.

That said, I would recommend starting from a clean `<md-fab-speed-dial>` component and building it with the functionality you need rather than copy/pasting as it may cause some issues later in your app.

**Comment by mu7amad** [comment]
Thanks so much, was really helpful from you :). I just copy/past the code to show you that this component will be repeat.
