### ISSUE TITLE
md-list-item active class

### ISSUE THREAD

**Issue by vinnitu** [angular/material#3420]
doesn't work or not exists in nature, am I right?

**Comment by topherfangio** [comment]
There currently is no active class on the `md-list-item`. What exactly are you trying to achieve?

**Comment by topherfangio** [comment]
@vinnitu Can you please provide some additional information about this so that we can respond?

**Comment by joerideg** [comment]
Hi @topherfangio ,
So in applications it happends a lot that you would have a sidenav with a list of items in them right. Usually these are links to pages, but in webapps they could be used to select a component on a page in a page-build-system for example.
Now such cases it is nice to have some kind of .active class + styling on a list-item to indicate that that list-item has been selected in the list and is currently active/selected.
Its a bit like [the Activated state in the contact chips list](http://www.google.com/design/spec/components/chips.html#chips-contact-chips) where the Activated contact is highlighted.

**Comment by Alplob** [comment]
Yes, that would be very useful :+1: , thanks!

**Comment by beyondsanity** [comment]
I've been searching for the same feature, it would be really useful

**Comment by timbrown81** [comment]
+1 on need

**Comment by darkmavis1980** [comment]
+1

**Comment by richi2666** [comment]
+1

**Comment by tex0l** [comment]
+1

**Comment by dalu** [comment]
what could be an alternative?
an always open menu?
is there an alternative currently?

**Comment by topherfangio** [comment]
I am not sure that this is a core feature of the list item itself. Particularly, I'm not seeing how anything we do would be easier than developers using the existing `ng-class` directive to apply the active class when they need it.

I guess what I'm saying is: I don't think Angular Material can always *know* when *your* app wants something selected.

If you can come up with some common usages, we will consider it, but it seems like you may want a higher-level component/directive that knows about how your application operates.

**Comment by darkmavis1980** [comment]
The problem of using just the ng-class is it's rather hard to override the css behaviour of the md-list-item, I tried as a first option (I simply needed to set a background colour), but it was giving me odd behaviours, and behaving differently on Chrome and Firefox

**Comment by joerideg** [comment]
Ng material should only define some styling under a md-listitem-active class (or similar). We can them add this class to the list item when we see fit.

**Comment by topherfangio** [comment]
@joerideg Since there aren't any styles provided by the spec, and the fact that you can add your own custom styles/active class, I don't see how this would really be beneficial since we'd basically be guessing at what you want the active class to look like.

@darkmavis1980 What issues were you having? This definitely seems like something we might be able to address to make it easier to add your own active class.

**Comment by OhDavit** [comment]
As I have just started to do some front end, not sure how achive this for md-list-item. But as a mobile developer can say it would be very weird that such kind of feature is missing.

**Comment by dalu** [comment]
Ok. How do you get a menu or navigation with ripple effect as in ng-click="null" and full fill different background color when the link is active?
Don't overcomplicate it. How do you do it?
I've been wasting 3 days now on this, what should've been a quick prototype I'm still stuck at navigation. Something that's done in an hour at most.
Where are ngmaterial's means to build navigation out of the box?
If you have to use custom styles why are you using ngmaterial at all then?

**Comment by joerideg** [comment]
Hey @topherfangio,  
See [here)](https://www.google.com/design/spec/layout/structure.html#structure-side-nav) and [here](https://www.google.com/design/spec/components/lists.html#lists-specs) for an example of what seems to be an active list item. It is true it is not mentioned specificly but the visuals show it.

**Comment by joerideg** [comment]
More examples at http://www.google.com/design/spec/patterns/navigation.html

**Comment by topherfangio** [comment]
@joerideg Thanks for the additional pointers.

@dalu Here is a quick Codepen that I put together to demonstrate how to do it: http://codepen.io/topherfangio/pen/EKQELJ?editors=0100

If you want to also change/remove the grey background on hover, you can uncomment the CSS at the top. I'll grant that this is definitely a bit ugly to have to add and we can perhaps make a fix for this, but otherwise, it seems to do what you want by very simply adding the active class.

Can you guys fork the above Codepen with some examples of what you're trying to do so that we can look at all of your needs? As I said, I'm not opposed to adding this, I just want to make sure we do something that's actually useful :smile: 

For instance, would you want to be able to do something like `md-primary`, `md-accent`, `md-warn` to change the text color? What about the background color?

If we can come up with some common use-cases, I'll see about creating a PR.

**Comment by joerideg** [comment]
Ill have a look!

**Comment by dalu** [comment]
@topherfangio I'm using ui.router and ng-click doesn't work there like this.
It needs an `<a ui-sref="routename">Title</a>`
or
`<md-list-item ui-sref-active="nav-active"><a ui-sref="routename">Title</a>`
but so far only ng-click provides the full width ripple effect.

Then the topnav. I can have a brand or home link and menu items (flex=row or float:left) inside the top navbar and it looks great on a large screen but it doesn't collapse properly on a small screen.
That means depending on wheter I'm using md-menu-bar or not and what kind of elements the menus/menu-items either disappear or align in a column.

**Comment by topherfangio** [comment]
@dalu I'm not sure about your topnav issue (if you can post a Codepen in a new issue we can take a look), but I definitely see your issue/frustration with trying to use ui-sref. I'm going to talk to the team and see how we might be able to address this. Off the top of my head, it seems like might want to provide a custom `<nav-list>` component or something that can handle these situations better.

**Comment by dalu** [comment]
eh... I .. of course I didn't commit the changes. That's how it always goes. There's git and you just don't use it the way you should because you're in the middle of it.

http://codepen.io/anon/pen/ZWoVzR

try reducing the width of your browser.

**Comment by joerideg** [comment]
@topherfangio I havent had time yet to set up some examples but hope to do so this weeked. You're idea of adding md-primary, md-accent or ms-warn styles on a listitem sounds good and workable though. Cheers.

**Comment by 700ghz** [comment]
temporary resolve with ng-class:
<md-list-item ng-repeat="title in titles" ng-class="title.id == note.id ? 'active' : false">

**Comment by gerardcarbo** [comment]
Or just use 'ui-sref-active' directive:

```
<md-list-item ng-repeat="item in app.menu" ui-sref="{{item.state}}" ui-sref-active="item-menu-active">
```

**Comment by gerardcarbo** [comment]
Or using md-colors:

```
<md-list-item ng-repeat="item in app.menu" ui-sref="{{item.state}}" 
        md-colors="{background: ($ctrl.isActive(item.state) ? 'primary' : 'grey-A100')}">

```
and in controller:

`
   isActive(state) {
        return this.$state.current.name.includes(state);
   }
`

**Comment by sajjad-shirazy** [comment]
`<md-list-item ng-repeat="item in vm.items" ng-click="vm.selectedItem = item;"  ng-class="vm.selectedItem == item ? 'active':false">`
 and
`md-list-item{

        transition: border-width 0.1s ease-in-out;
        &.active{
            border-right: 4px solid #d84315;
            background-color: rgba(0, 0, 0, 0.03);
        }

    }`

**Comment by topherfangio** [comment]
With all of these valid solutions, I don't think we need to add anything else? If someone can give a specific example, we will reconsider and reopen.

**Comment by joerideg** [comment]
Adding a class and styling yourself was never the issue. Thats out of the box with angular.

Techincally this issue still has not been solved because md-primary, md-accent and md-warn [do not work on a list item](https://material.angularjs.org/1.1.2/Theming/02_declarative_syntax). 

The request was to provide some styling behaviour on a md-listitem-active class or similar in the angular material framework following the specs as provided in the links I posted above. 

It would basicly make this workaround a lot better (example using ui router):
from
```html
<md-list-item md-colors="{background: ($ctrl.isActive() ? 'primary' : 'grey-A100')}">
<!-- and then some controller who checks the active state via $state -->
```
to
```html
<md-list-item ui-sref-active="md-list-item-active">
```
Where `.md-list-item-active` adds 'active' styling per the spec, changable by adding md-primary, md-accent or md-warn classes.

But I guess the workaround, although not as great, is doable.

**Comment by Nextsun-Limited** [comment]
routerLinkActive is the solution in the last angular version:
<code>
<a routerLink="/user/bob" routerLinkActive="active-link" [routerLinkActiveOptions]="{exact:
true}">
</code>

documentation: https://angular.io/api/router/RouterLinkActive
