### ISSUE TITLE
Nested layouts and flex

### ISSUE THREAD

**Issue by mnn** [angular/material#3436]
Flex seems to be broken on Chrome when used in a nested layout. Firefox renders it as expected.

I'm new to Angular Material so it might be my fault somehow. If this is expected bahaviour what is recommended solution? I have tried a lot of different combinations without any luck,  I would welcome any suggestions on solving this.

Pictures
===
Firefox
---
![Firefox](http://i.imgur.com/OPRrnBY.png)

Chrome
---
![Chrome](http://i.imgur.com/HPIX6OQ.png)
In an inner layout only attribute "flex" without value works.

Code
===
http://codepen.io/monnef/pen/xGPXvB

Relevant snippet:
```html
  <body layout="row" ng-controller="AppCtrl">
    <div flex="30" layout="column" class=a>
      flex="30"
      <md-card flex="40">flex="40"</md-card>
      <md-card flex>flex</md-card>
    </div>
    <div flex layout="column" class=a>
      flex
      <md-card flex="70">flex="70"</md-card>
      <md-card flex="10">flex="10"</md-card>
    </div>
  </body>
```

**Comment by ThomasBurleson** [comment]
@mnn - See [Nested Flex Containers](http://codepen.io/team/AngularMaterial/pen/WvMeMQ) demo where the card containers (using class "a" or "boxWithHeight") have an explicit height style attribute.

Per feedback from @gkalpak:

Relevant spec sections:

1. [flex-basis][1]
2. [definite/indefinite sizes][2]

--
**Summary:**

* `flex="XYZ" sets `flex: 0 0 XYZ%` => `flex-basis: XYZ%`.
* Because it is a percentage value and it is resolved against the flex container's indefinite block size, it becomes equivalent to `flex-basis: auto`.
* Since there is no `height` value (so it is by default `auto`), it falls back to `flex-basis: content`.
* The flex-basis is determined by the element's content (not our specified XYZ :disappointed:).

<sub>I am not 100% sure I am interpreting the spec correctly, but it kind of makes sense :)</sub>

--
Setting a different height value on the flex-container (e.g. `height: 100%`), makes everything work as expected. ([Updated demo][3])

[1]: http://www.w3.org/TR/css-flexbox-1/#flex-basis-property
[2]: http://www.w3.org/TR/css-flexbox-1/#indefinite
[3]: http://codepen.io/team/AngularMaterial/pen/WvMeMQ

**Comment by amritk** [comment]
So every interior flex container needs a height value? Then what is the point of using flex if it doesn't work vertically?

**Comment by amritk** [comment]
Now say I want to nest another one in there, it doesn't work. Is there a way to keep nesting them properly to get the correct vertical split?

http://codepen.io/anon/pen/WvWRqp

You don't seem to be able to get a proper height % wise inside a flex child.

**Comment by jdwilliams15** [comment]
+1 Looking for a solution when using multiple layers of nesting as well.

**Comment by Pexak** [comment]
@ThomasBurleson your solution is not working

**Comment by ThomasBurleson** [comment]
@Pexak - Your comment is not very helpful. 
*  Do you have a snapshot ?
*  Can you provide more details ?
*  Which browser and version are you using ?

**Comment by Pexak** [comment]
@ThomasBurleson  Sure, sorry,
I'm using Chrome 45 and firefox 31
It seems your codepen example - http://codepen.io/anon/pen/PPGNEm is not working, sections area do not expand to flex value, it only adjust to text size

**Comment by ThomasBurleson** [comment]
We do not support FireFox 31: our support are N-1 where N === browser's
current release version. Chrome works (with some fixes):

You *MUST *create an ng-app with a 'ngMaterial' dependency.

Here is an updated CodePen that works:
http://codepen.io/ThomasBurleson/pen/wKzOvm

**Comment by jmuharsky** [comment]
@ThomasBurleson I'm having a similar issue with nesting, and it's a regression since 0.10.0 (the last version I used).  Looking at the CodePen you linked, I'm seeing a similar issue -- the nested items' flex heights aren't being respected.

**Comment by ThomasBurleson** [comment]
Fixed and working in master. See CodePen http://codepen.io/ThomasBurleson/pen/wKzOvm

![screen shot 2015-10-15 at 8 30 24 pm](https://cloud.githubusercontent.com/assets/210413/10531799/ae394d0e-737b-11e5-81be-f5e1be9c61a6.png)

**Comment by ThadeuLuz** [comment]
just to further illustrate, OP's codepen looks even worse on Safari 9.0.1, with no height at all

![screen shot 2015-10-28 at 15 29 30](https://cloud.githubusercontent.com/assets/5687190/10799965/5badfae0-7d8e-11e5-81cd-5355870c963e.png)

That explains why my the page crawled into a ball..

**Comment by sstorie** [comment]
With 1.0.0-rc4 I'm seeing strange behavior with Chrome. I don't really understand the root issue to provide much constructive feedback here, but I posted a question on stackoverflow trying to get some help with why the vertical heights of flex'd elements don't work intuitively in Chrome:

http://stackoverflow.com/questions/33785146/building-simplest-gmail-layout-with-angular-material-chrome-issue

Here's the codepen I created to illustrate the issue: http://codepen.io/sstorie/pen/ZbPybm

**Comment by jbcpollak** [comment]
@ThomasBurleson Your CodePen doesn't seem to work with another level of nested vertical flexes:

http://codepen.io/anon/pen/VeeOER

Is this considered a bug?

**Comment by kapil-kharade** [comment]
Also when we try to change the flex value of row from 30 to 40 or any other value, then chrome fails to apply.
