### ISSUE TITLE
mdInputContainer: Add an unexpected md-icon-float class when used placeholder attribute

### ISSUE THREAD

**Issue by mbarakaja** [angular/material#3463]
When adding a floating label to an input element using the placeholder html attribute,  **md-input-container** adds a **md-icon-float** class, which apply a 36px margin-left rule to the label.

In the image below, you can see a space on the left side of the label.
![screenshot from 2015-06-25 15 25 00](https://cloud.githubusercontent.com/assets/7861175/8363681/91e5a3f8-1b4e-11e5-8639-42c0e283517b.png)

`Reproduce the Error:` http://codepen.io/anon/pen/yNPWMg
`version:` 0.10.0 and v0.10.0-master-27b535e
`Browser:` Google Chrome 43, Firefox 38. On Ubuntu 15.04

**Comment by brianpkelley** [comment]
+1

**Comment by topherfangio** [comment]
This appears to be fixed in the latest release: http://codepen.io/topherfangio/pen/RWBYEZ?editors=100

Quick note: the `layout-padding` on the wrapper seems to cause some issues with the heights of the labels if you have the `<md-input-container>`s direct children. Wrapping them in an extra `<div>` appears to fix this.

If you're still seeing this issue after upgrading, please comment and we will reopen. Thanks!
