### ISSUE TITLE
md-autocomplete not working on the device - phonegap

### ISSUE THREAD

**Issue by asaadbaw** [angular/material#3490]
Hello

when I test my md-autocomplete page on wamp it works put when I deploy it to my device through build.phonegap.com I see white screen. Any help?
![image](https://cloud.githubusercontent.com/assets/8416276/8393333/44a21f5a-1d14-11e5-91c8-4396efd7559f.png)

**Comment by jlmagee** [comment]
I have a similar issue in a development project. It appears to be related to the positioning of the containing element on the page. Trying to develp a sanitized example.

**Comment by jlmagee** [comment]
There are 2 demo pages at https://ngmatdemo.appspot.com/#!/service/demo and https://ngmatdemo.appspot.com/#!/service/demo2 

The 2nd behaves acceptably on my Nexus 6

The first does not. The upper autocomplete incorrectly positions the selection scroller but it sort of works. The lower autocomplete seems to position the scroller and the input area under the keyboard and neither are viewable or accessible in any other way.

Perhaps you'll think this is a stretch, but I believe this and several other peculiarities I've encountered to be associated with incorrect calculations of element sizes when the height of the page content exceeds the height of the viewport  AND the page contains any element with a fixed height in style.

**Comment by jlmagee** [comment]
Autocomplete on Chrome for Android on a Nexus 6 is fundamentally broken on a page that contains more content than fits on the screen. If it is alone in a dialog box it is somewhat better but eventually degrades, whites out unrelated content, and hangs.

My most recent breakthrough is to use it in a dialog box and hide all the page content just before the $mdDialog.show. I'm pretty certain this behaves similarly on all mobile devices,

And I still believe it is caused by the fundamental flaw in the last paragraph of my previous comment here. 

@ThomasBurleson @robertmesserle and it really ought to get more priority  than it will see in Backlog.
