### ISSUE TITLE
(md-select) fails to display text on pre-selected object

### ISSUE THREAD

**Issue by bijoux** [angular/material#3495]
It appears the text values are not displayed for pre-selected objects
http://codepen.io/anon/pen/jPYwwY

**Comment by rschmukler** [comment]
The issue is that `<md-option ng-value="{{topping.name}}"> sets the `ng-model` to the `topping.name` property so in this case it is `"Bacon"` not `{name: "Bacon", category: "meat"}`. See [this codepen](http://codepen.io/anon/pen/aOEVLx) for an example of it working.

**Comment by bijoux** [comment]
sorry to reopen this but what if I need the model to be an object like how md-select behaved before the change. I think this [codepen](http://codepen.io/anon/pen/MwrMoV) shows the issue better.

**Comment by rschmukler** [comment]
The issue is that `ngModel` doesn't know that these objects are the same (because technically, they point to different objects in memory). To get around this `ngModel` exposes `ng-model-options` where you can specify what you track by. Check out [this code](http://codepen.io/rschmukler/pen/WvMePx) for a demo of using it.

**Comment by bijoux** [comment]
Cool, thanks. I think I got md-select behaving like it was before. Thanks for the quick response, we really appreciate that.
