### ISSUE TITLE
md-input container md-input ng-disabled/ng-readonly

### ISSUE THREAD

**Issue by robertbaker** [angular/material#3564]
When the input is disabled or readonly, should the color highlight when it's clicked still be visible?

When the input is disabled, should the md-char-counter div be visible? I think it should only be visible when the field isn't readonly or disabled.

Color highlight is working well with readonly directive but md-input doesn't manage properly the ng-readonly directive (color highlight is still active with ng-readonly="true").

**Comment by MarcLoupias** [comment]
There is another issue on top of that.

Color highlight is working well with readonly but md-input doesn't manage properly the ng-readonly directive (color highlight is still active with ng-readonly="true").

**Comment by robertbaker** [comment]
@ThomasBurleson Simple enough to get it into the 0.12 milestone?

**Comment by ThomasBurleson** [comment]
@robertbaker - It is not a question of simple. All issues in our queue must be prioritized and triaged. These are good questions and issues to fix... but they are not critical.

**Comment by robertbaker** [comment]
@robertmesserle since you did the disabled styling, mind taking care of this quick task :)
or
@topherfangio

**Comment by topherfangio** [comment]
@robertbaker We have a lot of tasks in our queue currently and we lean on a lot @ThomasBurleson to help us prioritize our tasks so that we are efficient with our time and provide a quality product. If Thomas has prioritized this for a later release, we are not likely to work on it unless we _happen_ to be fixing a related (and higher priority) issue and can add this in without too much effort.

However, as an open source project, we also lean a lot on the community to help us build a product that meets their needs. If this is something that you really want to see, and you need it before our scheduled timeframe, a Pull Request would certainly be most welcome!

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by flaviocolonna** [comment]
To fix by own the problem, just add 'ng-disabled':attr.ngDisabled in the for each of ion-md-input.js when it is adding the attributes to the input tag. Cheers
