### ISSUE TITLE
Why does md-2-line md-list-item-text h3 have line-height of 0.75em?

### ISSUE THREAD

**Issue by fRzzy** [angular/material#3584]
Instead of 1em to show full text height when overflow is set to hidden (to use text-overflow: ellipsis)

Please check the attached screenshot, I think the problem isn't arise with English language but in Vietnamese there are tone marks above or below a character that got clipped off.
![screen shot 2015-07-05 at 22 18 29](https://cloud.githubusercontent.com/assets/126648/8512234/767abad6-2364-11e5-85d2-391d96129092.png)

**Comment by topherfangio** [comment]
I believe this has been fixed in the latest version by increasing the `line-height` to `1.2em`.

<img width="364" alt="screen shot 2015-11-03 at 11 00 05 am" src="https://cloud.githubusercontent.com/assets/54370/10916721/19f36cf8-821a-11e5-81cd-f5d6ae988327.png">

If you are still seeing issues after upgrading, please comment and we will reopen.
