### ISSUE TITLE
Issue Reporting Workflow

### ISSUE THREAD

**Issue by rschmukler** [angular/material#3606]
- [ ] link to `code.google.com` for master on new codepens
- [ ] consider adding a bot to check codepens for code not running master

@robertmesserle can you ask @naomiblack about this (specifically the first one, the second one is just the victory lap)

**Comment by robertmesserle** [comment]
@rschmukler We should talk about this more - I don't think this is a good idea.  One of the reasons that I had originally setup the SHA-specific links on HEAD (aside from the CDN issue) is that we often had bugs logged against master that were no longer broken by the time we saw the issue.  It's important for us to be able to see the broken version so that we can confirm that it has been fixed, and this will not be possible if CodePen demos are linked to HEAD.  (Without seeing it broken first, we will have no idea if the issue is fixed or if we are just not recreating it properly.)
