### ISSUE TITLE
md-autocomplete TypeError with Angular 1.4.1

### ISSUE THREAD

**Issue by tuhoojabotti** [angular/material#3637]
When typing into the input I get:
> TypeError: Cannot use 'in' operator to search for 'ctrl' in \<searchString\>*

\* searchString is what I typed in the field.

Demo of the issue: http://codepen.io/anon/pen/PqRgVO

**Comment by nestorneto** [comment]
+1

**Comment by ThomasBurleson** [comment]
@robertmesserle - is this an AngularJS issue or an Angular Material issue.

**Comment by tuhoojabotti** [comment]
@ThomasBurleson There is no problem with Angular Material 0.10.0, after upgradign to 0.10.1-rc1 the problem occurs. I tried to debug it, but it is in some function that Angular generates on runtime, so it's a bit tricky to track down.

**Comment by nestorneto** [comment]
in 0.10.1 (or master) using angular 1.4.1+ the error occurs.

**Comment by robertmesserle** [comment]
@ThomasBurleson This was from a recent PR that was merged (it's on our end) - committing a fix now.

**Comment by epelc** [comment]
@robertmesserle Your fix breaks `mdSelectedItemChange` if it expects the selected item to be passed in as a parameter. This use to work but your fix essentially removed the argument.

You can work around this by binding something to `mdSelectedItem` and using that object instead of the argument to `mdSelectedItemChange` but I think it'd be good to mention this in the change log as it tripped me up. I had to step through a few commits related to auto complete to find it.

**Comment by robertmesserle** [comment]
@epelc This was intentional (for now) - the idea is that the user has access to these values through bindings; however, I am going to re-introduce that functionality today.

**Comment by robertmesserle** [comment]
@epelc Committing the change now, including unit-test

**Comment by epelc** [comment]
@robertmesserle Thanks I'll let you know if it works

**Comment by epelc** [comment]
@robertmesserle It works! Thanks for fixing this.
