### ISSUE TITLE
dp conversion pixels incorrect

### ISSUE THREAD

**Issue by britztopher** [angular/material#3655]
I came across an issue when dealing with the spacing between some md directives.  For example, the documentation for google material states that 'Cards' should have `16dp` before and after its content. [Google Material Cards](https://www.google.com/design/spec/components/cards.html#cards-content-blocks)  So when using `md-card` with `md-card-content` it compiles down to use `padding: 16px`, which isnt exactly correct since 16dp = 12px.  At least according to this online tool:  [Android Pixel Calculator](http://angrytools.com/android/pixelcalc/).  

This is a really minor issue as I see it, but thought that you should know.  I cant start changing these as I see them and submitting PRs if that is what we need to do to correct this.

**Comment by danwkennedy** [comment]
If you change the density, the pixel size changes. So 12 px = 16dp at a density of LDPI (120 ppi) but 16px = 16dp at a density of MDPI (160 ppi).

**Comment by iamfrank** [comment]
Is there a reason why Angular Material relies so heavily on pixel dimensions as opposed to relative units like em/rem/% ? 

Using relative units, you wouldn't have to deal with different screen densities either.

**Comment by cadilhac** [comment]
I had the same thinking about density. Right now, I design my app essentially for the desktop. When I create a modal dialog it becomes quickly very long because of the relatively low density. I was looking at how to change the density, hoping to find a sass variable but found nothing. I guess there is no option yet...

As a workaround I'm adding a scrollbar but I don't even know if this is in the spirit of Material Design...
