### ISSUE TITLE
<html> with overflow-y:scroll when <md-menu> is open

### ISSUE THREAD

**Issue by GustavoCostaW** [angular/material#3665]
Why the tag HTML receive the style attribute overflow-y:scroll when the md-menu is open? and add scroll in app? and how fix it? thx!

![screen shot 2015-07-09 at 19 19 01](https://cloud.githubusercontent.com/assets/874909/8608255/7560328a-266f-11e5-94a3-a9da5bf646ac.png)

**Comment by faustomorales** [comment]
Looks to be the same issue as #3667 and results from a function that appears to prevent unwanted scrolling of the page body when some elements are opened. Looking at the code, this issue appears to exist in some form for mdMenu, mdSelect, mdDialog, and mdAutocomplete as they all call the "disableScrollAround" function in mdUtil.

The fix is likely what @simongcc suggested which is to "scroll" to "auto" though I'm not sure if that meets the objective that originally called for the style to be applied in the first place.

**Comment by faustomorales** [comment]
No need to fear. Looks like this has already been fixed in 0.10.1-RC1 by @rschmukler in 7fe482cf9a632fcaade2d5827ac9bfd658eb90a3.

**Comment by GustavoCostaW** [comment]
@faustomorales, thx for replys!

**Comment by sinai-doron** [comment]
I am having this problem in 0.11.4
![screen shot 2015-10-15 at 8 41 04 pm](https://cloud.githubusercontent.com/assets/7936419/10522334/4f630d54-737d-11e5-9645-0dfd08b71959.png)

**Comment by dkgC** [comment]
The problem is still reproduced.

**Comment by lprusch** [comment]
Same thing here. Workaround for me was to manually set overflow-y in the html tag, so it doesnt get changed by the menu afterwards.

**Comment by nkoterba** [comment]
Getting this issue with MD 1.1.4 and Chrome Version 58.0.3029.110 (64-bit).  

What's surprising to me is why any component or control would **ever** explicitly set the entire HTML page to *force* scroll.  Why not `auto`?  

We have a SPA with extensive *flex* and no scrolling ever expected and when an `<md-select>` is opened anywhere on the page, an empty scrollbar appears on the page (see graphic, scrollbar on right):

![image](https://user-images.githubusercontent.com/2508944/27643636-9ae67dd6-5bef-11e7-92f4-1b4e614be5a8.png)

I'm confused as to how `overflow-y: scroll` is supposed to prevent "unwanted" scrolling when it explicitly shows a scrollbar even when no scrolling would indeed occur.

**Comment by nkoterba** [comment]
I think I figured out the issue in my case.  We have a component on our SPA, flexbox-based UI that scrolls content.

The MD code that determines whether to force scrolling or not checks `body.scrollHeight`.  I believe  the component that has its own scrolling is returning a value greater than `body.clientHeight`.

Since this issue is popping up now perhaps its a browser issue and Chrome is incorrectly calculating `body.scrollHeight`?

Here's the MD code:
```javascript
      function disableBodyScroll() {
        var documentElement = $document[0].documentElement;

        var prevDocumentStyle = documentElement.style.cssText || '';
        var prevBodyStyle = body.style.cssText || '';

        var viewportTop = $mdUtil.getViewportTop();
        var clientWidth = body.clientWidth;
        var hasVerticalScrollbar = body.scrollHeight > body.clientHeight + 1;

        if (hasVerticalScrollbar) {
          angular.element(body).css({
            position: 'fixed',
            width: '100%',
            top: -viewportTop + 'px'
          });
        }

        if (body.clientWidth < clientWidth) {
          body.style.overflow = 'hidden';
        }

        // This should be applied after the manipulation to the body, because
        // adding a scrollbar can potentially resize it, causing the measurement
        // to change.
        if (hasVerticalScrollbar) {
          documentElement.style.overflowY = 'scroll';
        }
```

You can see this line `var hasVerticalScrollbar = body.scrollHeight > body.clientHeight + 1;` determines whether to force scrolling or not.  In our app, when I check `body.scrollHeight` it's much greater than `body.clientHeight` but our UI never shows vertical or horizontal scrollbars.  We are however using a Grid/table that does scroll content and I'm guessing Chrome is considering that content when calculating `scrollHeight`.

As mentioned above, setting an explicit `overflow-y: auto` or `overflow-y: hidden` works in our case.

**Comment by nkoterba** [comment]
For posterity, it turns out we had a child item that was not correctly contained with a FLEX'd parent.

Thus, although we were not showing scrollbars in our UI, the content was extending past the `body.clientHeight`.  Fixing our flex issue caused the logic above to correctly calculate whether to show or hide scrollbar and things are good now without any other fixes/updates.

Leaving this here in case others may be having a similar issue and not realizing it.

**Comment by mminnie** [comment]
nkoterba, 
How did you set an explicit `overflow-y: auto`?

I'm not sure how I would identify a child item that was not correctly contained with a FLEX'd parent.  
**Can you provide a snippet of your code before and after the fix?**

**Comment by mminnie** [comment]
I thought the style='overflow-y: scroll' inserted by the code into the HTML tag would take precedence over the .css definitions, but it does not in my testing.  I set the css to have:
`html {overflow-y: auto}` 
and it works.  However.....the UI is really glitchy when this workaround is implemented.  I am assuming I have a FLEX child issue as you mentioned, so seeing how you found your issue would help immensely.
