### ISSUE TITLE
layout-fill: does not work in every situation without height: 100%

### ISSUE THREAD

**Issue by stefan-schweiger** [angular/material#3761]
You should really add `height: 100%` to `[layout-fill]` because else it won't work in every situation.

[CODEPEN](http://codepen.io/anon/pen/eNjOmQ)

**Chrome:**
![Chrome](http://i.imgur.com/cEQiN1D.png)

**IE:**
![IE](http://i.imgur.com/IwRUvdh.png)

**Comment by gkalpak** [comment]
I too believe that `layout-fill` will be better of with `height: 100%`.
See the conversation in #2954 for more context.

(Also not tat there is a special style for Firefox setting `height: inherit`, which is not as good as `height: 100%`, but still works most of the time, so the codepen works correctly on FF.)

--
But, quoting myself:

> [...] I think we first need to decide (and clearly document) what `layout-fill`'s purpose is.
   Is it supposed to fill its parent both **horizontally** and **vertically** ?
   Or is it supposed to fill its parent on the **main axis** (i.e. depending on `flex-direction`) ?
   <sub>Right now this is very unclear to me :confused:</sub>

(emphasis...mine)

**Comment by sscovil** [comment]
I've noticed this too, and would add that the CSS should look something like this:

```css
*[layout="column"][layout-fill] {
  height: 100%;
}

*[layout="row"][layout-fill],
*[layout=""][layout-fill] {
  width: 100%;
}
```

I haven't fully tested the row CSS, nor am I certain it is necessary, but the distinction between row and column should be considered.

**Comment by ThomasBurleson** [comment]
Fixed with lastest/HEAD commits:  http://codepen.io/ThomasBurleson/pen/PPzgxZ.

> To expedite future resolutions, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).
