### ISSUE TITLE
Include scss sheets in bower distribution

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#381]

**Comment by jgoux** [comment]
I hope this will be in the NPM distribution too. :)

**Comment by filipesilva** [comment]
I'd love this as well. My company is starting on a project that's using angular material, and having the scss files would help a lot.

**Comment by jonnysamps** [comment]
+1

**Comment by ThomasBurleson** [comment]
If you want the SCSS files, grab them from the [project source](https://github.com/angular/material) repository. The [project builds](https://github.com/angular/bower-material)** repository is used for deployment.

**Comment by nicbon** [comment]
It is my understanding that the source repository is meant to be used by whoever wants to develop angular-material and the deployment repository is for developers that use angular-material in their own projects.

If that's the case, I would argue that there are valid uses cases for exposing the SCSS in the project builds repository. In these cases the developer doesn't want to mess with the original angular-material css but rather use the SCSS as a library to build his own classes. For instance I might want to access the SCSS variables, or use the handy mixins to build more *-sm *-gt classes.

I personally see the SCSS as being integral part of the library exposed to the developers rather than purely part of the library sources.  

PS
I'm sorry to have to comment on a closed issue but this seems to me the most relevant place to leave this comment.

**Comment by johannesjo** [comment]
For those interested I extracted the styles and put them into their own repository:
https://github.com/johannesjo/angular-material-sass-files
