### ISSUE TITLE
md-toolbar and angular-scroll not work

### ISSUE THREAD

**Issue by GuilhermeMaia91** [angular/material#3839]
Hi, i have a problem with angular-scroll (https://github.com/oblador/angular-scroll) and md-toolbar, the effect of scrolling does not work with my md -toolbar when you click on the links, here's Plunker: http://plnkr.co/edit/eJZZEF?p=preview with the source code. Can someone help me?

**Comment by mckenzielong** [comment]
This might have been a good candidate for a question on the [forums](https://groups.google.com/forum/#!forum/ngmaterial).

You have set up the scrolling to take place on your $document element.  In this case, we do not scroll the document node.  Since you are using md-content to hold your scrollable content, you will have to use that element as your target for scrolling.

[Updated version of your plunk here](http://plnkr.co/edit/VmojWhmTChcRg5z4ok4S?p=preview)

**Comment by GuilhermeMaia91** [comment]
Hi @mckenzielong your modification in my plunker example worked perfectly. thank very much!!!
