### ISSUE TITLE
ng-focus on md-autocomplete

### ISSUE THREAD

**Issue by YorffoeG** [angular/material#3906]
When focus set to md-autocomplete, ng-focus function not call.

**Comment by mrichar1** [comment]
Same issue applies to ng-blur as well.

**Comment by tolemac** [comment]
+1 
Perhaps the `ng-onblur` on `md-autocomplete` have to be $eval on `ng-onblur` of internal input.
Actually the internal input have `ng-blur="$mdAutocompleteCtrl.blur()"`

Te same for ng-focus.

**Comment by jelbourn** [comment]
Bumping this to 0.12 since more users have been asking for it and it should be relatively straightforward to implement.

**Comment by RavenHursT** [comment]
+1 

A simple modification to the autocompleteDirective and autocomepleteController to expose a directive attribute, something like ```md-focus`` and ```md-blur``` would allow consumer controllers to operate on those events.  as @tolemac pointed out, the internal input already has ng-focus and ng-blur implemented.  Hooking in attribute expressions using $parse should be quite simple to implement.

I have a standing PR in https://github.com/angular-ui/ui-select that does something similar: https://github.com/angular-ui/ui-select/pull/1153

**Comment by julian-iFactory** [comment]
+1 for ```md-blur``` on ```md-autocomplete```

**Comment by DeGuitard** [comment]
+1

**Comment by Patzick** [comment]
+1

**Comment by jsenecal** [comment]
+1!

**Comment by hedder** [comment]
+1

**Comment by friedolinfoerder** [comment]
+1

**Comment by SHkreddy** [comment]
+1

**Comment by abeniwal** [comment]
+1

**Comment by beny78** [comment]
+1

**Comment by fdomig** [comment]
+1

**Comment by KarmaCop213** [comment]
+1

What I did to still have an "onBlur" event fired:

Created a directive called "autocompleteBlur", the $timeout is important, otherwise the input textbox isn't rendered at that time.

allocateApp.directive('autocompleteBlur', function($timeout){
    return{
        link: function(scope, element, attrs){
            $timeout(clearInputBoxOnBlur, 0);

            function clearInputBoxOnBlur(){
                element.find("#autocomplete-input-id").bind("blur", function(){
                    angular.element(this).val('');
                });
            }
        }
    }
});

Then on the md-autocomplete element, add the newly created directive, and give an id to your input textbox (mine is called "autocomplete-input-id"):

<md-autocomplete
    (...)
    autocomplete-blur
    md-input-id="autocomplete-input-id">
    (...)
</md-autocomplete>

**Comment by cleever** [comment]
+1

**Comment by shichan** [comment]
+1

**Comment by valtersboze** [comment]
+1

**Comment by uditalias** [comment]
+1

**Comment by mwiley63** [comment]
+1

**Comment by george-i** [comment]
+1

**Comment by DomenicD** [comment]
+1

**Comment by wizzzet** [comment]
+1

**Comment by bluebirdtech** [comment]
+1

**Comment by madeFromCode** [comment]
+1

**Comment by SHkreddy** [comment]
any update on this ticket, or new work arounds?

**Comment by saffabook** [comment]
+1

**Comment by RavenHursT** [comment]
LOL... I'm so glad that I've moved on to React: http://www.material-ui.com/#/components/app-bar

**Comment by bsandrow** [comment]
I'm not sure why this is marked as an edge-case. Consider the use-case where you want to allow the user to enter *any* input into a text field, but allow them some pre-defined options via autocomplete. Right now there is a strict separation between `searchText` and `modelValue`.

If `searchText === modelValue` *and* there is an exact match in the matches list then you'll have a hard time. The matches list will *not* display because `$mdAutocompleteCtrl.hidden` will be `true`. It isn't difficult to create a scenario. Consider that the user types something like `3m` into the input. The matches are: `3m`, `3M`, `3M ESPE`. The `searchText` is `3m`, so it matches something in the list. `$mdAutocompleteCtrl` thinks that it's time to pack everything up, so it renders the list of matches, and hides them from view.

(I'm specifically referring to [`shouldHide`](https://github.com/angular/material/blob/v1.0.5/src/components/autocomplete/js/autocompleteController.js#L516-L521) calling [`hasSelection`](https://github.com/angular/material/blob/v1.0.5/src/components/autocomplete/js/autocompleteController.js#L543-L545) here.)

Now consider that you want the user to be able to enter `3m2m` and save it. My first thought to work around this would be to use `ngBlur` to copy `searchText` to `modelView` when the user explicitly leaves the autocomplete. Without `ngBlur` though this will not work.

Now I'm sure that "using it as a work around" is your target for features, but by giving users a broader set of tools to work with they can at least work around issues that are not entirely ironed out yet rather than ending up waiting for mainline to fix the issues, or maintaining their own fork (neither of which are entirely palatable options).

**Comment by DeGuitard** [comment]
It can be even more common. Imagine you want to show something when the user is editing the auto-complete field, and hide it once he's done. `ngBlur` would be really handy.

**Comment by fernandogomesdf** [comment]
+1 for ng-focus

**Comment by FBurner** [comment]
+2

**Comment by robguy21** [comment]
+1

**Comment by donwitti** [comment]
+1

**Comment by simonepri** [comment]
I've improved a bit the workaround provided by @KarmaCop213:


    (function() {
      'use strict';

      angular
      .module('app')
      .directive('autocompleteBlur', function($timeout) {
        var directive = {
          restrict: 'A',
          link: function($scope, $element, $attributes){
            $timeout(function(){
            console.log($element[0].querySelector("input.md-input"));
              angular.element($element[0].querySelector("input.md-input")).bind("blur", function(){
                $scope.$eval($attributes.mdBlur);
              });
            },0);
          }
        };

        return directive;
      });

    })();

Just change yourCallback with whatever you want.


    <md-autocomplete
       (...)
       md-blur="yourCallback()">
       (...)
    </md-autocomplete>

**Comment by alois-wever** [comment]
+1

**Comment by jojogeyer** [comment]
+1

**Comment by monmon29** [comment]
hey.. All of you commuting +1.. I cannot understand how you solve this issue. :(

**Comment by RizwanAslam** [comment]
+1

**Comment by Aniltilanthe** [comment]
+100

**Comment by dmeh89** [comment]
+1

**Comment by SHkreddy** [comment]
Can we get a dev to actually give us an update on this issue? The ticket has been open for 9 months, there hasn't been one comment by a dev other then to lower the priority or reschedule looking at this issue.  Every month there is at least one more +1, and who knows how many people just read this thread and give up because of the poor communication from the devs.  

All I want to know is are you ACTIVELY  working on this issue or is this ticket just going to remain on the sidelines forever?

**Comment by phoenixjun** [comment]
+1

**Comment by KalpanaAr** [comment]
+1

**Comment by jpike88** [comment]
A million +1s, and the ticket gets put in ... deprecated? Without a reason why?

**Comment by tim93422** [comment]
It would awful nice to have ng-focus and ng-blur work. Why is this deprecated? Do you need a pull request?

**Comment by DevVersion** [comment]
@tim93422 It's not deprecated anymore. 

Pull Requests are welcome as always, but please discuss the possible solutions first.

**Comment by tim93422** [comment]
I'm not really in the position propose a solution yet. If you have a fruitful avenue for me to explore, please let me know. If not, I'll put some time into understanding the issue more fully

**Comment by KalpanaAr** [comment]
+1

**Comment by sachst1000** [comment]
+1

**Comment by gunsline2** [comment]
+1

**Comment by Dunos** [comment]
+1

**Comment by feastofvermin** [comment]
+1

**Comment by beny78** [comment]
Here is my workaround to override blur function of the autocomplete controller
```
app.directive('mdBlur', [ "$mdUtil", function($mdUtil) {
    return {
        require: "^mdAutocomplete",
        link: function($scope, $element, $attributes, $mdAutocompleteCtrl) {
            $timeout(function() {
                var input = $element.find("input");
                var element =  $element[0];
                var nativeBlur = $mdAutocompleteCtrl.blur;
                $mdAutocompleteCtrl.blur = function() {
                    nativeBlur.call($mdAutocompleteCtrl);
                    $mdUtil.nextTick(function () {
                        $scope.$eval($attributes.mdBlur, {"$mdAutocomplete": $mdAutocompleteCtrl });
                    });
                };
            });
        }
    };
} ]);
```

**Comment by ibo549** [comment]
+1

**Comment by rguruprakash** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by naveenboda1993** [comment]
:+1:  ng-focus on md-autocomplete

**Comment by sergiy-talashko** [comment]
@all **ngBlur** and **ngFocus** is start working from 1.1.1 version

**Comment by mikila85** [comment]
+1
