### ISSUE TITLE
Documentation samples for Menu and Checkbox layout issues in IE11

### ISSUE THREAD

**Issue by stevenmiles** [angular/material#3926]
Layout issues with Checkbox examples

![image](https://cloud.githubusercontent.com/assets/623813/8928228/d8d204d4-3514-11e5-81b0-b3fe6c778c83.png)

Layout issues with Menu examples

![image](https://cloud.githubusercontent.com/assets/623813/8928175/82406868-3514-11e5-9490-0c9149f7708b.png)

**Comment by Londovir** [comment]
Comparing how the Menu example looks under 0.10 MD under IE11 (when it looks basically fine) with the more recent one, it appears to be related to the fact that they used to use a `layout-fill` attribute on the container DIV which hosts the 3 different samples which are all overlapped. Now that attribute has been removed from the demo page markup, and under IE11 that causes the items to all collapse together because of the missing `width: 100%` which used to be granted by virtue of the `layout-fill`.

This appears to be an IE11 specific flex model issue, as Chrome/Firefox appear to have no problem with growing the DIV to fit the parent width without being specifically told to do so. Under IE11, if you toss either the `width:100%` style, or even a `align-self:stretch` style on the DIV, all works as planned.

Not sure about the checkbox issue, but likely the same sort of problem.

**Comment by ThomasBurleson** [comment]
@stevenmiles Do you see these same issues in IE using the latest in master (v0.11.0-rc2)?

**Comment by stevenmiles** [comment]
Yes, still happens.

![image](https://cloud.githubusercontent.com/assets/623813/9678543/46b2cc4a-52de-11e5-824c-49373b245bc1.png)

Checkbox is also the same as before.

**Comment by ThomasBurleson** [comment]
@stevenmiles - do you have some CodePens for us to validate and test with?

**Comment by langdonx** [comment]
Probably this: https://github.com/philipwalton/flexbugs#2-column-flex-items-set-to-align-itemscenter-overflow-their-container

**Comment by topherfangio** [comment]
Closed by #5089.
