### ISSUE TITLE
How to make an <md-select> view switcher with ui-router

### ISSUE THREAD

**Issue by kingIZZZY** [angular/material#3984]
What is the best way to bind an &lt;md-select&gt; with ui-router routes, so that they update each other correctly; ui-router initializes the md-select to appropriate option upon page load, and selecting another option changes ui-router state?

Here is a working example without Angular Material http://plnkr.co/edit/b3pOQKRmuJRS7RyLbDP8 (courtesy of ctanga)
Here is a fork of the above appropriated for Angular Material, not working yet http://plnkr.co/edit/uwYRhgunssmGkdFkfG36 as you can see the initial landing on a url/view fails to initialize the md-select.

**Comment by epelc** [comment]
@kingIZZZY You are setting your model to the state object while your option values use the name. Also you should using `ng-value="something"` instead of `value="{{something}}`.

Here is a working version http://plnkr.co/edit/UqSwd3t1gRPfQdM5AMt6?p=preview

Note I'm not quite sure while there's still a blank option it may be because of how you obtain the states list. As ui-router may have an empty root state or something odd.

**Comment by kingIZZZY** [comment]
Ah perfect, that seems to solve it. Thanks!
