### ISSUE TITLE
md-fab-top-right md-bottom-right: Position not fixed with md-content within md-tabs

### ISSUE THREAD

**Issue by dg1202** [angular/material#4035]
The classes used to fix fabs buttons to the top or bottom becomes broken inside a `md-tab` containing the `md-content` directive  
  
![screen shot 2015-08-05 at 2 10 01 pm](https://cloud.githubusercontent.com/assets/2365581/9095241/c950b1d2-3b7b-11e5-9f51-804179964c88.png)
  
http://codepen.io/dgavigan/pen/KpJXNw

**Comment by topherfangio** [comment]
I think I understand the problem, but I have a quick question: what is your expectation of where the FAB will appear?

Do you expect it to:

1. appear at the bottom right of the content after scrolling it into view
1. or appear outside of the tabs at the bottom right of the screen

**Comment by dg1202** [comment]
I expect it to stay in view on the bottom right within each tab. 

My example use case is that I have scrolling content on multiple tabs, and trying to use a fab in the lower right for actions specific to current tab. 


![screen shot 2015-08-05 at 2 40 29 pm](https://cloud.githubusercontent.com/assets/2365581/9095997/1a4b368a-3b80-11e5-9c30-baf5293d4e90.png)
![screen shot 2015-08-05 at 2 40 34 pm](https://cloud.githubusercontent.com/assets/2365581/9095996/1a4b1204-3b80-11e5-878a-189a0375c859.png)

**Comment by topherfangio** [comment]
Based on the [FAB style recommendations](http://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-behavior) (*check the "For tabbed screens..." paragraph under Behavior*), I would recommend an approach similar to this: http://codepen.io/topherfangio/pen/vObeQb

This way, each FAB is shown/hidden based on what tab is selected, but they aren't inside the tabs. This is important because it means that they won't "slide" with the tab's animation.

**Comment by dg1202** [comment]
@topherfangio you da man! thanks for the help. your fab wizardy strikes again.

**Comment by topherfangio** [comment]
@dg1202 Glad to help! ;-)
