### ISSUE TITLE
md-contact-chips attribute filter-selected is not implemented

### ISSUE THREAD

**Issue by metamatt** [angular/material#4131]
https://material.angularjs.org/latest/#/api/material.components.chips/directive/mdContactChips documents a `filter-selected` attribute which doesn't work because the directive doesn't actually look at the attribute. (It does have code to honor `this.filterSelected` on the controller, but it never propagates the attribute to the controller property.)

It's missing this, basically:

```
--- a/web/jspm_packages/github/angular/bower-material@0.10.1/modules/js/chips/chips.js
+++ b/web/jspm_packages/github/angular/bower-material@0.10.1/modules/js/chips/chips.js
@@ -926,6 +926,7 @@ MdContactChipsCtrl.prototype.filterSelectedContacts = function(contact) {
       compile: compile,
       scope: {
         contactQuery: '&mdContacts',
+        filterSelected: '@',
         placeholder: '@',
         secondaryPlaceholder: '@',
         contactName: '@mdContactName',
```

**Comment by topherfangio** [comment]
We will definitely take a look and get this fixed. In the meantime this would make a pretty good/easy PR if you're interested in contributing :-)

**Comment by danwkennedy** [comment]
Looks like this commit to the contact chips controller turned filtering on by default (removing the filter-selected option on the directive):
https://github.com/angular/material/commit/48c7c448fc100540af8cd2b27bd710825be0346e#diff-6681e88f57d33d8aa66a99c2544f2802R22

However, the following commit to the controller reverted the first commit but didn't change the directive:
https://github.com/angular/material/commit/786b0ed3652b7460c2c802efa1aa79972bd96f5d#diff-6681e88f57d33d8aa66a99c2544f2802R22

It's unclear what the intent is here since this comment is currently in the directive:
https://github.com/angular/material/blob/master/src/components/chips/js/contactChipsDirective.js#L33

I'm willing to submit a PR to fix this, I just need to know which way to implement it. Either:
1. The option exists and it's false by default
2. The option doesn't exist and it's on by default

Those are the two choices I've found reading the code. You could also have the option and turn it on if it's null or undefined which works best for consuming the API but is kind of odd to me since I always consider an optionally boolean to be false ¯\_(ツ)_/¯

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (413/400 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:56454 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZY-001Z4S-KJ
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:06 +0200
Date: Thu, 28 Apr 2016 13:29:22 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875362;
	bh=ROzL5LzT9RsaFcLrmDNjObVkocNt9cPzFUZGDjvvHiw=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=em5eJ/pykQJI2dD3w3dKe0SjIZ3+ukhEyKZNqh9qSYYlOqsaYSbdLlIDLL8ygvsAp
	 5/MHQj9ugGwbZlmQv0q2Fn8bOEpepFMQUJz8IxybN9QNiygRzG1f13vQqSqKxdIkrC
	 6hHN3Z8W3he0Q3U3+AfIzRmZWbNOrHMwTUkO4TxA=
