### ISSUE TITLE
Change tabs display on small screen

### ISSUE THREAD

**Issue by no-more** [angular/material#4141]
Hi,

This is not a bug, but I think the way tabs are working currently it's not really good for small screen. The display of tabs should switch to a menu like display. I mean display the current tab name full witdh, and when clicked on, display a list of other available tabs. This way you can easily have an overview of all tabs, and you can switch easy from the first one to the last one for example.
I know it's possible to handle this by my own, and probably not too hard to do it, but perhaps this should be the default behavior as it's really not easy to use on mobile as it's currently implemented.

Thanks.

**Comment by matthiasg** [comment]
Nice option, but i would rather have it behave like the tabs in the google play store (sections) meaning swiping live. Right now there are swipe actions, but they are not intuitive since they only start after the swipe is finished .. it should start swiping right away just like a scrollable container... that would be much faster.

**Comment by matthiasg** [comment]
@thomasburleson can i assume that optimizing for mobile was not considered relevant enough or is there another reason ?

**Comment by matthiasg** [comment]
I see .. Its  spring cleaning ;)  good idea
