### ISSUE TITLE
Input field loses focus in safari while coping text from other tabs into input field.

### ISSUE THREAD

**Issue by ashishghone01** [angular/material#4203]
open input in demos in material angular site > click on some input field > switch the tab in browser > copy some text > paste in previously focused field 

label was expected to transform and move up, but it does not. 
![screen shot 2015-08-17 at 11 33 45 pm](https://cloud.githubusercontent.com/assets/11266090/9312157/92ee0f6a-4538-11e5-9d1d-16114e669f06.png)

**Comment by topherfangio** [comment]
Need to review and see if this is still an issue.

**Comment by topherfangio** [comment]
This appears to be fixed on master.

If you are still experiencing this after upgrading, please comment and I will reopen.

**Comment by satyaki1** [comment]
Hi @topherfangio - 
This issue is still reproducible , following are the steps which you need to follow to reproduce this issue -
Open https://material.angularjs.org/latest/demo/input 
1. Highlight any field (Preferably the "required" field one). 
2. Now Go to other tab on browser e.g. Go to Google Maps which opened on other tab on safari browser. 
3. Copy something from that tab 
4. Come back to Meterial site. 
5. Paste in highlighted field.

**Comment by topherfangio** [comment]
@satyaki1 Thanks, I didn't read closely enough and I was switching browsers (i.e. Chrome to Safari).

I can now reproduce and will investigate.
