### ISSUE TITLE
mdSidenav: stops working after a state transition

### ISSUE THREAD

**Issue by swami108** [angular/material#4209]
I have a left and right sidenav--in an ionic project. The left one works fine, but the right one opens up only the first time. After a state transition (to the same state, different id), the right one does not open anymore. Once I refresh the page, it then opens.   

```
<md-button ng-click="openSideMenu()">Menu</md-button> 

$scope.openSideMenu = function() {
      $mdSidenav('side').toggle();
};

<md-sidenav md-component-id="side" class="md-sidenav-right">
   ...
</md-sidenav>

$state.go('home', { 'id': id }); //after this, sidenav stops working.
```

I must mention that the left menu (which works fine) is in the index.html view, outside the ion-nav-view tags, whereas the right menu (which is problematic) is in a nested view, so within ion-nav-view.

Wondering if it has anything to do with this...

**Comment by ThomasBurleson** [comment]
Angular Material and Ionic used  together have known issues (incompatibilities) regarding touch and gestures (and possibly animations). We are unable to support any Ionic issues before the 1.0 release.

**Comment by MadMub** [comment]
Can confirm sidenav animation is broken with:
angular-material 0.10.1
angular 1.4.x
angular-animate 1.4.x
angular-ui-router 0.2.15
when inside a ui-view

Animation working when angular/angular-animate is rolled back to 1.3.x.
I would provide a plunk but plnkr doesn't seem to play nice with ui-router. I can host an example on my personal site at another time.

To be clear, this is NOT an ionic project, I just commented here since I suspect the issues are related. When I have a live example I can create a separate issue.

**Comment by bonatoc** [comment]
Same problem here.

    $mdSidenav('OrderOpenTicketsSidenav').toggle();

Only works before route change (ionic ui-router).
When changing route (same route, different id), it does not work, but $mdSidenav does not throw an error.

Also, when going back to the first initlal route with the working $mdSidenav, $mdSidenav is already open, even if it was closed before leaving the initial route.

Other than that, I have an md-sidenav which works as expected, which is placed outside ionic <ion-nav-view> tags.

So it could be either ui-router related, or ionic. Possibly a problem with $templateCache, as Ionic tries to cache templates during app's bootstrapping?

**Comment by swami108** [comment]
Changing $state.go to $window.location.assign fixes the issue.

**Comment by bradrich** [comment]
I have another interesting issue that I feel matches this.

If using $state.go('state-name', null, { reload: true }), concentrating on the reload part of that ui-router call for this issue, the subsequent reload will cause a second mdSidenav to appear if the first is using md-is-locked-open. You can disable the potential $animate for the mdSidenav element and it fixes the secondary mdSidenav from appearing, however, the animation for opening the mdSidenav on smaller screens is eliminated. Damned if you do...

I am using angular-material 1.0.6.

**Comment by bonatoc** [comment]
By the way, for me the problem is fixed since I started to use the code provided in the demo.

@bradrich — You could try a CSS overwrite empeaching the sidenav to open based on a conditional coming from $scope, using ng-class and !important (eww). 
Isn't it already triggered like so, with transform:translateX + transitions?

**Comment by bradrich** [comment]
@bonatoc - I am guessing that I had been staring at my screen for too long yesterday because this morning I came up with a small solution that does not by any means fix the issue, it just puts a bandage over it:

Add this to your CSS to keep the duplicated mdSidenav issue from occurring (making sure to replace <md-sidenav-class> with whatever your side navigation class is):

```
md-sidenav.<md-sidenav-class>:not(:first-of-type) {
    display: none !important;
}
```

To answer your questions about mdSidenav's transition CSS properties, you are correct. But, when you transition between states, and in this case, reloading one, ngAnimate flies in and tries to be Houdini, fading things out, etc. It causes messes sometimes, IMHO.

**Comment by bonatoc** [comment]
@bradrich 

I personally prefer to manage all sidenav on a "root" app level, listening to $state and $state.params to trigger them. I keep them outside the routes views, and use shared services for whatever data the sidenavs need to be aware of when the app is in a particular state/route.
