### ISSUE TITLE
md-button with tooltip displays focus style on window refocus

### ISSUE THREAD

**Issue by mhchen** [angular/material#4245]
Similar to #3035

Steps to reproduce:
1. Click on a button, observe that the focus style (darker color) is present.
2. Mouse off the button, observe that the focus style fades.
3. Tab to another window, and tab back.

Expected: button should not have focus style
Actual: button regains its focus style

**Comment by mhchen** [comment]
Sorry, to clarify, this only happens when used with the tooltip

**Comment by akanimh** [comment]
Also witnessing this, here's a gif:
![focused-event-bug](https://cloud.githubusercontent.com/assets/3221476/9374037/d1c09cbc-46a5-11e5-9d36-30983cb06049.gif)

**Comment by mhchen** [comment]
Blocked by #4249 as the focus state is always shown

**Comment by akanimh** [comment]
Also seeing this with any buttons, no tooltip required:

![focused-event-bug-button](https://cloud.githubusercontent.com/assets/3221476/9374152/8c464ca2-46a7-11e5-858b-7af11038bc23.gif)

**Comment by topherfangio** [comment]
So, is the underlying issue that the button does not lose focus once clicked?

I think the code might assume that some other element will gain the focus after whatever action the click triggers fires, but since we don't fire any real action on the demo site, the button never loses focus.

Can you describe how exactly this is affecting your live apps (or maybe provide a link/demo) so that we can make sure to prepare a good fix?

**Comment by topherfangio** [comment]
I believe this is related to #4249.

**Comment by SanderElias** [comment]
This seems to be a duplicate for #4249, I'm closing this one, so we can concentrate this on 1 place
