### ISSUE TITLE
Add md-icon in front of the md-chips input

### ISSUE THREAD

**Issue by maelfrize** [angular/material#4260]
Right now, it's not possible to add a md-icon in front of the the md-chips input. At least, I haven't figured out how to do it.

Would be good to add this feature so that it is more consistent with the regular inputs.

![input_icons](https://cloud.githubusercontent.com/assets/11228926/9385975/9aafa222-4759-11e5-8f56-d891843c8015.png)

https://material.angularjs.org/latest/#/demo/material.components.input

**Comment by topherfangio** [comment]
This should be a semi-easy fix; I spent about 5 minutes and got close to a solution. Probably needs < 1 hour of work.

**Comment by maelfrize** [comment]
Glad to hear that. Looking forward to it!

**Comment by bluebirdtech** [comment]
+1

**Comment by ibnYusrat** [comment]
My solution for this problem is to wrap md-icon and md-chips in a div, set layout of the div to row and add flex to md-chips tag. You will probably want to add some magin to the md-icon to make it look like the rest of the input fields. 

<div **layout="row"**>
<md-icon style="color:black;margin:14px 3px 3px 3px;">category</md-icon>
<md-chips flex ng-model="selectedCategories" ng-attr-id="test" md-autocomplete-snap md-transform-chip="transformChip($chip)" md-require-match="false">
              <md-autocomplete md-selected-item="selectedCatItem" md-search-text="catSuggestions.searchText" md-items="item in catSuggestions.querySearch(catSuggestions.searchText)" md-item-text="item.name" placeholder="Artwork Categories..">
              <span md-highlight-text="catSuggestions.searchText">{{item}}</span>
              </md-autocomplete>
              <md-chip-template>
                <span>
                  <md-icon>label</md-icon>
                  <strong>{{$chip}}</strong>
                </span>
              </md-chip-template>
            </md-chips>
</div>
