### ISSUE TITLE
Animation Circle draw in md-checkbox after navigating back from other browser tab

### ISSUE THREAD

**Issue by climberwoodi** [angular/material#4274]
1. click on check box
2. click another tab of the browser (chrome or firefox tested)
3. navigate back to the tab with the check box

![temp](https://cloud.githubusercontent.com/assets/7993771/9411780/5c3c187a-4828-11e5-8411-859e73a5e940.png)

The circle from the animation is still draw. Can be reproduced on the official home page.

**Comment by ngraef** [comment]
That's just the browser restoring focus to the correct element on the page. Because there's no accompanying mouse event, [the checkbox applies its focus state styling](https://github.com/angular/material/blob/master/src/components/checkbox/checkbox.js#L110).


You could flip the logic and only apply the focus state if the keyboard is being used (rather than disabling it for the mouse), though I'm not sure if that goes against accessibility best practices. Something like this might fix it:
``` javascript
scope.keyboardActive = false;
element.on('click', listener)
    .on('keypress', function(ev) {
        scope.keyboardActive = true;
        $timeout(function(){
            scope.keyboardActive = false;
        }, 100);
        keypressHandler(ev);
    })
    .on('focus', function() {
        if(scope.keyboardActive) { element.addClass('md-focused'); }
    })
    .on('blur', function() { element.removeClass('md-focused'); });
```

**Comment by marcysutton** [comment]
As long as it works reliably for the keyboard and doesn't show the focus ring, it could be an improvement! The fix for the staying-focused-after-mouse-click is evolving, since it highlights a hole in support for custom focus styling. Here's a read on how we're hoping to address this in browsers in the future: http://radar.oreilly.com/2015/08/proposing-css-input-modailty.html
Feedback on the [Discourse thread](http://discourse.wicg.io/t/exposing-a-users-input-modality/1067) would be appreciated!

**Comment by ngraef** [comment]
@marcysutton Interesting read! Thanks for sharing.
