### ISSUE TITLE
md-virtual-repeat does not work without predefined height

### ISSUE THREAD

**Issue by uriva** [angular/material#4314]
codepen: http://codepen.io/uriva/pen/doxdVP

**Comment by Pusnow** [comment]
I think md-virtual-repeat-container should have fixed height

**Comment by uriva** [comment]
Yup. That was the issue. Perhaps a doc clarification on that point?

**Comment by Pusnow** [comment]
I referred to official doc's sample codes

**Comment by robertbaker** [comment]
+1 Would be nice to figure out a way to allow flexable heights.

**Comment by kseamon** [comment]
It's on my to-do list. It's tricky because any solution comes with performance trade-offs.

**Comment by alias1** [comment]
+1 This tripped me up for a while, a note on the docs would be cool.

**Comment by colinskow** [comment]
Here's my workaround in the mean time:

```js
this.getListHeight = function() {
  return {height: '' + ($window.innerHeight - 72) + 'px'};
};
$window.addEventListener('resize', onResize);
function onResize() {
  $scope.$digest();
}
$scope.$on('$destroy', function() {
  $window.removeEventListener('resize', onResize);
});
```

Then in the HTML

```html
<md-virtual-repeat-container id="vertical-container" ng-style="ctrl.getListHeight()">
...
</md-virtual-repeat-container>
```

**Comment by Madd0g** [comment]
@colinskow - Thanks, it's close to working, it works for me on refresh, but not on regular state-changes
(Note that I'm measuring the parent node of the virtual list, not the body like in your example).

A huge +1 for making virtual-repeat flexable.

**Comment by colinskow** [comment]
@Madd0g - I actually refactored it a little bit and it seems to work better. At least on Safari and Chrome it always appears to be the right size.

```js
this.listStyle = {
      height: ($window.innerHeight - 112) + 'px'
    };
    $window.addEventListener('resize', onResize);
    function onResize() {
      self.listStyle.height = ($window.innerHeight - 112) + 'px';
      if(!$scope.$root.$$phase) $scope.$digest();
    }
```

```html
<md-virtual-repeat-container id="vertical-container" ng-style="ctrl.listStyle">
...
</md-virtual-repeat-container>
```

**Comment by Madd0g** [comment]
@colinskow - that does work better, but it seems like the internal `md-list` doesn't get resized to the necessary height, I don't even understand what causes it to be smaller in size, I've combed through the styles tab and don't see anything that can cause it :(

**Comment by colinskow** [comment]
@Madd0g if I open and close the Javascript console or developer tools, it will thereafter render an incorrect height. As long as I don't do that, my implementation seems to render correctly.

Do you have a CodePen to demonstrate your issue?

**Comment by colinskow** [comment]
Here's my CSS that is working perfectly. Note that the repeat items all must be the EXACT specified height without any padding or overflow, otherwise scrolling will be really glitchy.

```css
#vertical-container {
    min-height: 300px;
    width: 100%;
}

.repeated-item {
    border-bottom: 1px dotted #757575;
    box-sizing: border-box;
    height: 50px;
    overflow: hidden;
    margin-right: 16px;
}
```

The `min-height` on the container seems to be important. This is later overridden by the actual height from your script. Also, `overflow: hidden` on the repeat item keeps any items from accidentally getting taller than 50px.

**Comment by Madd0g** [comment]
@colinskow - it's definitely something about my HTML that's causing it (and weirdly it only breaks on ui-router state change, not a page refresh), but the directive I posted solves my problem perfectly, so I'm not worried, it will be enough for me until the virtual repeater is officially flexable.

Thanks for your help

**Comment by Voltasalt** [comment]
bump, fix soon?

**Comment by guiporto** [comment]
+1

**Comment by SpenceDiNicolantonio** [comment]
+1

**Comment by csvan** [comment]
+1

**Comment by jamalx31** [comment]
+1

**Comment by kseamon** [comment]
As of 1.0-rc4, you can $broadcast $md-resize to induce the repeater to recompute its height.

**Comment by jamalx31** [comment]
@kseamon could you explain how to do that ?

**Comment by kseamon** [comment]
On a scope that contains the repeater, call $scope.$broadcast('$md-resize') and the repeater container will attempt to remeasure its height/width. If it started out with the incorrect size, this will hopefully fix it. You might need to put your call into a $timeout. Sorry that this is so awkward, but I haven't yet come up with a great solution to this.

**Comment by nkoterba** [comment]
**First a disclaimer...we are woefully behind in updating our MD version.  We have everything working and no issues so at the moment we are still using v0.11.4.  Perhaps this issue may be fixed or better 'handled' in new versions as @kseamon suggests calling `$scope.$broadcast('$md-resize')`.**

Thanks @Madd0g for the directive idea and fix.  Our situation is similar.  We have `md-virtual-repeat-container` in a "collapsible panel" that is in an accordion control.  We allow multiple accordion panels to be "open" at the same time, which dynamically adjusts the size of each panel.  As user's collapse/expand each panel, thanks to flex the collapsible item's content fills the height.  

However, as noted in this issue, even if the html elements containing `md-virtual-repeat-container` are correctly "resized" and even `md-virtual-repeat-container` itself, the internal logic to fetch and "redraw" more items is not triggered.

Here is some depiction of what's happening:
![image](https://cloud.githubusercontent.com/assets/2508944/13545563/77a5c2f2-e25e-11e5-836e-80ca30dd19b8.png)

As you can see above, we've "expanded" a collapsible panel in our accordion and while the container and scroll bar are all correctly "flexed" to the new dynamic height, the `md-virtual-repeat-container`'s `md-virtual-repeat-offsetter` does not trigger "fetching" and "drawing" items to fill up the space.  As opposed to calling `setSize_` in @Madd0g suggestion above, since our components are correctly flexing, we just need to trigger a refresh and re-fetch of the items.  Here is our solution:
```javascript
	var directive = {
		restrict: 'A',
		require: '^mdVirtualRepeatContainer',
		link: link
	};

	return directive;

	///////////////////////////

	function link(scope, element, attributes, mdVirtualRepeatContainer)
	{
		// Watch the offsetHeight (not great...triggers browser reflow...but oh well)
		// When it changes, call the md-virtual-repeat-container controller's internal
		// updateSize() (could also call setSize_ with the value but still need to trigger an update
		scope.$watch(function () {
			return element[0].parentNode.offsetHeight;
		}, function(value){
			//mdVirtualRepeatContainer.setSize_(value); // Doesn't seem to trigger refetching items
			mdVirtualRepeatContainer.updateSize();
		});
	}

	///////////////////////////

	// Put any additional methods here
```

However, as @kseamon points out, watching `offsetHeight` could cause performance issues due to browser layout reflow (https://gist.github.com/paulirish/5d52fb081b3570c81e3a).  Performance will obviously depend on overall app, how many times this watch expression gets called, etc.

In our case, we modified our directive above since we actually have a user-event that triggers the `md-virtual-repeat-container` to be resized...so instead of creating a watch that triggers layout reflow we can just call `updateSize` whenever we know the user has expanded our accordion panel.

One suggestion on how to potentially handle this without any watches (especially on offsetHeight), would be to create a virtual repeat service, `$mdVirtualService` similar to other services in MD.  This service would have an `updateSize` or other similar method that users could call to trigger internal updating when they detect that things should be refreshed/redrawn/fetched.

**Comment by warent** [comment]
Hi,

I actually came up with a fully functioning solution for virtual repeating dynamic height items without predefined values. I'm going to be upfront in saying that I'm not experienced in working on open-source projects or the processes therein (I do have some team dev experience in the company I work for), but if someone could get in touch with me I would love to work together in sharing and implementing the solution, or even rebuilding it to specifications so we can possibly add this as a feature.

Thanks!

**Comment by jualvarez** [comment]
Hello @warent, have you forked these changes? Do you mind pointing us to the relevant part of the code that you modified in order to make it work? We would really appreciate some directions to get this working. Thanks!

**Comment by clarson0** [comment]
dynamic row height would be very helpful, especially when using rows as headers (ex: when doing something similar to the demo with scroll to / md-top-index)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by johnSowingo** [comment]
+1

**Comment by Schlesiger** [comment]
+1

**Comment by AndrewEastwood** [comment]
+1

**Comment by timactive** [comment]
+1

**Comment by davidwilcox** [comment]
+1

**Comment by Jervelund** [comment]
Please use the reaction feature instead of posting more "+1" updates to this thread.

**Comment by warent** [comment]
@jualvarez It is, but that was some time ago. I'll see if I can remake it using the latest updates and if so I'll submit a PR :)

**Comment by nkoterba** [comment]
@Jervelund 

> Please use the reaction feature instead of posting more "+1" updates to this thread.

I'm a little out of touch following the MD issues, what do you mean by 'reaction feature'?

**Comment by Jervelund** [comment]
Sorry for not being clearer. Read about reactions here:
https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by davasqueza** [comment]
I found a little workaround that worked for me, first make a class like this:
```
.virtual-repeat-full-height{
  height: 100%;
  position: initial;
}
```

and next in the HTLM do something like this:
```
<md-content flex>
  <md-virtual-repeat-container class="virtual-repeat-full-height">
    <div md-virtual-repeat="thing in vm.things" md-on-demand>{{thing.name}}</div>
  </md-virtual-repeat-container>
</md-content>
```

PD: sorry for my english

**Comment by nil4you** [comment]
I added below css
```
.md-autocomplete-suggestions-container{
    .md-virtual-repeat-sizer{
        height:auto!important;
    }
}
```

**Comment by tylerjames** [comment]
Has anyone found a reliable way to set the height using a directive or otherwise?

Ideally the height would be responsive,  but without setting it explicitly in the CSS the virtual repeat container will not layout anything at all.

I've tried setting it in the link function of a directive but simply attaching a directive to my md-virtual-repeat-container element will cause it to not lay out any items, even if the directive doesn't do anything.

**Comment by tylerjames** [comment]
Ugh.

The problem with my directive was that it had a controller attached to it and that was preventing it from working properly when I eventually did find the correct method.

Here is a working directive that will resize the container:

    (function (){
		'use strict';

		angular.module('vyNewReportModule').directive('runtimeHeight', runtimeHeight);
		function runtimeHeight() {
			var directive = {
				link: link,
				require: 'mdVirtualRepeatContainer'
			};
			return directive;

			function link(scope, elem, attr, mdVirtualRepeatContainer) {
				elem.css('height', newSize);			
			}
		}
	})();

**Comment by 0101adm** [comment]
+1 responsive

**Comment by mckinleymedia** [comment]
None of those answers quite worked for me. I ended up coding a new solution. This one just updates with window resize. In my build, I've got a fixed footer.
`
angular.module('app')
  .directive('updateSize',['$window', function ($window) {
        return {
            restrict: 'A',
            require: '^mdVirtualRepeatContainer',
            link: function(scope, element, attributes, mdVirtualRepeatContainer) {
                var footer = 45;
                function getHeight() {
                  var height = $window.innerHeight - (element[0].getBoundingClientRect().top + footer);
                  angular.element(element).css('height', height + 'px');
                  return height;
                }

                function onResize() {
                  mdVirtualRepeatContainer.setSize_(getHeight());
                }
                getHeight();
                angular.element($window).on('resize', onResize);
            }
        };
      }
  ]);
`
Then add it here:
`<md-virtual-repeat-container update-size>...`

**Comment by yweing0720** [comment]
for me this worked
`md-virtual-repeat-containe{
    height: calc(100vh - 75px);
}`

**Comment by Splaktar** [comment]
There is work happening in PR https://github.com/angular/material/pull/11516 to allow variable height items in autocomplete via `ng-repeat` instead of `md-virtual-repeat`.

Also the Angular CDK has a [`*cdkVirtualFor` directive](https://material.angular.io/cdk/scrolling/overview#virtual-scrolling) that can be used in Angular or hybrid projects to create a virtual scroll component that can have items of different heights.
