### ISSUE TITLE
md-button inside md-menu does not align with ui-sref attribute

### ISSUE THREAD

**Issue by kheide** [angular/material#4353]
When using md-menu and md-button with ui-sref instead of ng-click the text does not vertically center, but instead offsets abit to the top. If using ng-click or no attribute at all it perfectly centers. 

Is this a known bug, intentional or is there a common fix for this?

**Comment by rschmukler** [comment]
Could possibly reference #4142

**Comment by alvarezc** [comment]
I'm still trying to figure out how the flex model works, but the fix seems to only work when you have text only within the md-button ... if you have a p or div tags then it doesn't work as it centers the text both vertically and horizontally, since I'm using it with icons (like the demo) I had to add all this for it to work, not sure if it's the "right way" but at least it worked
```html
<md-menu-item>
    <md-button ui-sref="top.register">
        <div layout="row">
            <p flex>Registration Form</p>
            <md-icon md-menu-align-target md-font-set="material-icons"
                style="margin: auto 3px auto 0; font-size: 15px">create</md-icon>
        </div>
    </md-button>
</md-menu-item>
```

```scss
md-menu-item {
    > a.md-button {
        display: flex;
        justify-content: center;
        flex-direction: column;

        > .layout-row {
            width: 100%;
        }
    }
}
```
