### ISSUE TITLE
mdBottomSheet: TypeError: Cannot read property 'runner' of undefined

### ISSUE THREAD

**Issue by topherfangio** [angular/material#4388]
There is an issue on the docs site which can throw the above error and break the site's formatting.

Steps to reproduce:

1. Open the [bottom sheet demo](https://material.angularjs.org/HEAD/#/demo/material.components.bottomSheet)
1. Click the "Show as Grid" button
1. Click the "Twitter" icon/button
1. VERY QUICKLY click another demo on the left before the toast starts to disappears

The error will be thrown and there will be two `<md-content>` tags on the page, the bottom one will be empty and cause 50% of the page to be empty (due to PR #4372).

<img width="1440" alt="screen shot 2015-08-31 at 11 03 41 am" src="https://cloud.githubusercontent.com/assets/54370/9583275/0a034cae-4fd0-11e5-8c26-b273377ea7bb.png">

**Comment by ThomasBurleson** [comment]
@matsko - how do we cancel an animation runner in `$destory()` ?

**Comment by DevVersion** [comment]
This will be easy to fix after we have #6684, because then the interim elements won't get removed directly if removing. They will be removed from stack, after their animation is done. 

Then we can use $mdBottomsheet.destroy() because after that we will find an interim element (see [here](https://github.com/DevVersion/material/blob/6a564508567cf1e352495bdf803f6db94334c601/src/core/services/interimElement/interimElement.js#L381-L381)).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
