### ISSUE TITLE
md-menu adding "top" style with negative value equivalent to scrolled valued. Totally breaks the view.

### ISSUE THREAD

**Issue by alexbouchardd** [angular/material#4399]
(Disclaimer) Totally new to GitHub and fairly amateur programmer, gotta start somewhere

When ever I am opening a md-menu on a fixed item (nav bar) and the page is scrolled, the scrolled value is applied negatively to the body style. So if I am scrolled by 100px, the body will be injected "top:-100px" and this screw up pretty much everything. All my fixed elements are moved upwards by the matching value and the bottom on the page is empty. Meaning even the backdrop doesn't go all the way down the browser view.
![capture](https://cloud.githubusercontent.com/assets/2049224/9596049/5085bfdc-503d-11e5-9dc5-f45fc7c63460.PNG)

Is this a known issue? Any clue what could be wrong?
Please let me know if you need more information (and what would those be) and if I am asking at the right place (like I said, new to this)

Cheers

**Comment by topherfangio** [comment]
Hey @alexbouchardd! Welcome to GitHub!

Typically, this is the place where you would report a bug with the framework and as such, it is mostly frequented/moderated by the Angular Material team. The [forums](https://groups.google.com/forum/#!forum/ngmaterial), on the other hand, are frequented/viewed by a vast number of developers, so for a more generic question like this, you may have more luck there.

Regardless of where you post, one of the most helpful things you can do is to provide a [CodePen](http://codepen.io) with the least amount of code possible that demonstrates the issue. A great way to do this is to find a demo on the site that is similar and click the "Edit on CodePen" icon in the top right. This will allow us to very quickly get an exact idea of the issue as well as allowing us to play with it and make changes. Typically, if we can find a quick solution, we will repost a modified version of the CodePen that you can look at to see the differences.

I'm not exactly sure what your problem is here, but I can say that you don't typically use `position: fixed` on the body element. Honestly, I find that I rarely use `position: fixed` at all as there is usually an easier way to accomplish the same thing. Again, a CodePen would be really helpful in seeing what you're trying to accomplish.

**Comment by alexbouchardd** [comment]
Hey @topherfangio, thanks for the insights!

I'll look over the forum and try to reproduced it in copepen as well. How ever I did notice that the position:fixed is also being injected when the md-menu is triggered, is this the expected behavior?
