### ISSUE TITLE
a md-icon-button ripple animation is broken when the action (of the button) is open a sidenav.

### ISSUE THREAD

**Issue by nestorneto** [angular/material#4433]
When a md-icon-button opens a sidenav. The ripple still there when sidenav closes.

![ripple](https://cloud.githubusercontent.com/assets/362382/9631919/6c3a8d34-515a-11e5-8780-dd0b273e890a.png)

tested in chrome and firefox linux version.

**Comment by ThomasBurleson** [comment]
Are you using the latest code from Bower-Master ?  (v0.11.0-rc1 or newer)

**Comment by nestorneto** [comment]
tested in 0.11.0-rc1 and olders.

I was just waiting for the ripple rewrite to see if could fix that before I post the issue.

**Comment by ThomasBurleson** [comment]
@nestorneto - understood! Thanks. 
>I see it now in https://material.angularjs.org/HEAD/#/ SideNav

**Comment by dmackerman** [comment]
This also appears to be the case for any button in a sidenav for us.  The "Help" button is not in a sidenav and ripples properly.

See GIF: 

![ripples](https://cloud.githubusercontent.com/assets/289938/10059217/a3e628f6-61fe-11e5-9e52-428d9b891170.gif)

Happens when `href=""` or a regular `button` element is used.

**Comment by robertmesserle** [comment]
@ThomasBurleson This is not the ripple, but the focus indicator.  The fix would be to clear the focus, but I'm not sure we want to do that.
