### ISSUE TITLE
fab speed dial bug: tooltip mispositioning 

### ISSUE THREAD

**Issue by accetone** [angular/material#4445]
When we want display tooltips with menu opening, tooltips become mispositioned

Screenshot:
![clip2net_150902231614](https://cloud.githubusercontent.com/assets/7840570/9643382/4d6f694a-51ca-11e5-811a-8053502000e0.png)

Sample:
http://codepen.io/anon/pen/YyPzrq

**Comment by topherfangio** [comment]
I believe this has already been fixed. Can you test this against the latest master code available?

**Comment by accetone** [comment]
Update my code sample (http://codepen.io/anon/pen/YyPzrq) with js and css from https://gitcdn.xyz/repo/angular/bower-material/master/. Issue still appearing.

**Comment by topherfangio** [comment]
Looks like this is due to the tooltips being shown right as the animation starts, at which point the FABs have a scale of 0, so the tooltip is not taking into account their full size. I will look into this, but I'm honestly not sure if we can fix it as the wrapping `<div>`s will currently scale with the inner FABs.

In the meantime, here is a quick workaround which sets the tooltips to have a slightly delayed opening so that they happen after the animation.

http://codepen.io/topherfangio/pen/Xmbqmw?editors=100

Note that if you have more FABs, you may need to increase the delay from `400` to something like `500` or `600`.

**Comment by SanderElias** [comment]
We need a callback from the animation system to get this to work. Problem is that the position gets calculated when the parent is still at size:0 in the animation.

**Comment by jpike88** [comment]
This one was driving me nuts, it really needs attention.

Topher thanks for that Codepen, but it turns out I needed to remove the if(isOpen) check because the tooltips wouldn't close after a button was clicked (in my app, not in the codepen).

**Comment by baelter** [comment]
@jpike88 @topherfangio 

Updated the codepen to use ng-if instead of md-visible and it is now working as expected: http://codepen.io/anon/pen/MKdgmB?editors=1010
