### ISSUE TITLE
md-autocomplete does not receive focus events after clear

### ISSUE THREAD

**Issue by hannupekka** [angular/material#4469]
Re-producable in this forked Codepen: http://codepen.io/hannupekka/pen/LpEegj

Steps:
1. Click md-autocomplete field
2. Select any suggestion
3. Click reset from the end of the field
4. Click md-autocomplete field

Expected outcome:
I get list of suggestions like in the beginning.

Actual outcome:
Suggestions not showing up. I have to click outside md-autocomplete field and then click back inside the field to get suggestions.

**Comment by nestorneto** [comment]
On focus, suggestions shouldn't showing up when something is already selected?

**Comment by topherfangio** [comment]
@hannupekka Your codepen example unfortunately uses a bad link to our CDN which always loads master. I have updated your codepen to use v0.10.1 (http://codepen.io/topherfangio/pen/MaoJpE) and can clearly see the error.

However, I then updated your codepen to use Angular 1.4.7 and the master branch of material (http://codepen.io/topherfangio/pen/yYXgXo) and I think it works like you would expect. I believe this was indeed fixed in PR #4958.

Please comment if you are still seeing issues after upgrading and I will reopen.
