### ISSUE TITLE
Autocomplete highlight not working on 0.11.0.rc2

### ISSUE THREAD

**Issue by williamweckl** [angular/material#4490]
Autocomplete highlight stopped working on 0.11.0.rc2 update. Tried to reproduce on codepen, but for an unknown reason the 0.10.1 file is always redirecting to 0.11.0.rc2.

The problem can be reproduced in own documentation. 

https://material.angularjs.org/0.10.1/#/demo/material.components.autocomplete
vs
https://material.angularjs.org/0.11.0-rc2/#/demo/material.components.autocomplete

I noticed that only item is available inside `md-item-template`, other scope variables are not, including the variable that is used to do highlight.

Testing on 0.10.1, the problem does not happen.

**Comment by siulung4073** [comment]
+1

**Comment by ricardobfa** [comment]
+1

**Comment by alexitooi** [comment]
+1

**Comment by topherfangio** [comment]
I just tested this on [HEAD](https://material.angularjs.org/HEAD/#/demo/material.components.autocomplete) because I thought I had run into it too, but apparently the demos require you to match the case when searching. Anyway, it looks like it's fixed (possibly due to the recent merge of #4391).

Can you guys confirm the fix or provide a [Codepen](http://codepen.io) demonstrating the problem?

**Comment by RolandHeath** [comment]
HEAD works for me, where 0.11.0 does not.

**Comment by williamweckl** [comment]
HEAD works for me too.
