### ISSUE TITLE
mdAutocomplete: pass ng-* applicable attributes to input

### ISSUE THREAD

**Issue by jualvarez** [angular/material#4492]
Attributes applicable to the input tag within an autocomplete should be passed to the control. For example: ng-trim, ng-blur, ng-focus, etc...

**Comment by spoco2** [comment]
Yes. +1 from me for this one. I need ng-trim in particular, having nothing happen when spaces are added to the input is frustrating.

**Comment by ThomsC** [comment]
+1
I need ng-trim and some custom directives too

**Comment by bayucandra** [comment]
+1, absolutely need ng-trim="false", as sometimes space is necessary to do some programmatic things on the input.

**Comment by DevVersion** [comment]
I was investigating at some possible solutions to dynamically forward attribute events to another element.

> For example I was linking the different attributes by connecting the different scopes with internal variables. 
> Those internal variables / functions will be parsed and evaluated in the user scope.

Unfortunately are we not able to access the `$locals` of a parsed expression, so this approach didn't work out.

- https://github.com/angular/angular.js/pull/13454 (>`1.5.x`)

We decided to manually forward the `ngBlur` and `ngFocus` to the input, since those are already used by autocomplete anyway.

`ngTrim` will follow in another change.
