### ISSUE TITLE
md-checkbox example is broken as of 0.11

### ISSUE THREAD

**Issue by csvan** [angular/material#4494]
https://material.angularjs.org/latest/#/demo/material.components.checkbox

See attached screenshot. Chrome 45 under Fedora 22.

![badselect](https://cloud.githubusercontent.com/assets/1127729/9741657/dd14b4a2-565b-11e5-90de-758c552f46fa.png)

**Comment by topherfangio** [comment]
I have a suspicion that it might be because both demos declare the same module `checkboxDemo1` as I had a similar experience when building other demos.

However, it's odd that it is working locally and on the master site, and it looks like 0.10.1 had the same code, so I'm a bit confused as to why it would be breaking now.

@ThomasBurleson @robertmesserle Perhaps something changed in our release build system recently that no longer allows duplicate modules?

A quick check shows that GridList also has a duplicate module name, but it doesn't appear to affect it's demo.

**Comment by topherfangio** [comment]
Looks like this was already fixed. Versions 11.1, 11.2 and HEAD all look correct. Please re-open if you experience any issues.
