### ISSUE TITLE
Md-autocomplete with md-floating-label defined not displaing label correctly when loading query results

### ISSUE THREAD

**Issue by gabguy** [angular/material#4503]
When using md-floating-label in an md-autocomplete that displays a loading progress linear bar the floating label is not displayed correctly.
Example:
![md-autoaomplete-bug](https://cloud.githubusercontent.com/assets/7655154/9754476/533dce0e-56d2-11e5-8957-170e676ba56e.png)

Please fix it

**Comment by EladBezalel** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by gabguy** [comment]
Hi, here is a codepen demo taken from your docs, I just replaced the placeholder with an md-floating-label.
In order to reproduce the bug you should tick the simulate query checkbox and start typing 'Alabama' for example. You should then see the label breaking into 2 lines

http://codepen.io/anon/pen/XmXGQE

**Comment by EladBezalel** [comment]
@gabguy good catch.

It is something with md-autocomplete-wrap that sets layout row

**Comment by bluebirdtech** [comment]
+1 for a fix

Is there a way to disable the progress indicator in the meantime?  (Search is fast enough in our case)  I didn't find anything about it in the docs.

**Comment by gabguy** [comment]
Also, when not using md-floating-label and just going with the default placeholder, the search query text disappear while the progress bar is displayed (can be reproduced with the default code pan from your docs)

**Comment by topherfangio** [comment]
This was partially fixed by PR #4958 which is now available in master. The codepen above actually shows the correct behavior because it is unfortunately using some bad CDN links which always point to master (this has been corrected for new codepens, but we haven't retroactively fixed old codepens).

I believe the only issue now is that the padding is incorrect which is already listed in #4988.

Closing for now, please comment if you are still seeing issues in master.
