### ISSUE TITLE
Resizing browser with md-dialog open is broken in 0.10.1 / 0.11.0

### ISSUE THREAD

**Issue by anupbelambe** [angular/material#4513]
Resize on browser window with md-dialog is broken in 0.10.1. The issue can be reproduced by opening demo custom dialog and resizing browser. We can see that the dialog is positioned correctly as it did in 0.10.0

for e.g. 
0.10.1:
open custom dialog on following AMD 0.10.1 link and resize the browser window.
https://material.angularjs.org/latest/#/demo/material.components.dialog

0.10.0
open custom dialog on following AMD 0.10.0 link and resize the browser window.
https://material.angularjs.org/0.10.0/#/demo/material.components.dialog

The custom dialog window is getting resized / positioned correctly on resizing the browser window in AMD 0.10.0 which seems to be broken in 0.10.1.

Appreciate if anyone can suggest any workaround for the same to use md-dialog in 0.10.1 with 0.10.0 behavior.

On Windows 7, google chrome Version 44.0.2403.157 m

Following is the snapshot of custom dialog on AMD 0.10.0 with small browser window 

![amd_0 10 0_custom_dialog](https://cloud.githubusercontent.com/assets/72758/9761371/fe119332-5719-11e5-8084-a455d0f691e9.PNG)

Snapshot with window maximized (AMD 0.10.0)

![amd_0 10 0_custom_dialog_full_screen](https://cloud.githubusercontent.com/assets/72758/9761334/b47e7230-5719-11e5-987d-e3f664e50980.PNG)

 snapshot of custom dialog on AMD 0.10.1 with small browser window 

![amd_0 10 1_custom_dialog](https://cloud.githubusercontent.com/assets/72758/9761358/e19fc1a6-5719-11e5-80dd-43e0328ce7aa.PNG)

Snapshot with window maximized (AMD 0.10.1)

![amd_0 10 1_custom_dialog_full_screen](https://cloud.githubusercontent.com/assets/72758/9761366/f16e729e-5719-11e5-819c-d78849e0d47f.PNG)

Let me know if you need any additional information.

**Comment by langdonx** [comment]
Here's the culprit:
 - https://github.com/angular/material/commit/b71fdfb609a9b8c5bf6e2f4b41638020e265acd2#diff-58cbee594b2fabf2c78b6d283750e535R704

Now that you can specify the dialog's parent, things got a bit trickier.  It won't be as simple as window.addEventListener('resize'), since a parent's height may change for other reasons.

You can get around the issue for dialogs that don't use the `parent` option by using the following CSS:

    body > .md-dialog-container {
      height: 100vh !important;
    }

**Comment by anupbelambe** [comment]
Thanks langdonx.This workaround seems to be working. When can we expect this issue to be fixed in Angular Material Design?

**Comment by ThomasBurleson** [comment]
@langdonx - nice work researching this. Submit a PR so we can acknowlege your efforts in the Changelog for 0.11.1 ;-)

**Comment by anupbelambe** [comment]
Thanks Thomas. Roughly by when can be we expect this milestone to be released. I see the the due date for milestone as Sep.11 (but also only 22% issues closed). This will help in taking appropriate steps for us.

**Comment by langdonx** [comment]
@ThomasBurleson Would be happy to submit a PR, but my CSS fix is more of a hack, since it won't affect dialogs with parents other than `<body>` whose heights are variable.  This might be an edge case not worth addressing though.  The issue can be demonstrated here:

http://codepen.io/anon/pen/XmXNjb
 1. Resize the browser so it's in md/sm mode where the buttons are stacked
 2. Click Alert Dialog
 3. Resize the browser so it's bigger than md

You'll see:

![image](https://cloud.githubusercontent.com/assets/441982/9851670/ecd07348-5ac7-11e5-947b-0cce0e8fbbfc.png)

**Comment by langdonx** [comment]
@ThomasBurleson Additionally there are 2 other issues when the page isn't bound inside of scrollable/flexable div (such as the docs are).  One you may have noticed above -- if you make the example page very short, click Custom Dialog, and then resize to make the page taller, the backdrop will not cover the viewport:

![image](https://cloud.githubusercontent.com/assets/441982/9852419/287ff3d8-5acc-11e5-8234-1c21a6359a4f.png)

Second, if you make the viewport short again, and scroll all the way down to click custom dialog, the top will be miscalculated:

![image](https://cloud.githubusercontent.com/assets/441982/9852484/79de62be-5acc-11e5-855b-c84d70c673b5.png)

These last two issues have to do with `disableParentScroll`, where the `<body>` ends up getting set to `position: fixed` and then `postLink` comes along and sets a specific height for the backdrop element.

There are a lot of moving parts and different cases here. =/

**Comment by logist** [comment]
Currently resize event is registered only if dialogs ```options.escapeToClose``` is set to true. It should be registered regardless of that option, outside of ```if (options.escapeToClose) ``` block.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
