### ISSUE TITLE
md-contact-chips readonly

### ISSUE THREAD

**Issue by rkimaoui** [angular/material#4537]
Hi,

Could you please add readonly to md-contact-chips, or make ng-disable working with it.

Thanks

**Comment by apat183** [comment]
+1 for this.

**Comment by jamalx31** [comment]
+1

**Comment by shprink** [comment]
+1

**Comment by dillyboy** [comment]
+1

**Comment by apat183** [comment]
Here is my temp solution:

http://codepen.io/anon/pen/YwjzGp

Since I'm using the md-chips directive, it also has all the features such as md-on-remove and md-on-add etc as well. I noticed that md-contact-chips directive is just md-chips so I'll try and do a pull request to update the current md-contact-chips to include all the features of md-chips, I've never done a pull request before so might take some time.

**Comment by csvan** [comment]
+1

@apat183 if I can help with anything, just let me know. I am eager to see this in master as well.

**Comment by forcewill** [comment]
+1
