### ISSUE TITLE
md-select and md-autocomplete lists make page content disappear

### ISSUE THREAD

**Issue by shp0** [angular/material#4603]
In version 0.11, clicking on an md-select option (in a directive) makes the page content disappear.  This occurs with the html body style=" overflow-y: auto; height: 100%;" and content overflowing the browser height.

Scrolling the body (with JQuery ScrollTo) after selecting an md-autocomplete item also makes the content disappear after a second search and select.

**Comment by shp0** [comment]
For one md-autocomplete, it seems scrolling the html body with JQuery.scrollTo is the causing the problem.  I changed the code to scroll a div with a fixed height instead of the body, and the page content doesn't disappear.

**Comment by DaHaiz** [comment]
+1 same here. happens only if the page is scrolled. only the part of the page that is not visible without scrolling is hidden.

**Comment by pl-j** [comment]
+1 ; although my problem is not exactly the same, it seems linked.
If there is a scroll on the page, clicking on a select will mess the page layout (in my case, it overrides the width set on the body, which in turn stretches everything).

My apologies if by mistake this is a different issue entirely.

**Comment by topherfangio** [comment]
Whenever possible, please provide a CodePen Demo. To expedite resolution, please always test with the latest versions:

*  Angular Material HEAD
 *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
 *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
 *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
 *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
 *  Angular 1.3.19 (or greater)
 *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by pl-j** [comment]
Thanks for replying @topherfangio . Using the latest versions of Angular+Angular Material does not change a thing. But, writing a pen was definitely worth it, since I found a workaround.

Here's the pen : http://codepen.io/anon/pen/NGgxbY

On my (sort of low) resolution, there is a scroll on the display panel. Clicking the select while there is a scroll on stretches the body. If you remove some of the paragraphs to remove the scroll, clicking the select works just fine.

An easy workaround is to wrap the content of the body in a div, and apply the .center-body class to that div instead of the body. Doing that, I don't seem to have any problem. Don't know if this will help the problem mentionned by the other two posters though.

**Comment by orhemi** [comment]
Find a solution:

Add to your css:

`body {
    height: auto !important;
}`

**Comment by orhemi** [comment]
FIX:

Add to your css:

`body {
    height: auto !important;
}`
