### ISSUE TITLE
md-input-container helper text

### ISSUE THREAD

**Issue by Yimiprod** [angular/material#4642]
Is it in project to handle helper text like described [here](https://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors) ?

<img width="790" alt="screen shot 2016-01-14 at 6 04 50 pm" src="https://cloud.githubusercontent.com/assets/210413/12343525/5b9c1594-bae9-11e5-8682-b130a8bb4b1f.png">

At the moment the text is always in warn color even if the input text isn't have `.md-input-error` class.

**Comment by Androguide** [comment]
This is handled using [ngMessages](https://docs.angularjs.org/api/ngMessages/directive/ngMessages), you can see an example in the errors section of the input demos [here](https://material.angularjs.org/latest/#/demo/material.components.input)

**Comment by Yimiprod** [comment]
That's the point, ng-message is only displayed as an error message (warn), not help text (gray).

**Comment by EladBezalel** [comment]
@Yimiprod Great call

@ThomasBurleson is this a feature request?

**Comment by topherfangio** [comment]
I feel like we should offer a solution for this, however, after playing around with it for a bit, I think it is a bigger issue that needs more thought.

For instance, one of the use-cases in the [spec](http://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors) shows how the help text can transform into an error message. This will sorta work out of the box with the quick-and-dirty solution I wrote, but there is not an easy way to disable it if you always want grey text (even if the input is invalid).

In any case, if you want to hack it, you can make it work by doing a custom `ng-messages` div pointing to your own hash and adding some super-basic CSS: http://codepen.io/topherfangio/pen/vNLbxJ

_**Note:** PR #4647 adds support for multiple messages so that you could have another `<div ng-mesages="...">` below it with any errors, but it hasn't been merged yet, so multiple messages will currently overlap._

**Comment by EladBezalel** [comment]
@topherfangio mind taking this also ? :smile:

**Comment by ThomasBurleson** [comment]
A pull request would be welcomed!

**Comment by topherfangio** [comment]
@Yimiprod We recently added a new "Errors Advanced" demo which shows one possible solution for this. I would still like to see something more robust, but this should get you started:

https://material.angularjs.org/latest/demo/input
