### ISSUE TITLE
<md-icon> left-aligned on Internet Explorer 11

### ISSUE THREAD

**Issue by jocel1G** [angular/material#4649]
I tested once again the code from the following CodePen http://codepen.io/ThomasBurleson/pen/JopjjN. But this time with the version 0.11.0 of Angular Material. In a local Web page, on Internet Explorer 11, I got what I signaled in the issue #3971: the <md-icon> are left-aligned. This time, I fixed the problem this way. In the file named angular-material.css, I commented out the following line, in md-icon[md-font-icon]:
**width: auto;**

The <md-icon> are now center-aligned, and it is also the case on Firefox, Chrome and Edge.

**Comment by programmist** [comment]
I tested on Win 7 IE 11 and can't reproduce the issue. The display of that Codepen in IE11 is exactly the same as on Chrome for me (not left aligned). Your Codepen is using the Angular Material head revision, so it's likely the issue was resolved.  If you can still demonstrate the issue, please reopen.
