### ISSUE TITLE
Suggestion list template appears before md-min-length is fulfilled for md-autocomplete

### ISSUE THREAD

**Issue by lscordilis** [angular/material#4678]
I'm sure I'm not the only one who's noticed this since the version bump. The list template appears blank before the min length is reached and then starts getting populated with suggestions.

It's a minor annoyance, as they cover the ng-messages below the input. In general, maybe there should be an option to have the suggestions list extend above the input as opposed to always below, as validation for ng-messages may be more sophisticated than just ```required```

**Comment by topherfangio** [comment]
Possibly related to #4665.

**Comment by topherfangio** [comment]
This should be fixed in master. Can you please let us know if you are still experiencing the issue, and if so, provide a Codepen demonstrating the problem? If so, I will reopen.

Also, regarding the position of the suggestions list, can you please open a separate issue so that we can mark it as a feature request?
