### ISSUE TITLE
mdTabs: Can't change ink ripple of tabs

### ISSUE THREAD

**Issue by httpete** [angular/material#4688]
Any clue? I went through the code, saw an attribute that I thought would work for ripple-color but no dice.

**Comment by EladBezalel** [comment]
```html 
<element md-ink-ripple="#color" /> 
```

Notice that this is not an issue and for more questions ask in the [Angular material forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by httpete** [comment]
It doesn't work on the tabs. I tried each tab, I tried the md-tabs container.

**Comment by EladBezalel** [comment]
Can you please provide a codepen or plunker?

**Comment by httpete** [comment]
http://codepen.io/anon/pen/rOeyMv

I took the default, added the attr on the tab, still red. Thanks Elad

**Comment by chrisryer** [comment]
To change the colour of the tab ripples & ink bars in material-design: 1.0.1 ( potentially close versions too )
/* override default styles of material design */
md-tabs.md-accent md-tabs-wrapper md-tabs-canvas md-pagination-wrapper md-ink-bar{
	color:#60c9f8; /* this changes the colour of the ripple */
	background-color:#60c9f8;  /* this changes the colour of the ink bar */
}

**Comment by httpete** [comment]
chrisryer, your css works fine in later versions, I had an old version. Thanks!

**Comment by gtsop** [comment]
Unable to find any working solution on the matter, I ended up using this css:

`md-tabs md-ink-bar {
    color:#6a2d94;
    background-color:#6a2d94;
}

md-tabs .md-tab:active .md-ripple-container {
  background-color: rgba(56,32,73,.1);
}

md-tabs .md-tab .md-ripple-container .md-ripple {
  background: #6a2d94;
  border-color: #6a2d94;
}`

Dumping it here for any future desperate wanderers.

**Comment by devdtu** [comment]
When tab is clicked, a backgorund color gets added to md-ripple-container and also a child of md-ripple-container is injected ( md-ripple ). For over riding the ripple effect. set the background-color of .md-ripple-container to transparent and give background color to md-ripple. I was not able to identify any class that gets applied when buttons get clicked ( this class shall apply for as much time as the ripple effect is there). Otherwise it would have been fairly straight forward. 
P.S - none of the above solutions worked for me -_-

.md-ripple-container {
    background-color: transparent !important;
}

.md-ripple-container .md-ripple{
  background-color: #44c8f5 !important;
}
