### ISSUE TITLE
When the focus is on md-tabs, pressing shift + tab doesn't do anything

### ISSUE THREAD

**Issue by ivan7237d** [angular/material#4696]

**Comment by osuritz** [comment]
This can be reproduced on the demo page for tabs at https://material.angularjs.org/latest/#/demo/material.components.tabs

Steps to reproduce:
* Press [TAB] until the focus in on the ````md-tabs```` control.
* Press [TAB] and notice that the focus moves on to the next element (expected).
* Press [Shift + TAB] and notice that the focus goes back to the ````md-tabs```` control (expected)
* Press [Shift + TAB] and notice that the focus stays on ````md-tabs control```` (as opposed to focus on the previous element).

Expected behavior:
* Pressing [Shift + TAB] while the focus is on ````md-tabs```` should move the focus to the previous element

This is a pretty big accessibility issue.

**Comment by osuritz** [comment]
Anyone from the team could take a look and classify this issue?
