### ISSUE TITLE
md-datepicker triangle button receives focus

### ISSUE THREAD

**Issue by bluebirdtech** [angular/material#4755]
Expected behaviour, triangle button does not receive focus, matching behaviour of md-select

**Comment by jelbourn** [comment]
The button receives focus separately from the text input in order to allow screen-reader users to interact with it. mdDatepicker has two different interactions: typing the date into a text input and opening the calendar. This is different from mdSelect, which only has one interaction (opening the list of options).

**Comment by bluebirdtech** [comment]
@jelbourn OK thanks. Shame that for the general case it feels like the focus is distracting.
