### ISSUE TITLE
mdContactChips: add option to specify default image

### ISSUE THREAD

**Issue by Frank3K** [angular/material#4779]
In the current implementation of `md-contact-chips` one can specify the field name of the image corresponding to a contact using the `md-contact-image` attribute.

However, when a given contact does not have set that field (i.e. the contact does not have an image), an empty `<img />` tag [is rendered](https://github.com/angular/material/blob/00474c39fb2c305ab43874809db3032a65cf40d6/src/components/chips/js/contactChipsDirective.js#L70-L72). Since an `alt`-attribute is added to the image some browsers (at least Chromium on Linux) render the image as wide as the contents of the `alt`-attribute. This messes with the layout of the contact chips.

It would be nice if there was a way to specify a default image, which is used in case there is no corresponding image. Another (slightly inferior) option would be to not render the `<img />` at all.

**Comment by topherfangio** [comment]
I think this is a good idea, but as a workaround, you can handle this at the "model" layer by making sure the data returns something useful when null.

I typically handle this at the JS model or even server layer (usually Ruby on Rails) so that I can use existing model data to dynamically change the URL based on that particular user (i.e. different pictures for male/female, etc).

**Comment by Frank3K** [comment]
I also thought of solving the issue in the model layer, but I thought a solution in the contact chips itself would be easier for the developer.

Do you think it is a good idea to hide the image if not image has been provided at all? I think I can work out a PR for that.

**Comment by topherfangio** [comment]
If you can find a solution that replaces the image with something of the same size (and maybe even an icon). I think that might work well.
