### ISSUE TITLE
md-autocomplete closes when scrollbar is clicked, IE 11 specific

### ISSUE THREAD

**Issue by webmandman** [angular/material#4785]
@robertmesserle This issue came up many many commits ago here https://github.com/angular/material/issues/1739 

I updated from 0.8.3 to 0.11.0 just two days ago and it continued to work on Chrome but on IE 11(edge) it is closing again when you click on the scrollbars. 

![md-autocomplete-ie-issue](https://cloud.githubusercontent.com/assets/991677/10032974/64c75ec4-613b-11e5-953a-b7a0f299798f.gif)

**Comment by bluebirdtech** [comment]
I've seen this occasionally happen in Chrome on Windows when dragging the scrollbar. Couldn't figure out a reliable set of repro steps.

**Comment by hillerstorm** [comment]
This was mentioned a while back without any response at all: #4625

**Comment by bluebirdtech** [comment]
Update: Actually, for me it was md-select with the problem..

**Comment by vladimir-ivanov** [comment]
Experiencing the same problem, 
it is happening because of ng-blur is triggered (in IE11 only) - calls function blur() and hides the autocomplete.
The underlying reason for that is how IE handles the blur / focus events:
http://www.barryvan.com.au/2009/01/onfocus-and-onblur-for-divs-in-fx/

multiple ways to fix it see:
http://stackoverflow.com/questions/2023779/clicking-on-a-divs-scroll-bar-fires-the-blur-event-in-i-e

I am in favour of this approach (obviously $(document) should be the md-autocomplete element only:
 $(document).bind('focusout', function(){
     preventHiding = false;
     //trigger blur event
     this.$element.trigger('blur');

});

$(document).bind('focusin', function(){
     preventHiding = true;
});

$(document).bind('blur', function(){
       // Did anyone want us to prevent hiding?
       if (this.preventHiding) {
         this.preventHiding = false;
         return;
       }
       this.hide();
});

**Comment by paulflo150** [comment]
How about:
1. Moving the events to md-virtual-repeat-container from ul since this is where the scrollbar is:
````
<md-virtual-repeat-container\
              md-auto-shrink\
              md-auto-shrink-min="1"\
              ng-hide="$mdAutocompleteCtrl.hidden && !$mdAutocompleteCtrl.notFoundVisible()"\
              class="md-autocomplete-suggestions-container md-whiteframe-z1"\
              ng-mouseenter="$mdAutocompleteCtrl.listEnter()"\
              ng-mouseleave="$mdAutocompleteCtrl.listLeave()"\
              ng-mouseup="$mdAutocompleteCtrl.mouseUp()"\
````

2. Add a scroll event which sets focus on the input.
````
function gatherElements() {
                ......
                elements.$.scroller.on('scroll', onScroll);
            }

function onScroll() {
                elements.input.focus()
            }
````

**Comment by PDSBGreg** [comment]
+1 still broken on IE11 with version 0.11.2

**Comment by foxx9** [comment]
+1

**Comment by npradeeptha** [comment]
+1 still not working in 1.0.0-rc1
