### ISSUE TITLE
md-chips adds $$hashKey to objects because `track by $index` is not used

### ISSUE THREAD

**Issue by sazonenka** [angular/material#4789]
The similar issue like in #3487

**Comment by sazonenka** [comment]
Should be a trivial fix by adding `track by $index` to [chipsDirective.js#L95](https://github.com/angular/material/blob/master/src/components/chips/js/chipsDirective.js#L95)

**Comment by jelbourn** [comment]
Took a look at this. Just adding `track by $index` breaks the removal of chips since the removal happens in place. I.e., if you have `['Apple', 'Banana', 'Orange']`, and remove the chip at index 1, you'd end up seeing `Apple | Banana` even though the model is `['Apple', 'Orange']`

The ideal solution would be to allow specifying a `track by` at the mdChips API level, but that's a bit more complexity than a quick fix.

**Comment by Thaina** [comment]
What? This bug is not fixed with any effort and just close like this???

**Comment by Splaktar** [comment]
@Thaina This was closed a couple years ago when the team did a mass closing of issues that they didn't have resources to address. If this is a concern to you now, please open a new issue with a reproduction and reference this issue.
