### ISSUE TITLE
Angular Material home page – closing Alert Dialog or Confirm Dialog issue

### ISSUE THREAD

**Issue by a8775** [angular/material#4796]
1.	Open the https://material.angularjs.org/0.11.0/#/
2.	Select “Demos”
3.	Select “Datepicker”
4.	Select “Dialog”
5.	Select “Alert Dialog” or “Confirm Dialog”
6.	Press “back” on browser or backspace

The dialogs close however the page change to the “Datepicker” page – intended action would be to just close the dialog.

**Comment by ThomasBurleson** [comment]
This has been fixed in https://material.angularjs.org/HEAD/#/

Please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by a8775** [comment]
Working with: https://material.angularjs.org/HEAD/#/

![snip_20150924213352](https://cloud.githubusercontent.com/assets/14092227/10084589/8d59ec92-6304-11e5-8c87-74ad3651d560.png)

Than you go to Demo > Dialog page, and select eg. Alert Dialog.

![snip_20150924213425](https://cloud.githubusercontent.com/assets/14092227/10084611/b24fba5e-6304-11e5-95c2-c4021395425a.png)

Every thing is ok. Now you press back buton on the keyboard and you get:

![snip_20150924213442](https://cloud.githubusercontent.com/assets/14092227/10084637/d3eb8b0c-6304-11e5-8679-dcd1ec69160e.png)

Expected behaviour would be just to close the modal dialog and stay on the Demo Dialog page.

**Comment by a8775** [comment]
I was looking more on this problem, similar problem was described on the following blog:
http://www.sgzhaohang.com/blog/2014/11/28/angularjs-hack-browser-back-button-to-dismiss-modal/
