### ISSUE TITLE
FAB moves out of viewport with scroll

### ISSUE THREAD

**Issue by vinkaga** [angular/material#4908]
FAB should stay in place upon scroll (like Google Messenger has for new messages). But in angular-material (tested with latest version), it scrolls with content and even moves out of the viewport.

http://codepen.io/vinkaga/pen/jbyPBB?editors=100

**Comment by topherfangio** [comment]
Try this: http://codepen.io/topherfangio/pen/NGdGvM?editors=100

First, you need to make sure you're using the same versions of the CSS and JS. You had CSS 0.8.3 with JS 0.11.1. Many things have changed with the layout in recent versions, so those need to be the same.

Also, instead of having `<body flex>` you should do `<body layout="column">` to achieve the proper effect.

**Comment by vinkaga** [comment]
Thanks :)
