### ISSUE TITLE
md-select + div:hover

### ISSUE THREAD

**Issue by rafamardegan** [angular/material#4920]
Hey guys! I'm new in AngularJS and I have a issue with md-select from Angular Material.
So, in this div (select-wrapper), that is displayed on mice hover, I added a md-select component. When the cursor is positioned on md-select, the div (select-wrapper) get mice hover out. 
I realize that another component is displayed in the last lines of my code, when I click on md-select component. How can I fix this!? Could you guys help me?

This is my code: http://codepen.io/anon/pen/OyWMdK

**Comment by dcoferraz** [comment]
:+1:

**Comment by topherfangio** [comment]
So, you'll probably need to use a bit of JS to make this happen rather than pure CSS. I would look at using the `ng-mouseenter` and `ng-mouseleave` directives on your DIV and having those fire a method on your scope/controller that checks whether the select is open (if open, don't close the div).

You may also want to look at the [docs for select](https://material.angularjs.org/0.11.1/#/api/material.components.select/directive/mdSelect), particularly the `md-on-close` as you may want to close your div when the select closes.

In general, this type of question is best asked/answered on the [forum](https://groups.google.com/forum/#!forum/ngmaterial) rather than on GitHub where we track bugs/issues.

**Comment by dcoferraz** [comment]
@topherfangio, could you suggest a implementation of this feature?

**Comment by rafamardegan** [comment]
@topherfangio, thank you for help me. I'm almost there using the directives that you suggest.

**Comment by dcoferraz** [comment]
@topherfangio, me and @rafamardegan ended up fixing the issue with these directives shown on this codepen.

http://codepen.io/anon/pen/ojBEEV

**Comment by rafamardegan** [comment]
@topherfangio, again... thank you!

**Comment by marcysutton** [comment]
Keep in mind that UI treatment is totally inaccessible to keyboard and screen reader users. Perhaps you could put `tabindex="0"` on the wrapper and expose it on `focus`? Though I'm not sure what the role for that element would be, since it has a select in it. Maybe treat it like a dialog?
