### ISSUE TITLE
All "Edit on CodePen" links are broken (globally)

### ISSUE THREAD

**Issue by vinkaga** [angular/material#4966]
Results in an empty CodePen.

**Comment by topherfangio** [comment]
All of the CodePens are currently unavailable due to a recent upgrade to the CodePen site. They are working diligently to resolve the issue. You can track the progress here: https://github.com/CodePen/redesign/issues/112

I will leave this open in hopes that others who notice the issue will see this and be able to track it more easily.

**Comment by jelbourn** [comment]
Issue has been resolved by CodePen.
