### ISSUE TITLE
Need the ability to keep the searched term at the search box after do the search (google behaviour)

### ISSUE THREAD

**Issue by cicw** [angular/material#5050]
I have my md-autocomplete set as follow:

- model: md-search-text="searchText"
- items: md-items="item in performQuery(searchText)"
- search (trigger): md-min-length="2"

Problem: when I select an item from the itens collection if I don´t clear the searchText model the window of itens collection pops again after the selection
but i need to keep the searched text there like google does with out this behaviour

How can I accomplish this?

**Comment by topherfangio** [comment]
I believe this was a bug fixed in PR #4958. Can you please test against master and see if you still experience the issue?

If so, please provide a Codepen demonstrating the issue and I will reopen. Here are some links to get you started:


* HEAD Demos
  * https://material.angularjs.org/HEAD/#/demo/material.components.autocomplete
*  Angular Material HEAD
 *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
 *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
 *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
 *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
 *  Angular 1.3.19 (or greater)
 *  Angular 1.4.7 (or greater)
