### ISSUE TITLE
$mdDialog: Passing a promise to locals also waits for the promise to resolve

### ISSUE THREAD

**Issue by L3V147H4N** [angular/material#5066]
When passing a deferred.promise inside the locals Object the dialog doesn't open until the deferred is resolved and to my understanding of the API, that is the job of the resolve property.

**Comment by janesconference** [comment]
+ 1

**Comment by EladBezalel** [comment]
Can you please post a codepen so we can investigate it ?

**Comment by L3V147H4N** [comment]
Nevermind, it seems that the issue is caused by something else, I just tested the dialog in this codepen [codepen](http://codepen.io/anon/pen/yYZJwy?editors=001).

**Comment by theartofme** [comment]
Can this issue be re-opened? If you pass a deferred to the locals object it uses it as-is, but if you pass a promise it waits until the promise is resolved. This is why the codepen above does not reproduce the issue. Here is a fork of the codepen, passing `$q.defer().promise` to the dialog instead of `$q.defer()`: http://codepen.io/anon/pen/yVoGxv?editors=0011#anon-signup
