### ISSUE TITLE
md-datepicker crashes Safari on iOS v7.1

### ISSUE THREAD

**Issue by HaySayCheese** [angular/material#5080]
Angular Material version - 0.11.0
Device - iPhone 5s

**Comment by jelbourn** [comment]
@HaySayCheese I just tried this on an iPad with Safari on iOS 8.1 and everything was fine. Would you be able to provide additional information about whether this is just on the phone hardware, or perhaps just on iOS 7.1?

**Comment by ThomasBurleson** [comment]
@HaySayCheese - I just HAVE TO say that I love your Github name **and** the minion avatar. #awesome.

**Comment by AsifGouri1** [comment]
@jelbourn i am also facing similar issues. This issue is coming ion iOS 7 on iphone  and working fine on iOS 8 & 9. Can you please help me on this.

**Comment by naomiblack** [comment]
We are deferring this -- not because we don't believe it should be fixed but because we don't have a lot of expertise on iOS7 on the core team. Since this is working fine on iOS 8 and 9, most cases should be covered. If someone in the wider community is more familiar with iOS 7 and can help us to resolve, we'd love your help.

**Comment by HaySayCheese** [comment]
@ThomasBurleson ![Yeap!](https://s.tcdn.co/053/c88/053c8895-10cf-3599-8164-226dbdd9bb93/1.png)

**Comment by ThomasBurleson** [comment]
iOS7 is not supported.

**Comment by vijaysutaria** [comment]
Do we have any quick fix for this?
