### ISSUE TITLE
Virtual repeat and ng-class

### ISSUE THREAD

**Issue by ErinCoughlan** [angular/material#5115]
ng-class is not applied to virtual repeat when used multiple times.

I'm showing three panels next to each other, all using virtual repeat. I'm adding a class for the selected item in each column using ng-class, but the class is only applied in the first column. After clicking on another item in the panel, the classes are applied correctly to that panel.

**Comment by erinkidd01** [comment]
Quick follow up:

ng-class also has the reverse problem where the class is being applied too frequently. After some interactions with the three panels, I can end up with 2 "selected" classes applied to each column (and not on the items that should have been selected initially.

**Comment by kseamon** [comment]
Can you try out https://github.com/kseamon/material/tree/virtual-ng-class (The added virtual repeat demo: demoTestCaseNgClassRepeat). Not sure what magic sauce is causing your issue, but everything seems to be working in the version I made.

Can you poke around at it and see if you can bring about the bug? Thanks.

**Comment by uriva** [comment]
+1 I'm seeing this sometimes in 1.0.7 (can't reproduce)

**Comment by uriva** [comment]
for ng-show as well as ng-class

**Comment by bluebirdtech** [comment]
+1 I'm seeing ng-show and ng-class both (occasionally) not update correctly.

I also saw a problem when adding just class with an expression.  Eg. class="my-class-{type}".  The class for two types were present on the div where it was used.

It may be when scrollTop is updated directly on the scroller rather than scrolling manually, or at least that's when I observe the problem.

Swapping ng-show for ng-if seems to fix it for me in this case.
