### ISSUE TITLE
md-switch with ng-true-value

### ISSUE THREAD

**Issue by Eden-Sun** [angular/material#5152]
https://codepen.io/anon/pen/LpzGoV?editors=101
switch 2 did not changed with its value

**Comment by PDSBGreg** [comment]
This isn't a bug. At least not IMO. When you use ng-true-value and ng-false-value, those are the values the switch is looking for in ng-model to determine if it is on or off. Since you're just toggling true/false, it won't turn on because the boolean true does not equal 'yup'.

If you change your pen to toggle between 'yup' and 'nope' it works. See https://codepen.io/anon/pen/LpzRzK?editors=101

**Comment by Eden-Sun** [comment]
thanks
