### ISSUE TITLE
hide-gt-sm attribute not working

### ISSUE THREAD

**Issue by verkestk** [angular/material#5166]
This bug is visible on https://material.angularjs.org/0.11.2/#/layout/options.

As the screen resizes, the sibling element with the "show-sm" attribute appears and disappears as expected. But the "hide-gt-sm" element is always visible.

Tested in safari & chrome.

![screen shot 2015-10-14 at 1 52 10 pm](https://cloud.githubusercontent.com/assets/2700492/10494274/09155904-727b-11e5-8a8c-3970c25ab952.png)

**Comment by ThomasBurleson** [comment]
Thank you. We are aware of this issue and will continue to improve the Layout features during the next several weeks.

**Comment by m19** [comment]
```
    <div layout="column" hide show-gt-md>
    </div>
```

Want to confirm this div is hidden on my Macbook Pro Retina screen with latest Chrome. Upgraded from 0.10.1 to 1.0.0-rc1

**Comment by chrisguerrero** [comment]
@ThomasBurleson 

I'm experiencing the same issue after upgrading from v0.11.4 to v1.0.1. I use `md-layout-css` to disable the Layout JS engine per [#5020](https://github.com/angular/material/issues/5020):

http://codepen.io/anon/pen/JGrPgw

When `md-layout-css` is removed, the class selectors added by the Layout JS engine work as expected. I require the layout selectors in my app because I use the ngMaterial grid system on non-angular pages. Any chance we can get this added to an active milestone?

**Comment by chrisguerrero** [comment]
It appears as though the issue is an incorrect attribute selector in layout-attributes.scss:

https://github.com/angular/material/blob/master/src/core/services/layout/layout-attributes.scss#L434

Compared to the same class definition in layout.scss:

https://github.com/chrisguerrero/material/blob/master/src/core/services/layout/layout.scss#L67
