### ISSUE TITLE
md-tab title styling incorrect after 11.4 update

### ISSUE THREAD

**Issue by ajn0592** [angular/material#5194]
## The tabs went from looking like this:

<img width="886" alt="screen shot 2015-10-15 at 2 42 40 pm" src="https://cloud.githubusercontent.com/assets/8495667/10525610/4029df0c-734b-11e5-8645-6c9679d93d34.png">

## To this:
<img width="887" alt="screen shot 2015-10-15 at 2 45 03 pm" src="https://cloud.githubusercontent.com/assets/8495667/10525633/61e2beb6-734b-11e5-9b76-d145a96d3861.png">

**Comment by ThomasBurleson** [comment]
Fixed in master.

Whenever possible, provide a CodePen demo.

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.7** (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.
