### ISSUE TITLE
md-autocomplete + scroll

### ISSUE THREAD

**Issue by 0101adm** [angular/material#5230]
0.11.4

result box does not stick to element when window is scrolled.

![untitled screencast](https://cloud.githubusercontent.com/assets/5133412/10560668/827fd82c-74cf-11e5-8fb3-76ed0f4d5cb4.gif)

**Comment by Splaktar** [comment]
Also visible [here](https://material.angularjs.org/HEAD/demo/autocomplete) on HEAD.

**Comment by EladBezalel** [comment]
It may be a feature :sweat_smile::
On google sheets if you edit a cell and scroll down the edit is still available but it's mentioned there what cell you're editing and it's highlighted 
![](http://goo.gl/pSwg6q)

**Comment by flipvh** [comment]
We have started using angular material because it has some sweet components. Unfortunately there are some issues with overall behaviours, such as the one here. Since I think it is very difficult to solve all this consistently, on short term, and with a high level of success for all different ways you can build your (css) layout, a suggestion:

Why not provide us with some classes on the html or body element during an interaction with for example autocomplete suggestions instead of just adding css directly to the dom? This way we can at least solve most of these behaviour issues for our own situation? Until there is a great way to do it consistently within Material design layout.

Given that many people want to use angular-material components, I think it could be a great strategy to make it more easy to start without restricting them to use a rather opinionated way to build your higher level css layout/choices.

**Comment by DevVersion** [comment]
Fixes in #6589

**Comment by ANILKUMARSURYAVANSHI** [comment]
you can fix with style adding to css
.ui-autocomplete {
    position: relative;
}

**Comment by msd117** [comment]
> you can fix with style adding to css
> .ui-autocomplete {
> position: relative;
> }

Doesn't work

**Comment by msd117** [comment]
> Fixed in #6589

How to use PR in our code, I am using min.js file in my code is it possible to generate a min js file?

**Comment by alanrichards86** [comment]
Im using the latest version of material and I still have this issue @msd117

**Comment by Splaktar** [comment]
@msd117 this is fixed in AngularJS Material `1.1.0` (first version with the fix) and should be working in the latest release (`1.1.20`). You can find CDN links to the `min.js` and matching `min.css` files for `1.1.20` [here](https://blog.devintent.com/announcing-the-angularjs-material-v1-1-20-release-64848d0f328f).
