### ISSUE TITLE
md-fab buttons with md-icon have delay

### ISSUE THREAD

**Issue by super-coder** [angular/material#5235]
http://codepen.io/anon/pen/meqXyE 
When you click the button it takes a good half a second for it to disappear, so for half a second they are displayed together.
Observed only with `md-fab`

**Comment by EladBezalel** [comment]
Well there's something wrong in there,
But, i suggest you use animations and meaningful transitions like [this](http://codepen.io/EladBezalel/pen/bVYxeV), 
also, there's no need to hide and show another fab button, you can do something like [this](http://codepen.io/EladBezalel/pen/MaOqjm)

**Comment by super-coder** [comment]
Thanks but I just used thumb icon as an example. IRL I am using different buttons, one of which doesn't have ng-click, I am displaying thumb-up md-fab as a confirmation. 
So if this is a confirmed bug can it be fixed please?

**Comment by sebakerckhof** [comment]
This happens regardless of icons (without icons: http://codepen.io/anon/pen/jbxRbQ )

Ever since I've added angular-material to my project I've seen lots of this duplicate content issues with ng-if, ng-show/hide and ng-switch (also on non ngMaterial stuff). I've traced it back to ngAnimate which  creates duplicate content for animation purposes, although there's no animation happening ( https://www.google.be/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=off&q=ng+animate+duplicate+content )

**Comment by super-coder** [comment]
when will it be in the master?

**Comment by DevVersion** [comment]
Its already merged into master, you can build the current version yourself / it should be even on 1.0-rc3

**Comment by topherfangio** [comment]
@super-coder I just tested your Codepen real fast and it now appears to be working (unfortunately, we had an issue that causes the v0.11.x links to always point to master).

If you're still having trouble, please post here or open another issue and reference this one. Thanks!
