### ISSUE TITLE
Disabled input border-bottom misaligned

### ISSUE THREAD

**Issue by RolandHeath** [angular/material#5286]
The bottom border of input elements becomes misaligned by 1 pixel when disabled, as demonstrated [here](http://codepen.io/RolandHeath/pen/XmEeqB)

The fix is pretty simple, you can see it in #5283 
In the example plunk you can see it by uncommenting the reference to style.css

**Comment by lazychino** [comment]
@RolandHeath I'm having the same problem and I think the problem is in this [`margin-bottom: -1px`](https://github.com/angular/material/commit/8f2b2c6835feb151e362d9e135c795055f9a5ccd#diff-74a081d9d358e41d6c52623c1b29422dR205) assigned to the input elements when disabled 

I tested on Chrome and Firefox and removing this rule fix the border-bottom misaligned

**Comment by DevVersion** [comment]
@RolandHeath Thanks for your pull request :+1:, can u please reference that pull request / commit with that issue, the right guidelines for ```contributing``` can u find here. https://github.com/angular/material/blob/master/docs/guides/CONTRIBUTING.md#-git-commit-guidelines

**Comment by RolandHeath** [comment]
@DevVersion Hopefully that should fix it - I've changed the PR title and redone the commit to update the message. 
Let me know if it needs any more work.

**Comment by DevVersion** [comment]
Looks good to me :+1: Thanks for fixing it :)

**Comment by RolandHeath** [comment]
This issue seems to be solved in the latest version
