### ISSUE TITLE
md-select scroll in IE11

### ISSUE THREAD

**Issue by manuelmoyaroldan** [angular/material#5300]
Problem in IE11 with the scroll bar when md-select is displayed.

![image](https://cloud.githubusercontent.com/assets/8969503/10648382/59a9bc7a-783e-11e5-9154-73051412c7af.png)

**Comment by Patrik-Lundqvist** [comment]
What kind of problem? Please be more specific and read the [issue guidelines](https://github.com/angular/material/blob/master/docs/guides/CONTRIBUTING.md#submit)

**Comment by manuelmoyaroldan** [comment]
Sorry. What i mean is that when you open de options in a md-select component, a scroll bar is displayed in the body of the page, how you can see in the right side of the attached picture. This error is showed only in IE11.

**Comment by van88** [comment]
This is due to IE rounding up body.scrollHeight when body.height is a number with a fraction. 
You can see in the screenshots below.

![image](https://cloud.githubusercontent.com/assets/8953595/10806259/183778e6-7e28-11e5-9c9c-cba25fb3cd58.png)

![image](https://cloud.githubusercontent.com/assets/8953595/10806276/34e09d56-7e28-11e5-9ece-295c7ab70047.png)

I'm not sure what's the good fix for this. Adding 1 to body.clientHeight?
