### ISSUE TITLE
md-datepicker without extra css

### ISSUE THREAD

**Issue by Thomas-P** [angular/material#5309]
Hi,

would it be possible, to make the md-datepicker usable without using extra CSS to pass it into a form?
If we use it without css, ng-messages is displayed in an ugly way, but also the datepicker hasn't the right margin/padding. So an input and a datepicker are not in line.

http://codepen.io/anon/pen/QjQygj

**Comment by bastienJS** [comment]
I experienced the same behavior. The md-datepicker  is the most inconsistent control of all material design controls IMHO.

Here are FOUR bugs:

![image](https://cloud.githubusercontent.com/assets/5945955/10712660/ad158024-7aa0-11e5-943a-54fa9701b7d9.png)

- White background?
- Not aligned to other controls
- Triangle/arrow should have black color
- Transparent background above/below the data string

![image](https://cloud.githubusercontent.com/assets/5945955/10712670/5bcb89ec-7aa1-11e5-907d-b5fa8ce9e72b.png)

Check this codepen with latest version 1.0.0-rc1:

http://codepen.io/helloworld/pen/NGYxKo

**Comment by ejbaker** [comment]
+1

This is definitely still happening as of 1.0.5. It happens because all of the Material themeing CSS expects errors to be inside of md-input-container, with which the md-datepicker is not compatible.

CodePen: [here](http://codepen.io/ejbaker/pen/obOXmY?editors=1010)

I'd like to _add_ that custom CSS on the user end isn't actually enough to fix all of the problems this causes.

- because the ng-invalid errors for datepicker are applied to md-datepicker, rather than a parent element, they don't get automatically inherited by ng-messages. I've tried to work around it by using adjacent sibling selectors, but this is fragile.

- we're missing out on not just colors and font sizes, which should ideally be kept *out* of the end user's CSS when they're using a theme -- but also on animations. Where's our graceful slide-down? And even if I add that myself, that's *also* fragile, since supposing a future Angular Material version changes the animation in some way? Now I'm in an unnecessary Red Queen's race trying to match styling.

I notice that md-select has its own separate ng-messages styling. Why can't md-datepicker get the same love?
