### ISSUE TITLE
similar class to md-primary for non-angular-material elements?

### ISSUE THREAD

**Issue by happschinson** [angular/material#5332]
Hi!

Are the colors defined by an angular-material-theme available for regular html elements as well?

let's say I have

`<div class="md-primary-background">This Element will have the primary color as BACKGROUND color</div>`

Is something like that already implemented, or are there any plugins for that?

**Comment by wthomsen** [comment]
As far as I can tell, generally no, Angular Material doesn't have atomic css classes like what you described.

It would be a helpful shortcut, but it's dangerous. If you have descendants of that div that are themed, they could be themed incorrectly (e.g., a primary button would look transparent against a primary background that was declared atomically).

It seems the correct way to do this is to define a separate theme that uses your primary color for the background palette, then use something like `<md-content md-theme="primaryInverse"></md-content>`.

**Comment by Todd-Werelius** [comment]
@happschinson [1599](https://github.com/angular/material/pull/1599) and [1269](https://github.com/angular/material/issues/1269) addresses this

They intend to add support for accessing theme colors, the work has been done, but it hasn't been checked in yet, I think it's waiting from someone to write a test script

**Comment by happschinson** [comment]
@Todd-Werelius 
awesome, thanks!

**Comment by PieterGoethals** [comment]
Been toying around with the same issue last weekend.

I got inspired by SanderElias'es work here:
https://github.com/angular/material/issues/1269

I particular like the way how he generates css once, 
after which no js burden is placed on the browser.

My major issues with his code was how he uses palette's 
and specific hues instead of themes. 

I dont want classes like 'md-fg-100', I want 'md-bg-primary'.

Here is my take on it:

http://plnkr.co/edit/QHIZgiOhhffLF0uQXkFb?p=preview

The first block shows all classes using the default theme.
The second block shows how all classes change using a specific theme.

In your example you could use the class md-bg-primary,
which would also apply the default foreground color.

The theme-specific example does assume the class 'md-theme-theme' 
gets applied either to the element itself, or an ancestor of the element.
Angular Material does this on md- elements, however on others 
you might have to do this yourself.

Unfortunately I'm rather new to angular, so I couldn't make
my code integrate as nicely as he did. I could copy-paste 
part of his code, and probably get it to work, but i'm not 
fond of using code I don't understand.
