### ISSUE TITLE
flex="initial" and flex="auto" calculate wrong width when shrinking in 1.0.0-rc1

### ISSUE THREAD

**Issue by Dotneteer** [angular/material#5347]
Take a look at this code snippet:

```html
<div layout="row">
  <div flex="initial" style="width: 400px">
    initial
  </div>
  <div flex="25">25%</div>
</div>
<div layout="row" style="margin-top: 24px;">
  <div flex="auto" style="width: 400px">
    auto
  </div>
  <div flex="25">25%</div>
</div>
```

It works great while screen width is 533px (flex="auto" and flex="initial" cells are exactly 400 pixels), and it still works OK when the screen width is higher, the 25% cells are calculated properly. For example, in 1920px  screen they are 480px. However, when you shrink the screen, cell widths are calculated improperly. In a 400px wide screen, 25% cells are 82px, initial and auto cells are 318px.

Here is the CodePen: http://codepen.io/pen?template=qOoBRO

**Comment by Splaktar** [comment]
Which browser are you getting those calculations from? The numbers are slightly different in Chrome on OS X. 

Once you get to that smaller resolution, the initial and auto divs are shrinking below 400px to accommodate the flex-25 divs. These flex-25 divs are also shrinking some due to the limited space. 

In this case, both elements are giving up some of their space. The flex-25 div does not stay at 25% and force the 400px div to be the only one that shrinks.

This is as designed atm, but I guess that the docs are not fully clear on this. They say:

`The element will stretch to the percentage of available space matching the value.`

It doesn't also call out that the % based flex element may also shrink if needed.

**Comment by Dotneteer** [comment]
I used Chrome and Edge on Windows, both produce exactly the same result. The phenomenon may be a feature and not a bug, nonetheless, I have not managed to find info about why the flex-25 divs do not keep their ratio.
As I imagine, while giving up some of their place, both the auto/initial and the flex-25 divs could shrink so that the flex-25 keeps its size 25% of the available row width.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
