### ISSUE TITLE
md-dialog not working correctly.

### ISSUE THREAD

**Issue by CrackerakiUA** [angular/material#5368]
In the controller of that dialog i have something like this: `angular.element(document.querySelector('#fileInput')).on('change',handleFileSelect);`
and `#fileInput` is inside the templateUrl file. When i am just calling it, controller don't see html's id. It's only working when i put it inside an timeout.

**Comment by EladBezalel** [comment]
Can you please post a codepen so we can investigate more?

**Comment by CrackerakiUA** [comment]
http://codepen.io/Crackeraki/pen/dYmBmM?editors=101
in controller of the dialog i show you with comments which is not working and which is working.
Basically the code inside timeout is working, so i believe html is loading after controller.

**Comment by bolerodan** [comment]
You generally do not want to do any DOM work, within a controller like this (barring directive controllers, exception to all rules).

You want to make your "cropped image" stuff into it's own directive, where the Link Function, within the directive, has access to the ready and compiled elements. Because In your situation, the dom just isnt quite ready.

Check out my fork. I created a directive and put in your "image crop" specific stuff, pass in some variables so you can access them outside of the directive if need be.

http://codepen.io/anon/pen/wKjvLX

**Comment by CrackerakiUA** [comment]
So, best option will be to wrap input file inside this plugin?

**Comment by EladBezalel** [comment]
@CrackerakiUA as @bolerodan said, DOM manipulation in a controller is a big no no.
You should absolutely create a directive that wraps your functionality.

But if you do want to keep it in a controller, a timeout is required to let your code run in the angular loop.

Hope you got your answer.
