### ISSUE TITLE
Documentation: default to current release instead of upcoming release?

### ISSUE THREAD

**Issue by bathos** [angular/material#5401]
The documentation pages seem to default to the (unreleased) release candidate. While working with mdDialog it took me a while to figure out that the errors I was getting using 'openFrom' and 'closeTo' were occurring because those methods actually don't exist yet. Although it's cool to see what's coming, it seems like it would be more helpful to devs if the docs defaulted to the current release instead of the "coming soon" release.

**Comment by bastienJS** [comment]
+1

**Comment by ThomasBurleson** [comment]
The docs default to "Latest" release not HEAD. And the "latest" === 1.0.0-rc1.

![screen shot 2015-10-28 at 5 15 51 pm](https://cloud.githubusercontent.com/assets/210413/10804836/a631284a-7d97-11e5-80d4-306dc073c506.png)


Since our docs support previous versions, the developer must make sure they are reading the correct version. Do you have any suggestions on how to avoid future confusion(s)?

**Comment by bathos** [comment]
I think it's great that all versions are documented, @ThomasBurleson. I agree that it makes sense to default to the lastest release. However I'm confused by how "latest release" is defined. I figured a release *candidate* is so named to say "I might end up being a release, but I'm not yet -- we're still testing." That could be a misunderstanding of the terminology on my part, but even if so, the rc isn't available on npm. Installing angular-material@latest gets you 0.11.4. (Maybe that's the real issue?)

**Comment by ThomasBurleson** [comment]
@bathos - You have a valid argument that I did not consider. Let me talk with the team... and reply with more details soon.

**Comment by ThomasBurleson** [comment]
Fixed.
