### ISSUE TITLE
Error on Autocomplete Demo

### ISSUE THREAD

**Issue by rhllor** [angular/material#5424]
Hi, 
I don't understand how use mdAutocomplete and mdNotFound with clickable item into mdNotFound.
On Demo(1.0.0 RC1) the link is clickable and working but on codepen the link is not clickable. If i use the exemple on my project ng-click don't work as codepen. 

Any Issue for this problem? 
Regards

**Comment by topherfangio** [comment]
It is broken on the Codepen because our links unfortunately always point to HEAD/master (this issue will be fixed in the next release). So, this is an actual/reproducible bug on both HEAD and the codepen.

We will investigate.

@robertmesserle Any chance this has something to do with the changes you made for the IE scrollbar fix?

**Comment by robertmesserle** [comment]
Seems unlikely, but it's possible.

**Comment by rhllor** [comment]
Thanks all for reply

**Comment by topherfangio** [comment]
I don't believe this was actually fixed by 5ae3d4c, I need to find a different solution and/or do some more testing to ensure the fix I had in mind doesn't break anything in IE.

**Comment by topherfangio** [comment]
I'm going to go ahead and bump this to RC5 so that I can test it more thoroughly when I get back to my IE machine.

**Comment by DevVersion** [comment]
Is this related to #5526?

**Comment by rhllor** [comment]
yep
