### ISSUE TITLE
md-slider + md-slider value bind bug

### ISSUE THREAD

**Issue by oivonin** [angular/material#5512]
md-slider + md-slider. Second slider depends on the first slider's value. If you slide from the left to the right and than back to the left slider's thumb position and slider's width are wrong.
CodePen example - http://codepen.io/anon/pen/rOrmqy

**Comment by EladBezalel** [comment]
@oivonin I can't understand why the thumb position is wrong?

If you will set the first slider on 100 than by your calculation the second slider should have 200,

The minimum value of the second slider should be 90 (`0.9 * 100`) and the max value 650 (`6.5 * 100`)
Your 100% is 560 (`650 - 90`) and the thumb position according its value (`200`) should be approx 20% from the left (`(200 - 90) / 560`) which is the applied percentages, from your codepen:
``` html
<div class="md-thumb-container" style="left: 19.8214%;">
```

**Comment by RolandHeath** [comment]
@EladBezalel While I think it's mostly due to the maths being done here, I do notice some odd behaviour if I move the top slider with the keyboard with the following steps:

1. Move up from 1 to 5 (seems ok, position ~18%)
2. Move to 6 (Jumps a bit, position ~21%)
3. Back to 5 (position now at around ~20%, not ~18%)

Not sure if it's a bug, but it seems like it should converge on the same value from either the left or the right.

**Comment by EladBezalel** [comment]
This is caused by the default step and your min/max calculation, you multiply the value from the first slider by two but the min/max is multiplied by rational number, this causing your value to be natural but the actual values are rational.
