### ISSUE TITLE
Can't get $mdIconProvider to work with mdi's SVG

### ISSUE THREAD

**Issue by xenit-raven** [angular/material#5514]
I'm trying to figure out how I can use the awesome [`mdi` package](https://materialdesignicons.com/) with the `angular-material` `md-icon`. Ideally I'd be loading in SVGs through the `$mdIconProvider` (first row in example) but that fails (first row, first icon). Alternatively I could use the web font, but that also doesn't seem to work (second row)

I've provided a set of examples I've played around with in this codepen:
http://codepen.io/anon/pen/GpBjWm

**Comment by DevVersion** [comment]
I think that's not the right section to ask for your personal questions.

**Comment by Todd-Werelius** [comment]
@xenit-raven 

What you are trying to load is a svg FONT, not a icon set of svg's, which is why your call for Row-1/Col-1 is not working 
```javascript
.defaultIconSet(...)
```

I got the other ones working by using these syntax's apparently you need both classes to make this work
```html
<md-icon id='icon' md-font-icon="mdi mdi-bell"/>
<md-icon id="icon" class="mdi mdi-bell"></md-icon>
```

The only thing I could not get to work was the ligatures, but looking at their website I don't see any mention or examples of using ligatures. 

Modified [codepen](http://codepen.io/Mopholo/pen/avRdPe?editors=100)

Don't think this is a bug

**Comment by programmist** [comment]
@Todd-Werelius.  That's right - This is a a misunderstanding of the API, not a bug. Thanks for your help!
@xenit-raven: You can find `mdIcon`-related documentation here.

* [`mdIcon` demos](https://material.angularjs.org/latest/demo/icon)
* [`$mdIconProvider` Service API](https://material.angularjs.org/latest/api/service/$mdIconProvider)
* [`$mdIcon` Service API](https://material.angularjs.org/latest/api/service/$mdIcon)
* [`mdIcon` docs](https://material.angularjs.org/latest/api/directive/mdIcon)

Thanks.

**Comment by xenit-raven** [comment]
Update: MDI has provided an alternative .svg set that is compatible with the format that $mdIconProvider can use:

https://github.com/Templarian/MaterialDesign/issues/854
