### ISSUE TITLE
md-fab-toolbar not rendering properly

### ISSUE THREAD

**Issue by jex310** [angular/material#5519]
I copied the codes in [demo](https://material.angularjs.org/0.11.2/#/demo/material.components.fabToolbar) but the ui is not rendering properly in my local.

Here are my codes
http://codepen.io/jex310/pen/QjBmdG

here's the screenshot
![image](https://cloud.githubusercontent.com/assets/12663043/10907748/ec5571b6-81fa-11e5-9e10-7f2a1eb33bfe.png)

**Comment by mckenzielong** [comment]
Just a heads up that the codepen you provided links two different versions of angular material (0.9.4 for css and 0.11.2 for js)  Here is an updated version of your pen (still broken) running master:

http://codepen.io/mckenzielong/pen/vNarXd

**Comment by jex310** [comment]
So this means md-fab-toolbar is really broken right now? But how come the demo is working properly?

**Comment by topherfangio** [comment]
@jex310 Here is an altered version of your Codepen that fixes the positioning issues (although it looks like some other issues remain): http://codepen.io/topherfangio/pen/GpwMVx?editors=100

Some notes on what I changed:

* First, I changed the direction to just `left` instead of `md-left` as this is what is supported.

* Second, I removed the `class="md-fab-bottom-right"` from the trigger. You CAN put it on the `<md-fab-toolbar>` element, however, I don't think that's actually going to do what you want as it makes the toolbar appear detached (`20px` bottom and right) from the sides of the page. Now that I think about it, these classes don't make a whole lot of sense at the moment, so we may remove them from the docs until we can position the trigger separately from the toolbar (right now, it's all one component).

* When using those positioning classes, they use `position: absolute;` for their styling, so it is important to have them as a child of the proper container. You can see that I have moved it to almost the top-level so that the `<md-content>`s aren't a wrapper as they use `position: relative` which will cause the toolbar to be positioned relative to it.

* I've fixed some issues with your layout by using the `layout-fill` attribute in appropriate places so that your containers take up all available height.

It looks like there are still a few things that may need to be fixed, and we may need to update/alter the docs to talk about the positioning, but hopefully this will get you on the right path.

**Comment by EladBezalel** [comment]
@jex310 I also was able to [produce](http://codepen.io/EladBezalel/pen/xwMWOG) the wanted result

If there's a specific bug/issue please tell me and i will reopen this.

**Comment by topherfangio** [comment]
I created a separate issue for the fab classes being confusing here: #5657.
