### ISSUE TITLE
d3 rendering on md-tab not working

### ISSUE THREAD

**Issue by groupsvkg** [angular/material#5539]
Hi Team,

I am trying to render svg elements via d3 inside md-tab.

But rendering is not working.

codepen - http://codepen.io/groupsvkg/pen/XmBvEL

![image](https://cloud.githubusercontent.com/assets/366335/10935138/05c7a668-830a-11e5-99a2-bb242ca46e27.png)

Regards,
vishal

**Comment by epelc** [comment]
@groupsvkg You need to delay your d3 code because the tab content isn't created until slightly after your controller runs. I've added a `$timeout` to demonstrate that it does work if you wait for the tab to be created.

Demo with delayed d3 execution(see the `$timout`)
http://codepen.io/anon/pen/epLNVZ

For prod you'd probably want to just move your controller inside the tab so your d3 code can run after the tab is created automatically. Also a directive may work even better for this.

**Comment by groupsvkg** [comment]
thanks for the solution  @epelc . I have checked codepen and its working fine!!!

**Comment by epelc** [comment]
Please note it may/may not work depending upon how fast the users computer is. I set the timeout at 1 second. But you should really use either the controller in the tab, or directive method.

**Comment by groupsvkg** [comment]
:+1: 

Thanks again @epelc  .....one last thing how did you figured it out that this is the problem?

**Comment by epelc** [comment]
@groupsvkg You just have to think of the order in which things are run. Generally controllers/directives which are higher up the html node chain run first. In your case your `ng-controller` was running(attempting to do d3 stuff) before the tab controller got to run(iirc I think the directives do certain steps first(part of the linking process) even if they are lower down the chain).

You could also easily see this if you put a break point just before your d3 selector then take a look at the html and see if what your about to select is there.

**Comment by rafagarcia** [comment]
Finally i managed to solved my issue by adding a timeout to my graph constructor method. This thread has been useful to me. Thanks.
