### ISSUE TITLE
md-button stays focused after a click

### ISSUE THREAD

**Issue by PaulMougel** [angular/material#556]
After clicking or touching on a `<md-button>`, it stays focused, both on latest Firefox, Chrome, mobile Chrome and mobile Safari (see the  [demo page](https://material.angularjs.org/#/demo/material.components.button)). Only by clicking somewhere else will the button loose focus. Is it the intended behavior?

Screenshot in latest Chrome stable, on Mac Os Yosemite, on the demo page:
![untitled](https://cloud.githubusercontent.com/assets/1788596/4944296/49b32bbc-65fc-11e4-91d7-873f0f6a3c95.gif)

**Comment by caok2709** [comment]
Does anyone know how to disable md-button hover effect?

**Comment by vas1468** [comment]
.md-button:not([disabled]):hover {
    background-color: transparent;
  }

**Comment by ananyaojha** [comment]
What's the exact solution to this issue? I'm still getting this in my application. When switching tab and coming back to application, button is still showing active.

**Comment by simhnna** [comment]
@marcysutton I think this issue should still be open. The linked issue has been closed without a resolution to this one...

**Comment by marcysutton** [comment]
@simhnna I don't work on Angular Material anymore, but I'd recommend looking into the proposed <a href="https://github.com/WICG/focus-visible"><code>:focus-visible</code> CSS selector</a> or the [What Input](https://github.com/ten1seven/what-input) JavaScript library. I lovingly refer to this problem as <a href="https://marcysutton.com/button-focus-hell/">Button focus hell</a> because it isn't easy to solve in a way that supports all users. However, the aforementioned projects can help provide more styling hooks based on the user's input modality.

**Comment by Splaktar** [comment]
@AngelQuirogaM Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.

**Comment by marcysutton** [comment]
@AngelQuirogaM the problem with that CSS is you're hiding the visible focus state, which means keyboard users can't see where we are on the screen (a huge accessibility/usability problem). It doesn't get at the core issue, which is that mouse users don't like the persistent focus state. See my above comment for a better way forward.
