### ISSUE TITLE
md-select change name attribute on form submit

### ISSUE THREAD

**Issue by Asoseil** [angular/material#5575]
On form submit, md-select add a point before the attribute name: 
md-select(name='test')
on submit change in .test

**Comment by Arf291** [comment]
Hello, I know this issue is closed, but I'm experimenting this problem and I would like to know if it has been solved in some concrete release.
 
Thank you very much.

**Comment by zeroblaz3** [comment]
I am experiencing the same issue. I have an md-select element with attribute name="state" but I can confirm the name is passed as ".state" in the URL is received as "_state" in the server side PHP code. I also see my value passed as "? string: FL ?" when it should just be FL. It seems that there is very little support or detailed documentation. Is this library production ready?

**Comment by ThomasBurleson** [comment]
@Arf291, @zeroblaz3 - please open a new issue with:

Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.
