### ISSUE TITLE
Ui-sref on list item breaks design

### ISSUE THREAD

**Issue by gpopovic** [angular/material#5608]
When using ui-sref instead of ng-click od list item, design is broken.

**Comment by jpike88** [comment]
workaround: use ng-click with $state.go

**Comment by gpopovic** [comment]
By doing that i'm loosing benefits like (open in new tab, open in new window...etc)

**Comment by byronh1016** [comment]
I've also seen this issue on md-buttons when using an icon. The icon appears above center from what I can tell
![off-center-fab-icon](https://cloud.githubusercontent.com/assets/2721034/11064495/7ce2f75e-878b-11e5-9bad-009b14bee70f.png)

**Comment by gpopovic** [comment]
Still not fixed in rc4

**Comment by Supratentorial** [comment]
I believe I am experiencing the same issue. I will provide additional detail.

In commit f8a8b3c md-list-item was fixed so that ui-sref attributes were recognised for compatibility with angular-ui-router. This was done to match the behaviour when a ng-click attribute is added to a md-list-item: you get a cursor on hover, and a ripple on click.

Currently, when I add an ui-sref attribute to a md-list-item, I can see that a nested anchor is created with the class md-button. The issue is that the anchor has horizontal margins of 8px and vertical margins of 6px. Thus, the ripple does not extend to the edges of the md-list-item. This is inconsistent with the behaviour of adding an ng-click attribute which does not result in these margins.

I suspect that the likely culprit is the md-button class which is added to the anchor. It adds the horizontal and vertical margins.

**Comment by ruant** [comment]
+1 for this.

**Comment by kaumac** [comment]
+1!
Not being allowed to use ui-sref brings a lot of headaches.
If we use ng-click with $state.go then we can't use ui-sref-active to highlight the active item, then we need to manually check the current state and do all the logic that ui-sref-active does.
We need to do a lot of workaround for something that should be simple.

**Comment by DevVersion** [comment]
@kaumac @gpopovic I'm trying to dive into this, but I can't reproduce the actual problem in master. Can someone of you create a little demo? (codepen etc.)

**Comment by gustavohenke** [comment]
@DevVersion I think the problem is the following: http://codepen.io/gustavohenke/pen/NxVBqM

**Comment by DevVersion** [comment]
@gustavohenke Your demo isn't showing any issue, but I took the time to built it myself. 
-  http://codepen.io/DevVersion/pen/wMLNOJ

I think I can see what the issue is.

**Comment by DevVersion** [comment]
**Update**
- There is already a PR pending, which is fixing that issue. See #6496

![](https://i.gyazo.com/c6d94dc8e40cabf58ef336356df5f1fe.png)
