### ISSUE TITLE
Elements in md-fab-actions can not be hidden using ng-show/hide in FAB Speed Dial

### ISSUE THREAD

**Issue by mbellezi** [angular/material#5651]
If some elements in the md-fab-actions of the FAB Speed Dial are optional (shown or hidden using ng-show/hide) they do not hide properly. They stay visible below the fab trigger.

1.0.0-rc3

See the codepen:

http://codepen.io/mbellezi/pen/epQRQv?editors=100

**Comment by topherfangio** [comment]
Yup, looks like the speed dial doesn't account for hidden elements when calculating positions. Should be a reasonably easy fix.

**Comment by epelc** [comment]
@topherfangio it also doesn't work with `ng-if`

**Comment by topherfangio** [comment]
@epelc Interesting; I would have assumed that `ng-if` worked since it removes it from the DOM. I'll definitely take a look.

**Comment by epelc** [comment]
@topherfangio I just looked a bit more and it only seems to happen if your `ng-if` is false on one of the top buttons. If you put it on the bottom one(closest to the large toggle fab button) then it doesn't push the elements below it.

ng-if on top [demo](http://codepen.io/anon/pen/mVegpG)

ng-if on bottom [demo](http://codepen.io/anon/pen/advxqW)

Note you have to turn the fab on/off to see it since your fix for the animations didn't get into rc7

**Comment by epelc** [comment]
I think I got top/bottom messed up. Please read it in the context of the html of your buttons. ie top would be the first button in your html. Bottom would be the last.

**Comment by topherfangio** [comment]
Ah, I see the problem indeed. The real issue is that we create a wrapper around your elements, but we don't copy directives like `ng-if` or `ng-hide` to the wrapper, so the wrapper is always visible.

_Note to self: We could potentially copy all of those directives to the parent, but it may be simpler if we just have the wrapper check for children and their visibility._

**Comment by badcoder28** [comment]
I found this issue when `md-mode` is selected to `md-fling` and there works well with `md-scale` there might be a bug in the animation.
