### ISSUE TITLE
$mdToast broken when bootstrapped inner div element

### ISSUE THREAD

**Issue by yoorek** [angular/material#5745]
After upgrading to 1.0.0-RC4 all my toasts are broken.

It appears that they work when app bootstraps on `html` or `body` element by when it bootstraps component of inner `div` the toast is broken (position top left outside of viewport and it's almost invisible, flashes for a second of animation).

Here is JSBin sample : https://jsbin.com/liwoje/edit?html,js,output )

**Comment by yoorek** [comment]
As a workaround : `toastPreset.parent(document.body)`, but with that animation is not working (another bug or feature?)

**Comment by EladBezalel** [comment]
The problem in your demo is that the div has no height therefore the toast has no place to be shown.

also your'e showing the toast before the DOM loading is finished, that's why you don't see the enter animation.

here's a [Codepen](http://codepen.io/EladBezalel/pen/GpzdoY) with toast that loads on start and on the div. 

Closing for now as i don't see this as an issue, just layout misunderstanding. If you haven't got your answer yet or I didn't understand you well please tell me and i'll reopen this issue.
