### ISSUE TITLE
$mdDialog emitting warning for being used in a scrolled context, but component is working correctly

### ISSUE THREAD

**Issue by ErinCoughlan** [angular/material#5769]
Warning: `<md-backdrop>` may not work properly in a scrolled, static-positioned parent container.

The dialog parent is $rootElement in the app. (This was necessary to allow animations to occur in the dialog.) The $rootElement is a layer above the header, which is where the dialog is created. The DOM looks like this:

```html
<div id="header">
  <md-backdrop class="md-dialog-backdrop md-opaque ng-scope md-ga-theme" aria-hidden="true"
  </md-backdrop>
  <div ui-view id="content" class="ng-scope">...</div>
  <div class="md-scroll-mask" style="z-index: 50" aria-hidden="true">...</div>
  <div class="md-dialog-container ng-scope" style="top: 0px; height: 620px;">...</div>
</div>
```

Despite this warning, the backdrop completely covers the full page of the app and clicking anywhere in the app dismisses the dialog, as desired.

The header div has a height and width set based on the content in the ui-view, even though the backdrop is larger than this height. If the content in the ui-view gets larger, this height will increase to accommodate, not adding any scrollbars.

**Comment by jelbourn** [comment]
@topherfangio would you have time to look into this?

**Comment by erinkidd01** [comment]
The problem was that is was throwing a warning but everything is functioning correctly, which seems odd. We can't have any warnings or errors in our apps and every time someone interacts with the dialog, they get this warning.

I'll look into seeing if I can change the positioning, but the component is embedded in another application not using Angular, so I'm not sure of the side effects there.

**Comment by topherfangio** [comment]
@jelbourn Perhaps this should be an info message rather than a warning? It does seem a bit harsh to throw a warning when the user might not have done anything wrong...

**Comment by jelbourn** [comment]
@topherfangio There are a couple teams at Google that build a library on top of ng-material that multiple products then consume. If that library generates a bunch of spurious warnings, it's a worse dev experience for people downstream.

**Comment by erinkidd01** [comment]
@topherfangio The component breaks if we set the position to relative. You mentioned the backdrop is using the first non-static parent, which in our case would be the body because all elements above the header are statically positioned. This is the behavior we want as it allows the dialog and backdrop to appear above the rest of the content on the page even though the $rootElement is a few levels in. If we use position: relative on the $rootElement (dialog parent), the backdrop is over that element, but that's only the header in the app, not the entire page. We cannot set the dialog parent to the body because it breaks animations. ngAnimate only allows animations if they are within the angular app, which for this product is not the body.

I realize this is getting a bit confusing because the $rootElement is not the body or html tags, like in most angular apps. It's on the header element. The angular code is embedded in a different framework, similar to the way Angular 2 would be embedded in Angular 1.

**Comment by topherfangio** [comment]
So, the backdrop specifically uses `$animate.pin()` to enable animations outside of the `$rootElement`. As far as I can tell, the dialog does not; so perhaps this is the real issue that we need to address.

That said, I still feel like the warning is out of place. Perhaps we could remove it from the code and update the dialog docs with an important note with the same info and a bit more description?

@jelbourn Thoughts?

**Comment by jelbourn** [comment]
@topherfangio I would be amenable to that. Having a warning for something that _might_ not work correctly is questionable.

**Comment by erinkidd01** [comment]
@topherfangio I like the idea of adding $animate.pin() to the dialog. That was one of the initial plans to get the component to work with animations in multiple products, but that behavior was outside our control and changing the dialog parent was the easier solution over changing material.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
