### ISSUE TITLE
<input> loses focus on each entered character when inside ng-repeat

### ISSUE THREAD

**Issue by djmarcus1** [angular/material#5798]
I have a simple `<input ng-model="...">` inside a `<div ng-repeat="...">`

As soon as I type a character the focus is lost. To continue typing I first have to click inside the input area for **each** character I want to enter.

An `<input ng-model="...">` not in the scope of ng-repeat works fine. I can type characters and backspace all day long.

The essence of the `ng-repeat` code that shows the problem is:

    <div ng-repeat="item in items">
        <input ng-model="items[$index]">
    </div>

However, an `<input>` inside the ng-repeat scope but which *does not* directly reference the `ng-repeat` array, works fine - I can enter data all day long. For example:

    <div ng-repeat="item in items">
        <input ng-model="george">
    </div>

**Note**: the problem is clearly related to the the ng-model referring directly to the $index-th element in the items array. My guess is that a $watch on the collection is triggered and that causes the loss of focus.

Here's a codepen that shows the problem:
    http://codepen.io/djmarcus/pen/bVZGvj

Here's a distillation:

    <div ng-controller="myCtrl">
        <div ng-repeat="item in items">
          <div>This fails</div>
          <div layout="row" layout-align="start center">
            <input ng-model="items[$index]"  label=""> 
          </div>
        </div>

        <div ng-repeat="item in items">
          <div>This works</div>
          <div layout="row" layout-align="start center">
            <input ng-model="george"  label=""> 
          </div>
        </div>
       
        <div>This works (its outside of ng-repeat) </div>
        <input ng-model="harvey" label="">
      </div>

**Comment by EladBezalel** [comment]
@djmarcus1 how's that exactly related to Angular Material project?

**Comment by djmarcus1** [comment]
Good point... I will resubmit this to the AngularJS group (unfortunately, the line between the two appears rather blurry).

**Comment by abhi9bakshi** [comment]
If you stumbled upon this thread and are looking for a solution in Angular 2, the solution is quite simple.
Instead of two way binding with the array, only bind the property and handle the change event using 'change' event instead of 'input'

Example:
```
// Instead of writing
<div *ngFor="let param of params.value; let id = index;">
    <input type="text" placeholder="0" [(ngModel)]="params.value[id]">
</div

// Write
<div *ngFor="let param of params.value; let id = index;">
    <input type="text" placeholder="0" [ngModel]="params.value[id]" (change)="onValueUpdate($event, id)">
</div>
```
and update the value in onValueUpdate function.

Since the change event triggers only when you blur from input, your will not face the error anymore.

**Comment by OlivierHokke** [comment]
I was having this same problem. The solution by @abhi9bakshi did not work for me all the time. Switching between input fields sometimes caused the input focus to (seem to) switch to one I didn't click on, and fill in other empty input fields.

My case: I had the problem because I was two-way-binding elements in an array of strings, but also binding to those of a different array that had the same size. (each element was linked as a values/options pairing). I think ngFor has issues tracking each element since they were primitive types.

How I solved this was not to define the arrays like this:
`values: string[];
options: string[];`

but like this:
` options: { value: string, option: string }[];`

Now the linking is object based, and caused no problems whatsoever
