### ISSUE TITLE
mdDialog not displaying contents

### ISSUE THREAD

**Issue by f1tech** [angular/material#5817]
Up until RC4 this function
```javascript
 function displayFile(data, fieldName) {
            var fileContent = eval("data." + fieldName);

            if (!fileContent) {
                fileContent = fieldName + " does not contain any content.";
            } else {
                if (String(fieldName.toUpperCase()) !== String("FILE_CONTENTS")) {
                    var x2js = new X2JS();
                    fileContent = JSON.stringify(x2js.xml_str2json(fileContent));
                }
            };
            var myAlert = $mdDialog.alert({
                title: data.FILE_NAME,
                content: fileContent,
                ok: 'Close'
            });
            $mdDialog
                .show(myAlert)
                .finally(function () {
                    myAlert = undefined;
                });
        };
```

was working properly. fileContent contains a long string that is either XML that gets converted to JSON or simply a string. The debugger shows the expected value for fileContent.

**Comment by adefran83** [comment]
In the changelog for RC4 they specifically mention this... 

Breaking Changes

Dialog presets for alert and confirm no longer have a content option. There is now textContent and htmlContent. In order to use htmlContent you must load the ngSanitize module. HTML will not be compiled as an Angular template to prevent XSS attack vectors.

**Comment by f1tech** [comment]
Thanks
