### ISSUE TITLE
Combination of row layout, flex, and wrap not working correctly

### ISSUE THREAD

**Issue by allan-lewis** [angular/material#5876]
I have 3 divs in a row layout set to wrap with a flex-gt-sm value of 50 and a flex-gt-lg value of 33.  In a large mode, things work as expected with the 3 elements displayed in a row.  In a medium layout, I'd expect the first 2 two to take up 50% of the view on one row, with the third taking up 50% on a second row.  Instead, the third wraps to a new row as expected, but takes up 100% of that row.

This works as expected in 0.11.4, seems broken in 1.0.0-rc4

Codepen below:

http://codepen.io/anon/pen/PPgLbG

**Comment by allan-lewis** [comment]
![screen shot 2015-11-23 at 2 47 29 pm](https://cloud.githubusercontent.com/assets/1211647/11347843/3719e988-91f1-11e5-97f8-75bb877dfb86.png)

**Comment by allan-lewis** [comment]
Sorry, one last edit.  If I add another empty div with a flex of 50 things render as expected.  Good enough for now, but seems that what I had in the codepen should have done it, as well

**Comment by dcarey** [comment]
+1

**Comment by ThomasBurleson** [comment]
MediaQuery notifications are dispatched for 'enter' and 'leave' activity. The issue is overlapping breakpoint regions which are both active at the same time. Consider:

```html
<div flex flex-gt-sm="50" flex-gt-md="33" class="one">
```

When the window horizontal size shrinks to less than 1280 pixels, a 'leave' notification is dispatched for **flex-gt-md**, bu a 'enter' or activate notification is not properly triggered... because they overlap and it already entered once before.

>  This has been fixed in the new generation-2 Layout engine that will be available after v1.0.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
