### ISSUE TITLE
Full height layout is broken (?)

### ISSUE THREAD

**Issue by ivoviz** [angular/material#5892]
I'm not sure if it was intended, but since a1889cd4726d1d36314dc164b5605da2eb4b50b4 it's impossible to have a full height page without explicitly adding `html, body { height: 100%; }`. Adding `layout-fill` to the body tag doesn't work either.

Pen that shows the issue: http://codepen.io/anon/pen/RWmKeR

**Comment by JunedS** [comment]
I have noticed that by adding position absolute to the parent it works. 
modified pen: http://codepen.io/anon/pen/wKbrwO

It doesn't work by even giving just height: 100% , that is because unless the parent has full height layout-fill will not work.

Correct me if I am wrong and if there are solutions I would be interested to know.

**Comment by jb29** [comment]
I experienced similar issues since I updated angular-material today.
My whole app is scrollable now instead of only the content area.
And on https://material.angularjs.org/HEAD/ it's not possible to scroll at all.

**Comment by EladBezalel** [comment]
@robertmesserle

**Comment by ivoviz** [comment]
Adding `layout-fill` to the `<html>` tag makes it work actually, but imo `html` and `body` should be handled by default.

**Comment by ThomasBurleson** [comment]
fixed.

**Comment by DallanQ** [comment]
Adding layout-fill to the html tag didn't work for me. I added layout-fill to the parent and grandparent nodes of the md-content node in order to get it to work on firefox (v42 on ubuntu). I'm using 1.0.0-rc5.
