### ISSUE TITLE
Issue with colors for menu bar inside toolbar

### ISSUE THREAD

**Issue by ramcaptora** [angular/material#6041]
I can barely see the menu items.
I can't set the color of menu unless I mention the property as important.

[Codepen for menubar inside toolbar](http://codepen.io/anon/pen/yeBEgw)

**Comment by RolandHeath** [comment]
It looks like because they are coming from inside an element with a dark theme colour, the text gets set to white. 

The very short term fix would be to use a different (light theme) colour on the toolbar. 

The (slightly less) short term fix is to use [$mdthemingprovider](https://material.angularjs.org/latest/Theming/03_configuring_a_theme), and set up the same colour as a light theme.

There is a real issue here though, and it needs a long term solution. It also looks as though the menu header is using black when it should be white, as well.

**Comment by PapyElGringo** [comment]
Related to #6049

**Comment by ramcaptora** [comment]
@RolandHeath thanks for the suggestion. Will try it for now.
