### ISSUE TITLE
mdContactChips: add support for md-separator-keys

### ISSUE THREAD

**Issue by Frank3K** [angular/material#6097]
It would be nice if `md-separator-keys` (`md-chips`) would also work on `md-contact-chips`.

**Comment by Frank3K** [comment]
@Ignigena: could you take a look?

**Comment by Ignigena** [comment]
@Frank3K I took a look and added basic support, probably has room for improvement.

For contact chips with `md-require-match` set to `false`, setting this attribute will function identically to the standard chips behavior and only treat the key codes present as valid separators.

However, this is slightly different with the autocomplete component that has require match set to `true`. In this case, the key codes will be evaluated in addition to the tab and return keys that are supported through autocomplete. This means it's not possible to remove support for the <kbd>TAB</kbd> or <kbd>ENTER</kbd> keys by simply committing the key codes from `md-separator-keys`

I'm not sure if this would even be desired so for now I just kept it simple. I can add this in to keep things consistent if it's deemed necessary.

Thoughts?

**Comment by Frank3K** [comment]
Thanks for looking into this, I see it is more complex than I initially thought. As for `md-require-match` set to `true`: I think your solution is good,  there is no need to change the behavior of `md-autocomplete` since the main use case for the separator functionality is extending the set of separator keys.

What happens when you enter a separator character when there's only a partial match?

**Comment by Ignigena** [comment]
Currently it appears the behavior of the contact chip autocomplete is to auto-highlight any partial match. Because of this, when you enter a separator character the currently highlighted match will be selected. You can modify the match by using the arrow keys and whatever row is highlighted will be selected once the separator key is pressed.

I modified the contact chip demo in the documentation to include <kbd>,</kbd> as a separator key so you can give it a whirl and see if it's sufficiently intuitive.

**Comment by Frank3K** [comment]
I have cloned the branch from your fork in order to test the added functionality. As far as I can see it works good; the handling of partial matches is what I expected.
