### ISSUE TITLE
md-progress-linear indeterminate is spazzing out

### ISSUE THREAD

**Issue by jpike88** [angular/material#6099]
Look at the progress demo, indeterminate progress is being weird

**Comment by jpike88** [comment]
Safari, OS X

**Comment by ThomasBurleson** [comment]
@jpike88  - How is it *spazzing out*? Can you provide more details.

**Comment by jpike88** [comment]
https://www.dropbox.com/s/428d9p0947kt46i/Untitled.mov?dl=0

**Comment by EladBezalel** [comment]
@topherfangio Can you please take a look i don't have access to mac.

**Comment by topherfangio** [comment]
Definitely seeing this issue; it appears to have something to do with the `scaleX()` in the animation. Changing it to use `width` instead makes it far less jumpy, but we **don't** use width/height because it causes a reflow, so we will need to find another solution.

Since this is a purely cosmetic issue, we are marking it low priority.
