### ISSUE TITLE
md-menu-item not enabled in RC6

### ISSUE THREAD

**Issue by sathishvj** [angular/material#6116]
We had the same code with both RC5 and RC6 and we're seeing that all the menu items are disabled.  Is anybody else also noticing this issue?  

I don't know if the md-toolbar is relevant, but when I tried the same thing outside it works.  It was also something that used to work with the exact same code with RC4.  A team mate who had earlier upgraded to RC6 noticed it first, and then when I upgraded to RC6 I was able to replicate it.  

```			
             <md-toolbar>
                      <md-menu  md-offset="0 25" md-position-mode="target-right target">
			      <a href="#" ng-click="openProfileMenu($mdOpenMenu, $event)" >first name</a>
			      <md-menu-content width="4">
			        <md-menu-item>
			          <md-button ui-sref='user.edituser'>
					Edit Profile
			          </md-button>
			        </md-menu-item> 
			        <md-menu-divider></md-menu-divider>
			        <md-menu-item>
			          <md-button ng-click="logout()">
			          	Logout
			          </md-button>
			        </md-menu-item>
			      </md-menu-content>
			    </md-menu>
         </md-toolbar>
```

**Comment by SuperheroicCoding** [comment]
Did you check if it's a problem with z-index stacking? The opened menu is not disabled. The pointer-events are cached by the md-backdrop.

For me, the md-backdrop that gets attached to the body, was in front of the opened menu.

The problem is that the md-open-menu-container is  in RC6 a child of md-menu. If the md-menu is inside a different z-index stacking branch the backdrop can be above it. In your case it's maybe the md-toolbar that has an z-index of 2.

    <md-backdrop> --> z-index: 94
    <any-element> 
      <another element> --> z-index: < 94
        <md-menu/> --> z-index: 95 but it is always under the backdrop because the z-index: 94 of the parent is handled as independent stacking branch.
      </another element>
    </any-element>
</element>

I hope this helps a little bit. When you increase the z-index of the <another-element> you'll loose that click anywhere to close menu behavior (above the area of the another element).

 If you have that z-index problem we should rename or create a new issue with a proper title.

**Comment by SuperheroicCoding** [comment]
Maybe same as https://github.com/angular/material/issues/6109
