### ISSUE TITLE
Feature request: support for number formatting in inputs

### ISSUE THREAD

**Issue by ivan7237d** [angular/material#6143]
A spreadsheet-like functionality where the value in a number input is formatted (e.g. 1,000,000, $50.00, 50%), but only when the input is not focused - once the user begins editing the number, it becomes 1000000, 50 etc. 

Here is an example http://jsfiddle.net/LCZfd/8/ (taken from http://stackoverflow.com/a/24057713) that keeps the advantages of type="number", except for displaying the small up/down arrows when the input is not focused (Firefox/Safari do this always, Chrome only on hover).

**Comment by DevVersion** [comment]
@EladBezalel Is this feature really desired? In general I can't find anything in the specs about that.

**Comment by ejohnsonw** [comment]
1+

**Comment by askucher** [comment]
+1

**Comment by ejohnsonw** [comment]
ended using ng-currency, no need to reopen

**Comment by ferchoman09** [comment]
@ejohnsonw are you using this library:
https://github.com/aguirrel/ng-currency

**Comment by Domvel** [comment]
Why closed? Because ng-currency exists? *eyeroll*
Just add another input attribute to format the displayed value. e.g. a display-function. And this should be called every time the value is really updated. Not from user only. input and change event is not enough. You have to handle it, when another element change the value and both shared the value over ngModel. 

Just looking for a fast clean solution to display the input type="number" value with fixed decimal places.

**Comment by andrea-capigiri** [comment]
+1
