### ISSUE TITLE
autocomplete results container height is not ok with a query ( after clear() )

### ISSUE THREAD

**Issue by NicolasBlois** [angular/material#6197]
![ezgif-820990270](https://cloud.githubusercontent.com/assets/6443098/11685658/f8060272-9e7a-11e5-8f2f-d3facca0467b.gif)

**Comment by alexkb** [comment]
+1

Confirming issue is in Chrome & Firefox but not IE10/IE11.

**Comment by blootch** [comment]
@kseamon @ThomasBurleson

**Comment by rfuhrer** [comment]
+1
seems to be some sort of race condition because I can cause the cause the issue on https://material.angularjs.org/latest/demo/autocomplete in the custom template section just by picking one and then clearing it multiple times.  It breaks about 95% of the time within 4 select and clears, sometimes it only takes one.

**Comment by jameswyse** [comment]
:+1: Seeing this in 1.0.1

**Comment by GavinPalmer1984** [comment]
+1
nice GIF by the way (never seen that used in a bug report and I am curious how you did it)

**Comment by NicolasBlois** [comment]
@GavinPalmer1984 : I used a screen recorder (kazam on ubuntu) then I convert it to gif
@ThomasBurleson https://github.com/angular/material/pull/6346/files this resolves this issue for me.

**Comment by ThomasBurleson** [comment]
Already fixed in HEAD.
