### ISSUE TITLE
Flex layout

### ISSUE THREAD

**Issue by reinos** [angular/material#6266]
HI Guys,

Is it possible to make a layout like this example

http://andyknapp.com/demo/learning-flexbox/

<img width="942" alt="screen shot 2015-12-12 at 11 10 07" src="https://cloud.githubusercontent.com/assets/633730/11761391/2ab212d6-a0c1-11e5-9dbb-368ad1d6d8ba.png">

While resizing, the box are filling the gaps.

Let me know.
Rein

**Comment by ThomasBurleson** [comment]
Yes. http://codepen.io/team/AngularMaterial/pen/VevQjR

**Comment by vapits** [comment]
Hey @ThomasBurleson is it possible to fill the space from left to right instead of filling first the height?
Because for example right now if you have only two boxes the there are going to one below the other leaving all the space on the right empty.

I haven't figured out if this is possible by following the example.

**Comment by vapits** [comment]
Hmm i found how to center items at least. except the ```align-content: center;``` you should add also the ```align-items: center;``` at least for my case.

Still though if you have a high height for the media-screen then you will have a very long column until you get correct screen filling.

If i found a way on this i'll share it. If you though already now the solution please share it :) :palm_tree:
