### ISSUE TITLE
codepen demos not loading svg icons

### ISSUE THREAD

**Issue by epelc** [angular/material#6343]
In 1.0.0 the demo's icons aren't loading correctly.

example speeddial demo http://codepen.io/anon/pen/obbPOE

The menu bar demo http://codepen.io/anon/pen/BjjOEE

I'm guessing it's all the demos using svg icons? As the icon demo which uses font icons works fine.
http://codepen.io/anon/pen/yeexWe

I also think it's specific to the demo codepen setup as my app's custom icons loaded via an svg icon set work fine in 1.0.0

**Comment by topherfangio** [comment]
This is likely due to commit 86ec22ad524b6f1f929b400085c8cbb925588959 where we fixed the Codepens not having the proper dependencies.

Interestingly, if we change it to

```js
  angular.module('MyApp')
```

it seems to work just fine. This is probably because of our assets cache that we use in the Codepen demos (https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-114/assets-cache.js) which declares the module  and dependencies for 'MyApp' already.

@ThomasBurleson Perhaps we could declare the assets cache as a separate service which gets injected as a dependency into our demos?

**Comment by DevVersion** [comment]
That's fixed in #6727 by @ThomasBurleson and is already merged.

**Comment by topherfangio** [comment]
@DevVersion Thanks for the update!
