### ISSUE TITLE
peerinvalid Peer angular-material@1.0.0 wants angular@^1.4.7

### ISSUE THREAD

**Issue by Hokutosei** [angular/material#6359]
Greetings,

can't use with angular 1.5.0.rc-0

```
-> % npm install angular@1.5.0-rc.0 --save
npm WARN package.json protoype1@1.0.0 No repository field.
npm WARN package.json path@0.11.14 path is also the name of a node core module.
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "angular@1.5.0-rc.0" "--save"
npm ERR! npm  v2.7.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package angular does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular-material@1.0.0 wants angular@^1.4.7
```

this is my package.json

```
  "dependencies": {
    "angular": "^1.4.8",
    "angular-animate": "^1.4.8",
    "angular-aria": "^1.4.8",
    "angular-material": "^1.0.0",
    "express": "^4.13.3",
    "express-http-proxy": "^0.6.0",
    "gulp": "^3.9.0",
    "gulp-concat": "^2.6.0",
    "gulp-ng-annotate": "^1.1.0",
    "gulp-replace": "^0.5.4",
    "gulp-typescript": "^2.8.2",
    "gulp-uglify": "^1.4.0",
    "less": "^2.5.1",
    "path": "^0.11.14"
  }
```

**Comment by chet-manley** [comment]
This is by design, and controlled by npm. 
https://github.com/npm/node-semver#prerelease-tags

**Comment by spock123** [comment]
@chet-manley  I read the document but didn't quite understand what to do. Am in the same situation, using Angular 1.5RC0. Downgrading to 1.4.x isn't possible due to the .component stuff in NG1.5

Any advice to get NG-Material installed would be welcome.

**Comment by chet-manley** [comment]
NPM only takes into account Major, Minor and Patch version numbers by default. It ignores Prerelease tags and versions (alphas, betas, release candidates, etc), unless explicitly included in the dependency version. For instance, a dependency of "^1.4.7" can be satisfied by version 1.4.7, 1.4.8, 1.5.x, 1.8.x, etc. 1.5.0.rc.0 however, does not meet the requirement, because pre-release versions are not counted. In other words, 1.5.0.rc.0 is not greater than 1.4.7 in the same way that 1.4.8.beta.1 is not greater than 1.4.7.

Since you cannot change the dependencies of a module you did not create (angular-material), the only option at the time would be to manually place the module into your app, and wait for 1.5.0 to be released.

**Comment by spock123** [comment]
@chet-manley makes sense, thank you so much

I'll be manually injecting Angular-Material into my project during initial development and when 1.5 hits final release I'll incorporate it with npm / webpack. Thank you again, I didn't know about betas and rc not "counting"... Happy Holidays btw

**Comment by jbcpollak** [comment]
you can install angular-material with angular 1.5 if you use npm 3.x:

    npm i -g npm

then do an `npm install` like normal. In npm 3.x the peer-dependency is change to a warning instead of an error.

Unfortunately we have found some sort of silent error when using angular 1.5.rc0 or the release version 1.5. We aren't sure yet if that is an interaction with angular-material  or some other cause, but for now we have locked our angular version to `1.5.0-beta.2`.

**Comment by ThomasBurleson** [comment]
Fixed.
