### ISSUE TITLE
Shadows and light grey text/lines disappear on bright monitors

### ISSUE THREAD

**Issue by StretchKids** [angular/material#6376]
When viewing on a monitor that was set a bit bright, the shadow on sidenav and the line on input fields and the label acting as placeholder text are not visible or are barely visible. 

We noted that the Angular Material website colored the sidenav backround blue. Is that the preferred technique rather than using the shadow? Is there a way to address this for input fields?

Thanks,

David

<img width="627" alt="angmat pic 1" src="https://cloud.githubusercontent.com/assets/6139842/11879135/8c707da0-a4c7-11e5-8f74-99c6fec19f76.png">

<img width="738" alt="angmat pic 2" src="https://cloud.githubusercontent.com/assets/6139842/11879141/9d3c5f6e-a4c7-11e5-8aaa-c7fef87103ba.png">

**Comment by nathanmarks** [comment]
Your monitor is poorly configured. If you have a cheap monitor, it's unlikely that you'll be able to retain the brightness level and get better greys.

Try turning down the brightness and adjusting the contrast.

BTW, colors should be following a heavily researched spec and are taken from https://www.google.com/design/spec/material-design/introduction.html

**Comment by StretchKids** [comment]
Unfortunately, it doesn't work that way. The application isn't built for my amusement...it is built for thousands (and we hope hundreds of thousands) of people we don't know, will never meet, and will never tell you about the problem...they will just say it is hard to read an leave. 

You can note that the Angular Material team abandoned the shadow for their own sidenav:
<img width="400" alt="angularmaterialwebsitesidenav" src="https://cloud.githubusercontent.com/assets/6139842/11886436/17a2553a-a4f8-11e5-9244-a66c92b63ab2.png">

For the record I use a 49" 4k TV that was calibrated with an x-rite iDesign calibration tool.

**Comment by nathanmarks** [comment]
I had the same issue and it was due to poorly calibrated monitors.

Anyways, I do totally understand your point about the readability for users who you don't know. You'll probably have to implement it yourself though. Unless the angular material team aren't following spec currently, you'll want to raise the issue elsewhere.

For reference, here's an image from the spec docs:
![image](https://cloud.githubusercontent.com/assets/4420103/11886589/a8b45162-a4f9-11e5-81a1-8f6471a23608.png)

In terms of a 'preferred technique', it largely depends on your colour palette. The vast majority of google applications using material design have a white drawer.

**Comment by bathos** [comment]
@StretchKids fwiw, regarding "You can note that the Angular Material team abandoned the shadow for their own sidenav" -- there actually *is* a shadow in that screenshot. But your point is valid that if people have miscalibrated displays, light colors can appear as white. If this is a concern, perhaps using the higher-number shadow classes to intensify the effect (e.g. maybe every third value instead of every one: .md-whiteframe-z3, .md-whiteframe-z6, etc)?

**Comment by EladBezalel** [comment]
@StretchKids first of all, our sidenav uses `md-whiteframe-z2`.
Second, if we are, somehow, not following the google material design spec, please mention where and we will fix it. We try out best to implement the material spec and follow its guidelines/
I do understand the problem here and for now, i suggest you to make your background in grey-50 (#FAFAFA) for more contrast.

**Comment by EladBezalel** [comment]
closing this issue as there's no progress or any misfollowing the spec from our side.
