### ISSUE TITLE
md-button's display differently when template is minified

### ISSUE THREAD

**Issue by Smolations** [angular/material#6390]
Correct me if I am wrong, but shouldn't
```
<md-button class="md-primary">Button 1</md-button>
<md-button class="md-primary">Button 2</md-button>
```
and
```
<md-button class="md-primary">Button 1</md-button><md-button class="md-primary">Button 2</md-button>
```
render the same in a browser? At the moment, they do not. Minifying an HTML template produces the second result, and removes spacing between the buttons when rendered. This may or may not be intentional, but I wanted to get it on the radar.

**Comment by DevVersion** [comment]
That makes no sense. A minified html code should be the same as the actual beauty code.

**Comment by paulflo150** [comment]
Why do you believe the two examples are equivalent? In the first example you have two elements with a line break (or white space since they are inline), in the second you don't have the line break.

Here is a simple example:
````
<span>Hello</span>
<span>there</span>
````
renders are "Hello there", whereas 
````
<span>Hello</span><span>there</span>
`````
renders as "Hellothere", so in order to achieve the same result you would need a space between the two spans.
