### ISSUE TITLE
menus inside fabToolbars

### ISSUE THREAD

**Issue by Badisi** [angular/material#6409]
Opening a menu inside a fab-toolbar will instantly close the toolbar.
I think it should be closed only when clicking on a menu item not on the menu itself.

Codepen showing the issue:
http://codepen.io/anon/pen/wMWaba

**Comment by rschmukler** [comment]
@topherfangio I did a little digging on this. It is caused by the click on the nested button triggering a `focusout` event. I think we can resolve this by changing [fabController.js#80](https://github.com/angular/material/blob/master/src/components/fabSpeedDial/fabController.js#L80) to something that checks if the source is inside the `$element`. I'm not sure how this behaves w/ the rest of the FAB components, so I leave it to you as a starting place:

```js
      if (event.type == 'focusout' && !closeTimeout && $mdUtil.getClosest(event.target, 'md-fab-toolbar') != $element[0]) {
        closeTimeout = $timeout(function() {
          vm.close();
        }, 100, false);
      }
```

**Comment by pieterwillaert** [comment]
+1
