### ISSUE TITLE
Input cursor stays when dragging screen

### ISSUE THREAD

**Issue by jpike88** [angular/material#6454]
On iOS Safari, when dragging the screen down while an input is focused, the text cursor stays where it is until drag stops, and then jumps to where it should be.

**Comment by topherfangio** [comment]
I cannot for the life of me find the original issue, but I do believe this is a duplicate/known issue. I'll try to find it if possible.

**Comment by EladBezalel** [comment]
@topherfangio do you have any iOS available for checking thinks?

**Comment by naomiblack** [comment]
Need to find dup issue

**Comment by skoszuta** [comment]
I've been investigating this a little due to a bug report on this in our project and have found an iOS bug regarding a similar case: https://bugs.webkit.org/show_bug.cgi?id=138201

Could this be it? Just a hint.

**Comment by topherfangio** [comment]
I am removing the "duplicate" label since I cannot find the duplicate.

@skoszuta I am not 100% sure (and I unfortunately don't have the time to test right now), but I think on iOS we create our own caret which means we should be able to watch for scroll events and hide it.

@EladBezalel Do you have an iOS device to test with? If not, we can reassign.

**Comment by EladBezalel** [comment]
@topherfangio sorry but i don't have any iOS device

**Comment by topherfangio** [comment]
No worries; reassigned to myself ;-)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
