### ISSUE TITLE
md-select is difficult to implement.

### ISSUE THREAD

**Issue by jpike88** [angular/material#6460]
I've just spent 2 hours on what is a tangled mess, over a very, very simple implementation I'm trying to make work with md-select.

The scenario is:

I have an array of states: ['QLD', 'NSW', 'ACT']

I have an existing selection that was pulled out of storage and placed in a scope variable: 'NSW'

I want an md-select that is to show the NSW selection on load, and then upon choosing on of the other options, have that scope variable change to that option.

Instead what I got was a rabbit hole and confusing documentation on md-select, which means I'd have to do some crazy workarounds to nail something which should be an extremely minimal example. It doesn't even have the ability to apply ng-change, which I find to be really strange considering it is in effect, an input field.

In the meantime I'm just avoiding md-select and sticking to a styled HTML select, because it took me about 5 minutes to achieve the intended result.

If I've just completely missed something, please let me know.

**Comment by jpike88** [comment]
So I dug around more, and looked at the 'input' demo of the documentation.

There was a select in there with a pre-selected value.

I had to convert my state array into this:


('QLD NSW ACT VIC TAS SA').split(' ').map(function(state) {
        return {abbrev: state};
      })


Why do I have to do that??

**Comment by skosno** [comment]
Hi,

Not really sure what seems to be a problem? Here is a very simple codepen:
http://codepen.io/anon/pen/pgPjzq

If I understand correctly it is doing exactly what you need?
(of course this simple example works because model is simple string value, if array would be of objects you would have to initialize your model as reference to the same object array is referring). Documentation is doing this split magic to quickly create objects - it is smart way to save some characters when writing code, while it might be a bit less readable and clear why it is done.

**Comment by naomiblack** [comment]
please direct discussion to our mailing list.
