### ISSUE TITLE
md-autocomplete binding not working inside ng-repeat

### ISSUE THREAD

**Issue by mihaellenic** [angular/material#6498]
I found an issue with data binding when using md-autocomplete inside ng-repeat directive.

When I use ng-repeat item in md-selected-item, the changes made to the item are not reflected to original array used in ng-repeat.

Here is the codepen example: http://codepen.io/mihaellenic/pen/bEBKrj

**Comment by skosno** [comment]
Hi,

This is not related to md-autocomplete but rather how angular handle scopes. In here ng-repeat is creating new scopes and "dataItem" is really referring inherited value instead of original one in "data".

You can solve it by passing "data[$index]" into autocomplete instead of "dataItem":
http://codepen.io/anon/pen/gPLNwQ

Hope it helps - if you believe this solves issue, please close it (to help cleanup issues).

**Comment by skosno** [comment]
To give better example, please see this codepen where I addded simple <select> next to autocomplete from your original example:
http://codepen.io/anon/pen/qbqzqV

You can see that changing select also changes autocomplete but it does not affect original one. If you change in both to data[$index] it works as expected:
http://codepen.io/anon/pen/zroVNZ

**Comment by mihaellenic** [comment]
Hi,

yes, I understand now, thank you.

In the past I have used DevExtreme's web framework and their approach is a little bit different and it looks like they avoided this issue by binding only one property of an object to the value representing selected item.
This is the link to the documentation where you can see they use 'valueExpr' to define which attribute is representing selected item: http://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxAutocomplete/?version=15_2

The solution you recommended, to use data[$index], is working fine, thank you again for your help.
