### ISSUE TITLE
Toast animation hides website's scrollbar and then shows it making website to jump

### ISSUE THREAD

**Issue by dht** [angular/material#6524]
When a toast is shown scrollbar will be hidden during the reveal animation and will come back when the animation is completed. This makes the content of the website "jump" left and right when a toast is animated in and animated out.

**Comment by hewaroth** [comment]
Which AM version you use?

**Comment by manish2535** [comment]
Taken from Toast Doc - 

Parent container notes
The toast is positioned using absolute positioning relative to it's first non-static parent container. Thus, if the requested parent container uses static positioning, we will temporarily set it's positioning to relative while the toast is visible and reset it when the toast is hidden.

Because of this, it is usually best to ensure that the parent container has a fixed height and prevents scrolling by setting the overflow: hidden; style. Since the position is based off of the parent's height, the toast may be mispositioned if you allow the parent to scroll.

You can, however, have a scrollable element inside of the container; just make sure the container itself does not scroll.

**Comment by EladBezalel** [comment]
@manish2535 thanks for your comment, you described it well :)
