### ISSUE TITLE
md-input-container not working using attribute interpolation and flex

### ISSUE THREAD

**Issue by cervecero** [angular/material#6549]
Hi guys! Sorry for my english. I'm working with angular material v 1.0.1 and it's awesome. However, I've found an issue when i'm using a ```<md-input-container></md-input-container>``` with class attribute interpolation and flex. In earlier versions of angular-material when i used ```<md-input-container flex class="{{myClass}}">...``` that directive applied flex as class in class attribute. But, in the latest version, that directive is not applying flex as class in attribute, it's only applying the value of myClass . This [codepen] (http://codepen.io/cervecero/pen/ZQeLbz/) shows the problem. 

**codepen**: http://codepen.io/cervecero/pen/ZQeLbz/
**angular version**: 1.4.8
**angular-material version**:1.0.1
**Browser**: Version 46.0.2490.86 (64-bit) Ubuntu

**Comment by ThomasBurleson** [comment]
*  use `ng-class="myClass"` for interpolated values... this approach will not interfere with the `class="flex"` injection. 
*  change **md-input-container** `display:flex` instead of `display:inline-block`

<img width="1061" alt="screen shot 2016-01-15 at 12 18 29 pm" src="https://cloud.githubusercontent.com/assets/210413/12364196/1fce961a-bb82-11e5-94f0-f5fd5fd88745.png">
