### ISSUE TITLE
Input messages disappear

### ISSUE THREAD

**Issue by gisek** [angular/material#6610]
I originally posted the question on angular.js repo (https://github.com/angular/angular.js/issues/13723), but was instructed to move it here.

Please take look at the Angular Material demo site at the `Postal Code` input:
https://material.angularjs.org/1.0.1/demo/input

Scenario 1 (works ok)
1) We start with
![a_1](https://cloud.githubusercontent.com/assets/1664094/12216965/f9b165b8-b6f2-11e5-8540-ef0c5c6b6184.PNG)
2) Mark whole text in the input and click `backspace`
3) Result
![a_2](https://cloud.githubusercontent.com/assets/1664094/12216968/0f34a8be-b6f3-11e5-9596-324cc610e99c.PNG)
4) Everything is ok

Scenatio 2 (bug)
1) We start with
![1](https://cloud.githubusercontent.com/assets/1664094/12216973/29cb15dc-b6f3-11e5-979d-2cd99713063b.PNG)
2) Delete last digit and you and up with (still ok)
![2](https://cloud.githubusercontent.com/assets/1664094/12216980/486e8b4a-b6f3-11e5-95e2-82c259cc5f1e.PNG)
3) Delete the rest of the input one by one:
![3](https://cloud.githubusercontent.com/assets/1664094/12216986/59a3751a-b6f3-11e5-94e5-5a6181a8fefa.PNG)
4) BUG, the should be 'You must supply a postal code' message, but there is nothing
5) Type a digit:
![4](https://cloud.githubusercontent.com/assets/1664094/12216993/86dfe66c-b6f3-11e5-81b4-2ef7dc067d09.PNG)
6) BUG again, there should be a message: 'That doesn't look like a valid postal code', but there is nothing
7) Type the rest of the digits
![5](https://cloud.githubusercontent.com/assets/1664094/12216996/b0969fa0-b6f3-11e5-8cef-c56b7ccf308c.PNG)
8) Now it's ok
9) Delete the last digit
![6](https://cloud.githubusercontent.com/assets/1664094/12217002/c285a800-b6f3-11e5-8178-994ae06b631d.PNG)
10) It's ok again

The messages are present in DOM, but the message container size seems to be calculated in a wrong way. 

This is how it looks when the message is visible
![image](https://cloud.githubusercontent.com/assets/1664094/12217051/808eb40e-b6f4-11e5-86bc-047e4a0d094e.png)

This is how it looks when the message is invisible
![image](https://cloud.githubusercontent.com/assets/1664094/12217040/5d4ab038-b6f4-11e5-9830-c7a6464760e0.png)

**Comment by grosem** [comment]
I think I found the problem:

https://github.com/angular/material/blob/1d71928ee7480464d34749284cb326d3ad127f93/src/components/input/input.js#L639-L642 says *If we have the md-auto-hide class, the md-input-invalid animation will fire, so we can skip*. However, it does not.

The animation is supposed to be triggered by the setInvalid function
https://github.com/angular/material/blob/1d71928ee7480464d34749284cb326d3ad127f93/src/components/input/input.js#L86

`setInvalid` is triggered by `scope.$watch(isErrorGetter, containerCtrl.setInvalid);`

It cannot differentiate between errors such as *invalid zipcode* or *missing zipcode*, therefore the new message is not displayed (isErrorGetter stays true). That also explains #6399 #6440 (and maybe #6443?)

A dirty fix is to remove https://github.com/angular/material/blob/1d71928ee7480464d34749284cb326d3ad127f93/src/components/input/input.js#L639-L642 but there might be other problems because of that.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (497/400 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:38119 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1aKBag-001uyW-Kb
	for yann.dupuy@zyapps.com; Fri, 15 Jan 2016 22:07:31 +0100
Date: Fri, 15 Jan 2016 13:06:40 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1452892000;
	bh=77Elth5lFWTrvyXDpTD06XJttyUPAMJ7ATOa66EzXxw=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=kId50+08eSIyUZnWoQQjgmNCuB4xNpVV/eQVSClKKRshi6bxywr5OAEREjGgniuzo
	 UkyVgds9GanjLJ0gt2HDXwfKGDPPmMxbAvyazE1ehkqs09+gcdgZE/As8qwcvdha4V
	 2GIbpotgPKHC4EtFOvaA5+T9TWKSqG/xf64yx3UE=

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
