### ISSUE TITLE
md-grid-list doesn't work with Fixed-height rows

### ISSUE THREAD

**Issue by super-coder** [angular/material#6634]
according to https://material.angularjs.org/latest/api/directive/mdGridList i can set Fixed-height rows:
**md-row-height="200px"**

but it doesn't work

http://codepen.io/anon/pen/NxgOKG

![image](https://cloud.githubusercontent.com/assets/2155554/12265199/d69b7864-b94c-11e5-9848-567365fedb9e.png)

**Comment by DevVersion** [comment]
@super-coder If you look at your codepen, you also specify the attribute `md-row-height-gt-md="1:1"`, so that actual `md-row-height="200px"` attribute will be ignored on your codepen (screenshot screen size).

If you remove this attribute and remove the `gutter` (only for example), then you can see, the first tile has a height of `600px` (`200px` * 3rows)

**Comment by super-coder** [comment]
@DevVersion thanks closing issue
