### ISSUE TITLE
improve form validation

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#6644]

**Comment by bourey** [comment]
We've found that users occasionally don't notice required fields and can't figure out why their form can't be successfully submitted.  Since the user has never interacted with the form field, it never shows an error state and the error is hard to find.  We typically check the form's validity on submit and if the form is invalid, set all error states visible rather than attempting to submit the form.

**Comment by bourey** [comment]
It turns out that since the Angular Material components set appropriate aria attributes, the browser's built-in behavior actually highlights validation errors for the user and won't allow the form to submit.  Example: http://codepen.io/anon/pen/zrXeOm.  I think this might be sufficient.

**Comment by mustela** [comment]
I don't think this should be closed. Its quiet important to let users understand which fields are required and which ones no, specially for big forms. Having to submit a form and just in that moment realice that they haven't fill the inputs, is really annoying (this is whats happening to mee now). 

So please, consider re-opening this issue.

**Comment by bourey** [comment]
There's also an update (I believe committed, but not released?) that adds an asterisk to all required fields: https://www.google.com/design/spec/components/text-fields.html#text-fields-required-fields.  I think this should make a big difference in helping users understand which fields are required prior to submit.

**Comment by mustela** [comment]
Oh totally! That change is what the world need :)

**Comment by DevVersion** [comment]
Yes @bourey , it's currently in HEAD, but not yet released - 1f99795
