### ISSUE TITLE
md-autofocus and autofocus do not work with md-select

### ISSUE THREAD

**Issue by rvarbanov** [angular/material#6689]
md-autofocus and autofocus do not work with md-select

**Comment by ThomasBurleson** [comment]
`md-autofocus` is intended to allow container components to identify a specific child element to have focus. Select should not be considered a 'container' component.

**Comment by rvarbanov** [comment]
Well, I need a way to focus the first form element of my form. My first element is a select dropdown.

What do you suggest that I should do to have that select focus after page load?

**Comment by jporcenaluk** [comment]
I second @rvarbanov on the question - how do you focus on the select after a page load?

**Comment by johnrix** [comment]
+1

**Comment by tiaoshi** [comment]
on v1.1.1 and Chrome 53

I am able to set a default focus on a md-select with `autofocus` and it works. But the md-select is a required field inside a md-sidenav. When the md-sidenav is eventually open, the md-select is in the warning state, and you can notice its color is changing while the md-sidenav is sliding in. Also, I think adding autofocus in this way would make the md-sidenav slide more distance, which looks weird.

**Comment by rvarbanov** [comment]
It is still not working.

**Comment by buzybee83** [comment]
I have a similar issue with autofocus - In my case I do not need to autofocus on the md-select itself but want the search input inside md-select to be autofocused when it's open -  Similar to how Select2 works. Currently have tried both, 'autofocus' and 'md-autofocus', on the search input but neither worked. Also, this is bad behavior for when navigating through the page with the keyboard as it renders the search input useless since can not select and type (without the click of the mouse).
