### ISSUE TITLE
Default shadows are inconsistent with material design specs

### ISSUE THREAD

**Issue by isavnin** [angular/material#6710]
The elevation shadows for most elements do not follow current material design specs:
https://www.google.com/design/spec/what-is-material/elevation-shadows.html#elevation-shadows-shadows

For example, FAB buttons should have resting state -> pressed state as 6dp -> 12dp. Right now it looks more like 2dp -> 6dp. Sidenav should default to 16dp. Card should default to 2dp. This should be checked for all elements.

**Comment by ethanmick** [comment]
Just ran into this issue while building a site that puts Fab buttons on top of many layering parts. The inconsistent shadows are visually noticeable. Thanks!

**Comment by isavnin** [comment]
I think this issue is critical taking into account the purpose of the project. It violates the most basic principles of MD. So I don't understand why it was sorted into Backlog.

**Comment by Todd-Werelius** [comment]
+1

I agree, I have to manually adjust these using classes to get them to work, while that's acceptable for the moment it really should default to the spec. 

For modal bottom sheets ( not widely used I admit ) I had to copy and modify the existing class just to get it to work at all since "top shadows" don't really exist in AMD at the moment. 

Proper Z order representation seems pretty key here and I have seen way to many "Material Design" sites that look like crap because they ignore this ( probably unintentionally )
