### ISSUE TITLE
Issue with input ? 

### ISSUE THREAD

**Issue by alapasset** [angular/material#6732]
Hello,

I start with angular Material and I try to do an input search bar. My work is here: https://lancea-news-agone.c9users.io/

The input label go outside top when I enter a search text inside and I don't understand why.

 My code : 

```javascript
<md-toolbar ng-show="showSearch" class="md-hue-1">
            <div class="md-toolbar-tools" layout="row">
                <md-button ng-click="showSearch = !showSearch" aria-label="Retour">
                    <md-icon md-svg-icon="images/back.svg"></md-icon>
                </md-button>
                <h3 flex="10">Retour</h3>
                <md-input-container flex>
                    <label id="labelSearch">Recherche</label>
                    <input type="search" ng-model="search" class="hue-2" id="inputSearch">
                </md-input-container>
                <md-button class="md-icon-button" aria-label="Recherche" ng-click="showSearch = !showSearch">
                    <md-icon md-svg-icon="images/search.svg"></md-icon>
                </md-button>
                <md-button class="md-icon-button" aria-label="Rédaction" ng-click="navToDetail(news.permalink)">
                    <md-icon md-svg-icon="images/redac_zone.svg"></md-icon>
                </md-button>
            </div>
        </md-toolbar>
```

Thx in advance.

**Comment by mckenzielong** [comment]
This might be [a candidate for the forums.](https://groups.google.com/forum/#!forum/ngmaterial) To quickly address this: md-errors-spacer is a div that is below the input, and is pushing the rest of your input up.  You can try hiding that class, but any ngmessage div will not be placed properly.  

Alternatively you could correct the positioning using something like this:
``` css
md-toolbar md-input-container {
 bottom:-20px;
}
```
An aside:  I would also consider using `md-no-float` on the md-input-container.  While I am not sure if it is against the spec, the [examples shown](https://www.google.com/design/spec/components/text-fields.html#text-fields-search-filter) do not use the floating label.

**Comment by scriptsure** [comment]
+1 on this... seems more like a bug then a forum discussion

**Comment by mckenzielong** [comment]
> +1 on this... seems more like a bug then a forum discussion

At first glance I read it to be a forum question, this is probably due to the wording of the initial issue / the way my brain interpreted it :+1:

With my excuses aside, it could also be considered a component integration bug.  There are two integration bugs here: error padding and theme problems.

First, I have some questions related to the spec: are inputs with floating labels allowed in regular sized toolbars? (there is an example of one in a larger toolbar in the spec) Keep in mind the toolbar has a height of 56dp on mobile  (64dp on larger devices) where a floating input is 72dp (or 60dp for dense floating labels).  There are problems with sizing.

Inputs without floating labels should be able to fit though (should be 48dp / 40dp) , but currently suffer the same integration problem with the error padding.

Does disabling error padding work as a solution?  Are errors allowed to be shown with a toolbar input?

Secondly we have theme issues.  The colours for both md-no-float and floating labels are wrong.  See [this codepen.](http://codepen.io/mckenzielong/pen/JGORqE)  The default floating label colour is too dark, and the md-no-float label is gray.  Once text is typed, both are incorrectly coloured.
