### ISSUE TITLE
Animations are frozen by javascript

### ISSUE THREAD

**Issue by mitchellwills** [angular/material#6738]
Consider the following code:

```js
$mdToast.show(
        $mdToast.simple()
                .textContent('Simple Toast!')
                .position('bottom right')
                .hideDelay(3000)
);
$timeout(function() {
    var start = Date.now();
    console.log('spinning: ' + start);
    while ((Date.now() - start) < 5000) {
    }
    console.log('done: ' + Date.now() + ' : ' + (Date.now() - start));
}, 50);
```
You will see that both the toast enter animation and button ripple animation freeze when an infinite loop starts 50ms later.

> [CodePen Demo](http://codepen.io/anon/pen/eJeBeB)

It seems like it is possible to allow some browsers to run animations off the UI thread (see link below). A workaround to this issue might be something nice for Angular Material to support. @see [Css Animations off the UI Thread](http://www.phpied.com/css-animations-off-the-ui-thread/)

**Comment by gpopovic** [comment]
Maybe related to pull #6631

**Comment by ThomasBurleson** [comment]
@mitchellwills - Thx for the excellent issue report and the suggested fix to support unblocked animations.

**Comment by topherfangio** [comment]
I did a bit of digging on this today and I don't think it's going to be an easy task. First off, we will need to make modifications to every component that has animation to ensure it uses transforms, but in many cases (as is the case with ripple), at the end of the animation we add/remove a class which resets the CSS back to the proper settings.

Off the top of my head, we could potentially rewrite everything as a CSS keyframe animation, where the final keyframe resets everything. This may work for the ripple since it has a definitive start/end, but I'm not quite sure if we could achieve something similar with the toast, as we pretty much require JS to kick off the hide animation on mouseOut or after a certain amount of time.

We should definitely look at solutions for this in Material 2.0, however, it looks like we can make some minor adjustments to various components which will improve things right now.

I think the next step is to list out which components would benefit from some minor updates, and perhaps open a ticket for each one so we can track them one at a time.

P.S. @gpopovic - Your PR does fix this partially by fixing the ripple animation on all browsers, but the `clearRipples()` method which is run in JS can still get stuck causing the ripple to be visible until the JS can remove them.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by russelltrafford** [comment]
Note, this is still an issue even in Material 2.
See https://github.com/angular/material2/issues/6094

**Comment by russelltrafford** [comment]
Now fixed in the latest material2 update. spinner is pure CSS now.
