### ISSUE TITLE
md-no-proxy appear on md-list-item randomly ?

### ISSUE THREAD

**Issue by EmmanuelPREVOST** [angular/material#6848]
# Description
```
<md-list-item>
    <md-icon md-font-set="material-icons" aria-label="Fichier pdf" title="Fichier pdf">picture_as_pdf</md-icon>
    <p class="thor-text-overflow">Ajouter le calendrier des ventes</p>
    <md-button class="md-icon-button" aria-label="icon">
        <md-icon md-font-set="material-icons">cloud_upload</md-icon>
    </md-button>
</md-list-item>
<md-list-item>
    <md-icon md-font-set="material-icons" aria-label="Fichier pdf" title="Fichier pdf">picture_as_pdf</md-icon>
    <p class="thor-text-overflow">plaquette_promo.pdf</p>
    <more></more>
</md-list-item>
```
On the second element `md-list-item` a class `md-no-proxy` appear but i don't know why.. and it is a problem.

Is this a bug ? If not why does it appear ?

EDIT : When i add a `<md-button>` in the second `md-list-item` the class is not added.

Thanks

**Comment by DevVersion** [comment]
Hey,

I just walk with you through the several steps of a `mdListItem`.
- At first we check if the list item is containing any clickable attribute (See [here](https://github.com/angular/material/blob/master/src/components/list/list.js#L98))
- If there is no clickable attribute specified (`in your case`) we continue checking for any proxy elements (See [here](https://github.com/angular/material/blob/master/src/components/list/list.js#L86))
- And after that we check if there was any proxy element was found. 
- If there was nothing found (`in your case of the second list item`) we check for a button (see [here](https://github.com/angular/material/blob/master/src/components/list/list.js#L109)) which should contain the `md-secondary` or `md-exclude`, if true -> we will add the `md-no-proxy` class (See [here](https://github.com/angular/material/blob/master/src/components/list/list.js#L110))

That's why the class isn't appearing when you add a `<md-button>`. So this isn't an issue.

**Comment by EmmanuelPREVOST** [comment]
First thanks for your fast answer !

Ok the comportment was weird for me cause i think you assume that `mdListItem` has same content in a `mdList`.

Maybe the [note](https://material.angularjs.org/latest/api/directive/mdListItem) isn't exact cause in my case not all the content is wrapped inside a `mdButton`: 
```
Note: We automatically apply special styling when the inner contents are wrapped inside of a <md-button> tag. This styling is automatically ignored for class="md-secondary" buttons and you can include a class of class="md-exclude" if you need to use a non-secondary button that is inside the list, but does not wrap the contents.
```
I think the right way for me to correctly use `mdListItem` is to add the class `md-exclude` on the button in first `mdListItem` tag.

Thanks again

**Comment by peio72** [comment]
How to avoid applying this on a md-checkbox element ? (which breaks my list responsive design)

**Comment by DevVersion** [comment]
@peio72 This is currently not possible. Please file an issue and write it as a feature request. 

But also show your issue, with the broken responsive design.

**Comment by peio72** [comment]
I have had lot of difficulty trying to make a list with:
checkbox-icon-text-actions icons (as secondary)
I wanted secondary icons to move under when screen reduces.
So I managed to find a solution. But adding the checkboxes breaks all by the addition of additional thing (div and class) i don't want.
