### ISSUE TITLE
ng-messages is not showing when checking more than one criteria

### ISSUE THREAD

**Issue by leobispo** [angular/material#6872]
I am facing a problem with md-input-container and ng-messages since v1.0.0

When you have 2 error checks: for example ng-required and ng-pattern

Whenever one of the 2 errors is visible, the other one stop working (it is not showing anymore)

You can check the issue by creating an input field with 2 ng-messages (ng-required and ng-pattern) and force the first error (for example leave the field empty). After that, go to the field again and fill it with a wrong pattern - it will not show the error message anymore.

**Comment by langdonx** [comment]
I'm seeing this bug as well.  I've reproduced it here:

http://codepen.io/langdonx/pen/vLajXR

1. Focus on the 4th input and type "123"
2. Blur the input (tab/click out)
3. Focus on the input again and delete "123"

At this point, it should tell you that you've got to charge something, but it doesn't... the field does say it has an error though.  The `ngMessage` element exists, but the opacity and marginTop aren't overridden on it, so it's out of view.

It appears to come down to not using `md-auto-hide`"false"`.  I can't reproduce it on the demo site, because the demo site specifics `md-auto-hide="false"`.

**Comment by langdonx** [comment]
Dug some and it appears that `ngMessageAnimation.enter` gets fired twice when the 2 messages appear, but when you delete "123", `ngMessageAnimation.leave` gets fired twice even though the 1 message stays behind.

I don't have a lot of experience with `.animation()`, so I can't get much further than that.

This is a duplicate issue anyway: https://github.com/angular/material/issues/6440

**Comment by usarskyy** [comment]
We experience same issue in version 1.0.4. Class that adds margin "-100px" and opacity "0" for validation messages is not removed correctly.

**Comment by felipemeirelles** [comment]
Hi, the problem lies on lines 12295 and 12296 on version 1.0.5. For some reason some suposed that messages would be shown outside the ngMessageAnimation method.

**Comment by mwymann** [comment]
+1

**Comment by arthurspa** [comment]
+1

**Comment by adam-s** [comment]
+1

**Comment by pjwalmsley** [comment]
+1
