### ISSUE TITLE
md-dialog not updates its height on window resize

### ISSUE THREAD

**Issue by AliPoder** [angular/material#6875]
![gif](http://g.recordit.co/9p2QVJeMnF.gif)

**Comment by DevVersion** [comment]
The `dialogs` are updating its size on window resize. (See [here](https://github.com/angular/material/blob/master/src/components/dialog/dialog.js#L749))
In your case they won't resize, because the Dev-Tools won't resize the window, they just overlay.
So if you resize the actual browser window, they will resize.

See here: http://codepen.io/DevVersion/pen/eJrJJR

**Comment by AliPoder** [comment]
actually if you try it on demo of custom dialog, dialog is resizing with dev-tools. and i tried resizing the window but it still the same.

**Comment by DevVersion** [comment]
In my case resizing works great. It may relate to your template of the dialog. But that seems to be a specific question, which should be solved in the [Google Group](https://groups.google.com/forum/#!forum/ngmaterial).
![](https://i.gyazo.com/7dc5b8c82643e415b283c9c1983a25ee.gif)

**Comment by AliPoder** [comment]
well okay, it looks like my issue happens when `escapeToClose` set to false. i'll create a plunker and open another issue to be more descriptive.
