### ISSUE TITLE
Support for input[time]

### ISSUE THREAD

**Issue by rvarbanov** [angular/material#6895]
When I use the input[time] it does not seem to be supported by Angular Material.

This is my code:

```html
<md-input-container>
	<label>From</label>
	<input type="time" placeholder="HH:mm" ng-model="appointment.timeFrom">
</md-input-container>
```
and this is the output:
<img width="504" alt="screen shot 2016-01-28 at 9 07 23 am" src="https://cloud.githubusercontent.com/assets/2780282/12646519/99d27640-c59e-11e5-8984-3819ec4da9cd.png">
As you can see the placeholder is not supported.

**Comment by DevVersion** [comment]
In general `type[time]` doesn't support a placeholder attribute.
 So you think about an extra feature from  Angular Material, which adds placeholder support for `input[time]`?

**Comment by rvarbanov** [comment]
I was not aware of that. After testing, it looks like time inputs do not make use of the placeholder.

I think it would be nice if it did. What do you think?

**Comment by DevVersion** [comment]
I think that won't make any sense to create placeholder support, which is only needed by `type[time]`. It would be much effort and wouldn't make any sense, because there is already an input template for the `type[time]` which will cause issues with a placeholder.

But the decision is from the team. So you can keep that issue open :)

**Comment by ThomasBurleson** [comment]
Will not fix. See pending feature 'TimePicker' in https://github.com/angular/material/issues/5029
