### ISSUE TITLE
mdAutocomplete: md-not-found template flashes before items are displayed

### ISSUE THREAD

**Issue by nfriend** [angular/material#6907]
The `md-not-found` template is briefly (as long as half a second) shown before the `md-autocomplete` displays its result set.  

**See this in action here: https://jsfiddle.net/NathanFriend/Lctcxjqr/**

Expected result: the `md-not-found` template should never be shown if the query returns at least one result.  The examples at https://material.angularjs.org/latest/demo/autocomplete don't exhibit this issue.

Some additional information:

Angular Material Version: 1.0.3
Angular Version: 1.4.9
Browser and OS: Chrome 47.0.2526.111 on Windows 8.1

**Comment by DevVersion** [comment]
Just investigated a bit, the problem is, the autocomplete will set the loading state to false if a previous promise is resolved. So when you search for `A-R-I-Z-O-N-A` (normally typed - not pasted) there will be a promise for each char. So the state of `setLoading` will change to false. This can be solved by adding a simple fetching queue. But only check the queue on the promise `finally` to store the retrieved results in cache.
