### ISSUE TITLE
Some blurriness in Chrome under high-dpi

### ISSUE THREAD

**Issue by akdor1154** [angular/material#6967]
Using Chrome with my Surface Pro 3 on Windows 10 with display scaling set to 125%, fonts in an mdDialog (among other places) appear blurry.
![Chrome (blurry)](http://imgur.com/MsPwBWV.png)
Chrome (blurry)

![Edge (not blurry)](http://imgur.com/hKLSmr3.png)
Edge (not blurry)

The background app is Polymer, not Angular.

On the Angular demo website (viewed at version 1.0.4), the Alert and Confirm dialogs are not blurry, however the Custom and Tab dialogs are.

**Comment by Phr33d0m** [comment]
I'm unsure this comes from Angular at all, as this has been an issue for years. Anyhow I've found the solution to be [this one](https://css-tricks.com/forums/topic/transforms-cause-font-smoothing-weirdness-in-webkit/#post-106050) in most cases.

This can also happens if you're using a ```font-weight``` not corresponding the font. For example, ```font-weight: 700;``` will make Roboto blurry unless you load Roboto:700.

**Comment by ThomasBurleson** [comment]
Will not fix.
