### ISSUE TITLE
mdVirtualRepeat: does not respect md-on-demand boolean value

### ISSUE THREAD

**Issue by vinaygopinath** [angular/material#7063]
I'm using angular-material 1.0.4 and md-virtual-repeat does not seem to consider the value of md-on-demand when I use the following code (`numbers` is a plain old array)
```html
<md-virtual-repeat-container id="list-container">
      <div md-virtual-repeat="num in numbers" md-on-demand="false">
        {{num}}
      </div>
</md-virtual-repeat-container>
```
I see this error:
```
Error: When md-on-demand is enabled, the Object passed to md-virtual-repeat
must implement functions getItemAtIndex() and getLength()
```
[Plunkr](http://plnkr.co/edit/YJUovKA0SaunlckEafeH?p=preview)

Removing the attribute solves the problem. I'd consider doing that, but in my case, I'm wrapping md-virtual-repeat within a directive that determines if the list is paginated (`md-on-demand=true`), or a bulk array of elements (`md-on-demand=false`, like the vertical usage example in the demo page) based on some factors.

**Comment by DevVersion** [comment]
@vinaygopinath Yes, that's because we only check if the attribute exists (See [here](https://github.com/angular/material/blob/master/src/components/virtualRepeat/virtual-repeater.js#L453)). I would like to submit a PR, when  #6803 is merged, because it adds a new util method for validating boolean attributes (using the string attributes).

**Comment by DevVersion** [comment]
Combined that into #6803

**Comment by elineopsommer** [comment]
I still entercounter this problem? I have the latest version of angular-material (1.1.3)
