### ISSUE TITLE
empty md-chips  readonly,  don't show the input field 

### ISSUE THREAD

**Issue by tipodisimmia** [angular/material#7136]
When i use the read only attribute in an empty md-chips the field disappear....

http://jsfiddle.net/bpxa44a5/40/

Ok is on the documentation but...
In a form i need to set in read only the md-chips, but the field must remain visible, so the user can undestand the readonly mode.

**Comment by DevVersion** [comment]
@tipodisimmia Yes, can see that. I'm not sure about this, but it seems like this is not by intention.

**Comment by topherfangio** [comment]
The [Chips spec](http://www.google.com/design/spec/components/chips.html#chips-specs) is unfortunately a bit thin and doesn't currently have anything regarding read-only mode. I believe we made the assumption that for chips, you shouldn't see the nested input since you could see the remaining chips.

Mostly, I believe this was because many people use the read-only mode for static chips to display tags or the like, and there was no input needed in that case.

Perhaps we can discuss this a bit with the Google UX team and get some feedback.

**Comment by topherfangio** [comment]
Sorry; just realized the real problem that this causes: it's not just the nested input that is hidden, but the full chips container. We'll definitely get this fixed.
