### ISSUE TITLE
Font awesome: the doc is not clear and I have a wrong alignment

### ISSUE THREAD

**Issue by cadilhac** [angular/material#7172]
Before checking the doc, I had:

```
<md-button class="md-icon-button md-accent md-fab">
    <md-icon md-font-set="fa" md-font-icon="fa-rocket" class="fa" style="font-size:28px;">
    </md-icon>
</md-button>
```

This is to show an icon inside a FAB. My issue is that the icon is too "bottom aligned". So I checked the doc. I see that I should use:

```
angular.config(function($mdIconProvider) {
  $mdIconProvider.fontSet('fa', 'fontawesome');
});
```

Well, I didn't have that and it changes nothing to do that. Then, the html example says:
`
<md-icon md-font-set="fa">email</md-icon>`

If I use something like that, I see the "email" text, not an icon.

Please, clarify the doc and let me know how the icon can be perfectly centered. Thanks.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by cadilhac** [comment]
Please, what's the status of this?

**Comment by DevVersion** [comment]
@cadilhac Just took a look at your issue.

You have a few problems in your snippet.
- `#fontSet(alias, classname)`
- `Ligature Support`

For the method `#fontSet(alias, classname)`, you used it wrong in your snippet.
In fontawesome the classname is `fa` and the alias would be `fontawesome``
So the correct snippet would look like:

```js
  $mdIconProvider.fontSet('fontawesome', 'fa');
```

So in my opinion, you don't need to specify an alias, since `fa` is even shorter than `fontawesome`

About the ligature support. It seems like `fontawesome` is not supporting ligatures. That means you need to use the given UNICODE, instead of the correct ligature.

https://en.wikipedia.org/wiki/Typographic_ligature#Ligatures_in_Unicode_.28Latin_alphabets.29
```html
<md-icon md-font-set="fa">\&Xf0f3</md-icon>
```

I agree, the docs are a bit unclear here. There are two things that need to be changed.
- Remove Fontawesome (no Ligature Support) and mention its missing support.
- Document the `#fontSet(alias, classname)` method.

cc. @topherfangio
