### ISSUE TITLE
md-select $index not updating

### ISSUE THREAD

**Issue by camden-kid** [angular/material#7173]
There seems to be an issue with $index not updating correctly when used with md-select. I have created an example to display this problem: http://codepen.io/camden-kid/pen/jWJXpL

The `select` behaves correctly, in that after selecting the first option and clicking the invite button the select options are updated and the correct option is shown below. Subsequent selections and clicks of invite also work correctly.

With the `md-select` you will notice that after selecting the first option and clicking invite the options are updated correctly and the correct option is shown below. However, selecting the new first option and clicking the invite button displays the wrong option below. This is because the value of `selectedArtistIndex` is 1, when it should be 0, as can be seen in the console.

**Comment by topherfangio** [comment]
It looks like the `md-select` doesn't currently setup a watch to watch the `value` attribute, it only reads it once. If you instead use `ng-value="$index"`, I think it will work as you expect.

I'm reaching out to the original developer to see if there is a reason we are only watching for changes to `ng-value` instead of both and will get back to you (please ping me if you don't hear back early next week as it means I forgot 😄 ).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
