### ISSUE TITLE
Elements fitting within screen width instead of overflowing

### ISSUE THREAD

**Issue by kanethal** [angular/material#7211]
Hi,
I feel like this should overflow the screen width and scroll horizontally, instead, all the elements are spaced within the viewport width. Can someone point me in the right direction? Thanks!
http://codepen.io/anon/pen/ZQNydW

**Comment by topherfangio** [comment]
The `flex="50"` attribute allows the element to grow and shrink with a max-width of 50%. If you have only two on the line, then they will take up 50% of the available space, but when you add more elements on the same line, they start to shrink so that all of the elements fit.

You may want to review our [Layouts Introduction](https://material.angularjs.org/HEAD/layout/introduction) for more info.

**Comment by topherfangio** [comment]
Also, you might ask this on the [Forums](https://groups.google.com/forum/#!forum/ngmaterial) and see if anyone can help you. GitHub is really for issues/bugs.
