### ISSUE TITLE
$mdToast and HTML entities

### ISSUE THREAD

**Issue by cadilhac** [angular/material#7241]
Example:
`$mdToast.showSimple('&euro;');`

does not display the euro sign.

I tried this too:

`$mdToast.showSimple($sce.trustAsHtml('&euro;'));`

**Comment by DevVersion** [comment]
Yes, I think this will be a really useful addition. What do you think, accepting plain HTML in a simple to toast is in my opinion not a good idea. Maybe we should just en/decode all the HTML symbols instead of parsing the full HTML (not sure how this can be implemented yet). Thoughts?

**Comment by cadilhac** [comment]
Don't ask me how, but would it be possible to just plug ngSanitize and make it sanitize the text to display?

**Comment by DevVersion** [comment]
Yes I don't need to know how, I just wan't to know, how you thought about your request. Should it only encode these symbols or either be able to compile HTML?

**Comment by cadilhac** [comment]
I think, but this is only my personal opinion and need, that a toast should display only simple messages, as per google specs. HTML entities are compatible with what one understands as "simple". An entity to represent a diacritic in my french language is a necessary thing. Html to format text is not necessary.

**Comment by DevVersion** [comment]
I started implementing that enhancement, but I'm not sure about implementing that to the public API, so I'll discuss that with the team. 

Just to pin that here - we can unescape the HTML entities by:
- Retrieving the plain text from a `HTMLElement`
- Manually replacing all entities.

**Comment by crisbeto** [comment]
IMO we could either make an opt-in toggle that would allow you to insert HTML into the messages, or have another method on the `$mdToast` provider that lets you insert HTML (e.g. `$mdToast.htmlContent`).

As for @cadilhac's example, I got it to work work like this:

```javascript
$mdToast.show(
    $mdToast
      .simple()
      .textContent($sce.trustAsHtml('&euro;'))
);
```

And in the template, we can replace the `{{ toast.content }}` with `<span ng-bind-html="toast.content"></span>`.

**Comment by DevVersion** [comment]
@crisbeto I agree, that would be a elegant solution, but it would also interfere with the actual method name. `textContent` expects to have a plain text string. 

I suggest, introducing another option. `htmlContent`, as same as in `$mdDialog`.

What do you think? @EladBezalel @ThomasBurleson

**Comment by DevVersion** [comment]
So, I confirmed with the team and design specifications.

I suggested, adding a new property, called `htmlContent`, which allows to use html strings as content.
Adding this new property, will interfere with a few things:
- The Material Specifications clearly say, that toasts should only show plain text (otherwise use dialogs)
- Once, we allow `htmlContent`, users may use directives in there, which means that we have to compile the string.

Adding a new property won't be a good solution, as well as supporting full HTML strings in toasts.

When using html entities inside of a toast, the user should use the plain UTF-8 (or other encoding) characters instead.

```js
.textContent('Euro Symbol: €')
```

But if it's really important to show HTML entities inside of a **text** value, then you should create a custom toast preset and use your own HTML code.
