### ISSUE TITLE
multiple secondary actions on md-list-item still do not work

### ISSUE THREAD

**Issue by adeptues** [angular/material#7285]
When using multiple "md-secondary" items on a list item only the first one is available as a secondary action.

codepen: http://codepen.io/anon/pen/RabpMQ

This was apparently fixed in 1.0.5 but still persists as in the codepen. was fixed in https://github.com/angular/material/issues/2595 but still perists.

**Comment by DevVersion** [comment]
Yes, the multiple secondary item support was recently added, but in this time ngMaterial changed its release process (see [here](https://github.com/angular/material#-our-release-processes)), so it's actually not released in v1.0.5. When you use the latest changes from `HEAD`, everything will work as expected.

See here - http://codepen.io/DevVersion/pen/JXPJMQ

PS: Please ignore the vertical alignment issue for the `list-item`, this is already known and will be fixed in #7060
