### ISSUE TITLE
md-progress-circular has different size if it is determinate vs indeterminate

### ISSUE THREAD

**Issue by GustavSt** [angular/material#7292]
I have a progress-circular that starts of as indeterminate and then I change it to determinate after x-time.

However the determinate is a lot bigger. Even if I set md-diameter to a specific value the determinate is much bigger than the indeterminate.

I edited the [codepen](http://codepen.io/anon/pen/BKBwRX?editors=1010) from the docs to show the difference (slick the toggle button to change between determinate/indeterminate). 

Related to #5955. It seems when the progress-circular is set to determinate the diameter is the actual one provided.

angular-material 1.0.5;
angular 1.4.9

**Comment by kvetis** [comment]
The issue is caused by this: https://github.com/angular/material/blob/v1.0.5/src/components/progressCircular/progress-circular.scss#L145
The progress is scaled down by the animation.
As mentioned in the referenced issue, the code was added here: https://github.com/angular/material/commit/ff2e92b4b97b5d2531bb53110127b24ffb8b741a#diff-30944a809922510e5d8034a3d99cc5c8R145

**Comment by topherfangio** [comment]
I know that the circular progress has had a lot of work recently. Can you test this against 1.1.0-RC1 or master and see if it's still an issue?

**Comment by crisbeto** [comment]
This is no longer an issue since the latest changes to progress circular.
