### ISSUE TITLE
Position fixed inside md-content is not scrollable

### ISSUE THREAD

**Issue by Artfloriani** [angular/material#7294]
Hey,

I am trying to do the same scroll-over effect as seen [here](http://purecss.io/layouts/marketing/) where a banner div stays fixed while the content scrolls over it.

I am using position fixed for my banner and my scroll-on content div is a block div with margin-top as the same height as the fixed div. 

`#fixedBanner{
    position: fixed !important;
    top:15px;
    width:100%;
}`

This works if I replace the <md-content> wrapping the banner for a div. If I keep the <md-content> the scroll does not work, even if I try to move the page using the side scroll bar. It looks like the fixed div is overlapping the side scroll bar and I can only click on the side scroll bar below the fixed div.

I tried adding `overflow-y: scroll; ` but the same thing happens.

Is this an issue or am I doing something wrong?

**Comment by topherfangio** [comment]
Can you please provide a Codepen demonstrating your issue so we can debug/play with it?

**Comment by Artfloriani** [comment]
I tried to remove almost everything from my html to leave mostly what is important:

http://codepen.io/anon/pen/NNKYrp

Maybe I'm doing something wrong as I'm just starting with Angular-material. If you try to scroll on 'Some Text' div, while being wrapped by the md-content, it won't scroll. If I change the `<md-content>` to `<div>`, it will work as expected. When using `<md-content>` I am able to scroll If the mouse is not on the `position: fixed` div.

**Comment by topherfangio** [comment]
I am not 100% sure why, but it seems to have something to do with using `margin-top: 100px`. I have edited your pen slightly to use `padding-top: 150px` and you can now scroll over the area. I also made the background transparent instead of white.

http://codepen.io/topherfangio/pen/KzPePK?editors=0100

There are a few issues with this because I honestly don't have time to jump in and make it all work, but this should set you on the right path. You will probably need to change your structure of the`<div class="central">` to be more nested, but I hope this helps.

Also, these types of question usually get a better response when posted on the [Forums](https://groups.google.com/forum/#!forum/ngmaterial) as there are more developers who watch that.
