### ISSUE TITLE
(feat) md-tabs + remember last tab selected

### ISSUE THREAD

**Issue by 0101adm** [angular/material#7325]
would be nice to have the last selected tab persist.

**Comment by uxitten** [comment]
you can use md-selected="selectedIndex" attr in md-tabs and bind with $localstorage

**Comment by 0101adm** [comment]
would like to have it work out of the box.

**Comment by uxitten** [comment]
out of the box?

**Comment by 0101adm** [comment]
no need to manually persist

**Comment by topherfangio** [comment]
@0101adm How exactly do you see this working? I mean, what would you do with the last selected tab?

**Comment by 0101adm** [comment]
hey @topherfangio.  ive seen this feature in other frameworks. when the page is revisted, its automatically selected. it seems like a better UX for the user.

**Comment by topherfangio** [comment]
Ah, I see what you mean. I don't think this is a feature of the tabs, I think it is a feature of the application because the component may be destroyed/recreated depending on how the developer writes it. Pretty much anything but `ngShow/Hide` will actually remove it from the DOM and call Angular's `$scope.$destroy()` method, so the component itself can't really keep this state.

I generally handle this type of scenario in my routing. The application remembers the last route that was visited, and you can use the `md-active` attribute on the tabs to active the appropriate one on page load.

**Comment by 0101adm** [comment]
:+1:
