### ISSUE TITLE
md-input-container input type="number" field resizes after value input

### ISSUE THREAD

**Issue by kanethal** [angular/material#7349]
Initial placement is fine. Upon entering a number, the field resizes. I tried setting 
```
    md-input-container input[type="number"]{
      width: auto;
      -moz-appearance: textfield;
      -webkit-appearance: textfield;
    }
```
as per another post (https://github.com/angular/material/issues/4864), without results.

![image](https://cloud.githubusercontent.com/assets/8418137/13412470/b0ac54a0-df00-11e5-8842-c7d59ebfe6bd.png)

![image](https://cloud.githubusercontent.com/assets/8418137/13412483/be807908-df00-11e5-880b-e4f767250933.png)

**Comment by topherfangio** [comment]
Can you please provide a Codepen showing the issue? Particularly, I'd like to know what your layout/container looks like.

**Comment by kanethal** [comment]
Thank you for replying.
Problem is reproduced here: http://codepen.io/kanethal/pen/remgeE

Probably something obvious, thanks for your interest

**Comment by topherfangio** [comment]
@kanethal You can probably use `min-width` to fix this temporarily, but it definitely seems like a bug.

@crisbeto Can you take a look at this please?

**Comment by crisbeto** [comment]
Sure and also wow that's some trippy behaviour.

**Comment by kanethal** [comment]
Great thanks, I'm still learning, and it can be tricky to differentiate
between my bad authoring and legit bugs ;).

These were setup to flex. I worked around the sizing issue by changing the
input type to just text. Not sure how to use min-width and maintain the
responsive sizing!

Thanks for your interest, Dan.

**Comment by crisbeto** [comment]
This seems to be some kind of strange behaviour in Webkit (IE, Edge and Firefox don't have it, but Chrome, Safari and Opera do) that happens if the input is `type="number"` and it has both a `min` and a `max` (if it's only one of them it doesn't happen). The browser seems to set the input width so it can fit the amount of digits in the `max` +/- a couple of characters and ignores all other widths. For example if you have a `max` of `999`, it resizes to fit ~4-5 characters. In the demo, the width is initially fine because the `ng-messages` is pushing it out, but when you enter a valid value, the `ng-messages` get removed from the DOM which makes it collapse.

I didn't manage to hack around it with CSS (e.g. `display: block`, `width: 100%`, `min-width: 100%` etc.) and I didn't find anything in the user agent styles that might be causing this. On the other hand I did find that if that setting the `step` attribute to `any` fixes the issue, but any other values for `step` don't.

@topherfangio I'll put in a PR for setting the `step` to `any` if both `min` and `max` are present.

**Comment by topherfangio** [comment]
@crisbeto Wow; that sounds like fun. Out of curiosity, did you test this with a plain number input? I'm wondering if there is something that Material is doing to cause it.

**Comment by crisbeto** [comment]
Just tried it, it's the same with a plain number input as well.
