### ISSUE TITLE
md-select block command+S and command+R when focused

### ISSUE THREAD

**Issue by AhmadZuhdi** [angular/material#7436]
![error md-select](https://cloud.githubusercontent.com/assets/3438626/13560718/34e8c894-e455-11e5-80f9-66d7cdabd87f.gif)

angular@1.4.9
angular-material@1.0.5
codepen: http://codepen.io/AhmadZuhdi/pen/YqwWWE

**Comment by iRoachie** [comment]
What are you asking exactly?

**Comment by AhmadZuhdi** [comment]
sorry, it is bug or intended?
because it blocks reload and save function from the browser

**Comment by iRoachie** [comment]
I think it's intended behaviour. The same happens for a normal html select. Pen here http://codepen.io/iRoachie/pen/yOeVdW

**Comment by AhmadZuhdi** [comment]
well, I think that clarify the behaviour then,
thanks

**Comment by alexilyaev** [comment]
@iRoachie I think this should be reopened.  
It's true that when the select is open, even the native one, you cannot reload the page with Cmd+R, but once you select an option and the select box is still in focus, with the native one you can, and with `md-select` you can't.

I have a client which specifically files a bug for me for that issue.

I can make a new issue if you want, but I already found this one when I searched for it.

**Comment by iRoachie** [comment]
@alexilyaev When the select is still in focus even after an option has been, the user can still choose options selecting using the letter keys or up and down. Which I think is good behaviour especially for those people who fill out forms using the keyboard only.

**Comment by alexilyaev** [comment]
@iRoachie I was pointing out how the native select works, in which after selection, you CAN do Cmd+R and reload the page, which makes a lot of sense, and is the expected behavior.

If `md-select` listens on key presses and does preventDefault, it's easy to to not do it if Cmd or Ctrl are pressed, and you won't lose any expected behavior like up/down or pressing a character.

Again, this is how the native select works, and me and my client expected the same behavior with `md-select`.
