### ISSUE TITLE
CodePen demos using HTTP resources fail to load with HTTPSEverywhere

### ISSUE THREAD

**Issue by jchull** [angular/material#7459]
This script: http://ngmaterial.assets.s3.amazonaws.com/svg-assets-cache.js is not available via HTTPS, so the entire pen fails to load. Disabling HTTPSEverywhere for codepen.io, or removing this script resolve the loading issue. Suggest that resource be allowed to be served over HTTPS, pretty sure S3 allows you to do that with just a setting

CodePen has an issue on the topic: https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/32

**Comment by Frank3K** [comment]
Good find, was already wondering why the codepens weren't working for me.

**Comment by DevVersion** [comment]
@ThomasBurleson 
Demos for the issue
- Serving with <kbd>https</kbd>: https://codepen.io/DevVersion/pen/pyEoRO
- Serving with <kbd>http</kbd>: http://codepen.io/DevVersion/pen/pyEoRO

As we can see <kdb>https</kbd> isn't working, because you can't inject insecure scripts into a TLS secured page.

>
Mixed Content: The page at [URL] was loaded over HTTPS, but requested an insecure script 'http://ngmaterial.assets.s3.amazonaws.com/svg-assets-cache.js'. 
This request has been blocked; the content must be served over HTTPS.

I can't really do anything about that, the asset cache just needs to be served over HTTPS.

**Comment by ThomasBurleson** [comment]
* when using HTTPS, loading HTTP content will result in a `blocked` content message
* when using HTTP,  loading HTTPS content will **not** result in the message.

#### Solution 
Change the **Launch to CodePen** settings to access the svg asset cache using a secure URL: https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-114/svg-assets-cache.js

**Comment by DevVersion** [comment]
@ThomasBurleson Awesome, thanks for the SSL served asset URL.
