### ISSUE TITLE
demo: github link for master uses git tag that has not been created yet

### ISSUE THREAD

**Issue by jchull** [angular/material#7462]
Current master (1.0.6) URL for github is https://github.com/angular/material/tree/v1.0.6 which the tag has not been created, so only older versions that are tagged navigate to the version on github successfully. Master demo github link should just go to master and be changed to tag as part of the tagging process

**Comment by DevVersion** [comment]
The tag has been created manually, because we had problems with the release script.

By default the release script will automatically create the tag and publish it to the upstream.

I will close that issue, because the release script failed accidentally.

[See the Tag Release Function](https://github.com/angular/material/blob/master/release.js#L179)

cc @topherfangio - Let me know if you had other thoughts.
