### ISSUE TITLE
Autocomplete ng-messages wrong font-size

### ISSUE THREAD

**Issue by gpopovic** [angular/material#7477]
In master, ng-messages font size for autocomplete is wrong.

In codepen, you can compare input ng-message  with autocomplete ng-message
http://codepen.io/anon/pen/ONNgMQ

**Comment by DevVersion** [comment]
Great demo, I'll take a look at this soon.

**Comment by gpopovic** [comment]
Any updates on this one?

**Comment by DevVersion** [comment]
Just investigated a bit and it seems to relate to the scope transclusion.

I tried to create a scope transclusion myself to take a look at its most elegant solution.

http://codepen.io/DevVersion/pen/WwRqaO?editors=1010

So just want to notify you, that this issue is in progress.

**Comment by EladBezalel** [comment]
This is related to the styles applied, 
Take a look at [input messages style](https://github.com/angular/material/blob/dbb75a64e76f5ac1c22b75e48318c6ce4d4095cb/src/components/input/input.scss#L233)

**Comment by DevVersion** [comment]
@EladBezalel Yes actually it is related to the styes. But updating the style selectors won't be the right solution, because the ngMessage isn't retrieving the animation class correctly. 

This is caused by the parent transclusion from the autocomplete. 

(https://github.com/angular/material/blob/master/src/components/input/input.js#L711)

**Comment by EladBezalel** [comment]
:+1:

**Comment by cairomax** [comment]
I am not sure if this may helps:

Pull request https://github.com/angular/material/pull/5637 removed the code the replaces a wrapper div generated by mdAutocomplete. See this line:
https://github.com/angular/material/pull/5637/commits/05d7f24d6929b034036daa43167335d5b32e2b8d#diff-f700fe0b273e851967e22440f2c464eeL25
Also, see the occurences of the string `md-autocomplete-replace` in the whole repository. It was used as a marker class on the div to remove, but it is never taken into account.

Since `mdInputContainer` requires `ngMessages` to be a direct child, this might be the cause of the problem.
