### ISSUE TITLE
Toolbar: mutliple toolbars z-index problem with whiteframe

### ISSUE THREAD

**Issue by richardsengers** [angular/material#7479]
Toolbars always have the same z-index. The z-index of the first toolbar should be higher then the second toolbar to make the whiteframe work. According to this example it must be possible to use more then 1 toolbar
![patterns_errors_app1](https://cloud.githubusercontent.com/assets/810038/13632188/bbcc9ee6-e5e8-11e5-8faa-fbf0658385f9.png)

source: https://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors

You can find an example here:
http://codepen.io/richardsengers/pen/XddaoZ

When enabling the css with z-index: 3, you can see the desired result.

Maybe another approach would be not to use double toolbars, but a md-content like in this example
http://codepen.io/richardsengers/pen/WwwZZZ

But I don't think that's according to the design specs.

Any feedback on this would be appreciated 

(Material design 1.0.6)

**Comment by topherfangio** [comment]
I don't think that is supposed to represent a second toolbar, but rather the "background" layer that you can find here: http://www.google.com/design/spec/style/color.html#color-themes

So, I *think* what you want is for the "On and switch" to be on the background layer, the "Google WiFi, Public WiFi" to be in a list, and the "Wifi password incorrect" to be in a dialog.

I don't really see anywhere else in the spec where they have a double toolbar, so I would stray away from that approach. That said, if you really want to, I think the easiest thing would be for you to add a custom "inset" class to the toolbar and drop the z-index, but I don't think this is something we want to support globally.

If you find some instances in the spec with a secondary toolbar, definitely let me know and we'll reconsider. Otherwise, I think this is just some app-specific styles you'll need to implement.

**Comment by richardsengers** [comment]
Thanks for clearing this one up
