### ISSUE TITLE
ng-click on md-list-item not triggered in Firefox

### ISSUE THREAD

**Issue by cgx** [angular/material#7490]
When defining an `ng-click` on a `md-list-item`, the action is never triggered in Firefox (tested with version 45).

Explicitly using a `md-button` inside a `md-list-item` is a workaround, but requires to use the now *private* underscore classes.

Test available on [codepen](http://codepen.io/flachapelle/pen/ZWWRVV).

**Comment by gpopovic** [comment]
+1

**Comment by devotis** [comment]
Looks like this problem got re-introduced with Material 1.1.1

This is 1.0.9:
![image](https://cloud.githubusercontent.com/assets/465989/18959214/954496f2-8665-11e6-8d04-6b403c04d320.png)
This is 1.1.1
![image](https://cloud.githubusercontent.com/assets/465989/18959228/a1a2a470-8665-11e6-82b5-347810d878f4.png)

I can't click the items in de list or at least the method defined with ng-click is not called with 1.1.1

This time however the problem is with both Chrome and Firefox.

**Comment by sjmiller85** [comment]
+1

**Comment by devotis** [comment]
@sjmiller85 You're +1-ing a closed issue. Do you have a test case or does the codepen previously provided actually produce the bug for you?
