### ISSUE TITLE
mdDialog: is there any way to provide already existing content (domNode)?

### ISSUE THREAD

**Issue by vajnorcan** [angular/material#7566]
versions 1.0.6, 1.1.0-rc1

I've been playing around the mdDialog that I'd like to use as a UI for the settings of the application. The content of the settings uses other Angular Material components (buttons, switches, selects), let's say up to 12 components.

It works reasonably well on the non IE browsers, but on IE it takes a really long time to render the template and inject it with all the scope values and to render the inner components. If the template is a simple text it's realtively quick.

I was wondering, is there any way I could provide the mdDialog already rendered content (with display: none; ) and keep the reference to this dialog somewhere (or I could place this content some elsewhere on hide)? Or does the mdDialog always constructs the inner content and destroys it?

Thanks

**Comment by topherfangio** [comment]
@DevVersion Can you please take a look at this and see if there is a way to do it right now? If not, can you mark this as Priority 4 and make it a feature request?

**Comment by DevVersion** [comment]
@topherfangio This can be easily done, by the interim element API. 

```js
$mdDialog.show({
  skipCompile: true,
  element: myDialogNode
});
```

But this will cause an error within the dialog service, because the dialog service tries to find a `<md-dialog>` element, but this isn't present, because there is no template processing and compilation anymore.

I've created a PR, which makes the dialog service compatible with the interim _skipCompile_ API and also added a test, which represents this issue.

**Comment by ThomasBurleson** [comment]
@topherfangio, @DevVersion - The idea is great... but I do not like this API.

**Comment by topherfangio** [comment]
@ThomasBurleson Are you worried about the `skipCompile` API? That already exists and is used by the select and menu components.

**Comment by ThomasBurleson** [comment]
```js
$mdDialog.show({
  anchor: myDialogNode  // existing element that will be extracted from the DOM, used in md-dialog-content, and then restored after dialog close.

});
```

* if the element is not found, log a warning
* anchor could be a element *reference* or a *query-selector*

**Comment by DevVersion** [comment]
@topherfangio Just talked to Thomas about the API. 

We found a good way to support element references. We wan't to add a property, which supports an element reference or a query selector.
```js
$mdDialog.show({
  contentElement: myDialogNode
});
```

If the `contentElement` value is an element, which is added to the DOM, then we'll extract it and restore it upon close. (Same for the Query Selector)

If it's just an element, which is virtual present, then we won't restore it, because it has actually no parent. So we will just remove it from the dialog container.

I think that's a very elegant solution and I like it.

**Comment by topherfangio** [comment]
@DevVersion Great! I was worried about naming it `anchor` because people might think that it has something to do with positioning. I like `contentElement` a lot better.

:+1:

**Comment by vajnorcan** [comment]
good stuff guys. thanks for implementing this that quickly. I'll be watchi this space for a new rc!

**Comment by DevVersion** [comment]
@topherfangio @ThomasBurleson This issue is currently blocked, due some missing information.

I've noticed, that using an existing DOM element (`anchor`-element) wouldn't make any sense, because the `md-dialog` directive is using an absolute position and applies some colors, which would mean that the page breaks. 

Hiding the element using `display: none` is likely the same as just providing the element as a variable.
```js
var contentEl = angular.element(...);
```

**Comment by topherfangio** [comment]
@DevVersion I believe that the point was to let the DOM element render off-screen (or some variety of non-visible) so that when the dialog opens it, it doesn't try to compile/render anything. I think this is for like static/known content, etc.

@vajnorcan Does that sound accurate?

**Comment by vajnorcan** [comment]
@topherfangio That is correct. If the dialog contains quite a lot of elements (with some data injecting from model), then the rendering suffers. I was thinking to generate the content once, then assign it to dialog as a content, and let dialog do the positioning. Once the dialog is closed, it should not be destroyed, rather it be display:none; Hope that makes more sense.

**Comment by ThomasBurleson** [comment]
This is related to another issue request to cache the Dialog content between hide/shows.
