### ISSUE TITLE
Error when trying to open a bottom sheet in this specific situation

### ISSUE THREAD

**Issue by cadilhac** [angular/material#7572]
Here is the codepen to reproduce the issue: http://codepen.io/anon/pen/dMOXdo
I'm targetting MASTER but it is the same problem with 1.0.6

I am using ui-router with states defined so that it's easy to display dialogs and bottom sheets. I started with dialogs and it works well. A parent state defines how to open the modal. A derived state defines what is the template to load in the dialog (inside a ui-view).
I copy/pasted this code for bottom sheets and this time it doesn't work. I get an error:

> Error: target[0].querySelectorAll is not a function
> scanForFocusable@http://gitcdn.link/cdn/angular/bower-material/master/angular-material.js:42:79
> UtilFactory/$mdUtil.findFocusTarget@http://gitcdn.link/cdn/angular/bower-material/master/angular-material.js:41:409
> onShow/<@http://gitcdn.link/cdn/angular/bower-material/master/angular-material.js:251:98

(sorry, this error is displayed in the console when my app runs but it is not displayed by the console of codepen, don't know why...)

In the codepen I have added a third case where the bottom sheet is a single state and there is no template. In this case it works.

**Comment by topherfangio** [comment]
Just tested your Codepen and I can't get the error to occur. Have you changed the Codepen recently?

That said, if you simply put the `ui-view="sheet"` attribute on a `<div>` inside of your `<md-bottom-sheet>`, it seems to work: http://codepen.io/topherfangio/pen/EKZPbj?editors=0010

**Comment by cadilhac** [comment]
Thanks for the workaround.
That said I don't understand why you can't reproduce the issue. If I take your new codepen and set the ui-view back on the md-bottom-sheet, it won't work.

**Comment by topherfangio** [comment]
@cadilhac Sorry for the confusion; it definitely doesn't **work**, but it doesn't throw an **error**. I was hoping to reproduce the actual error so we could fix it.

I tried to dig into the ui-router source a bit to find out what's going on, but I don't have time to track it down at the moment. It seems to be something within the following directive:

https://github.com/angular-ui/ui-router/blob/1e46c8d/src/viewDirective.js#L120

Of note, I noticed that each time you click the button, the `updateView()` method (https://github.com/angular-ui/ui-router/blob/1e46c8d/src/viewDirective.js#L244) is called twice for each time you have pressed the button.

 * So, the first time, it's called twice (which I think is correct because it has a `firstTime` attribute it passes).
 * The second time, it's called 4 times,
 * The third time, it's called 6 times.
 * etc.

It seems like it's getting confused and recompiling the view multiple times. Additionally, both the `ui-view` directive and the `md-bottom-sheet` apply their own enter/leave transitions which very well may be causing issues.

If you can track down the exact issue, we'd be happy to look into it more, but I think the general solution is to not use `ui-view` as an attribute on the bottom sheet (and possibly some other components).
