### ISSUE TITLE
md-progress-circular with svg animation slow in Android

### ISSUE THREAD

**Issue by GustavoCostaW** [angular/material#7577]
After launch 1.1.0-rc1 the md-progress-circular was totally rewrite with svg, but the animation is so low in good Android devices :( Works fine in before version of animation 1.0.6, someone have answer about this?

**Comment by crisbeto** [comment]
What version of Android are you running (it might be falling back to a timeout-based animation if your device doesn't support requestAnimationFrame)? The framerate was pretty good on the devices that I've been testing (an iPhone 5 on iOS 9.3 and an iPad mini). 
Otherwise the progressbar is being animated with js for compatibility reasons (the CSS animation doesn't work on IE) and that might not be quite as fast as CSS.

**Comment by GustavoCostaW** [comment]
I test in Moto X (second gen) with Android 6.0... It's a good device man.

**Comment by crisbeto** [comment]
Alright, well that isn't a lot to go on. Are you running it inside an app or just running the demo?

**Comment by crisbeto** [comment]
Managed to get my hands on an Android emulator which has somewhat decent performance. I wouldn't say there's too much of a difference between the framerates of the old and the new, considering the improvement in quality. Below's a side-by-side between the two: 

**New implementation:**
![new](https://cloud.githubusercontent.com/assets/4450522/13794706/9649cc7e-eafd-11e5-8ad2-15aea2e5388d.gif)
--- 

**Old implementation:**
![old](https://cloud.githubusercontent.com/assets/4450522/13794916/c4dd268e-eafe-11e5-9545-21a83e140ac7.gif)

**Comment by GustavoCostaW** [comment]
Angular Material version with SVG: 1.1.0-rc1 (I left on display md-progress-circular for testing, check that it takes a while to start the animation when the screen begins, delay to appear and start animation)

https://www.dropbox.com/s/b2a90fycnlv0cob/final-problem-1.1.0rc1.mp4?dl=0

1.0.6 ( Check when I change the routes not have lag in animation and the md-progress-circular show fast)

https://www.dropbox.com/s/ha2cb7wwgqcz03s/fine-1.0.6.mp4?dl=0

@crisbeto @DevVersion

**Comment by crisbeto** [comment]
It definitely takes a bit for the whole thing to get set up and we don't really have too much control over how and when it starts to execute since the whole point of `requestAnimationFrame` is to let the browser determine the best time for something to happen. 

How are you showing/hiding the progressbar? If you're removing and adding it to the DOM (e.g. with `ng-if/ng-switch/` or having the loader be a part of each partial), you could switch to using `ng-show` instead, which will only render it once and will be much quicker to start up afterwards.

**Comment by DevVersion** [comment]
@GustavoCostaW At first, your app looks very nice, like a native app :+1:

And yes, I can see the difference between your versions. That's why we need more information about your device, maybe your browser has some SVG constraints.

So can you please provide more browser specific information:
- Are you running this in an Android `WebView` (which BrowserAdapter? - Chrome, Default)
- Is this an App, which has been added to the Home Screen? (Which Browser? Chrome, Opera)
- Mobile Browser Version (Version)

**Comment by GustavoCostaW** [comment]
@crisbeto I'm using ng-show to show and hide loadings.... 

@DevVersion Thx for feedback :)

- I'm using Cordova for build application, yes, the WebView is Chrome.
- Debugging application in inspect and console.log(navigator.userAgent) is 

"Mozilla/5.0 (Linux; Android 6.0; XT1097 Build/MPE24.49-18; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/48.0.2564.106 Mobile Safari/537.36"


Moto X (second gen) Android 6.0

**Comment by crisbeto** [comment]
Hmm are you sure? The animation wouldn't restart like that unless it either has a specified `value` or it gets added/removed from the DOM. That being said, I've been playing around with a way that will allow the animation to start earlier than the first digest. I'll push something for it a bit later.

**Comment by DevVersion** [comment]
I agree with @crisbeto, it seems like the animation will start, when the digest is performed. The circular should run independently of the digest IMO.

**Comment by GustavoCostaW** [comment]
@crisbeto @DevVersion It's inside the my custom directive, but like video, I only update Angular and this problem runs... 

@crisbeto I not have value in progress, I'm using exactly this:

`<md-progress-circular class="md-primary" md-mode="indeterminate"></md-progress-circular>`

**Comment by crisbeto** [comment]
And where's the ng-show? Is it somewhere on the parent?

**Comment by GustavoCostaW** [comment]
@crisbeto yep, ` <div class='loading' ng-show="!summary.data.data">
            <md-progress-circular class="md-primary" md-mode="indeterminate"></md-progress-circular>
        </div>`

**Comment by GustavoCostaW** [comment]
@crisbeto @DevVersion for my curiosity, what the angular and angular animate version you use in your tests?

**Comment by crisbeto** [comment]
I'm testing with 1.4.8.

**Comment by GustavoCostaW** [comment]
fixed.
