### ISSUE TITLE
build-all-modules throws error

### ISSUE THREAD

**Issue by magic-77** [angular/material#7612]
Hi,
i´m trying to build all components with
`gulp build-all-modules` but it throws an error:

   Building` material.components.select ...
       events.js:85
        throw er; // Unhandled 'error' event
                ^
    Error: src\components\select\select-default-theme.scss
    Error: no mixin named checkbox-primary

           Backtrace:
            stdin:362
            on line 362 of stdin
    @include checkbox-primary('[selected]');
      

how to fix this?

**Comment by DevVersion** [comment]
Indeed, introduced in 3524aa9573fe29e53341c60ce6127fc7ad323446, I'm currently trying to find a way to make the select dependent to the checkbox. But by building all the modules, the dependencies have no role... A solution would be: 
- Move the mixin to the mixins.scss

But that would destroy the component project structure, because the styles of a specific component should be in the same directory / file.

**Comment by DevVersion** [comment]
Also prevents the update of `bower-material` and the docs.

cc @ThomasBurleson

**Comment by magic-77** [comment]
Hi DevVersion,
i moved the Mixins "checkbox-primary" and "checkbox-container" to mixins.scss. Now compiling Process runs fine.
When i take a look inside core.css i see some unprocessed vars.
Just a snippet of these:

`html.md-THEME_NAME-theme, body.md-THEME_NAME-theme {
  color: '{{foreground-1}}';
  background-color: '{{background-50}}'; }`

**Comment by topherfangio** [comment]
@DevVersion I'm assigning this one to you since you've taken lead. Please ping me if you need help ;-)
