### ISSUE TITLE
mdMenuBar: Switching from one menubar item to another and back again causes the menu to hide

### ISSUE THREAD

**Issue by nkeeslin** [angular/material#7626]
This bug can be seen on the demo page https://material.angularjs.org/latest/demo/menuBar
If you click on a top level menu item then hover over a neighboring item and then return to the original item, the menu closes and then won't re-open if you click on that first menu item.  To get it to open, you have to click on a different menu item.

Angular-material v1.0.6

**Comment by RolandHeath** [comment]
Which browser are you using, and is the issue still present in 1.1.0-rc1?

**Comment by topherfangio** [comment]
I know we fixed something similar to this recently, so please do test again on HEAD or 1.1.0-rc1 and provide us browser info.

**Comment by nkeeslin** [comment]
I just re-tested it using 1.1.0-rc1 with the same results.  I'm using Chrome version 49.0.2623.87 (64-bit)

**Comment by RolandHeath** [comment]
I think I've worked out the missing piece - you have to hover and return to the original item faster than the close animation, in order for this to occur. Which is why I was originally not seeing this. 

So, to repro (1.1.0-rc2, chrome 48-ish):
1. Click a top level menu item.
2. Hover a neighbouring top level menu item, then quickly (before the open animation ends, I think) move back to the first one.
Both menu items should close, and the first top level menu item now has focus as though it has been clicked.
3. Click on the first menu item. Nothing happens.
4. Hover/click another menu item to fix.

I found that hovering/clicking another menu item was enough to clear things up again, the first menu item displayed as though it had focus but until clicking on it again, tabbing didn't move to the next menu item, and that tabbing to the next menu item didn't clear/fix the issue but using the arrow keys did.

**Comment by topherfangio** [comment]
@RolandHeath Thanks for the extra info; it looks like this is still happening on HEAD as well.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
