### ISSUE TITLE
Disabled fieldset won't apply disabled styles to child elements

### ISSUE THREAD

**Issue by antoinebrault** [angular/material#7639]
Fields/buttons in a disabled fieldset should have the same style as disabled fields/buttons.
http://jsbin.com/gajohacimo/1/edit?html,js,output

See https://github.com/angular/material/issues/895
https://github.com/angular/material/commit/66fa1e3e276ddf33d669da0ef4d13c73c668e654#diff-f95bd6261dc8555a2e9557219ff9851d
was modified in 
https://github.com/angular/material/commit/5da3c4561e690c2ba0c7f6f01abaa5d0a3cae111#diff-f95bd6261dc8555a2e9557219ff9851d

**Comment by antoinebrault** [comment]
Should probably be: 

```css
.md-input {
    &[disabled],
    [disabled] & {
	[disabled] {
		...
	}
}
```

**Comment by crisbeto** [comment]
@topherfangio I've fixed the issue for inputs and buttons, however there are quite a few components that have `[disabled]` styles, but don't account for the parent being disabled. Here's the full list:

* autocomplete
* button
* checkbox
* datepicker
* input
* radio
* select
* slider
* switch
* tabs

This might turn into a pretty large amount of changes since some components (like the checkbox) would also need to traverse the DOM in order to determine whether to disable the interaction. Do we really want to jump down this rabbit hole?

Alternatively a pretty quick and easy fix (note that it doesn't work in IE10 and below) could be to only account for the "static" state (for example a button that isn't being hovered) and use `pointer-events` to disable any hovers or clicks:

```css
fieldset[disabled]{
  pointer-events: none;
}
```

**Comment by topherfangio** [comment]
@crisbeto I think this would be a great addition, but I honestly think we have some higher-priority issues to address first, so I would hold off on any work on this for now.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
