### ISSUE TITLE
clickable md-list-item contents not filled

### ISSUE THREAD

**Issue by Shirohana** [angular/material#7656]
excuse me (´・ω・｀)
Should it has 'box-sizing: border-box' attribute?
or just I used it in the wrong way?

http://codepen.io/shirohana/pen/jqBLzv?editors=1100

**Comment by DevVersion** [comment]
The list item should have a padding of 16px at left and right.

![image](https://cloud.githubusercontent.com/assets/4987015/13914729/91227fd2-ef50-11e5-8ee8-f81d29662b9f.png)

**Comment by Shirohana** [comment]
I know but if it without 'box-sizing: border-box',
it'll get out of boundary (´・д・｀)
<img width="567" alt="2016-03-21 5 47 51" src="https://cloud.githubusercontent.com/assets/11359892/13915131/b0a41ed2-ef8d-11e5-825d-5f7cc8c22288.png">

**Comment by DevVersion** [comment]
@Shirohana You are right, this is an issue on your demo.

And we recently fixed that in `master` / `HEAD`, you still have this issue, because you're using `v1.1.0-rc1`.

But I also noticed that `bower-material#master` is not containing the newest changes. That's why you can't use `gitcdn.link/...../master`.

Here is a demo, which includes the fix
http://codepen.io/DevVersion/pen/zqZRZB?editors=1100

So as conclusion, it is fixed with SHA 91585893db8a84312b9fb2a904008ffb169e0946

**Comment by Shirohana** [comment]
I'm using version `v1.1.0-rc1` because I just fork your mdSidenav demo directly (๑•́ з •̀๑)

Thanks a lot for your reply and solved my problem (๑• ω •๑)
