### ISSUE TITLE
md-tabs content not swipeable with or without md-swipe-content

### ISSUE THREAD

**Issue by jdgeier** [angular/material#7669]
I downgraded from 1.10.0-rc1 to 1.0.6 and it resolved the issue. I did a cursory search and did not see this issue open for 1.10.0-rc1. I hope this is not a duplicate.

**Comment by DevVersion** [comment]
Oh it works like a charm for me.

See http://codepen.io/DevVersion/pen/bpqmdx

**Comment by jdgeier** [comment]
That's because you are using https://cdn.gitcdn.link/cdn/angular/bower-material/v1.0.6-master-991cd7a/angular-material.js 1.0.6

**Comment by DevVersion** [comment]
@jdgeier Yes that's true, but the tag `v1.0.6-master-991cd7a` is one of the latest deployed versions into `bower-material`. We are still tagging the `v1.1.0-rc1` version with `v1.0.6`, since it's a release candidate.

To convince you:
`v1.0.6-master-`**`991cd7a`** contains these SHA shortcut, which referes to SHA 991cd7a, which is the latest commit.

That means, my demo is using the most recent version.
