### ISSUE TITLE
md-backdrop animation doesn't work

### ISSUE THREAD

**Issue by GuyPie** [angular/material#7717]
Hi,
The animation on the backdrop when opening dialogs seems to be broken in angular 1.4 and up (it works on 1.3.16). I tried it on versions 1.0.5 and 1.0.6. Attached is a codepen:

http://codepen.io/anon/pen/remGoe

**Comment by DevVersion** [comment]
Updated your demo, to use v1.3.16, and it seems like it's working there. 

That's really strange, because we are using ngAnimate probably here:
- https://github.com/angular/material/blob/master/src/components/dialog/dialog.js#L869

Maybe it's a bug, related to ngAnimate, I will dive into it as soon as possible.

http://codepen.io/DevVersion/pen/grWQYQ

**Comment by DevVersion** [comment]
@GuyPie Just tested it again and it works fine, when I use my own demo with the same assets.

http://codepen.io/DevVersion/pen/oxwXBz

Also fixed your problem in your demo, by changing codepens `rootElement` to `body`. (http://codepen.io/DevVersion/pen/EKXjoV)

Another possibility is, bootstrapping the app from the `body` element (http://codepen.io/DevVersion/pen/QNgbaz)

So as conclusion, the wrong animation is caused by your entrypoint of the application.

- `$rootElement`, which is used by the interim element, to find a possible parent, if none is specified.
