### ISSUE TITLE
md-slider-container in a directive produces errors in the console

### ISSUE THREAD

**Issue by camden-kid** [angular/material#7728]
If you view [this CodePen example](http://codepen.io/camden-kid/pen/remqNg?editors=1010) with the console window open you will see that moving the slider in a md-slider-container produces the following error:

> console_runner-ba402f0….js:1 TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
>     at TypeError (native)
>     at ctrl.fitInputWidthToTextLength 
>

**Comment by DevVersion** [comment]
@EladBezalel Seems like the `md-slider-container` is depending on the `md-input-container`, maybe we should document the slider container as well. And explain what it does and what the requirements are.

Currently the directive description is really unnecessary / empty.
https://material.angularjs.org/HEAD/api/directive/mdSliderContainer

**Comment by Magador** [comment]
If I understand correctly, when [jqLite is called to find `md-input-container`](https://github.com/angular/material/blob/master/src/components/slider/slider.js#L73), it is because `md-input-container` should be present in the `md-slider` template, but it is not present.

And since `var input = element.find('md-input-container')` returns an empty jqLite object, `getComputedStyle(input[0])` is called with `undefined`, thus throwing an error.
