### ISSUE TITLE
mdListItem: some styling issues

### ISSUE THREAD

**Issue by aldeso** [angular/material#7742]
- Avatar 3-line-item must be positioned on top, instead vertically centered
- Checkbox in secondary container is not vertically centered (Avatar with Secondary Action Icon)

The item directive sould not used to break styling issues. It´s only a list item! Less is more! Somtimes its better to start from scratch, Sorry.

**Comment by DevVersion** [comment]
@aldeso We are working internally on a new `list` component. We have noticed that the current list implementation contains a lot confusing containers and more.

We are currently minimizing the work on the list item and focusing on the new component.
Meanwhile #7651 will be one of the last PR's for the old list implementation.

**Comment by aldeso** [comment]
@DevVersion Great news! 

A demo for the Checkbox issue? Please check your self made demo! (Avatar with Secondary Action Icon)!

I´ve already developed a new list-item. I make a PR next week. Perhaps you'll find it useful...

Greetings

**Comment by DevVersion** [comment]
@aldeso Yes, I will take a look at it later and recheck with #7651 

About your PR, I don't think a PR is currently desired for the list component. We are still planning and analyzing the current implementation.

But if you really would like a PR for that, then I will take a look, maybe we'll find some useful concepts.

**Comment by DevVersion** [comment]
@aldeso I've tested it with #7651 and it's fixed in there.

About the avatar in the 3-line-item, I can see that and it's only happening when using `ng-click` with it.

So please file another issue for the 3-line-item avatar and mention that this bug was even present before the big component refactor.

Meanwhile I'll close that issue, because it's already a known issue and it's fixed in #7651.
