### ISSUE TITLE
Right-align icons in md-select

### ISSUE THREAD

**Issue by noilly** [angular/material#7755]
I can't right-align an icon in an md-select.

Here is my code-pen that exposes the issue: http://codepen.io/noilly/pen/JXJEdJ

It appears this is because, by default, the icon has a margin of "auto". Setting the margin to "0" appears to correct the issue.

This incorrect behaviour only appears to occur when the menu is open for selection.

**Comment by topherfangio** [comment]
It looks like you're using `<div layout="row" layout-align="space-between">`, so I think that is the expected behavior. If you want, you can replace

    <div>{{network.ssid}}</div>

with

    <div flex>{{network.ssid}}</div>

This will make the name div fill up available space (right now it's only taking up as much space as the text) and it will push the icon to the right. Alternatively, you can put a `<div flex></div>` between the two to take up available space.
