### ISSUE TITLE
md-checkbox inside md-list-item have wrong colour text in 1.1.0-rc2

### ISSUE THREAD

**Issue by kylemacfarlane** [angular/material#7885]
You can see this bug in the list demos.

Under 1.1.0-rc2 labels for checkboxes in lists are a lighter shade of grey: http://codepen.io/anon/pen/reYGVp

Which doesn't happen in the demos for 1.0.7: http://codepen.io/anon/pen/GZOMpK

**Comment by DevVersion** [comment]
@DerekLouie I investigated at that issue and found the problem, which was introduced in SHA 3524aa9573fe29e53341c60ce6127fc7ad323446

The actual bug is, that you added a line in the select theming, which uses an attribute selector.
```scss
[md-checkbox-enabled].md-THEME_NAME-theme {
```

So the issue is, that the `theming` service, is only checking for `class selectors` and `element selectors`, which means, that the `[md-checkbox-enabled]` selector isn't working.

```js
/((?:(?:(?: |>|\.|\w|-|:|\(|\)|\[|\]|"|'|=)+) )?)((?:(?:\w|\.|-|\[|\])+)?)\.md-default-theme((?: |>|\.|\w|-|:|\(|\)|\[|\]|"|'|=)*)/g;`
```

So this bug can be solved, by replacing the `[md-checkbox-enabled]` attribute with a class selector.

**Comment by DerekLouie** [comment]
Ahh very good catch! I will change this with haste. Thank you for looking into this :)
