### ISSUE TITLE
Required asterisk on md-select

### ISSUE THREAD

**Issue by corentin-gautier** [angular/material#7928]
@DevVersion As mentioned in #6647 it would be great to have the same required asterisks on md-select as for normal input.

**Comment by DevVersion** [comment]
Yes, this will be an easy fix, but at first we need to confirm with the Specs, did you find anything in the specs yet, which shows a required asterisk on the select label?

**Comment by corentin-gautier** [comment]
@DevVersion I don't think I ever saw it in the specs but IMO that would not be very coherent to have a form with required inputs with asterisks and required select without.

**Comment by DevVersion** [comment]
@corentin-gautier I agree with you. @ThomasBurleson what do you think?

**Comment by manuelagard** [comment]
+1

**Comment by djmarquette** [comment]
We are manually adding the asterisk to our required select fields to maintain consistency with our required input fields.  It's ugly, and await a better solution.  Thanks.

**Comment by vlichtenberg** [comment]
I'm still getting an issue here, and I suspect that it's because `containerCtrl.label` can't be evaluated [here](https://github.com/angular/material/commit/d9784584d82070894965170f7c598825e2a95310#diff-d7b463f733c2e3fbc783f38073561b74R293). When I put this block into a function and then execute it when the class processes, it does work (same as the setupAttributeWatchers method in inputTextareaDirective).
