### ISSUE TITLE
md-input-messages not displayed on IE11 with 1.1.0-rc2 

### ISSUE THREAD

**Issue by peio72** [angular/material#7931]
The md-input-messages (or error messages)are not displayed on IE11.

I see it's working if i remove: overflow:hidden

from the css rule: angular-material-css, line 2230:
md-input-container .md-input-messages-animation

Please help.

**Comment by mpiasta-ca** [comment]
[I can open the demo in IE 11](https://material.angularjs.org/latest/api/directive/mdInput) and error messages appear without any problems.

You will need to post a codepen/plnkr to demonstrate the specific error in your use case.

**Comment by peio72** [comment]
Could you mail me so I can show you on live app.

**Comment by DevVersion** [comment]
Thanks @peio72 for the issue. But I'm not able to reproduce this as well. You're not providing much information (like Exact Browser Version, Operating System etc.)

Please resubmit your issue with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Comment by peio72** [comment]
Sorry, but i can't reproduce it in Codepen. I can show you the issue on our live app. Please email me. Thanx.

**Comment by DevVersion** [comment]
@peio72 Hm, this is weird. For the start it would be enough, to know, which Browser Version, OS Version you have. Please resubmit with the new issue template.

You can skip the CodePen section :)

**Comment by peio72** [comment]
Behavior:

    What is the issue?

The md-input-messages (or error messages)are not displayed on IE11.

I can make it working if i remove: overflow:hidden

from the css rule: angular-material-css, line 2230:
md-input-container .md-input-messages-animation

    What is the expected behavior?

md-input-messages displayed on IE11 like others browsers.



Angular Versions: 

    Angular Version: 1.5.5
    Angular Material Version: 1.0.8

Additional Information:

    Browser Type: Internet Explorer, Edge
    Browser Version: 11
    OS:  Windows 7 and Windows 10
    Stack Traces:
