### ISSUE TITLE
$mdDialog text content not shown when 'onShowing' option is used

### ISSUE THREAD

**Issue by mdenburger** [angular/material#7944]
When the $mdDialog option `textContent` is used together with an `onShowing` callback, the text content is not shown anymore.

Code example:
```javascript
$mdDialog.confirm({
  title: 'foo',
  textContent: 'bar',
  onShowing: function () {
    console.log('showing dialog');
  }
}).show();
```
This confirmation dialog will only show the title 'foo', and not the text content 'bar'.

It seems that Angular Material uses the default `onShowing` function to initialize essential parts of the dialog, including the text content. When a custom callback function is used the dialog is not initialized properly anymore. That's unexpected: the `onShowing` callback should just be a hook, and the default implementation should do nothing.

**Comment by DevVersion** [comment]
@mdenburger I can reproduce your issue. 

This is because we're validating `textContent` and `htmlContent` in the `onShowing` function, which has been overridden by your custom options.

I suggest, moving the validation down to the `onShow` function, this will allow developers to use the `onShowing` function probably.

https://github.com/angular/material/blob/master/src/components/dialog/dialog.js#L596-L610

@jelbourn What do you think? since you originally introduced the validation.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
