### ISSUE TITLE
Required validation is not working for md-select dropdown if the ng-model value is not null

### ISSUE THREAD

**Issue by indrajithreddy** [angular/material#7954]
In my case I am using integer type for ng-model value which by default contains value as zero.
The ng-options doesn't contain any item with the value zero. But still validation is not firing.

If I set model value as null then it is working.

please check the below link.

https://plnkr.co/edit/X8zJ56?p=preview

**Comment by nebulr** [comment]
I'm still seeing this issue with 1.1.0-rc.5

**Comment by topherfangio** [comment]
@nebulr Can you please provide a Codepen against the latest master branch that reproduces your issue so we can take a look?

**Comment by nebulr** [comment]
@topherfangio just updated the dependencies for the plunkr above. Same problem.

[https://plnkr.co/edit/pj26hRGMPTl6OJm2vf50?p=preview](https://plnkr.co/edit/pj26hRGMPTl6OJm2vf50?p=preview)

**Comment by topherfangio** [comment]
@nebulr By default, we still hide the message until the form has been altered/submitted. If you want them to appear immediately, you can use the `md-auto-hide="false"` expression:

https://plnkr.co/edit/H64bgR31cop84QEAqkP1?p=preview

Does this work for you?

**Comment by nebulr** [comment]
@topherfangio Well that doesn't really make sense for validation since ng-model is not null and required is true. statusForm.status2.$error should be an empty object at that point but its not. The md-select should be valid but its still throwing an error that its required. Because it doesn't function it makes the whole form invalid. 

Here's an example of a use case: 

Say I have some md-select fields that need to be pre-populated based on previous entry. I'm editing a user for one field like changing an email address and all the md-select values I had already selected should have pre-populated the md-select directives in the form. But low and behold I can't submit the form because all of the pre-populated md-select directives are invalid. I have to then manually go through each md-select change a selection and change it back for them to correctly validate. See the problem?

If the ng-model != null for that required md-select it should validate correctly.

[https://plnkr.co/edit/l41Tf0Sjwz6iJYdSkW1d?p=preview](https://plnkr.co/edit/l41Tf0Sjwz6iJYdSkW1d?p=preview)

**Comment by topherfangio** [comment]
@nebulr Apologies, I misunderstood what you were saying. I thought you were saying that the message was **not** showing up when it **should**. Instead, you were saying that the input was marked as invalid when it **should** have been valid. Correct?

Regardless, we've made a bunch of changes since RC5, so I updated the Plunkr to HEAD instead of 1.1.0-RC5 and it appears to be working properly now. Can you confirm that it works if you upgrade to HEAD/master?

https://plnkr.co/edit/kmFXkmlBxlOvHWeYqxOd?p=preview

**Comment by nebulr** [comment]
@topherfangio Yep that looks like it fixed it. However I'm using npm for my actual project so I'll need to change the version to a git url thanks! 👍

**Comment by wsheeraz** [comment]
Hi there, I have exactly the same issue that nebulr had. I am relatively new to AngularJS, so how can I get the latest changes to resolve this issue?
Waj

**Comment by nebulr** [comment]
@wsheeraz Topherfangio was saying to change the cdn url to 
  <script src="https://material.angularjs.org/HEAD/angular-material.min.js"></script> instead of the version specified version. The code change in HEAD haven't been officially released in bower or npm so we're kind of SOL for the moment.

**Comment by Makatun** [comment]
@nebulr  dude you fucked up. Original thread was ok but you hijacked it, confused contributers, made them make a wrong decision that is not fixable at this point since project is closed and made my life much harder, 
Solution to your problem is easily fixable by adding required-if="!model.field" solution to original problem is not as easy. Now I have a form that has an invalid/missing option selected but user cannot see that option is invalid since model is populated.

**Comment by Splaktar** [comment]
@Makatun FYI, this project is not closed. However, this issue is closed. If you have questions, please try the [AngularJS Material forums](https://groups.google.com/forum/?pli=1#!forum/ngmaterial). If you have found a bug in AngularJS Material, please open a new issue that follows the issue template and includes a CodePen reproduction.
