### ISSUE TITLE
Setup multiple themes from json file

### ISSUE THREAD

**Issue by thanhtruong0315** [angular/material#7968]
Dear,
Multiple themes is good feature in material. In my project, I have to load Palette color from Json files. But I did not find any solution for that. This is my code:
```
.config(['$mdThemingProvider', function($mdThemingProvider) {
$http.get('themes/config.json').success(function(config) {
        var theming = config.theming;
        if (theming) {
            $mdThemingProvider.definePalette(theming.paletteName, theming.paletteValue);
            $mdThemingProvider.theme(theming.themeName)
                .primaryPalette(theming.paletteName);
            $mdThemingProvider.alwaysWatchTheme(true);
        }
    });
}])
```

I got error when I used $http in angular.config. May you help me to resolve my issue?
Thanks so much.

Thanh Truong

**Comment by topherfangio** [comment]
Unfortunately, the `config` phase of Angular happens before the services (like `$http`) are instantiated. That is why `$http` is not available and only Providers are available.

I had a similar issue a while back and wound up using jQuery's `$.get()` method to make the request because we were already using jQuery in the project as well. If you don't have jQuery available, you may need to make your own [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest) to get the JSON.

**Comment by lazychino** [comment]
@thanhtruong0315 check this out https://github.com/angular/material/issues/5502#issuecomment-189627192
