### ISSUE TITLE
mdChips without angular.copy, problem in other variables

### ISSUE THREAD

**Issue by hectorgr** [angular/material#7980]
When I assign manually a value to md-chips and others variables, the rest of variables are modified when md-chips is modified.

For example:

**`chipsModel = foo`**
`var1 = foo`   <--This is modified when chipsModel is modified _(for my code is a problem)_
`var2 = foo`   <--This is modified when chipsModel is modified
`varX = foo`   <--This is modified when chipsModel is modified

This does not happen when I use angular.copy function. For example:

**`chipsModel = angular.copy(foo)`**
`var1 = foo`   <--This is independent
`var2 = foo`   <--This is independent
`varX = foo`   <--This is independent

**It's a bug or a normal functionality?**

Here a CodePen example (need follow the steps)
[http://codepen.io/cadete/pen/bpLoPw](http://codepen.io/cadete/pen/bpLoPw)

**Comment by topherfangio** [comment]
This is the intended behavior. In this case, when you set the `chipsModel` to `foo`, it gets passed by reference so that the chips component can keep it up-to-date. Anything that is also using that same reference (`foo`) will be updated accordingly.

When you use `angular.copy(foo)` this works because you are creating a new object and passing it (again by reference) to the chips model. It is still updating the copy you created, but since none of your other variables use it, you will not see the changes outside of the chips component.

You can learn a bit more about passing by reference here: http://snook.ca/archives/javascript/javascript_pass
