### ISSUE TITLE
virtualRepeat: change to md-top-index binding not reflected in view

### ISSUE THREAD

**Issue by maximivanov** [angular/material#7982]
I make a $http call for data for virtual repeat scroll, in success callback I set both virtual repeat items and scroll top index. Items are rendered but not scrolled to the value set (they stay on default index).

Angular Material version: 1.0.6
Browsers and Operating System: Chrome, Safari, FF on Mac (likely other platforms as well)

Relevant sample code ($http replaced with $timeout, same effect. Here I expect items to be scrolled to `2`):
```
...
  <md-content layout="column">
    <md-virtual-repeat-container md-top-index="currentIndex" id="horizontal-container" md-orient-horizontal="">
      <div md-virtual-repeat="item in items" class="repeated-item" flex="">
        {{item}}
      </div>
    </md-virtual-repeat-container>
  </md-content>
...
    angular
      .module('MyApp',['ngMaterial'])
      .controller('AppCtrl', function($scope, $timeout) {
        $scope.items = [];
        $scope.currentIndex = 1;
        $timeout(function() {
          for (var i = 0; i < 1000; i++) {
            $scope.items.push(i);
          }
          $scope.currentIndex = 2;
        })
      });
...
```
http://codepen.io/anon/pen/QNQORB

Then I found `md-start-index` (applicable to `md-virtual-repeat`, not mentioned in the docs). Setting it does seem to make it work. Is it a right way to go? What's wrong with `md-top-index`?

**Comment by topherfangio** [comment]
@maximivanov I can't seem to get it to work with `md-start-index` and I spoke briefly with the original developer, he said that `md-start-index` wasn't a 2-way binding and was only checked on initialization whereas `md-top-index` was added later is is watched/updated.

So, I think you should be using `md-top-index`, but it sounds like there is a bug with this.

**Comment by DrDanRyan** [comment]
My `md-top-index` stopped working as well. It had worked prior to some upgrades.... Now I can even make a button that sets the `md-top-index` value and it will have no effect. It is like the `$watch` got broken somehow.  I am using `md-on-demand` as well; that might be relevant.

**Comment by DrDanRyan** [comment]
I figured out what was happening in my case:
1.  The getLength() method on the md-on-demand model was returning 0 until an async call comes back with the actual count from the server.
2.  When `virtualRepeatController` makes the call to  `this.container.scrollToIndex(startIndex)` on line 710 inside of the `if (this.isFirstRender)` block, it does pass the correct `startIndex` based on `md-top-index`.
3.  When `virtualRepeatContainerController` handles this call, it sees that `itemsLength` is 0 and then changes the index to 0 which then gets passed to `handleScroll_` as a 0 position and no scroll happens.

When I was trouble shooting, I put a button in the UI to bind the scroll value I wanted to the `md-top-index` attribute but it was not causing the `$watch` to fire because the value of `this.topIndex` on the `virtualRepeatContainerController` was already correctly set to the non-zero value, so no value is changed and no new scroll event is triggered.

My solution was to not instantiate the `md-on-demand` model until the async call to get the actual count of items from the server comes back. That way the scroll behavior in the `if (this.isFirstRender)` block doesn't get messed up and the initial scroll position is set correctly.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
