### ISSUE TITLE
Error CSS Angular Material CDN version

### ISSUE THREAD

**Issue by wender440** [angular/material#8003]
I tried to download the Angle Material from version 1.0.6 using the CDN version, however, I found errors in the CSS file, is coming with javascript code with the css.

**Comment by ThomasBurleson** [comment]
Can you provide more details?

*  How did you download?
*  What was the URL ?

**Comment by michalsokolowskitouk** [comment]
https://ajax.googleapis.com/ajax/libs/angular_material/1.0.5/angular-material.min.css contains css, as expected.
But for 1.0.6 and 1.0.7 this is not the case - the following links both contain javascript rather than css:
https://ajax.googleapis.com/ajax/libs/angular_material/1.0.6/angular-material.min.css
https://ajax.googleapis.com/ajax/libs/angular_material/1.0.7/angular-material.min.css

**Comment by ThomasBurleson** [comment]
@michalsokolowskitouk - I see it now...  Thank you.

**Comment by ThomasBurleson** [comment]
@robertmesserle - Somehow the `angular-material.min.css` CDN deployment for 1.0.6 and 1.0.7 are incorrect. Yet the [v1.1.0-rc2](https://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc2/angular-material.min.css) version is correct:
