### ISSUE TITLE
(IE11) Floating label does not float when ::first-letter is styled

### ISSUE THREAD

**Issue by Anaphase** [angular/material#8008]
If you try to style an input label via it's `::first-letter` selector, the label does not float. This may just be an Internet Explorer quirk, and it's certainly a very niche use case, but maybe there's a workaround?

[See this code pen for an illustration of the bug.](http://codepen.io/Anaphase/pen/XdZQMW)

**Comment by topherfangio** [comment]
I'm not seeing the issue my IE11 (11.162.10586.0; on Windows 10). What OS are you using?

**Comment by Anaphase** [comment]
I'm seeing this issue in IE 11 (11.0.9600.17843):

<img width="1392" alt="screen shot 2016-04-14 at 1 01 12 pm" src="https://cloud.githubusercontent.com/assets/2358694/14538436/643007e8-0241-11e6-90e9-3cea196d0d17.png">

On Windows 7 SP1:

<img width="1392" alt="screen shot 2016-04-14 at 1 02 14 pm" src="https://cloud.githubusercontent.com/assets/2358694/14538447/6f949e46-0241-11e6-9017-a348873a164a.png">

Maybe it's a quirk that has since been fixed?

**Comment by DevVersion** [comment]
@Anaphase I can reproduce your bug on Win 7 IE11.

This seems to be a common bug in that old IE11 version, but we are unfortunately not able to fix this bug because it's caused by a browser bug.

But if you find any workaround, we'd love see a PR or at least the workaround :)

- http://stackoverflow.com/questions/19855499/css-animation-doesnt-work-in-ie-when-using-hover-and-hoverfirst-letter?rq=1

Thanks for your help.

**Comment by Anaphase** [comment]
I figured that was the case. Classic Internet Explorer!
