### ISSUE TITLE
iOS + subheader: positioned incorrectly

### ISSUE THREAD

**Issue by 0101adm** [angular/material#8049]
AM 1.1.0-rc3

http://codepen.io/0101adm/full/greZqe/

md-subheader is positioned incorrectly in any browser on iOS.

![untitled screencast](https://cloud.githubusercontent.com/assets/5133412/14544131/d8e44898-0254-11e6-9c4d-62e4c6312348.gif)

**Comment by rayita** [comment]
Same problem here, Iphone 6, iOS 9.2.1, AM 1.1.0-rc3

**Comment by topherfangio** [comment]
Subheader is also mispositioned in Desktop Chrome and bounces.

**Comment by ThomasBurleson** [comment]
@topherfangio - can you investigate. Nice to have this in the RC4 build for later today.

**Comment by topherfangio** [comment]
@ThomasBurleson Yes; working on it now.

**Comment by topherfangio** [comment]
@0101adm The subheaders are actually cloned and appended as children to the `<md-content>`, so when you see the "sticky header", that is the clone.

They use absolute positioning and the `<md-content>` has `position: relative;` set so that they are absolutely positioned relative to the content.

Things got a bit confused because you applied your layout/flex/padding properties directly on the `<md-content>`. I have updated your Codepen to put those on a separate `<div>` and everything works as expected (although it's slightly off because of your 1px black border; so you will need to account for that manually).

http://codepen.io/topherfangio/pen/WwJbVP?editors=1000

I am dropping the priority of this issue, but we definitely need some better docs on the subheader to explain how it works. I could have sworn we added this before, but I guess not.

**Comment by 0101adm** [comment]
👍 thanks

**Comment by topherfangio** [comment]
I'd like to actually keep this open so that we remember to update the docs to make it easier for people to use :smile:

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
