### ISSUE TITLE
"UNSPECIFIED_EVENT_TYPE_ERR: DOM Events Exception 0:"

### ISSUE THREAD

**Issue by praskarnam** [angular/material#8078]
on iOS 9.2.1 getting the below error on any touch event and not able to proceed with anything.

"UNSPECIFIED_EVENT_TYPE_ERR: DOM Events Exception 0: The Event's type was not specified by initializing the event before the method was called. - undefined:undefined"

Am using angular material with appgyver supersonic framework.

Appreciate your earliest reply.

Regards
Prashanth Karnam

**Comment by ThomasBurleson** [comment]
Closing as invalid issue submission:

---

**Actual behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.
