### ISSUE TITLE
mdIcon: size and component's layout

### ISSUE THREAD

**Issue by radzikp** [angular/material#8091]
Angular material version: `1.1.0-rc4-master-9679be3`
Browsers and Operating System: All browsers/systems

If I set `font-size `ex: `md-96` in css and add this as class name with `md-icon` directive, layout doesn't look well (column). This is because `md-icon` `height`, and `width` are set to `24px` in `md-icon` directive by default. 

Suggested fix: They should be set to `auto`.

![screen shot 2016-04-18 at 13 14 51](https://cloud.githubusercontent.com/assets/8318755/14602357/bf180eac-0567-11e6-9ac5-67527bf92179.png)

**Comment by DevVersion** [comment]
@radzikp Please provide a demo, which shows your issue.

**Comment by mariopolo2805** [comment]
I tried this and it works:
```
md-icon.md-96 {
    font-size: 96px;
    height: 96px;
    width: 96px;
    min-height: 96px;
    min-width: 96px;
}
```

**Comment by DevVersion** [comment]
This is not an issue.

-----
The size of an icon should be adjusted, through the `height` and `width` property.

See demo - http://codepen.io/DevVersion/pen/eZabBK

Actually overwriting `min-height` and `min-width` is only required, when the icon should be smaller than `24px`.

Icon's should also not depend on the font-size. Since those are not counting as text characters. 

If you have other thoughts, please let me know and we will discuss about that :)
