### ISSUE TITLE
mdListItem: rendering problem with WebKit (angular-material >= 1.1.0-rc2)

### ISSUE THREAD

**Issue by igdtl** [angular/material#8094]
It seems that [this](https://github.com/angular/material/commit/9bb78e06107de7ada8a9251e3100eff747d8329e) fix breaks `md-list-item` on WebKit browsers (tested with Chromium 48 and Safari 9.1)

**angular-material-1.1.0-rc1**
```html
<html>
  <head>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc1/angular-material.css">
  </head>
  <body ng-app="app">

    <md-list>
      <md-list-item>Test 1</md-list-item>
      <md-list-item>Test 2</md-list-item>
    </md-list>

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular-animate.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular-aria.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc1/angular-material.js"></script>

    <script>
      var app = angular.module('app', ['ngMaterial']).controller('AppCtrl', function(){});
    </script>
  </body>
</html>
```
![angular-material-1.1.0-rc1](http://i.imgur.com/loG8g6c.png)

**angular-material-1.1.0-rc2**
```html
<html>
  <head>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc2/angular-material.css">
  </head>
  <body ng-app="app">

    <md-list>
      <md-list-item>Test 1</md-list-item>
      <md-list-item>Test 2</md-list-item>
    </md-list>

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular-animate.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.3/angular-aria.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc2/angular-material.js"></script>

    <script>
      var app = angular.module('app', ['ngMaterial']).controller('AppCtrl', function(){});
    </script>
  </body>
</html>
```
![angular-material-1.1.0-rc2](http://i.imgur.com/vrwrM3P.png)

Note: not reproducible on Codepen / Fidle

**Comment by ThomasBurleson** [comment]
@DevVersion - Can you investigate?

**Comment by DevVersion** [comment]
@igdtl Thanks for the issue, you're right - it's a bug and it's caused by the secondary item container, which expects a height of 100%.

The problem is, that those 100% are in some cases not in relative to the actual list-item, which causes the 100% to use the screens 100%.

This issue was introduced in a previous commit, which made the secondary items static.

The relevance of that feature was really high, because this fixes some **huge** issues with the overflow on list-items.

Also we've removed the behavior of wrapping all content inside of a button, this actually made the list-item usable with Firefox. Before of that, items inside of a list-item were not clickable, because Firefox and IE are blocking pointer events inside of a button (our wrap)

So actually there was a *lot* of improvement in the `md-list` the last releases, but it also introduced a few edge-case bugs, but I'm trying my best to solve them.

**Comment by igdtl** [comment]
Thanks! @DevVersion
