### ISSUE TITLE
mdListItem : list of mdButtons breaks from 1.06 to 1.1-rc4

### ISSUE THREAD

**Issue by fmalk** [angular/material#8097]
In 1.0.x it was straightforward to have a mdList of mdButtons, where each would fill (`flex`) an entire row, with secondary icons as well (note the `md-raised` on the buttons):

http://codepen.io/fernandopj/pen/eZrwye

The same code with 1.1-rc4 breaks:

http://codepen.io/fernandopj/pen/aNGgEK

Demos do provide lists where each mdListItem is "flexed", and yes an item can be made clickable, but IMO a button is more flexible and better suited for the intended interaction.

I haven't found a fix yet. I honestly doubt I could pinpoint the problem and suggest a PR, but if I find a workaround I'll post it here.

**Comment by clshortfuse** [comment]
A set of mdButtons inside an mdList is rather awkward and goes against spec. Is there any reason why you're not using a vertical layout?

I'm assuming you want to do something like this: http://codepen.io/shortfuse/pen/MyXWpp ?

**Comment by fmalk** [comment]
@clshortfuse I don't know why it would be against spec, but yes, a vertical layout with `ng-repeat` will do. Thanks, I wasn't aware of that double `<md-icon>` use, I assumed a need for `class='md-secondary'`.
I also assumed a mdList/mdListItem would just be a "md" version of regular `<list>`, in 1.0.6 it just put a few, standard rules like padding and spacing between items, but now it seems to be more "opinionated", I guess.
But still, with "clickable" mdListItem you still lose a few styling; for example, `ng-disable` doesn't gray out an item, it just looks the same, disabled or not.

**Comment by RolandHeath** [comment]
There's been a few issues/bugs, including this one, which I think are related to changes to md-secondary in lists. I'm not sure what the end goal is, but it looks like it's still being tested - I hope it will only be present in the next release if it's not breaking anything.

**Comment by fmalk** [comment]
Thanks for the input, @RolandHeath and @clshortfuse 
I'll close the issue since a reasonable workaround has been presented, and quirks with mdList should be addressed in other issues

**Comment by DevVersion** [comment]
@RolandHeath @fmalk 

Yes, there were a few changes to the `md-list` component.
- Secondary Items are now static
- Content is no longer wrapped inside of a button

Making the secondary items static was a really **important** change, because it finally fixes the overflow issues with the secondary items, which means that the list-items were not responsive, when secondary items are present.

Moving the content out of the button was also a very important change, because browsers like `Firefox` and `IE11` are not able to retrieve clicks (bubbled) inside of a button.

For example if you have a checkbox, inside of a button, those browsers are blocking all clicks on the checkbox.

@RolandHeath - If there are any bugs you've noticed, please file an issue and ping me

If there are any further questions, please let me know.
