### ISSUE TITLE
md-select: broken styling

### ISSUE THREAD

**Issue by djfd** [angular/material#8102]
Hi,

if we place ```<label />``` containing ```<md-icon />``` into simple ```<md-input-container />``` then it is visible all the time: when there is / or is not value in an input field.

But if we use ```<md-select />``` instead of plain input then that icon is only visible when selector's model is not empty.

Kindly check https://codepen.io/djFD/full/qZoMoN/

Thanks

UPD: just noticed. an animation of md-select from filled to empty state is missing too
Firefox 45.0.1

**Comment by RolandHeath** [comment]
Had a quick look into it, it appears to be (partially) a side-effect of the code to stop md-select from showing both a placeholder and a label.
The relevant css is:
`md-input-container .md-placeholder { top: 0; opacity: 0; }`

This class is removed when the model is filled, because the placeholder goes away. 
So the md-icon is getting not getting passed to the label properly, and is therefore only displayed in a hidden placeholder.

Looking in the code for md-select, it looks like there is an option to provide an md-select-header element when you need more than just text in the label. That might be worth a try.

This needs an example in the docs, but otherwise, you can have a look [here](https://material.angularjs.org/latest/api/directive/mdSelect), then scroll to the section on using select-header.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
