### ISSUE TITLE
broken md-icon styling in master

### ISSUE THREAD

**Issue by djfd** [angular/material#8118]
Hi,
```
fill: rgb(255, 255, 255);
: inline:1;
: md-toolbar:not(.md-menu-toolbar) md-icon > rgb(255, 255, 255);
: angular-material.css:2038;
: md-icon > currentcolor;
```
in version 1.0.7 we have
```
fill: rgb(255, 64, 129);
: angular-material.css:1910;
: md-icon > currentcolor;
```

this particularly does not allow md-icon-button s accenting

Thanks

**Comment by ThomasBurleson** [comment]
Closing as this is not a valid issue

---

**Actual behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Comment by djfd** [comment]
http://codepen.io/djFD/full/reKYey/
@ThomasBurleson 
you are not right, we are not in sandbox, very first post provides all required information

**Comment by djfd** [comment]
@ThomasBurleson 
please reopen
