### ISSUE TITLE
md-progress-linear + md-progress-circular: Animations are frozen by Javascript (#6738)

### ISSUE THREAD

**Issue by migingreen** [angular/material#8173]
I wanted to use either (in)determinate mode in order to display a waiting process:
[Codepen example](http://codepen.io/anon/pen/XdBaOO)

It would be nice if we can use both components in case of Javascript processing if this is possible with a minor update in the meantime, as suggested by @topherfangio in #6738:
> I think the next step is to list out which components would benefit from some minor updates, and perhaps open a ticket for each one so we can track them one at a time.

**Comment by crisbeto** [comment]
I'm not sure what the case is for progress linear, but progress circular has to do the animations with JS in order to work on IE.

**Comment by migingreen** [comment]
Thanks for the input, I just tested both components in IE, FF and Chrome.
The linear progress in IE also relies on JS.

[Progress Circular example](http://codepen.io/anon/pen/XdBaOO)

My application is used internally where we only work with Chrome and FF, that's why I didn't test out IE in the first place. :)

**Comment by ThomasBurleson** [comment]
Your blocking JS code will block many animations including non-ngMaterial UX.  Will not fix.

**Comment by samosale** [comment]
I have the same problem with pages that require heavy js parsing. Loader is frozen except rotate which is done in css. Animations should not be animated with js, but with css, because css uses separate thread. In md progress ciricular (indeterminate) rotating is done with css, but line which animate  is done with js changing directly path element.
