### ISSUE TITLE
mdSelectHeader add the posibility to be fixed

### ISSUE THREAD

**Issue by stalinb87** [angular/material#8185]
Would be great with the new md-select-header component stay on top when i drodpdown all item list on the md-select

**Comment by ThomasBurleson** [comment]
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.
