### ISSUE TITLE
column layout flex broken on Chrome, works on firefox

### ISSUE THREAD

**Issue by scottrodoty** [angular/material#8247]
in layout="column", flex="##" is ignored on Chrome, but works on Firefox.

I am running Chrome 50, Firefox 45. When I run the code pen below on Chrome, the flex attributes are ignored, however, when I run in Firefox, they are honored.

See codepen:  [http://codepen.io/scottrodoty/pen/pyxvBW](http://codepen.io/scottrodoty/pen/pyxvBW)

**Comment by ivoviz** [comment]
Pretty sure it's working on Chrome just fine, here is a really simple pen: http://codepen.io/anon/pen/pyxjQv

**Comment by RolandHeath** [comment]
@scottrodoty 
It is (sort of) working. 
You need to add height:100%; on the layout element, because of the way some browsers calculate the height of elements (based on the content).

See this modified codepen: http://codepen.io/RolandHeath/pen/oxabKR

It appears that this style is applied implicitly on the body element, which is why @ivoviz codepen worked as normal. 
Here is the relevant page in the [documentation](https://material.angularjs.org/latest/layout/tips).

**Comment by scottrodoty** [comment]
Thanks @RolandHeath, that did the trick ... somehow I didn't scroll down on that page in the documentation and missed all of that. Closing this issue
