### ISSUE TITLE
NuGet Support?

### ISSUE THREAD

**Issue by atentis** [angular/material#831]
See title. It would be nice to have this install-able from nuget as visual studio is my primary ide. Also any date on cdns? 

Keep up the great work!

**Comment by atentis** [comment]
Thanks David. Sorry for the super late response

**Comment by mbeckenbach** [comment]
I checked out the bower and grunt support in 2013. Works quite good, so that you can use bower. But as usual with MS they missed a thing. New files added via bower are not added to your project, so they will not be deployed to production if you do not add them manually. 

Will there be a day when microsoft finished work before releasing something? :-)

**Comment by dpaquette** [comment]
To be fair, the Grunt / Gulp / Bower plugin is in preview mode for VS 2013. I would rather have it now with some limitations that have to wait a year until they 'finish' it.

This problem goes away in VS 2015. In VS 2015 the project system has been completely changed for ASP.NET. You will no longer need to add files to the project. All files in the project folder are included by default and there are ways to exclude files if necessary.

**Comment by mbeckenbach** [comment]
The new project system looks awsome. Looks like similar to the old website projects but with some more cool features regarding real applications.

Hope that MS will get their .net components ported to vnext soon after release, so that we can really use that new system. For now i found that to many basic components in asp.net vnext are still missing.

Do you know if they have fixed the node_modules + git bug? If a node module contains filepaths that are to long you are able to commit although the node_modules folder is excluded.

**Comment by ThomasBurleson** [comment]
We will support Bower, NPM, and JSPM.
