### ISSUE TITLE
Unexpected locations for tooltips

### ISSUE THREAD

**Issue by daiches** [angular/material#8389]
**Actual behavior**:
-  What is the issue? Tooltips are centered for wrapped text and truncated for close-to-edge text. See CodePen link below for a demo.
-  What is the expected behavior? Tooltips should always be close to the original text and never truncated.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/dMawjz
-  Details: Hovering over wrapped span text shows the tooltip in the center of the screen (away from the text). Hovering over non-wrapped span text which ends all the way on the right edge of the screen shows a truncated tooltip. You may need to resize your browser to see these occur.

**Angular Versions**: *
-  Angular Version: 1.4.7
-  Angular Material Version: 1.0.7

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.94
-  OS: Linux
-  Stack Traces: N/A

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by RolandHeath** [comment]
It looks like top/bottom position is correct, but not left/right. 

What I found (testing on chrome 50.0.2661.94, fedora linux) was that hovering non-wrapped text on the right caused a horizontal scrollbar at the bottom of the page, whereas non-wrapped text on the left was truncated. 
Otherwise the behaviour was the same as described. 

It looks like the positionTooltip function handles tooltips without `md-direction` incorrectly, but the code to do this correctly is obviously present, just not getting utilised properly.

Setting `md-direction="top"` fixes the truncation problem, but not the centering on wrapped elements.
Setting `md-direction="left"` fixes the truncation and centering problem, but forces the tooltip to the center left position the rest of the time as well.

**Comment by ThomasBurleson** [comment]
@crisbeto - perhaps we should use $mdPanel for the container for tooltips?

**Comment by crisbeto** [comment]
Could be, I haven't given $mdPanel a try yet. I'll take a look.

**Comment by crisbeto** [comment]
I haven't looked at the tooltip being truncated yet. On the other hand, after looking into the positioning when the text is on multiple lines, I don't think there's much we can do about it, because these are the numbers that the browser returns. For example, the browser returns ~60px for a `span` on a single line and ~840px for one on multiple lines (basically 100% of the container). I also tried replacing the `getBoundingClientRect` call with `offsetWidth`, but the result is pretty much the same (~1px difference between the two). The only way I see us getting the proper width in those cases is to either clone the parent or take it out of the flow, but that's just not worth it, considering all the issues it could cause.
