### ISSUE TITLE
sidenav not flexing in ui.view

### ISSUE THREAD

**Issue by pnahtanoj** [angular/material#8392]
**Actual behavior**:
-  What is the issue?
When sidenav element lives in a ui-router ui-view, it stops flexing.
-  What is the expected behavior?
I'd expect it to still flex.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
This works:
http://codepen.io/pnahtanoj/pen/pyQKjP?editors=1000
This doesn't:
http://codepen.io/pnahtanoj/pen/aNQKvK?editors=1000
-  Details:

**Angular Versions**: *
-  Angular Version:
In codepen, it's 1.3.11.
I have the save problem locally with 1.5.5
-  Angular Material Version:
In codepen, resource listed as:
http://rawgit.com/angular/bower-material/master/angular-material.js
Locally:
1.0.8

**Additional Information**:
-  Browser Type: 
tested in Chrome and Firefox
-  Browser Version: 
Chrome: 50.0.2661.94
FF: 45.0.2
-  OS: 
OSX 10.11.4
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
@DevVersion - really interesting issue... the Layout injectors do not appear to be firing for the template instantiation.

**Comment by crisbeto** [comment]
I've been looking at it, but it seems like everything is working fine with Material. The example without ui-router works because the direct parent of the sidenav has the `layout` attribute. If you wrap the sidenav in a plain `<div flex>`, it will break like the ui-router example. [Here's a fork.](http://codepen.io/crisbeto/pen/XdvvEE)

@pnahtanoj you can get it to work by adding the layout attributes to the ui-view. [Here's a fork of yours original codepen.](http://codepen.io/crisbeto/pen/mPNNKb)

I'll close this, but we can continue discussing and re-open it if necessary.

**Comment by pnahtanoj** [comment]
So far, your solution has worked for me.  Thank you!
