### ISSUE TITLE
bug(md-menu): icons misaligned on md-menu

### ISSUE THREAD

**Issue by stunaz** [angular/material#8464]
Icons are not aligned.
Works on Safari and Chrome, not on Firefox

CodePen Demo which shows your issue : https://material.angularjs.org/HEAD/demo/menu

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: 1.1.0-rc4/head

**Additional Information**:
-  Browser Type: Firefox

**Comment by ThomasBurleson** [comment]
![screen shot 2016-05-19 at 7 13 46 am](https://cloud.githubusercontent.com/assets/210413/15393132/41565a68-1d91-11e6-8880-9cb2cd532acf.png)

**Comment by topherfangio** [comment]
@EladBezalel Do you recall making the following commit: https://github.com/angular/material/commit/34f2704c8a004c98ecece39313249ed5e2caa72a

It appears that using `display: flex` on a `<button>` element does not render properly in Firefox (and may not for a while; but it does look like they are planning to fix it): https://bugzilla.mozilla.org/show_bug.cgi?id=984869

Can you think of another fix/workaround instead of setting `display: flex` in the `menu.scss`? Ping me if you want to pair on it.

**Comment by topherfangio** [comment]
@EladBezalel Found a different fix that uses `display: inline-block` for both so the new PR should fix this 😉
