### ISSUE TITLE
Create a polyfill for the new .component() API in Angular 1.5

### ISSUE THREAD

**Issue by topherfangio** [angular/material#8474]
In order to show best practices and help users upgrade from Material/Angular 1 to Material/Angular 2, we are planning to rewrite some of our components to use the new `.component()` API available in Angular 1.5.

In order to achieve this, we will need a polyfill to make this backwards compatible with Angular 1.3 and 1.4.

**Comment by ThomasBurleson** [comment]
Please see Todd Motto's [Angular component() back-ported to 1.3+](https://toddmotto.com/angular-component-method-back-ported-to-1.3/).

Because we want to limit external dependencies, we should:

a) Ask Todd to submit a PR to Angular Material  `/src/core/util/component/angular-component.js`
> Note this appears to be only a partial implementation 
b) Implement tests (perhaps copied from Angular 1.5.x) for `/src/core/util/component/angular-component.spec.js`
c) Implement mocks `$componentController` in `/src/core/util/component/angular-material-mocks.js`
d) Test "lifecycle hooks"  (@see https://docs.angularjs.org/guide/component)

**Comment by david-gang** [comment]
This is really exciting. Does this mean that we will be able to use angular material with ngupgrade? This would be great news as angular material 2 won't be ready for a long time.

**Comment by topherfangio** [comment]
@david-gang I have not personally seen the issues with using ngUpgrade and Material, but from what I understand, there are some different technical issues that prevent us from being compatible.

@ThomasBurleson Can you perhaps chime in on this topic?

**Comment by david-gang** [comment]
Hi
I researched the issue than and there are a couple of issues I am aware of.
Ng-upgrade needs an isolated scope so that every component is controlled either by angular 1 or 2.
Therefore all directs which replace the scope are problematic. For example button.
We have then problems with terminal directives and directives which have an complex compile phase. As i understood from the issue there are plans to migrate the am directives to components which are out the box upgradable so all issues will be resolved

**Comment by david-gang** [comment]
Look at #6636 for more info

**Comment by topherfangio** [comment]
@david-gang I believe we are planning to upgrade some of the components to use the new `.component()` feature, but I don't know if we can do that with all of them. As you said in the other issue, we have some attribute directives that we may not be able to migrate.

However, I'm thinking that quite a few should be able to be upgraded, we might be able to release a compatibility list (or perhaps a version) that is compatible with ngUpgrade. Not sure what this would require, but I'll talk to the team about it at our next meeting.

**Comment by toddmotto** [comment]
Hey guys, just jumping in as Topher and I have chatted. So, I authored the `.component()` polyfill (repo: https://github.com/toddmotto/angular-component) a few months ago and have been adapting it to align with the changes that're happening with 1.5+ (there were quite a lot at the beginning from 1.5.0 - 1.5.5).

Originally the polyfill started as a quick proof of concept / fun hack which turned into lots of people actually using it! Around 1000 downloads a month on `npm`: https://www.npmjs.com/package/angular-component

At the moment I have these things that I'm working on:
- Locally I'm cleaning up a lot of the code to minimise footprint and `angular.*` API calls (such as `isArray` etc for extra speed to make it more JS less Angular (where possible as I've no got access to the globals Angular exposes in it's internal scopes)
- Also converting the whole thing to ES6, using Object destructuring for some of the new refactoring work I'm doing
- I'm planning on adding a bunch of unit/e2e tests to it in the next few weeks (super limited on time right now due to travelling for 3 weeks straight for work)

You can checkout the table of what's polyfilled so far in the readme link above.

Version 1.5.6 of Angular looks like it's integrating `$onChanges` to not only call for `'<'` bindings but also `'@'` bindings, so I've made an issue to implement this after I'm done refactoring and rewriting in ES6: https://github.com/toddmotto/angular-component/issues/27

I'm chatting with Topher next week, will be great :)!

**Comment by Splaktar** [comment]
This is not a required part of the ngUpgrade path at this time. Additionally, we won't be supporting AngularJS 1.4.x much longer and we've already dropped support for AngularJS 1.3.x. For those reasons, I think that it's time to close this one out.
