### ISSUE TITLE
md-autocomplete selection has troubles with md-chips with md-separator-keys property

### ISSUE THREAD

**Issue by viktorzavadil** [angular/material#8479]
**Actual behavior**:
-  When I set <code>md-separator-keys</code> for TAB and ENTER keys in my <code>md-chips</code> component and use <code>md-autocomplete</code> (with properties <code>md-autoselect="true"</code> and <code>md-select-on-match="true"</code>), TAB key is not propagated for selection action - only for chip confirmation.

-  I expect propagation event for <code>md-autocomplete</code> component.

**CodePen**
http://codepen.io/vikiza/pen/yOWbPB

**Angular Versions**:
-  Angular Version: 1.4.10
-  Angular Material Version: 1.1.0-rc4

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by skarpushin** [comment]
Today you rejecting valid issues for Angular 1 in favor of development of Angular 2.
How do I know you're not going to repeat same tomorrow for Angular 2? 
How do I rely on technologies you produce?

p.s. I'm really wondering what is your real goal, Because certainly it's not to develop stable technology and let last.
