### ISSUE TITLE
'md-select' causes 'md-fab-speed-dial' to trigger

### ISSUE THREAD

**Issue by drorsou** [angular/material#8527]
**Actual behavior**:
-  What is the issue? I have md-select and md-fab-speed-dial in my code, and when I click on the md-select element it also opens up the md-fab-speed-dial element.
-  What is the expected behavior? These are seperate elements, md-fab-speed-dial shouldn't open.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/drorsu/pen/XdvddG
-  Details: Just click on the select menu.

**Angular Versions**: *
-  Angular Version: 1.5.3
-  Angular Material Version: 1.1.0-rc2

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.102
-  OS: 
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by topherfangio** [comment]
It appears that the `<md-select>` component sets the `isOpen` property on the scope: https://github.com/angular/material/blob/master/src/components/select/select.js#L346

It used to read `scope.$apply('isOpen = true');`, so I assume the select is indeed watching that variable or something. Ideally, we would watch a variable on our controller similar to how the speed dial works.

As a quick workaround, you should be able to use something other than `isOpen` in your `md-open` expression on the speed dial so that there isn't a conflict.

**Comment by drorsou** [comment]
Thanks for the solution. :)
