### ISSUE TITLE
perf(select): Don't pre-render the dropdown

### ISSUE THREAD

**Issue by crisbeto** [angular/material#8534]
As discussed with @ThomasBurleson, we should look into rendering the select's dropdown on demand, instead of pre-rendering it, which is problematic on large pages like http://codepen.io/sheaujye/pen/GZbqdL.

**Comment by alexkh13** [comment]
Use a virtual repeat to avoid rendering too many selects.
Here is an example: [http://codepen.io/alexkh13/pen/beqbYB](http://codepen.io/alexkh13/pen/beqbYB)

**Comment by akvaliya** [comment]
Has anyone found solution for md-select without using virtual-repeat

**Comment by Splaktar** [comment]
Having a select on the page that has no options causes accessibility audit failures and won't pass as valid HTML. 

The virtual repeat approach is the right way to do it. This will render some subset of options instead of creating all of the DOM elements in advance. It's recommended that you use `md-autocomplete` in this instance as it works with virtual repeat.
