### ISSUE TITLE
Item centered while scrollable 

### ISSUE THREAD

**Issue by GeneSLee2** [angular/material#8601]
Hi, I just wanted to know if there was a way to make the viewer centered while I scroll through a list 
i.e: <md-list role="list"> and when I iterate through my list, my view goes with it automatically; preferably not 100% centered.

**Comment by DevVersion** [comment]
Please provide more information and follow our issue template.

**Comment by GeneSLee2** [comment]
**Actual behavior**:
-  md-list does not move along with actively used items *
-  Expected behavior is that the user can see what he or she is pressing on, the button he or she is using, is in another md-toolbar outside of the md-list

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details to reproduce: run a similar style to this
<div>
        <div id="results" style="overflow-y:auto;">
            <md-list>
                <md-list-item>
                </md-list-item>
            </md-list>
         </div>
         <md-toolbar id="footer">
            <div class="md-toolbar-tools">
                <div>
                         <md-button>1</md-button>
                         <md-button>2</md-button>
                 </div>
         </div>
        </md-toolbar>
    </div>

**Angular Versions**: *
-  Angular Version:1.5.5

**Additional Information**:
-  Browser Type: chrome/firefox
-  Browser Version: latest
-  OS: windows,mac,linux

**Comment by DevVersion** [comment]
It's actually really hard to understand your problem. But It looks like you're asking for support, instead of reporting an issue / bug.

As much I understand your issue, you're searching for a way to make the toolbar fixed to the top / center. 
- The solution would be using a fixed position.

If I didn't understand your question correct, please post in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
