### ISSUE TITLE
Flex/layout attributes not being compiled

### ISSUE THREAD

**Issue by GabrielGil** [angular/material#8620]
**Actual behavior**:
-  What is the issue?
Setting the flex and layout attributes programmatically doesn't gets the classes on the element added.

-  What is the expected behavior?
After the element attributes are compiled, the according classes to be applied.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue:    
http://codepen.io/GabrielGil/pen/wWBOEy
-  Details:    
I am using the following code in a directive link function: 
``` js
function link () {
  // Specify the region direction for its children.
  attrs.$set('layout', scope.pageRegion.properties.layout.default)
  // Defines how will adjust its size with respect to its parent
  attrs.$set('flex', scope.pageRegion.properties.flex.default)
}
```

**Angular Versions**: 
-  Angular Version: 1.5.9
-  Angular Material Version: 1.0.9

**Additional Information**:
-  Browser Type: Desktop
-  Browser Version: Chrome v50
-  OS: Mac OS X
-  Stack Traces: ----

**Comment by DevVersion** [comment]
That's not how you correctly compile attributes.

The AngularJS lifecycle hooks are the followed (minimized)
- Compile
- Pre Link
- Post Link

This means, you have to set the attributes in the `compileFn`, or compile the attributes manually in the postLink

Another approach would be, just to apply the given CSS class, instead of the attribute.
```js
element.addClass('layout-row');
```

But actually it's not a bug / feature request, so I'll close that issue. You better ask in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
