### ISSUE TITLE
mdDatePicker messes up the date when typed in instead of picked from calender

### ISSUE THREAD

**Issue by helloworld1987** [angular/material#8633]
**Actual behavior**:
When I type in the Date instead of actually picking it from the Calender, the output is messed up.
An example is to change the year..:
The datepicker shows 3.6.2016.
Change the year to 2015 by typing it in, the result ist 6.3.2015.

**CodePen** or Steps to reproduce the issue: *
The same behavoir on the official Demosite:
https://material.angularjs.org/latest/demo/datepicker

**Angular Versions**: *
-  Angular Version: 1.4.8
-  Angular Material Version: 1.1.0-RC4

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: Version 51.0.2704.79 m
-  OS: Win10
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
That's because it's taking your locale formatting by default (there's https://github.com/angular/material/pull/8162 to change the default behaviour). You have to override the `parseDate` and `formatDate` in the `$mdDateLocaleProvider`. [You can read more about it in the docs](https://material.angularjs.org/latest/api/service/$mdDateLocaleProvider).

**Comment by crisbeto** [comment]
Closing this since #8162 is now in master. Material shouldn't be using the default locale formatting anymore.
