### ISSUE TITLE
md-virtual-repeat not binding data to directives with link function

### ISSUE THREAD

**Issue by hprofit** [angular/material#8638]
**Actual behavior**:
-  What is the issue? - First element (or even all elements as my last example shows) is not rendered properly due to a data binding issue
-  What is the expected behavior? - All elements be rendered and all data be bound properly to the directives

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/hprofit/pen/PzqWJp?editors=1010
-  Details: When binding data to a directive with a linker function (presumably a linker function that manipulates the DOM in some way, but I'd imagine that much doesn't matter), the data is not present inside the linker function. 

**Angular Versions**: *
-  Angular Version: Tested using 1.4.8 and 1.4.10
-  Angular Material Version: Tested using 1.1.0-rc4 and 1.0.9

**Additional Information**:
Occurs in Chrome, FF, and Safari (all OS X, haven't tested on Windows)

**Comment by JTCols** [comment]
+1

**Comment by DevVersion** [comment]
I was investigating at that issue (this took long)

Actually it's not an issue. The directive, which adds the text on `postLink` is the problem.

Since you're loading the *page* from the `On-Demand` prototype, when current page is not available yet.

```js
if (page) {
  return page[index % this.PAGE_SIZE];
} else if (page !== null) {
  this.fetchPage_(pageNumber);
}
```

This would mean, that the first item (`index = 0`), will return `null` and it will have to wait for the next indexing of the virtual repeat.

```js
virtualList.$$includeIndexes(this.newStartIndex, this.newVisibleEnd);
```

After the second indexing, the virtual repeat has properly resolved the item at `index = 0`.
The scope will be updated with the new item variable, but the `postLink` / `<another-directive>` will not change it's text on variable change (The text will applied once at postLink).

```js
.directive('anotherDirective', ['$compile', function ($compile) {
    return {
        bindToController: {
            'data': '='
        },
        restrict: 'E',
        controller: function(){},
        controllerAs: 'ctrl',
        link: function(scope, elem, attrs, controller) {
          scope.$watch('ctrl.data', function(newData) {
            elem.children().text(newData.name);
          })
        },
        template: '<span></span>'
    };
}]);
```

So as conclusion, this is actually not an issue, but we could probably move that description (above) to the docs to clarify how the `On-Demand` mode works.

**Comment by hprofit** [comment]
@DevVersion  

Very good to know and it makes sense. Thank you for looking into it!

**Comment by DevVersion** [comment]
After coming back to that issue, I decided to not document this, since this is a basic Angular 1 behavior.
> `postLink` functions will be only called once, at initialization.

**Comment by nitin7dc** [comment]
@DevVersion : thanks for the post

**Comment by frikkievb** [comment]
Thanks for investigating it. Much appreciated.
