### ISSUE TITLE
Unable to trigger click on file input inside the returned promise of an $mdDialog confirm popup

### ISSUE THREAD

**Issue by trevorhreed** [angular/material#8639]
**Actual behavior**: With the switch turned on, after clicking the `Choose File` button and then clicking `Continue`, nothing happens.
-  What is the issue? Before opening a file dialog (e.g. `fileInput.click()`), I attempt to have the user confirm the action by showing a confirmation dialog. When I trigger the file dialog without the confirmation, everything works fine; however, when I trigger the file dialog inside the `then` callback of a confirmation dialog (`$mdDialog.confirm`), nothing happens.
-  What is the expected behavior? With the switch turned on, clicking the `Choose File` button and then clicking `Continue`, a browser file dialog should appear.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/trevorhreed/pen/RRPVMm?editors=1010
-  Details:

**Angular Versions**: *
-  Angular Version: 1.5.6
-  Angular Material Version: 1.1.0-rc4

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50
-  OS: Mac OS X (10.11.5)
-  Stack Traces: None (no errors)

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
@trevorhreed I can reproduce your issue, but we're not able to fix this issue. 

Because the browsers are only able to open the `file` dialog, if the click was triggered inside of an event handler, that was triggered by the user and is trusted.

- http://stackoverflow.com/questions/8595389/programmatically-trigger-select-file-dialog-box
- http://stackoverflow.com/questions/12134014/how-can-i-programmatically-open-the-file-picker-with-javascript

**Comment by trevorhreed** [comment]
Understood. That makes sense.
