### ISSUE TITLE
md-bottom-sheet issue with VScroll

### ISSUE THREAD

**Issue by mavillar** [angular/material#8676]
Hi,

   I have a bottom-sheet that when invoked and shown the template, a general vertical scroll come up. I do not know why, because the template is not long.

This is the template:

```
<md-bottom-sheet class="md-grid" layout="column" ng-cloak>
    <div layout="row" layout-align="end center">
        <h5>Click outside or press ESC to close</h5>
    </div>
    <div layout="row" layout-align="start center">
        <div flex="25">
            <md-checkbox aria-label="Select All"
                         ng-checked="session.advance_search.select_all"
                         ng-click="toggle_all_sites()">
              <span ng-if="advance_search.select_all">Un-</span>Select All
            </md-checkbox>
        </div>
        <div flex="25">
            <md-checkbox aria-label="Show price models"
                         ng-checked="session.advance_search.show_cost"
                         ng-click="session.advance_search.show_cost=!session.advance_search.show_cost">
              Show price models
            </md-checkbox>
        </div>
        <div flex="25">
            <md-checkbox aria-label="Show free models"
                         ng-checked="session.advance_search.show_free"
                         ng-click="session.advance_search.show_free=!session.advance_search.show_free">
              Show free models
            </md-checkbox>
        </div>
    </div>
    <div>
        <fieldset>
            <legend>Repositories </legend>
            <div layout="row" layout-wrap flex>
                <div flex="15" ng-repeat="item in session.advance_search.items">
                    <md-checkbox ng-checked="item.selected" ng-click="item.selected=!item.selected">
                        {{ item.name }}
                    </md-checkbox>
                </div>
            </div>
        </fieldset>
    </div>
</md-bottom-sheet>
```

and here I attach a snapshot of my site to see the issue:

![captura de pantalla 2016-06-06 a las 23 08 58](https://cloud.githubusercontent.com/assets/3111892/15837910/ade69342-2c3b-11e6-8e2d-06d7ea7a3d28.png)

**Comment by bradrich** [comment]
@mavillar The reason that you are seeing the scrollbar is because of the way that the bottom sheet is built. Here are a few points to put it simply:

- The bottom sheet is given an extra 80px of bottom padding that is hidden out of view by `transform: translate3d(0, 80px, 0);` (https://github.com/angular/material/blob/master/src/components/bottomSheet/bottom-sheet.scss#L14) This is done so that the animation of the bottom sheet into view is smooth. Without it, there is a slight hiccup in the entry animation.
- The bottom sheet component is appended by default to the body or root element of the application, but you can specify another parent element in the configuration.
- The reason that you do not see the scroll bar in the demo documentation is because the container for the demo has `overflow: hidden;` specified.

The way that you can fix your layout in order to remove the scroll bars is to add `overflow: hidden;` to the parent element that you specify in the configuration in your controller, as well as to the body element. Then, wrap the content of your site in a `md-content` element with `flex` and `md-scroll-y` attributes. To give you an idea of what I mean, I built this pen for you: http://codepen.io/bradrich/pen/grWbYo.

This is expected behavior of this component and the documentation states that "This UX pattern is intended for mobile devices only, and may not make sense to use on responsive sites." (https://material.angularjs.org/latest/demo/bottomSheet)
