### ISSUE TITLE
md-menu: ng-transcluded menu content causes first item to always be selected

### ISSUE THREAD

**Issue by jasonbaker** [angular/material#8693]
**Actual behavior**:
-  What is the issue? If you transclude the menu content into an md-menu, the first item will always be selected regardless of what you highlight or do with the keyboard
-  What is the expected behavior? Menu items should be selected when you hover them or when you keyboard to them.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/amnorvend/pen/aZvYRx
-  Details: Version that uses ng-transclude demonstrates issue, while version that uses manual transclude does not

**Angular Versions**: *
-  Angular Version: 1.4
-  Angular Material Version: 1.09

**Additional Information**:
-  Browser Type:  Chrome
-  Browser Version: 52.0.2743.24 beta (64-bit)
-  OS: Linux
-  Stack Traces: n/a

**Comment by jasonbaker** [comment]
#3352 is probably related

**Comment by crisbeto** [comment]
@jasonbaker I just got a chance to look into this. The `ng-transclude` example fails, because the menu directive expects the _direct_ children of `md-menu-content` to be the menu items. In your case you have `ng-transclude` as the direct child, which causes your example to break. I don't think we can fix this in Material, without making assumptions that users will always use `md-menu-item` (we mention in the docs that any element can be inside the menu) and sacrificing some flexibility. 
You can get your example working easily by moving the `ng-transclude` from a DOM node to an attribute of the `md-menu-content`. E.g. this is what your template looks like at the moment:

```js
template: `
  <md-menu md-position-mode="target-right target">
   <md-button ng-click="$mdOpenMenu($event)">ng-transclude</md-button>
   <md-menu-content>
     <ng-transclude></ng-transclude>
   </md-menu-content>
  </md-menu>`,
```

And here's what it should look like:

```js
template: `
  <md-menu md-position-mode="target-right target">
   <md-button ng-click="$mdOpenMenu($event)">ng-transclude</md-button>
   <md-menu-content ng-transclude>
   </md-menu-content>
  </md-menu>`,
```

[Also here's an updated working codepen.](http://codepen.io/crisbeto/pen/mEXbjm)

I'll close this issue for now, but we can continue discussing, in case there any more problems.
