### ISSUE TITLE
md-menu: ng-repeat with md-menu-item

### ISSUE THREAD

**Issue by lemoinet** [angular/material#8697]
**Actual behavior**:
-  What is the issue? 
When using ngRepeat with mdMenuItem (type 'checkbox'), the icon is null and throws an error
-  What is the expected behavior?

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/xOwMwq
-  Details:

**Angular Versions**: *
-  Angular Version: 1.5.6
-  Angular Material Version: 1.1.0-rc4 >

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:
TypeError: Cannot read property 'style' of undefined
    at render [as $render] (http://localhost:58246/Scripts/angular-material.js:27808:11)
    at ngModelWatch (http://localhost:58246/Scripts/angular.js:27102:14)
    at Scope.$digest (http://localhost:58246/Scripts/angular.js:17211:34)
    at Scope.$apply (http://localhost:58246/Scripts/angular.js:17486:24)
    at done (http://localhost:58246/Scripts/angular.js:11637:47)
    at completeRequest (http://localhost:58246/Scripts/angular.js:11843:7)
    at XMLHttpRequest.requestLoaded (http://localhost:58246/Scripts/angular.js:11776:9) undefined

**Comment by DevVersion** [comment]
You have to add the icon yourself, ngMaterial is not adding any icon by default.

Also you have to wrap the text content inside of a button, to make the menu item clickable.

See http://codepen.io/DevVersion/pen/PzPgzK?editors=1000

**Comment by lemoinet** [comment]
I don't have to set the icon, the menu items are of type **checkbox**.

**Comment by ThomasBurleson** [comment]
@lemoinet - What exactly is it you expect to happen?

**Comment by lemoinet** [comment]
You can see an example right here, under the view tab.  
[https://material.angularjs.org/latest/demo/menuBar](url)
It works when you don't use an ngRepeat to list the options.

**Comment by wesleycho** [comment]
This fails because when in an ng-repeat, ng-repeat creates a document fragment with the element as the template - this causes the isInsideMenuBar check to fail [here](https://github.com/angular/material/blob/master/src/components/menuBar/js/menuItemDirective.js#L58) because the parentNode is the fragment.

This would be fixable if that logic was moved to the linking function, but it has a perf cost.

**Comment by lemoinet** [comment]
but it worked in previous versions (1.0.*)

**Comment by wesleycho** [comment]
Looks like it worked prior because it didn't have the `isInsideMenuBar` check - see [here](https://github.com/angular/material/blob/v1.0.9/src/components/menuBar/js/menuItemDirective.js#L12).

This broke because of 560474f705af750022b5cb07a8102c6ad490aec3 adding that check. A decision probably should be made whether it is worth the perf hit to have that check and move the logic to the linking function, or whether to remove the check. I would probably remove the check, but I'm not a maintainer :) .
