### ISSUE TITLE
mdProgressLinear: Substantial CPU use while disabled

### ISSUE THREAD

**Issue by justinappler** [angular/material#8764]
**Actual behavior**:
-  When `ng-disabled` is set to `true` on the mdProgressLinear component, substantial CPU is used while the page is idle. This can be easily reproduced by watching the Chrome Task Manager while the disabled mdProgressLinear is on the page and then removing it and checking again.
- In a barebones Plnkr, I see about a 10% CPU usage difference between the component being present and disabled vs not present. In my real world app, it can get as high as a 30-40% usage difference.

**CodePen** or Steps to reproduce the issue:
-  https://embed.plnkr.co/h3UQqnp0LK9GxPlfjOJv/

**Angular Versions**:
-  Angular Version: 1.5.5
-  Angular Material Version: 1.1.0-rc5

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50
-  OS: OSX

**Comment by crisbeto** [comment]
I couldn't see any change in CPU usage between enabled and disabled. I don't think just looking at the task manager is the best way to diagnose these types of issues, since it can be anything else on that page causing it (e.g. Plunkr's own JS). That being said, we could improve the disabled state, because at the moment, the element is still animating in the background.
