### ISSUE TITLE
mdSelect is not working with mdDialog

### ISSUE THREAD

**Issue by nikhiljanshali** [angular/material#8780]
When use dynamic data mdSelect option properties is not display list as i use ng-repeat in md-option area

**Comment by DevVersion** [comment]
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Comment by nikhiljanshali** [comment]
Hi,

**Comment by nikhiljanshali** [comment]
Thanks 
it was my css issue so it will complete now
