### ISSUE TITLE
Nested dropdown within sidenav shifts content of state/view to the right

### ISSUE THREAD

**Issue by wbarbee** [angular/material#8849]
**Actual behavior**: Horizontal shifting of content whenever there is an overflow-y.
-  What is the issue? * 

I have a dropdown nested in the material sidenav and have noticed that, when the content of  a state/view is longer than the height of the browser window, the content shifts to the right when i open the dropdown within the sidenav.

-  What is the expected behavior? I

'd like for the content to remain fixed, as it does in views where the content does not have overflow-y

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : site: https://www.willbarbee.com/#/work/personal-porfolio
-  Details: if you open the sidenav and then click on 'Work', the dropdown menu should appear and shift the content of that view to the left

**Angular Versions**: *
-  Angular Version: 1.4.5
-  Angular Material Version: 1.1.0

**Additional Information**:
-  Browser Type: *Chrome
-  Browser Version: *51.0.2704.103
-  OS: *10.11.5
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by clshortfuse** [comment]
I'm not sure if I understand the issue correctly. You should use a codepen instead of a fully built website so we can help better. Also, this seems like a general help issue, that would probably be suited for the Angular Material Forum: https://groups.google.com/forum/#!forum/ngmaterial

Issues are Github are meant for issues in the Angular Material framework itself.

Regardless, I took a look and it seems as though it's working correctly. I believe you might want to set the button and md-menu button to 100% width and use `md-offset` to perfect the positioning. You can find more information here: https://material.angularjs.org/HEAD/api/directive/mdMenu

If you still feel the issue is with the framework itself, please post a new issue using a Codepen demo.
