### ISSUE TITLE
locals

### ISSUE THREAD

**Issue by Jenny888** [angular/material#8862]
**Actual behavior**:
-  What is the issue? *
Can't get locals work when creating a simple dialog.
-  What is the expected behavior?

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
I am trying to create a simple dialog and pass a variable through locals. This is the codepen where you can see the variable is not appearing: [Demo 1](http://codepen.io/Evgenia8888/pen/OXpLpM).

- When I set scope: $scope to the dialog, the variable is appearing but after closing dialog, the button never triggers again. This is the codepen: [Demo 2](http://codepen.io/Evgenia8888/pen/NrpKYp).
-  Details:

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: v1.1.0-rc.5

**Additional Information**:
-  Browser Type: Google Chrome *
-  Browser Version: Version 51.0.2704.106 (64-bit) *
-  OS: Linux Mint 17.3 Rosa *
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by zlovin** [comment]
@Jenny888 By using a prerendered dialog, the {{name}} variable in the html is bound to the _originating_  angular scope, i.e. the scope for AppCtrl. The default action for creating a dialog controller's scope is to make that scope isolate. However, you can use the `scope` parameter of the $mdDialog options to bind the dialog scope to the AppCtrl scope. See here: http://codepen.io/anon/pen/LZWEje?editors=1010

Do note though that since you're binding the scope of AppCtrl to the DialogController, you're defeating the purpose of locals, which allow you to pass in parameters to an _isolated_ scope in the first place. So, if you want to keep using an isolated scope (recommended) and keep using locals (also recommended), you'll have to use a template for your dialog, like this: http://codepen.io/anon/pen/XKMJep?editors=1010

Hope that helps.

**Comment by DevVersion** [comment]
This is not an issue. I'll explain why.

**Demo 1**
You're using a pre-rendered dialog, which will be not (re)-compiled upon dialog opening.
This would mean the dialog would never retrieve it's new scope from the controller.
It only uses the scope from your App Controller, since the dialog element was placed there.

**Demo 2**
Since you're using the default scope of your main controller and the scope will be destroyed upon dialog close, you have to preserve the scope on destroy.

```js
{
  preserveScope: true,
  scope: $scope
}
```

Just saw, while I was writing, that @zlovin posted some correct thoughts. Thanks.

**Comment by Jenny888** [comment]
@zlovin,  @DevVersion Thank you very much for the explanation and help. It was very helpful!
