### ISSUE TITLE
md-autocomplete with a md-input-maxlength and md-min-length 0 make all the items appear when maxlength is exceeded

### ISSUE THREAD

**Issue by coteke** [angular/material#8947]
**Actual Behavior**:
 -  `What is the issue?` When I have a md-autocomplete with a md-input-maxlength and a md-min-length 0 and I exceed the maxlength, the field become in error (This is what I want) but probably because the view value is now empty (0), all the values appear.
 -  `What is the expected behavior?` No values should appear when then maxlength is exceeded.

**CodePen** (or steps to reproduce the issue): 
 -  `CodePen Demo which shows your issue:` (http://codepen.io/kcote/pen/yJMdpR)
 -  `Details:` Enter letters to exceed the maxlength (18) and then all the values are showing.

**Angular Versions**: *
 -  `Angular Version:1.5.6`
 -  `Angular Material Version:1.0.9`

**Additional Information**:
 -  `Browser Type: Google Chrome`
 -  `Browser Version: 51.0.2704.103 (64 bit)`
 -  `OS: Windows 10`
 -  `Stack Traces:`

**Comment by DevVersion** [comment]
The issue seems to be, that the input value is getting cleared, once the maximum amount of chars has been reached.

The input itself is not getting updated properly, but the autocomplete already thinks that the input is clear, and shows all available options.

> http://codepen.io/DevVersion/pen/kXwooK

**Comment by clshortfuse** [comment]
@DevVersion We've talked about this before, but my work with decoupling displayText from searchText is a good start for this. In reality, invalidated text isn't the searchText, but if the user wants to know what's in the input, this PR could help bringing that functionality.

https://github.com/angular/material/pull/8904/files

To clarify, this is without needing to use the `replaceTextOnSelect` option. Not that I'm thinking about it, it might more sense to call it `inputText` instead of `displayText`
