### ISSUE TITLE
md-select design issue

### ISSUE THREAD

**Issue by prabhum07** [angular/material#8959]
**Actual Behavior**:
- md-select hiding the input while opens
- width and position is not correct

![image](https://cloud.githubusercontent.com/assets/16848610/16615412/20067cc0-4394-11e6-8d6f-ca59cf4a3a1a.png)

**Expected behavior:**

I have modified using devtools for sample

![image](https://cloud.githubusercontent.com/assets/16848610/16615367/c534fee8-4393-11e6-831b-e2bbead536f3.png)

**Angular Versions**: *
 -  `Angular Version:15.7`
 -  `Angular Material Version:1.1.0-rc.5`

**Comment by EricBorlandAGS** [comment]
Hi @prabhum07, Regarding the positioning I believe that's the expected behaviour of the md-select, like the material design specs say: https://material.google.com/components/menus.html#menus-behavior

Another thing would be the width, maybe that's really a bug, not sure though. Looking at the case of the country selector in the specs I can see the width of the menu showing on top of the md-select has a bigger width than the input itself...

**Comment by wolfika** [comment]
@EricBorlandAGS is correct, the specs states clearly:

> Menus are positioned over their emitting elements such that the currently selected menu item appears on top of the emitting element.

**Comment by agencia** [comment]
what to do if I want the input to be displayed? this behaviour is annoying on autocomplete

**Comment by eric-borland** [comment]
We were talking about md-select, where the specs says the menu should close the input. Another thing is the autocomplete, where I don't see any issue with the menu showing the suggestions that is placed right under the input
<img width="440" alt="screen shot 2016-08-22 at 08 56 35" src="https://cloud.githubusercontent.com/assets/16647281/17846053/96dbf84e-6846-11e6-94bf-4f07d33e5973.png">
<img width="881" alt="screen shot 2016-08-22 at 08 56 19" src="https://cloud.githubusercontent.com/assets/16647281/17846059/9c656962-6846-11e6-9e1f-9c6a6b83333a.png">

**Comment by ThomasBurleson** [comment]
Will not fix.
