### ISSUE TITLE
Async error validation message not shown with md-input-container

### ISSUE THREAD

**Issue by miguelCT** [angular/material#8973]
**Actual Behavior**:
 -  `What is the issue?` * When specified a **ng-messages** directive for a $pending error in an input field (md-input-container), it doesn't show the *pending message* when the async validation is in progress.
 -  `What is the expected behavior?` It should show the *pending message* until the async validation is done.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/QErZLq?editors=1010
 -  `Details:` 
   - The codepen demo has 2 inputs, exactly the same input but **one** of them is styled with **material** (md-input-container) and the **other is not**. Entering a value in one of them will launch the async validation (mocked with $q).
   - When you enter '123' in the first one (material), the async validation is started but no *pending message* is shown. 2 seconds later the *error message* will show.
   - When you enter '123' in the second one (not material), the async validation is started and the *pending message* is shown. 2 seconds later the *pending error* will be replaced by the *error message*.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5 (checked also in 1.5.7)
 -  `Angular Material Version:` 1.1.0-rc5

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 51.0.2704.106 (64-bit)
 -  `OS: *` Ubuntu 14.04
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by topherfangio** [comment]
This is actually a dual-issue:

1. This is due to the default behavior of the `md-auto-hide` functionality that we provide. By default, we do not show messages unless the input is in an invalid state. Since this is still "pending", it's not marked as invalid.
2. You **should** be able to use `md-auto-hide="false"` to turn off this functionality on your second `<div ng-messages>`, however, there is a bug here in our [`getMessagesElement()`](https://github.com/angular/material/blob/master/src/components/input/input.js#L1013) function which is finding the *first* messages div instead of the second.

I am working on some tests and a fix for (2), but you will still need to use the `md-auto-hide="false"` expression to disable the auto hiding ability.

Will update this when I have a fix.

**Comment by rickyk586** [comment]
I had to set `md-auto-hide="false"` (note: it can't be dynamic), and put a ng-show on the message set to a variable
