### ISSUE TITLE
Strange behavior of md-tooltip with md-tabs when clicking next to tab area.

### ISSUE THREAD

**Issue by iconexperience** [angular/material#9015]
When using tooltips with `md-tabs`, there is a strange behavior when clicking next to the tab area. The tooltip of the selected tab is displayed and it stays visible, even when the mouse moves over another tab.

The expected behavior is that no tooltip is displayed at all on a mouse click next to the tab area.

Here is the code pen to reproduce the issue:

http://codepen.io/anon/pen/EybRxB

Steps to reproduce:

1) Click next to the tab area. Tooltip 1 will appear:

![image](https://cloud.githubusercontent.com/assets/2122773/16795016/5697fc72-48db-11e6-8e1a-8c4b2d111636.png)

2) Move mouse over tab 2. Tooltip 2 will appear, with Tooltip 1 still being displayed:

![image](https://cloud.githubusercontent.com/assets/2122773/16795090/c60b89fc-48db-11e6-8256-cbf6aaac9f1f.png)

This issue occurs on Angular Material 1.1.0-RC5. It should be browser and OS independent.

**Comment by crisbeto** [comment]
I tried looking into it. [It's this line that's causing the issue](https://github.com/angular/material/blob/master/src/components/tabs/js/tabsController.js#L637), although I'm not sure if there's a good way of solving it without breaking something else.

**Comment by crisbeto** [comment]
@iconexperience I'll have to close as being inconvenient, mainly because it's hard to solve in a generic way that doesn't break integration with other components and doesn't interfere with accessibility. If you want to solve it for this particular case, and you don't mind that the tooltip won't show up while tabbing through, you can throw this somewhere in your CSS:

```css
md-dummy-tab {
  pointer-events: none;
}
```
