### ISSUE TITLE
Use bound html variable as md-item-template in md-autocomplete 

### ISSUE THREAD

**Issue by sebastiendan** [angular/material#9027]
Hi,

I've been trying to create a generic component wrapper for md-autocomplete. Its template looks like this:

```
<md-autocomplete
        md-input-name="{{ sac.name }}"
        md-selected-item="sac.model"
        md-search-text="sac.searchText"
        md-items="item in sac.querySearch(sac.searchText)"
        md-item-text="item['{{ sac.itemTextKey }}']"
        md-min-length="0"
        md-floating-label="{{ sac.label | translate }}"
        md-menu-class="autocomplete-custom-template"
        ng-disabled="sac.disabled"
        ng-required="sac.required">
    <md-item-template><div ng-bind-html="sac.itemTemplate"></div></md-item-template>
</md-autocomplete>
```

This actually renders "sac.itemTemplate" html without replacing all angular {{ }} variables which are inside of it. I've tried to compile again manually but it does not work.
It looks like `md-item-template` is compiled somehow right before my bound html variable is compiled, so `md-item-template` takes my html and uses it in each autocomplete result but it does not process {{ item.[sth] }} (and compiling manually again does not affect this because template has already been processed by `md-item-template`).

Do you have any idea how to achieve that?
Is there a way to stop `md-item-template` compilation and run it manually after my component compilation is done?

I also tried to use transclusion for that, but we cannot transclude inside `md-item-template` component from my own component...

Thanks!

**Comment by DevVersion** [comment]
The autocomplete manually fetches the child HTML of the `md-item-template` element. That's why it's not possible to transclude it, as well as having some bindings on the top element.

Actually your HTML binding, should work, since it's not on the top element, but I can't investigate without having any demo.

Please provide one.

**Comment by sebastiendan** [comment]
Here's a demo:

https://plnkr.co/edit/EKohSCYA3JkH7t2HsYfl?p=preview

**Comment by sebastiendan** [comment]
Any news on this?

**Comment by DevVersion** [comment]
@sebastiendan So after taking a closer look at that issue. 
> Angular is not compiling the bound HTML into any scope, which means that the template won't be interpolated.
http://codepen.io/DevVersion/pen/wWyxyQ

Here is a thread on Stackoverflow
- http://stackoverflow.com/questions/19726179/how-to-make-ng-bind-html-compile-angularjs-code

So actually the `ng-bind-html` should work, since the autocomplete re-compiles the provided template (`<div ng-bind-html="..">..</div>`), but the problem is that the bound HTML is not running inside of any scope, which means that the interpolation isn't running.

> https://plnkr.co/edit/SPXu5MOAzJcjurCo3yWY?p=preview

Closing this as it's not an issue.

**Comment by sebastiendan** [comment]
@DevVersion Mmhh I had tried to compile the bound html again but I guess something else was wrong on my test...

Thank you for your prompt reply and proved example!

**Comment by sebastiendan** [comment]
@DevVersion I had indeed seen this topic on Stack Overflow.
Just copied logic from ngBindHtmlCompile directive, it works.

Thanks!
