### ISSUE TITLE
Documentation stuck at 7f01138

### ISSUE THREAD

**Issue by gpopovic** [angular/material#9055]
Instead of using the latest version on HEAD, angular material docs are stuck at
These docs were generated from ( v1.1.0-rc.5 - SHA 7f01138) on (2016-06-28 13:51:10 -0700) GMT.

URL: https://material.angularjs.org/HEAD/

**Comment by DevVersion** [comment]
I just checked with our repository and the versions seems to be correctly updated (except for one commit, since test didn't pass)
- https://github.com/angular/code.material.angularjs.org/commits/master/HEAD

Here you can see that the docs has been updated 2 days ago.
- https://github.com/angular/code.material.angularjs.org/blob/master/HEAD/js/build-config.js

This is the build config, which actually hols the SHA, which will be shown in the introduction.

---
Everything looks fine here. I guess there is something with the firebase publishing.

**Comment by gpopovic** [comment]
Any news on this one?

I'm unable to use codepen to report new bug on md-required-match

**Comment by DevVersion** [comment]
@gpopovic We're internally working on that. Please file the issue anyway and ping me on that. Thanks in advance.

**Comment by jelbourn** [comment]
Just fixed this a few minutes ago.
