### ISSUE TITLE
tab swipe not smooth as ionic SlideBox does

### ISSUE THREAD

**Issue by nvcken** [angular/material#907]
I make two demo sample as two link
https://material.angularjs.org/#/demo/material.components.tabs
&
http://ionicframework.com/docs/api/directive/ionSlideBox/

I feel swipe gesture on Material Tabs not feel smooth like ionic SlideBox and Material Tabs sometimes swipe not work, need swipe twice or third times.

**Comment by jeffthompson1971** [comment]
How were you able to get the events to work when you pull  in both ionic and angular-material?   I had to stop using ionic becuase when i include that library, any events from angular-material input controls (i.e. text-box, buttons etc) all throw an error due to the event-type not being defined.  So some issue with how events are managed between the 2 frameworks.    

how did you get around that issue?

**Comment by nvcken** [comment]
@jeffthompson1971 
No, I am not pull in ionic + angular-material together, I make separate sample follow links above.

**Comment by code-tree** [comment]
This sounds related to the drag support that is happening with the sidenav (#6174). Perhaps the same sort of implementation could be carried over to md-tabs as well?

**Comment by code-tree** [comment]
@nvcken 

> sometimes swipe not work, need swipe twice or third times

This is probably due to the sensitivity, which I've just opened an issue for (#7855)

**Comment by DevVersion** [comment]
I already built a *drag* functionality for tabs, but this was some months ago. It is really hard to calculate the correct transformations for two tab contents. 

Once you've finished the general drag behavior, many problems will appear, with static tabs and dynamic tabs etc.
