### ISSUE TITLE
md-select-header with input inside md-input-container error

### ISSUE THREAD

**Issue by viktarkorshun** [angular/material#9091]
When md-select-header with input is wrapped inside custom directive there is an error:
> can only have one , or `<md-select>` child element!" 

However putting `md-select-header` directly inside `md-select` works without any error.
[codepen](http://codepen.io/vkorhsun/pen/BzYwBL)

Angular Version: 1.4.8
Angular Material Version: 1.1.0-rc4

**Comment by ErinCoughlan** [comment]
This is likely an issue around this if statement:
[select.js](https://github.com/angular/material/blob/master/src/components/select/select.js#L278)

**Comment by crisbeto** [comment]
It's actually because both the `select` and the `input` try to register themselves with the input container. We need a check in the input container that'll ignore the child if the parent is already registered.

**Comment by Bakirelived** [comment]
I've run into this error a few days ago, and again today. Will try to implement the fix, but I just wanted to comment that I find weird that on the select demo page(vegetables), it works without problems, but when implementing on my code I have the error. Was it something caused by an lib update? should the demo page be updated or something else added?

**Comment by crisbeto** [comment]
@Bakirelived The select demo works, because it uses a plain text element for the label, whereas @viktarkorshun's demo uses an input. The error came from the fact that when an input is inside a `md-input-container`, it tries to register itself with the container, in order to do some custom interactions, however in the demo the input's parent select has already registered itself with the container.

**Comment by Bakirelived** [comment]
I was talking about this code
`<md-input-container>
        <label>Vegetables</label>
        <md-select ng-model="selectedVegetables"
                   md-on-close="clearSearchTerm()"
                   data-md-container-class="selectdemoSelectHeader"
                   multiple>
          <md-select-header class="demo-select-header">
            <input ng-model="searchTerm"
                   type="search"
                   placeholder="Search for a vegetable.."
                   class="demo-header-searchbox _md-text">
          </md-select-header>`

where there is an input tag for the search term.

I've implemented the fix but I still have the error. I have a custom directive witch is basically a widget, witch has an add button that prompts a dialog. in that dialog i want to have a select field, and I could use the search functionality, as it is on the demo, but I get this error.. I'm not sure if it is completely related, of if this fix won't work for my setup. here is my code:

`<md-input-container flex="none">
                                        <label>{{ '_parcel_list_'| i18n }}</label>
                                        <md-select ng-model="group.parcels"
                                                   multiple>
                                            
                                                
                                                       
                                                       
                                            
                                            <md-optgroup label="parcels">
                                                <md-option ng-value="parcel" ng-repeat="parcel in parcels">
                                                    {{parcel.name}}
                                                </md-option>
                                            </md-optgroup>
                                        </md-select>
                                    </md-input-container>`

**Comment by crisbeto** [comment]
Which fix did you apply? The one from PR #9101?

**Comment by Bakirelived** [comment]
yes, this commit 349c49d638e5d76451ae25383b1642cbad3c59f3
but i've edited the angular-material.js file by hand, as I couldn't find the master build file

**Comment by crisbeto** [comment]
I'll take another look at it, but could you post a new issue for it so it's easier to track?

**Comment by Bakirelived** [comment]
my issue was fixed with the latest release, I wasn’t implementing the fix right. 

One thing that I think should be added, is the css that is on the demo page(demo-header-searchbox _md-text) to the angular-material.css so that when there is an input field inside of the md-select-header directive it would behave just like the demo page
