### ISSUE TITLE
md-input-container the input bottom line disappeared in chrome installed on android

### ISSUE THREAD

**Issue by birdman2005** [angular/material#9121]
the bottom line of he input included in md-input-container display normal in chrome installed on mac,but it disappeared in chrome installed on android

**Comment by DevVersion** [comment]
Please provide more information. That's why there is the issue template.

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Comment by birdman2005** [comment]
Thans @DevVersion ,the problem has been solved when i rewrite the demo.
