### ISSUE TITLE
md-select directive default value can't make the required be valid

### ISSUE THREAD

**Issue by wcmboy** [angular/material#9124]
**Actual Behavior**:
 -  `What is the issue? *`When set default value to the select directive which is required,the form still invalid.
 -  `What is the expected behavior?`The form should be valid.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`http://codepen.io/wcmboy/pen/BzxJQv
 -  `Details:`In the six line of the AppCtrl controller,I set $scope.myModel default value was 2.But the myForm.$invalid still was ture.

**Angular Versions**: *
 -  `Angular Version:`1.5.5
 -  `Angular Material Version:`v1.1.0-rc.5

**Additional Information**:
 -  `Browser Type: *`Google Chrome
 -  `Browser Version: *`49.0.2623.110 m
 -  `OS: *`Windows 10
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by vishalcshinde** [comment]
`
angular.module('MyApp',['ngMaterial', 'ngMessages', 'material.svgAssetsCache'])
.controller('AppCtrl', function($scope) {
  $scope.data = {};
  $scope.clearValue = function() {
    $scope.data.myModel = undefined;
  };
  $scope.data.myModel=2;
  $scope.save = function() {
    alert('Form was valid!');
  };
}); `

and in html 

`ng-model="data.myModel" `

**Comment by rhllor** [comment]
Hi, 
this patch resolve problem with numeric value. But if ID is Zero value the problem persist. 
This is correct? Or we can fix?

**Comment by xplodwild** [comment]
Bump :) Can this PR be merged? I'm hitting the same issue and since our architecture is type-dependant, we'd rather not rely on a type cast workaround.

**Comment by AleksueiR** [comment]
This seems to be solved in 1.1.0: http://codepen.io/AleksueiR/pen/vKqXQd

**Comment by xplodwild** [comment]
@AleksueiR No, your CodePen doesn't match the issue here. Replace `"one"` and `"two"` with `"1"` and `"2"`, and `=2;` as the default value: http://codepen.io/anon/pen/RRXqRm

**Comment by xplodwild** [comment]
Bump! Any news on a fix for this issue? Surely I'm not the only one using numerical values for md-select options?

**Comment by topherfangio** [comment]
@xplodwild I'm not sure this is considered a bug anymore. We made some changes and updated the docs available at https://material.angularjs.org/1.1.1/api/directive/mdSelect

Specifically, the following note is important (particularly the "always evaluates to a string" portion):

> **Note:** Using the `value` attribute (as opposed to `ng-value`) always evaluates to a string, so `value="null"` will require the test `ng-if="myValue != 'null'"` rather than `ng-if="!myValue"`.

So, in your case, if you want the model to be set to `2`, you should use `ng-value` which will evaluate to a number rather than a string.

Does this solve your issue?

**Comment by xplodwild** [comment]
Thanks, it indeed seems to work using ng-value. I didn't notice the change in the docs.
Updated CodePen for reference: http://codepen.io/anon/pen/PGKogB
This issue can be closed :)

**Comment by topherfangio** [comment]
@xplodwild Awesome, glad you got it working! Thanks for letting us know.

I'll go ahead and close this.

**Comment by jblaketc** [comment]
@topherfangio I'd almost put a throw error restriction on using value in md-option, like y'all do in some of the other directives for certain tags, unless there's a specific use case for having value instead of ng-value.

The reason I say this is I upgraded a project to 1.1.1 and it wasn't obvious that my selects on an edit page weren't working because I was using value in the md-option tag. The selects that weren't working were those tied to ids. When I went to submit the form, those selects that store ids in my ng-models were being marking with ng-invalid-required, even though the model itself had a number valid, non-zero number.

. The reason I bring this up is because: 

````
Note: Using the value attribute (as opposed to ng-value) always evaluates to a string, so value="null" will require the test ng-if="myValue != 'null'" rather than ng-if="!myValue".
````
doesn't make clear that at this point, md-select won't even see an option as valid if you store numbers in the value tag.
