### ISSUE TITLE
md-item with type checkbox is broken when using ng-repeat together

### ISSUE THREAD

**Issue by rokaakio** [angular/material#9164]
**Actual Behavior**:
![image](https://cloud.githubusercontent.com/assets/2730454/17220045/7353e900-54b3-11e6-84e6-9b9a966dde02.png)

 -  `What is the issue? *`
When using ng-repeat for md-item with checkbox type, css of items are broken, and checkbox is not functional
 -  `What is the expected behavior?`
Should work as good as hard code items

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
http://codepen.io/rokaakio/pen/QExRQN
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:1.5.5
 -  `Angular Material Version:1.1.0

**Additional Information**:
 -  `Browser Type: Chrome
 -  `Browser Version: 
 -  `OS: Windows
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by topherfangio** [comment]
Looks like the majority of our code currently runs in the `compile()` function of the MenuItemDirective. Need to see if we can refactor this to run during the `postLink()` phase to better accommodate cases like this.

**Comment by topherfangio** [comment]
Actually, it looks like this has been fixed since RC5.

Here is an updated Codepen where I stripped out the unnecessary menus and upgraded to the HEAD version which will be 1.1.0: http://codepen.io/topherfangio/pen/Lkgypb

Note, though, I did not update your `ng-model` statement which is incorrect as it does not account for the `ng-repeat`.

Please try upgrading. If you still have trouble getting it to work properly, please post another comment here and we will re-open.
