### ISSUE TITLE
md-select required problem

### ISSUE THREAD

**Issue by rhllor** [angular/material#9176]
Hi, 
I have a problem with md-select. 
I have preloaded data and select is required. I see error required but value already exists.

For see error click validate button on codepen

http://codepen.io/rhllor/pen/VjBjOa

**Comment by DevVersion** [comment]
This is actually not an issue. The validation turns invalid because of https://github.com/angular/material/commit/da02ea2eb500dc297f4028b9cdedd4e86bffd69b.

That's because you're setting the ngModel to a number, while the values are actually a `string`.
We will probably add another _helper_ to cast those numbers to a string.

See https://github.com/angular/material/issues/9124

**Comment by rhllor** [comment]
Thanks for solution
