### ISSUE TITLE
$mdDialog.hide() in a promise callback does now work when the promise is immediately resolved

### ISSUE THREAD

**Issue by xylosper** [angular/material#9200]
**Actual Behavior**:
 -  `What is the issue? *`
$mdDialog.hide() (also $mdDialog.cancel()) does not work when it's called in promise callback which is resolved immediately.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`http://codepen.io/anon/pen/OXwKxQ
 -  `Details:`
good button shows normal case.
bad button shows the buggy case. The dialog can't be closed.

**Angular Versions**: *
 -  `Angular Version:` 1.5.7
 -  `Angular Material Version:` 1.0.9

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` Chrome 51
 -  `OS: *` Windows 8.1
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
I just checked your Codepen.

It seems like you accidentally used `$q.defer()` which doesn't resolve automatically. 
> That means that the `close` function will be never called.

Here is an updated Codepen: http://codepen.io/DevVersion/pen/yJxVdg

I will close that issue since everything works as expected.

Just FYI: `.show()` returns a callback which will be resolved / rejected after close`
