### ISSUE TITLE
Md-list-item with ng-click has no hover effect for inner content

### ISSUE THREAD

**Issue by jweinstein92** [angular/material#9247]
**Actual Behavior**:
 -  `What is the issue? *` Previously, I was able to have an md-list-item with an ng-click (or ui-sref) and the inner content still had the hover effect. Currently, if an md-list-item has an ng-click the hover effect stops at the button that gets created.
 -  `What is the expected behavior?` Hover effects on nested content should occur.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/QEkmLw
 -  `Details:` The first md-list-item is one without an ng-click event. The hidden text can be seen by hovering over it. The second md-list-item has an ng-click event. Hovering over it will not show the hidden text

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.0-rc5

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 52.0.2743.82
 -  `OS: *` Mac OS X El Capitan
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
This is actually a known issue - We had similar issues like #8946.

The problem is that we are not able to fix that issue on the core, because we had to decide whether we want to support the `md-list-item` on several browsers or give users more flexibility for their custom content.

The button which overlays the whole `md-list-item` is needed to provide proper support for the different browsers like Safari / Firefox and IE. Those browsers are strictly following the W3C specification for the `button` element.

> Content Model: Phrasing content, but there must be no interactive content descendant.

This means that we are not allows to place any interactive content inside of the button (as it was previously and didn't work for the mentioned browsers).

However we hope to provide more flexibility for the `md-list-item` with #8482.

In meanwhile you are able to elevate your specific element to archive the same behavior as before.

```css
.overlaying-element {
  position: relative;
  z-index: 1;
}
```

**Comment by jweinstein92** [comment]
@DevVersion That works to get the hover effect working, however then the click event no longer occurs. http://codepen.io/anon/pen/EydZgG

Would the solution then be to move the click event to the overlaying element instead of the md-list-item?

**Comment by DevVersion** [comment]
@jweinstein92 That would make sense. 

If you don't care about the aforementioned browser support, then you could also create a parent `md-button` with `md-no-style` on it, and wrap everything you need inside of it.

> codepen.io/DevVersion/pen/AXJPom

**Comment by jweinstein92** [comment]
Great thank you
