### ISSUE TITLE
Compatibility Issue with IE11

### ISSUE THREAD

**Issue by okaiyong** [angular/material#9262]
May I know if the team has tested Angular Material on IE11? There was no errors but the components didn't work well in IE11 compared to Chrome.

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'deprecated' category. We deprecate issues for one or more of the following reasons:

*  Issue has a reasonable workaround
*  **Issue doesn't have a demo or reproducible case available**
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests are welcomed to resolve this issue. But note that **not** all community PRs will be merged into master. Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
