### ISSUE TITLE
unable to show the error error messages

### ISSUE THREAD

**Issue by technotomahi** [angular/material#9274]
Hi,

I was trying to implement a custom server side error message display at md-input container. The [plunker](http://plnkr.co/edit/4lLDijmmjfzN9PSbzpPK?p=preview)  is here.

Here I can set the error class at the md-container so the level and the red botton border is highlighted. But I am unable to show the error message for the same.

Can anyone have a look . what I am doing wrong.

**Comment by topherfangio** [comment]
Ok, your main issue was that you were not including the `ngMessages` module (neither as an Angular dependency or a script tag). This is not included by default with Angular Material and you have to add it yourself.

http://plnkr.co/edit/sQiq8gUPrWrd58UQB7SN?p=preview

The above Plunk shows:

1. How to add the script tag and the `ngMessages` dependency,
2. How to manually set/update the validity of one of your inputs (in this case, we modify the `loginValid` property of the `lastName` field),
3. Using a service to do this instead of putting it directly in your controller, and
4. The service fakes a HTTP request by using `$timeout` and `$q.defer()` to make it asynchronous

Hope this helps. I'm going to go ahead and close this. Let me know if you have questions/issues/or if this is not fully resolved.
