### ISSUE TITLE
md-autocomplete highlight support for multiple strings

### ISSUE THREAD

**Issue by teckwrek** [angular/material#9282]
As designed, the md-item-template in the md-autocomplete only allows for a single string to be mentioned for highlight (md-highlight-text).

Need to be able to pass in an array of strings to md-highlight-text and highlight all of those in the display. This will allow people to see multiple token hits in a given autocomplete entry.

The only trouble could be with overlapping highlight spans, but that should be ok if the input array is split at word boundaries.

**Comment by DevVersion** [comment]
I don't think we are going to change that behavior of the `md-highlight-text` directive, because the `autocomplete` is actually designed to only highlight one string. Mostly the `searchText`

If I understood your issue correctly, you want to be able to pass another highlight text to the `md-highlight-text` attribute.

A possible workaround would have been to pass in a regex with a match group, to be able to search for multiple strings.

```js
self.getHighlightRegex = function() {
  var searchStrings = [self.searchText, 'test'];
  return '(' + searchStrings.join('|') + ')'
}
```

But this does not work, because the `md-highlight-text` directive sanitizes the specified value of the `md-highlight-text` attribute.

I recommend asking in  the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or on Stackoverflow.
