### ISSUE TITLE
md-datepicker doesn’t allow changing date manually when date format contains time

### ISSUE THREAD

**Issue by mirik123** [angular/material#9327]
The md-datepicker doesn’t allow changing date manually when date format contains time.
For example, when date is of this format it works: ‘DD/MM/YYYY’,
and when of this format is doesn't work: ‘DD/MM/YYYY HH:mm:ss’

Codepen: http://codepen.io/sdfgfdgfdg/pen/rLRJjJ?editors=1010

**Comment by crisbeto** [comment]
A couple of notes:

1. In your case, the value isn't being set to the model, because it doesn't pass the `dateLocale.isDateComplete` check which does some further date validation ([you can check which inputs pass here](https://github.com/angular/material/blob/master/src/components/datepicker/js/dateLocale.spec.js#L59)). You can override this method in the same way you override `parseDate` and `formatDate`. E.g. here's how you can disable it completely:

```js
$mdDateLocale.isDateComplete = function() {
  return true;
};
```

2. **This behaviour is not supported.** This means that even if you override the `isDateComplete` check, the user still won't be able to set the time, because Material sets the time to midnight before applying it to the model. You might be able to monkey patch the `$mdDateUtil.setDateTimeToMidnight` method, however this pretty hacky and could lead to unexpected behaviour.

**Comment by mirik123** [comment]
Thanks,
Updated codepen with working example: http://codepen.io/anon/pen/akAvOr?editors=1010
