### ISSUE TITLE
the question of .min.css'size

### ISSUE THREAD

**Issue by lesonli** [angular/material#9334]
why the size of .min.css on google cnd only is 33k?but the same file download from github is 360k??

**Comment by crisbeto** [comment]
Seems fine [to me from this link](http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0/angular-material.min.css). What link are you using?

**Comment by DevVersion** [comment]
I just compared the contents of the file inside of [bower-material](http://www.github.com/angular/bower-material) and the one from the Google CDN and those look from the content equal.

![image](https://cloud.githubusercontent.com/assets/4987015/17769664/f26953b0-6539-11e6-8227-e78ed713909f.png)


When reading from the Chrome devtools and not enabling `Big Rows` you will only see the transfer size, instead of the content size (of the resource)

![image](https://cloud.githubusercontent.com/assets/4987015/17769661/efc3abe2-6539-11e6-98f4-e3bd06d7e3b2.png)

The downloaded files should show the correct size.

**Comment by lesonli** [comment]
@DevVersion thank u very much~~~
