### ISSUE TITLE
Move polyfills to separate optional file

### ISSUE THREAD

**Issue by epelc** [angular/material#9378]
Polyfills like the one described in #9169 should be optional if you are using a newer version that does not require them.

Please consider moving these so that we can have smaller more efficient builds if we are using the latest and greatest :)

**Comment by topherfangio** [comment]
I did a quick check. I think the `animateCss.js` file is the only one we have which does a polyfill. When compressed, this only saves 3K, so we're thinking it's not really worth the investment/breaking change to separate them.

Additionally, we're hoping (although this hasn't been approved yet), that v1.2 of Material will be able to use only ng1.5 so that we can get rid of the polyfills altogether. Should have a verdict soon on that.

In the meantime, I'm going to go ahead and close this.
