### ISSUE TITLE
md-colors theme doesn't affect child md-icon 

### ISSUE THREAD

**Issue by amitport** [angular/material#9435]
**Actual Behavior**:
 -  `What is the issue?` md-icon is not affected be non-direct md-colors
 -  `What is the expected behavior?` md-icon should be affected

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/EyqXJA

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type:` chorme
 -  `Browser Version:` 52
 -  `OS:` win10
 -  `Stack Traces:`

**Comment by EladBezalel** [comment]
Hey, at first i was thinking about letting `md-icon` inherit the text color which should easily solve this issue,
but after reading a bit in the [Material Design Spec](https://material.google.com/style/icons.html#icons-system-icons) (at the end of the page) there's only one place that talks about the icon color and on all of the examples the icon has the same color as mentioned.

Quoting:
> **Color**

>The standard opacity for an active icon on a light background is 54% (#000000). An inactive icon, which is lower in the visual hierarchy, should have an opacity of 26% (#000000).

>The standard opacity for an active icon on a dark background is 100% (#FFFFFF). An inactive icon, which is lower in the visual hierarchy, should have an opacity of 30% (#FFFFFF).

If you still want to overcome it and make all icons (inside `md-colors`) to inherit i suggest you the next override:
```css
[md-colors] md-icon {
  color: inherit;
}
```
working example [here](http://codepen.io/EladBezalel/pen/YWmbrO)

**Comment by amitport** [comment]
Hey @EladBezalel, I think the paragraph talks about opacity, and only opacity. It mentions black and white codes, but refer to "dark" and "light" backgrounds. As I understand it, the color should inherit and adjust for opacity depending on the background being dark or light.

In any case, even if it should be interpreted as you say, angular material does not implement this behavior and md-icon does not change its color or opacity when inside `md-colors="{background: 'grey-900'}", etc,.

So, although your solution works fine for me, md-icon won't adjust for opacity as the spec says and. IMHO, this issue should be re-opened

Thanks!

**Comment by EladBezalel** [comment]
I'm having doubts about this one,
the issue you're describing isn't entirely `md-colors` related,

`md-icon` specifically sets it's own color so it **shouldn't** inherit from text color (since it has it's own opacity)

**but** `md-colors` get's the correct foreground color for you (if you're not explicitly specifying - `color`).
in that case i would've to agree that icon should inherit.

**BUT** in your demo you set the foreground color with `md-colors` which is like putting a class on `md-icon` wrapper element with `color` css property and expect `md-icon` to inherit.

Any way, the solution is 
```css
[md-colors] md-icon {
  color: inherit;
}
```

The question is, are we going to support it or not?

cc: @topherfangio @ThomasBurleson @ErinCoughlan

**Comment by amitport** [comment]
shouldn't it be something like this? (always inherit and adjust for opacity)
```css
md-icon {
  color: inherit;
  opacity: 0.54;
}
md-icon[disabled] {
  opacity: 0.26;
}
.md-dark-background md-icon {
  opacity: 1;
}
.md-dark-background md-icon[disabled] {
  opacity: 0.3;
}
```

(I know implementing this may not be worth the effort for this use-case, but I just want to communicate my understanding of the spec)

**Comment by EladBezalel** [comment]
Sort of, but our theming service doesn't work like that, 
@clshortfuse afaik we can't distinguish between dark and light themes am i right?

**Comment by clshortfuse** [comment]
@eladbezalel Correct. There is stashed code for using special rules specifically for dark themes, but that is more for situations like `md-slider`. What he wants is the color to follow spec based on theme lightness, which already has a pending PR.

On the point of using `color: rgba` and not using an `opacity` rule: opacity is actually expensive since most browsers will render it as a 3D object because, generally, you animate that property.

Finally, on the actual issue, IMO, this works works as expected. If I wanted to color an md-content or md-card, I don't want my icons to change colors. I'm pretty sure you can do md-colors on md-icon. I believe the string passed doesn't have to be literal. You can do `md-colors="{color: myIconColor, opacity: myIconColorOpacity}"`

Since the developer is in control of when themes change, he can modify `myIconColorOpacity` as needed when the theme changes.

**Comment by amitport** [comment]
Of course I can set the color on the icon either indirectly using md-colors or directly using class or style. That may be a reasonable _workaround_.

Again, I understand this may be rejected for being too much of a code change or a potential performance issue. I just don't get why you would consider an issue that forces users to add custom-redundant code for aligning with the spec as 'working as expected'.

**Comment by clshortfuse** [comment]
What I meant by working as expected is that fact that md-icon not inheriting color is correct. Because they use a different alpha channel than text, they shouldn't be using the same RGBA value. That's what this topic is about. This isn't a bug that needs to be fixed.

Yes, there is work that needs to be done with opacity values, but that's not the scope of this issue. I didn't explicitly state which PR because of github's auto referencing when I said:

> What he wants is the color to follow spec based on theme lightness, which already has a pending PR.

But I believe you should take a look at : https://github.com/angular/material/pull/8872

It should provide more valuable tools when you mix it with `registerTheme`.

But I think you should take a look at planned
