### ISSUE TITLE
AutoComplete doesn't filter and highlight while looking for text in the middle

### ISSUE THREAD

**Issue by mohanskumar** [angular/material#9445]
**Actual Behavior**: 
 -  `What is the issue? *` AutoComplete doesn't filter by contains text
 -  `What is the expected behavior?` AutoComplete should filter by contains text

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`  ttps://material.angularjs.org/latest/demo/autocomplete
 -  `Details:` Go to the basic usage card and type the word "for" in the AutoComplete. California should show up. But its not.

**Angular Versions**: *
 -  `Angular Version:` 1.5
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *`  Chrome
 -  `Browser Version: *` 52
 -  `OS: *` Windows 10
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
This is not an issue. The demo is only matching the characters at the beginning of a result.

In our demo we specified the `^` flag, which says that we only match at the beginning of the result.
> https://material.angularjs.org/latest/api/directive/mdHighlightText

If we remove that and specify the flag `g` (for global), then it will highlight all matches.

But this also requires the `query` function to be updated, because it also filters and currently only at the beginning.

```js
// At the beginning
return (state.value.indexOf(lowercaseQuery) === 0);
// Globally matching
return (state.value.indexOf(lowercaseQuery) !== 1);
```

Here is a demo, which shows how it works.
- http://codepen.io/DevVersion/pen/KrOYoG

Closing as it's not an issue.
