### ISSUE TITLE
input-container: use in table cells

### ISSUE THREAD

**Issue by cybercoder** [angular/material#9459]
``` html
          <td>
            <md-input-container class="md-block" flex-gt-sm>
              <md-select ng-model="selected.FoodCategoryId" required name="foodGroup">
                <md-option ng-value="{{fc.id}}" ng-repeat="fc in foodCategories">{{fc.title}}</md-option>
              </md-select>
              <!-- <input ng-model="selected.FoodCategoryId"/> -->
            </md-input-container>
          </td>
          <td>
            <md-input-container class="md-block" flex-gt-sm>
              <input ng-model="selected.title">
            </md-input-container>
          </td>
          <td>
            <md-input-container class="md-block" flex-gt-sm>
              <input type="text" ng-model="selected.price">
            <md-input-container>
          </td>

input elements are not in a fixed row, their positions change like ladder. I can't use a "<div layout="row">" in the table rows to fix it, so how can fix it?!
```

**Comment by EladBezalel** [comment]
Our issue template is there not to be deleted,

Please follow the instructions of filing an issue:

**Actual Behavior**:
 -  `What is the issue? *`
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.
