### ISSUE TITLE
tooltip: conflict when used in mdInputContainer's label

### ISSUE THREAD

**Issue by ErinCoughlan** [angular/material#9464]
**Actual Behavior**:
-  `What is the issue? *`
  Tooltips are not allowed within an md-input-container label. Instead, they are placed on the entire input.
-  `What is the expected behavior?`
  I can place a tooltip within the label.

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` http://codepen.io/erincoughlan/pen/NRKaOk
-  `Details:`

Summary from slack: The tooltip looks for it’s first parent that does not have `pointer-events: none;`. Unfortunately, it looks like the input container’s label uses `pointer-events: none` so the tooltip skips it and goes straight to the input container. A quick workaround is to just add `style="pointer-events: auto;"` to the label.

AngularJS: 1.5.5
Angular Material: 1.1.0

**Comment by crisbeto** [comment]
To mention my findings on this:

- The tooltip looks for the closest parent that doesn't have `pointer-events: none`. This is necessary, because the parent wouldn't fire mouse events if it had `pointer-events: none`.
- The input labels have `pointer-events: none` in order to allow the user to click through them to focus the input.

As of now, I see a few solutions which aren't ideal.

1. Removing the `pointer-events` from the input labels and changing their cursor. The labels would forward focus in that case, but it means another event handler.
2. Removing the `pointer-events` logic from the tooltip. This would cause it to not appear in certain cases. We could log a warning if we encounter it.
3. If the tooltip parent has `pointer-events: none`, we can add an overlay via `::after` which causes the events to start firing again. This sort of defeats the purpose of `pointer-events: none` and would require us to change the `position` of the parent.

**Comment by Splaktar** [comment]
This does seem like a valid and possibly common use case, but so far there have been very few 👍🏼 on this issue.

I updated the [CodePen](https://codepen.io/Splaktar/pen/jdpNEG?editors=1010#0) to `1.1.12` and removed the complication of a `md-chips` in an `md-input-container` which is not well supported. Even with this more simple case, the tooltip behavior is not ideal and the position is not correct.

**Comment by Splaktar** [comment]
https://github.com/angular/material/issues/10878#issuecomment-326202176 actually asks that we generate a console warning if things aren't right. We could consider removing the `pointer-events` logic and generating warnings in `1.2.0` but I think that would be a breaking change that couldn't go into `1.1.x`.

**Comment by Splaktar** [comment]
No feedback has been provided on the above discussions and this did not get into `1.2.0`, so a breaking change isn't viable at this point. Plus there has not been a lot of 👍  on the issue. So I'm going to close this.
