### ISSUE TITLE
md-input-container not flexing evenly - edge case?

### ISSUE THREAD

**Issue by parky128** [angular/material#9469]
**Actual Behavior**:

I have come across a scenario when using md-input-containers inside a parent that has a combination of layout column and row, that the md-input-containers do not always flex as I would want.

This issue only seems to occur where I have an input followed by an md-select, both inside their own md-input-container's

**CodePen** 

http://codepen.io/parky128/pen/amojra

If you take a look at the first card, the md-input-container that contains the md-select is not flexing evenly, unlike in the other examples on the other two cards.

The only difference is that the first card uses an input followed by an md-select. I can fix by using flex="50", but I would have thought using flex alone would give me the same sizing behaviour as in the other examples.

Is this misuse on my part, or a bug?

**Angular Versions**:
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 52.0.2743.116 m
 -  `OS: *` Windows 7
 -  `Stack Traces:`

**Comment by topherfangio** [comment]
So the idea behind flex is that it allows components to grow to take up the "remaining available space".

I think Chrome (and possibly other browsers) define the "natural" width of the input/select a bit differently, and thus they take up unequal amounts of extra space.

That's why it works fine for rows that have two of the same element, but gets funky when you mix & match. So this is really a flex-related issue/question; not sure Material can really do anything about it.

If you want a 50/50 split, you should definitely use `flex="50"` to achieve it.

Let me know if you have more questions or see a specific issue that you think needs to be fixed and I can reopen 😃
