### ISSUE TITLE
md-tabs with layout-padding but without md-dynamic-height causes misalignment of content

### ISSUE THREAD

**Issue by hhp21** [angular/material#9503]
This relates to angular-material 1.1.0. When you use md-tabs under a div with layout-padding, and you are not using md-dynamic-height, because of this rule:

`md-tabs-content-wrapper {
    display: block;
    position: absolute;
    top: 48px;
    left: 0;
    right: 0;
    bottom: 0;
    overflow: hidden;
}`

and since `position: absolute` does not respect padding the content will be misaligned with the tabs. As a workaround for my use case I've simply added a rule like this:

`.layout-padding > md-tabs:not(.md-dynamic-height) > md-tabs-content-wrapper {
  top: 56px;
  bottom: 8px;
  left: 8px;
  right: 8px;
}`

but it probably needs similar rules for the other breakpoints.

**Comment by EladBezalel** [comment]
Please don't ignore our issue template:

**Actual Behavior**:
 -  `What is the issue? *`
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'deprecated' category. We deprecate issues for one or more of the following reasons:

*  Issue has a reasonable workaround
*  Issue doesn't have a demo or reproducible case available
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests are welcomed to resolve this issue. But note that **not** all community PRs will be merged into master. Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
