### ISSUE TITLE
md-tooltip wont work until scrolled

### ISSUE THREAD

**Issue by djfd** [angular/material#9506]
**Actual Behavior**: 
 -  `What is the issue? *` a set of md-tooltips sharing their visibility state through md-visible attribute (initially set to true) do not disappear on blur. After scrolling (and thus disappearing) they become to operate as expected

UPD. adding ng-cloak to outer DIV gives unexpected result: both tooltips are shown in wrong location
 -  `What is the expected behavior?` it is expected that they have to disappear on blur.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/djFD/pen/rrNQjZ http://s.codepen.io/djFD/debug/rrNQjZ
 -  `Details:` right after page load hover on and off over gray stripes, nothing happens, tooltips still visible. now scroll a few, then play with hover/blur. all works fine at this moment

**Angular Versions**: *
 -  `Angular Version:`1.5.7
 -  `Angular Material Version:`1.1.0

**Additional Information**:
 -  `Browser Type: *`firefox
 -  `Browser Version: *`48.0
 -  `OS: *`linux
 -  `Stack Traces:`nope

**Comment by crisbeto** [comment]
After looking into it, it seems like this behaviour is intentional. The point of `md-visible` is to allow programmatic toggling of the tooltip, which is why it doesn't bind the "leave" events (the exception being "scroll"), in order to prevent the user from closing it manually. E.g. you can try toggling the "Insert drive" checkbox in [the demo](https://material.angularjs.org/HEAD/demo/tooltip) and hovering over the tooltip container.

**Comment by djfd** [comment]
well, maybe intentional, thank you for clarification. But what about misplaced tootlips in a presence of ng-cloak on containing div?

**Comment by crisbeto** [comment]
That's because the parent still hasn't been laid out when the tooltip is being positioned. This is a little tricky to solve without layout thrashing, because Material can't know in advance when the parent will become visible. It's possible to solve by watching for the element's `offsetParent`, however [each read on that property can cause a reflow](https://gist.github.com/paulirish/5d52fb081b3570c81e3a).

**Comment by djfd** [comment]
hmm, I could not agree, but too lazy now to open new issue. please check http://codepen.io/djFD/pen/EgxqjL all the same conditions (ng-cloak) but works correct

**Comment by crisbeto** [comment]
I'm not sure how the `wl-tooltip` works, but if it has a timeout on initialisation, it could delay it enough so that the element has dimension by the time it has to be measured. I can check if something like this would work in Material.

**Comment by djfd** [comment]
yeah, btw about delay. it is configured for both codepens as 500ms, just FYI

wl-tooltip works exactly same, with a few exceptions: there is not isolated scope (ie. scopeless at all) and there will be the only watcher in case when we have md-visible set to some control variable. Well, one more watcher is added by angular if we have interpolated md-direction.
