### ISSUE TITLE
md-icon failed to render inside SVG

### ISSUE THREAD

**Issue by djfd** [angular/material#9539]
**Actual Behavior**:
 -  `What is the issue? *`It is impossible to insert md-icon into SVG's ```<text />``` tag
 -  `What is the expected behavior?` it is expected it have to work exactly same as in HTML context

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` [here](http://codepen.io/djFD/pen/mAJypb)
 -  `Details:`there are 4 md-icons in total, 3 of them are inside of svg graphics. the only shown icon is that inserted into plain ```DIV```

**Angular Versions**: *
 -  `Angular Version:`1.5.7, 1.5.8
 -  `Angular Material Version:`1.1.0

**Additional Information**:
 -  `Browser Type: *`firefox, chromium
 -  `Browser Version: *`48.0, 52.0.2743.116
 -  `OS: *`linux
 -  `Stack Traces:`--

**Comment by clshortfuse** [comment]
@djfd I see what you're trying to do, but the issue isn't with the framework. There are issues with your SVG code.

SVG `text` element will display any child `foreignObject` elements, regardless of tag or if you include `xlmns` Also, the bottom SVG doesn't rendered because you didn't wrap it with a  `foreignObject` tag.

http://codepen.io/shortfuse/pen/NRyYWW
