### ISSUE TITLE
mdListItem. If inner element has "transform" property it's not clickable

### ISSUE THREAD

**Issue by levgaas** [angular/material#9549]
Updated to **v1.1.1** And facing this issue.
I want to rotate icon inside `md-list-item` but have no ability to click on it

http://codepen.io/levgaas/pen/zKGaqr

As you see I can click on it only once when there is no "transform" prop. And then after it is added. I have no ability to do that

**Comment by DevVersion** [comment]
This is kind of a known issue and we don't had an easy way to fix that, because otherwise there would be a huge accessibility issue. But we have some efforts in progress to simplify the list a lot (#8482 #9194)

But there is a workaround which was explained [here](https://github.com/angular/material/issues/8946#issuecomment-230326674).
>  Your example doesn't work, because there's a transparent button overlay on top of the list item. This is necessary for proper accessibility and cross-browser compatibility. Working around this in Material might not be appropriate, however fixing it on your side should be pretty simple: you just need to add a z-index to the text

I would recommend using a normal icon button instead. 

```html
<md-button class="md-icon-button">
  <md-icon>...</md-icon>
</md-button>
```

But having a relative position also works

```css
.myIcon {
  position: relative;
  z-index: 1;
}
```

**Comment by levgaas** [comment]
@DevVersion  I think that it's not the same issue because I've tried it with `<md-button>` and had no success. To fix that I need to duplicate `ng-click` on `md-button`
Seems like `md-button` doesn't propagate events

**Comment by DevVersion** [comment]
It's definitely not the same issue, but the cause is the same. 

The overlaying button is "overlaying" the icon and that means that the clicks are not emitted. Elevating the icon per z-index moves the element over the button, and the element is able to receive clicks.
