### ISSUE TITLE
md-virtual-repeat

### ISSUE THREAD

**Issue by mikila85** [angular/material#9573]
an edit has been sent to the server and now i want to refresh the list.
what i currently do is recreate the object:
$scope.dynamicItems = new DynamicItems();

but it takes the list back to top (scroll Index 0).

how can i "refresh" the list and still remain on the same scrolled index?

**Comment by ThomasBurleson** [comment]
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

!! **CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.
