### ISSUE TITLE
mdInputContainer: theme classes not applied to mdSelect 

### ISSUE THREAD

**Issue by mckenzielong** [angular/material#9592]
**Actual Behavior**:
-  `What is the issue? *` mdSelect inside an md-input-container does not respect theming classes (md-accent for example)
-  `What is the expected behavior?` mdSelect will behave like input, mdDatepicker and textarea inside an input container and use the theme class set on the input container.

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` http://codepen.io/mckenzielong/pen/mAVXLJ
-  `Details:`
  - tab through the inputs.  First input is accent, first select has accent placed on the container, second input has accent placed on the select element.
  - note that the first select does not respect the theming class

**Angular Versions**: *
-  `Angular Version:` 1.5.8
-  `Angular Material Version:` 1.1.1

**Additional Information**:
-  `Browser Type: *` Chrome/ Opera
-  `Browser Version: *` 53/39
-  `OS: *` Windows 7
-  `Stack Traces:` N/A

**Comment by mikila85** [comment]
+1

**Comment by Splaktar** [comment]
I updated the [CodePen](https://codepen.io/Splaktar/pen/PBqxzx?editors=1010) to 1.1.10 and still see this issue. I also [reproduced this issue](https://codepen.io/Splaktar/pen/xJGQrL?editors=1010#0) in the Validations demo for select.

@rudzikdawid do you think that you can look at this one please?

**Comment by rudzikdawid** [comment]
@Splaktar in your CodePen example there is no `md-theme` directive inside view or any  `$mdThemingProvider` inside controller, i think that is why theme classes not applied to mdSelect.

Look at https://codepen.io/anon/pen/XBmJjZ?editors=1010 here with `md-theme` theme classes are applied to mdSelect

**Comment by Splaktar** [comment]
Right, but the default theme (indigo primary and pink accent) should still work properly. I added that in another [CodePen](https://codepen.io/Splaktar/pen/jpbemx?editors=1010#0) but it didn't make a difference.

![screen shot 2018-07-13 at 8 02 27 pm](https://user-images.githubusercontent.com/3506071/42718537-d5bac958-86d7-11e8-85f0-6747371f42fc.png)
The ink isn't taking the accent color here but the label is.

Also when I don't select an option, I get the label with a primary color instead of the accent.
![screen shot 2018-07-13 at 8 05 11 pm](https://user-images.githubusercontent.com/3506071/42718570-16ecb1e8-86d8-11e8-8d45-ffbf081c67cb.png)

**Comment by rudzikdawid** [comment]
![](https://i.imgur.com/3K6505o.png)

`input` element behavior: changing `label` color after click (focus), so firstable we need investigate label from `md-select` element


inside rendered DOM `md-input-container` element with class `md-accent` we have `label` element witch have accent color `rgb(255,64,129)` so theme engine affect on `label` element
```
<label for="select_5" class="md-placeholder">Favorite Color</label>
```
but... what we see as label of `md-select` is not that `label` element. 
Blue label comes from element:
```
<md-select-value>
   <span>Favorite Color</span>
   ...
</md-select-value>
```
and yes that element has color: `rgb(63,81,181)` and `md-accent` class from `md-input-container` doesnt affect on that color.
