### ISSUE TITLE
button: themed buttons showing primary color when hovered instead of theme color

### ISSUE THREAD

**Issue by jex310** [angular/material#9601]
**Actual Behavior**:
-  `What is the issue? *`
  themed buttons not working properly when hovered
-  `What is the expected behavior?`
  I think it should still use the defaulted themed colour

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:`
  http://codepen.io/jex310/pen/YGqwGE
-  `Details:`
  Checkout on the green button(this is themed) and try to hover on it. Notice that it goes back to default colour not the themed colour

**Angular Versions**: *
-  `Angular Version:` 
  1.5.8
-  `Angular Material Version:`
  1.1.1

**Additional Information**:
-  `Browser Type: *`
  Chrome
-  `Browser Version: *`
  53.0.2785.113
-  `OS: *`
  windows 10
-  `Stack Traces:`

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by jex310** [comment]
And I think these three css rules should have the same colour.
![image](https://cloud.githubusercontent.com/assets/12663043/18518133/c7d31d8c-7a6c-11e6-93fa-206aee0e3cf7.png)

**Comment by Soren234** [comment]
Without knowing if this is intentional, but using $mdThemingProvider.extendPalette()  you are extending the existing color palet, and thereby still using default colors. I guess you should register a new theme or override the default theme by something like this:

http://codepen.io/soren234/pen/zKBvbV?editors=1010

**Comment by Soren234** [comment]
@jex310 i see your point. This might be related to the dynamic theme integration, which i think is still a work-in-progress. As of the state now, i think the issue is the color palet and the creation of themes, that has been changed, and this might be fixed when the dynamic theme integration is finished. 

Anyway this is all speculation from my part. :)

**Comment by Splaktar** [comment]
It's using the color from the palette that you defined as mentioned above. For primary, raised buttons that are hovered the theme uses the `600` color which you didn't override.

Adding something like `'600': '#43a047',` solves this as [demonstrated here](https://codepen.io/Splaktar/pen/LBVMrK?editors=1010).
