### ISSUE TITLE
Pagination on tabs should not appear

### ISSUE THREAD

**Issue by cadilhac** [angular/material#9644]
I use ui-router. When I load a page that shows the tab component with only 2 tabs (and they have much space) the pagination does not appear since it's not needed. I can navigate to another router state (that hides the DOM tree where the tabs are) and come back and all is fine. But strangely, when I load my page on another state that does not show the tabs and go to the state containing the tabs (the same 2 tabs that have enough space), pagination is displayed although, again, it's not needed (it's disabled on both sides). As soon as I resize the browser, they disappear. I though this was a sign a $scope.$apply would be needed because of an event external to angular, but I have no such events. So, I'm clueless.

Difficult for me to take time to reproduce because in the middle of a contract but wanted to mention it in case an obvious idea comes to the mind of someone. I'm using 1.1.1.

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'deprecated' category. We deprecate issues for one or more of the following reasons:

*  Issue has a reasonable workaround
*  Issue doesn't have a demo or reproducible case available
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests are welcomed to resolve this issue. But note that **not** all community PRs will be merged into master. Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
