### ISSUE TITLE
Center aligned tabs are getting into 2 rows and second row is not showing

### ISSUE THREAD

**Issue by mohammadrafigh** [angular/material#9660]
**Actual Behavior**:
 -  `What is the issue? *` sometimes (specially on small screens) center aligned tabs are getting into 2 rows and the second row is hidden as md-tab-item parent has set to overflow: hidden. I don't know the regeneration process as it's randomly appears. but the problem may be related to calculating each md-tab-item size (adding 1px to the width of the parent of md-tab-item resolves the issue).

for now overwriting float: left with float: none and adding a top: 12px for screens smaller than 422px for md-tab-item resolved this issue for me.
if it's important I have 3 tabs.

**Angular Versions**: *
 -  `Angular Version:` 1.3.20
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome, Android WebView
 -  `Browser Version: *` Chrome 52.0.2743.98
 -  `OS: *` tested both on desktop and Android

----

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'deprecated' category. We deprecate issues for one or more of the following reasons:

*  Issue has a reasonable workaround
*  Issue doesn't have a demo or reproducible case available
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests are welcomed to resolve this issue. But note that **not** all community PRs will be merged into master. Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
