### ISSUE TITLE
Tabs not resized and dummy tabs

### ISSUE THREAD

**Issue by cadilhac** [angular/material#9684]
I wanted to demonstrate in a codepen a very tricky problem that I have with tabs.
In my app, tabs are inside a sliding panel that appears from the left (with a CSS transition on width). The tab labels are truncated and keep the same truncated width during all the animation. They display fine as soon as I resize the browser window. So I tried to replicate this in a codepen but without success. In this case tab labels are always fine during and after the expanding of the tabs container.
I checked the DOM generated by Angular Material in chrome for both and the only diff I see is that a style has been applied to md-tab-item: "max-width:3px;". Of course, if I uncheck it the labels expand and display correctly.

I'm sorry not to be able to replicate this. Any idea?
Using 1.1.1.

PS: sorry, the title is incorrect. It has nothing to do with dummy tabs (at first I thought it was incorrect in my app). The title should say: "Tabs incorrectly sized when tabs container expands with a css transition" or something like this in better english.

**Comment by cadilhac** [comment]
Note that with 1.0.0 the behaviour is different. It's almost correct. During the animation, tabs are first truncated, then the first one gets some ellipsis and the second one (shorter word) is correct.
Ellipsis is removed and tab labels appear correct as soon as I resize the browser window (by 1px).

**Comment by ViDaNgEr** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'deprecated' category. We deprecate issues for one or more of the following reasons:

*  Issue was filed a long time ago
*  Issue has a reasonable workaround
*  Issue doesn't have a repro case available
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests are welcomed to resolve this issue. But note that **not** all community PRs will be merged into master. Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
