### ISSUE TITLE
fixed body when open md-select!?

### ISSUE THREAD

**Issue by smahdi** [angular/material#9699]
Hi,
How to set disableParentScroll in md-select?
I don`t want disable Scroll in body!

**Comment by smahdi** [comment]
![issu](https://cloud.githubusercontent.com/assets/12386385/19014138/b9be5e2c-87f1-11e6-91cc-136d76bc2205.png

please

**Comment by mvanderlinde** [comment]
I'll give this a +1, but will also add some context of my own:

I have a fixed-position sidebar that stays in view as a user scrolls. As soon as an `<md-menu>` is clicked (or `<md-select>`, as noted by @smahdi ), however, because the `<body>` tag is set to a fixed position, it breaks the positioning of all other fixed-position elements on the page (including my sidebar).

If the reasoning for fixing the `<body>` position on open is to prevent scroll, I would strongly encourage using a different approach (hidden overflow, for example), as to not break other parts of the layout that rely on fixed positioning.

**Comment by jbdemonte** [comment]
+1

**Comment by ycy233** [comment]
+1
I found this problem, too.
I have my md-select in the right-top conner of the page, and the page has a horizontal scroll bar.
When I open the md-select, the page will scroll to the most left side because of the fixed body position.
How can I make the body do not have a fixed position when open md-select?

**Comment by mvanderlinde** [comment]
@smahdi: I'm curious why you closed this issue; has Angular Material released a fix? If not, could you re-open the issue, as there are a number of us who have also experienced this?

**Comment by imashishks** [comment]
Did anyone found a solution for this?

**Comment by SOftEngrAtta** [comment]
i am getting this issue , my paretn div position is fixed and i am using md-select inside the parent div . when i click on md-slect the select options will open on top of the page why ?

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue and sorry for the delay in responding. However it does not follow our required issue template. We need a CodePen demo to be able to debug and fix the issue.

There are also a number of other duplicate issues that are filed that have more complete information and a demo. So I'm going to close this one and work on a fix in one of those other issues.
