### ISSUE TITLE
md-tab ng-click or md-on-select called before md-tab transition is finished which causes freezing

### ISSUE THREAD

**Issue by twizzzlers** [angular/material#9713]
**Actual Behavior**:
 -  `What is the issue?` <br/>
The ng-click or md-on-select on md-tab is executed before md-tab transition is finished which causes freezing
 -  `What is the expected behavior?` <br/> The tab finishes its transition and then the ng-click function starts

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue: ` https://jsfiddle.net/twizzlers/vvstgg4g/4/
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version: 1.5.5`
 -  `Angular Material Version: 1.1.1`

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: Latest`
 -  `OS: Ubuntu 14.04`
 -  `Stack Traces:`

----

**Comment by topherfangio** [comment]
I'm having a bit of trouble trying to figure out exactly what your issue is. `ng-click` and `md-on-select` both fire immediately and this is to be expected.

If you need to wait until after the transition finishes, then you can use

```js
$timeout(function() {
  // This will run after the transition which takes 500ms
}, 500);
```

That said, it also looks like you're using `md-dynamic-height` and also dynamically changing the tab's content. This won't really work with `md-dynamic-height` as it assumes the content is rendered before the animation begins.

Perhaps you can provide a bit more information on what exactly you are trying to accomplish?

**Comment by ThomasBurleson** [comment]
Closing. Will reopen based on additional information that indicates ngM1 has a specific bug.
