### ISSUE TITLE
Datepicker Component has incorrect validation (allows 31 days for any month)

### ISSUE THREAD

**Issue by velesin** [angular/material#9714]
**Actual Behavior**:
 -  `What is the issue? *` Datepicker allows 31 days for any month when you enter date string manually, directly in the input field. E.g. you can type 31 Feb and the calendar widget will then show 2 Mar (while the text in the input field still shows 31 Feb). When you type 32 Feb, the Datepicker correctly marks the field as invalid (red border etc.)
 -  `What is the expected behavior?` Validation should consider if the date is really correct, not only match simple pattern month=1-12, day=1-31.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` can be observed on your official demos page https://material.angularjs.org/latest/demo/datepicker (manually type 02/31/2016 into any of datepickers and see what happens)
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` in our project 1.5.5, don't know the version on your demos site...
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 53.0.2785.116
 -  `OS: *` Windows 7
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
The issue here is that the `Date` constructor accepts anything for the "day" field, e.g. you can do `new Date(2016, 0, 100)` and it'll give you a date in April. I'll see how we can fix it in the default validator, before passing it on to the constructor.

**Comment by crisbeto** [comment]
After looking into it, it seems like browsers don't have a decent way of validating this. I'd prefer not to try and parse the dates within Material manually, because the default validation is intended to be pretty basic and any default parsing will break as soon as somebody provides custom formatting.

That being said, you can still fix it easily on your end. You can either:

1) Do the validation yourself by [supplying a custom `formatDate` function to the `$mdDateLocaleProvider`](https://material.angularjs.org/latest/api/service/$mdDateLocaleProvider). Here's an example:

```js
angular.module('yourModule').config(['$mdDateLocaleProvider', function($mdDateLocaleProvider) {
  $mdDateLocaleProvider.parseDate = function(dateString) {
    return /* do your custom parsing here and return a Date object */;
  }
}]);
```

2) Use some existing validation. [You can see examples in our documentation](https://material.angularjs.org/latest/api/service/$mdDateLocaleProvider) on how to do it with moment.js.

Let me know if you need any help with implementing these.

**Comment by velesin** [comment]
Wow, an awesome explanation! Thanks!
