### ISSUE TITLE
Add close and open events in sidenav

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#974]
I was trying to bind a button with indication of the sidenav state..

would be easy if you broadcast an event.

this is my temporary solution:

``` javascript
angular.module('myApp')
  .controller('ToolBarCtrl', function ($scope, $mdSidenav, $mdComponentRegistry) {
    $scope.isNavIconOpened = false;

    $scope.$watch(function(){
      return $mdComponentRegistry.get('rightNav') ? $mdSidenav('rightNav').isOpen() : false;
    }, function(newVal){
      $scope.isNavIconOpened = newVal;
    });

    $scope.toggleMenu = function() {
      $scope.isNavIconOpened = !$mdSidenav('rightNav').isOpen();

      if($scope.isNavIconOpened) {
        $mdSidenav('rightNav').open();
      }
      else{
        $mdSidenav('rightNav').close();
      }

    };
  });
```

**Comment by nkoterba** [comment]
I'm a little confused how the suggested solution above solves the original issue.  How does binding a scope-based function notify me when the md-sidenav is closed by the user clicking somewhere else in the UI?

Seems like md-sidenav should have an `md-on-open` and an `md-on-close` event/directive attribute.

Otherwise, I have to setup a `$watch` inside my controller and if I'm doing that, I might as well just watch `$mdSideNav('mySideNav').isOpen()`.

Am I missing something obvious here?

**Comment by jvmccarthy** [comment]
I agree with @nkoterba.  I would rather listen for an event instead of adding a watch.  Any chance in opening this issue again?  (In my case, I want to reset a sidenav after it's closed.)

**Comment by chris-carrington** [comment]
Tackled this with event emiters and a custom service ```$glSidenav``` to silo all communication to ```$mdSidenav```. Below is an example of how I can open a sidenav from a controller, and then call an api once the sidenav is opened.



Directive HTML:
```<md-sidenav md-component-id="filters" class="md-sidenav-right">

</md-sidenav>```



Controller:
```$scope.launchFilterSidenav = function()
{
  $glSidenav.toggle('filters');
};```



Service:
```angular.module('app.service.sidenav', [])



.service('$glSidenav', ['$rootScope', '$mdSidenav',

function($rootScope, $mdSidenav)
{
  return {
    

    toggle: function(id)
    {
      var self = this;

      if($mdSidenav(id).isOpen())
      {
        return self.close();
      }
      else
      {
        return $mdSidenav(id).open().then(function()
        {
          $rootScope.$broadcast('sidenav-open-' + id);
          $('html, body').css('overflowY', 'hidden'); 
          $('.md-sidenav-backdrop').off('click');
        });
      }
    }, 


    close: function(id)
    {
      return $mdSidenav(id).close().then(function()
      {
        $rootScope.$broadcast('sidenav-closed-' + id);
        $('html, body').css('overflowY', 'auto'); 
      });
    }
    
  };
}]);```



Directive JS:
```$scope.$on('sidenav-open-filters', function()
{
  $scope.model.getFilters();
});```

**Comment by chris-carrington** [comment]
Tackled this with event emiters and a custom service ```$glSidenav``` to silo all communication to ```$mdSidenav```. Below is an example of how I can open a sidenav from a controller, and then call an api once the sidenav is opened.



Directive HTML:
```
<md-sidenav md-component-id="filters" class="md-sidenav-right">

</md-sidenav>
```



Controller:
```
$scope.launchFilterSidenav = function()
{
  $glSidenav.toggle('filters');
};
```



Service:
```
angular.module('app.service.sidenav', [])



.service('$glSidenav', ['$rootScope', '$mdSidenav',

function($rootScope, $mdSidenav)
{
  return {
    

    toggle: function(id)
    {
      var self = this;

      if($mdSidenav(id).isOpen())
      {
        return self.close();
      }
      else
      {
        return $mdSidenav(id).open().then(function()
        {
          $rootScope.$broadcast('sidenav-open-' + id);
          $('html, body').css('overflowY', 'hidden'); 
          $('.md-sidenav-backdrop').off('click');
        });
      }
    }, 


    close: function(id)
    {
      return $mdSidenav(id).close().then(function()
      {
        $rootScope.$broadcast('sidenav-closed-' + id);
        $('html, body').css('overflowY', 'auto'); 
      });
    }
    
  };
}]);
```



Directive JS:
```
$scope.$on('sidenav-open-filters', function()
{
  $scope.model.getFilters();
});
```

**Comment by LeoLozes** [comment]
I'm really struggling to find a way of capturing when a sidenav is toggled, opened and closed. Is there really no other way than doing an intermediate service like @chris-carrington ? 

I don't understand why this doesn't fire every time a sidenav is closed ...
```
$mdSidenav(componentId)
   .close()
   .then(function(){
     $log.debug('closed');
   });
```

**Comment by dalelarsen** [comment]
I don't understand why this issue was closed. There is still poor/no support for knowing the state of the sidenav. Also, the API docs are oddly empty for the $mdSidenav service...  there is a usage example and nothing else: https://material.angularjs.org/latest/api/service/$mdSidenav

I have tried watching:

`$mdSidenav('left', true).then(function () { 
   $scope.$watch(function () {
         return $mdSidenav('left').isOpen();
   }, function (_leftOpen) {
         $scope.isOpenLeft = _leftOpen;
   });
});`

I've also tried assigning this to a `$scope` variable in 2 ways.

`$scope.isOpenLeft = $mdSidenav('left').isOpen();`

`$scope.isOpenLeft = function(){return $mdSidenav('left').isOpen();}`

Nothing works.

I have mine locked open for gt-xs. So it's closed on small screens. I simply want to know if it's closed so I can show a toggle button only when it's closed... which is really basic behavior.
