### ISSUE TITLE
virtual-repeat: horizontal does not work with RTL

### ISSUE THREAD

**Issue by david-gang** [angular/material#9754]
**Actual Behavior**:
-  `What is the issue? *`
  The viewport does not get updated when scrolled. We get blank entries
-  `What is the expected behavior?`
  The scrolled elements should show up in the viewport

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:`
  http://codepen.io/david-gang/pen/vXpGXA
-  `Details:`
  Just add the tag dir="rtl"

**Angular Versions**: *
-  `Angular Version:` 1.5.5
-  `Angular Material Version:` 1.1.1

**Additional Information**:
-  `Browser Type: *` firefox
-  `Browser Version: *` 47.0.1
-  `OS: *`
-  `Stack Traces:`
## This also happens in ie11

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by marosoft** [comment]
I found the main reason why this is happening. It is caused by the way the RTL mode is being detected.

This is a piece of code:
`var ltr = document.dir != 'rtl' && document.body.dir != 'rtl';`

(from https://github.com/angular/material/blob/master/src/components/virtualRepeat/virtual-repeater.js#L381)

As you can see it expects the whole document to be RTL not only the element you want to test.

When you inspect the bottom part of the CodePen (the one showing you the demo) and add dir="rtl" into the `body` or `html` of that iframe, it will start behaving properly:

`<body dir="rtl">`
or
`<html dir="rtl">`

The question is, can this be totally normal to have just an element within the web page as RTL but the rest being LTR? I am not sure how common it is. If that is quite possible, the RTL check in the mdUtil should be changed then or a different way of detecting the RTL should be implemented.

Related issue (detecting RTL):
https://github.com/angular/material/issues/11016#issuecomment-400248656

**Comment by Splaktar** [comment]
[Updated CodePen](https://codepen.io/Splaktar/pen/ZRNOYw) that shows the right way to do this atm since we only support applying `dir="rtl"` to the `html` or `body` elements.

Please see [my comments](https://github.com/angular/material/issues/11016#issuecomment-402551370) to discuss how you would like to move forward on this issue.

**Comment by marosoft** [comment]
@Splaktar As mentioned in issue #11016, I did some work on RTL issues.
It is not perfect. In some cases you need to add a `dir` attribute on the parent tag too.

Please see the [CodePen](https://codepen.io/marosoft/pen/LBqbVO) and you can see my commit above too.
I can create a PR if this is fine with you.

**Comment by Splaktar** [comment]
That would be great! Please open the PR 😄
