### ISSUE TITLE
Issue with md-menu and absolute positioning + z-index

### ISSUE THREAD

**Issue by sebakerckhof** [angular/material#9767]
**Actual Behavior**:
 -  `What is the issue? *`
Having an md-menu inside an element that is absolute positioned and has a high z-index makes it so that the menu trigger appears above the menu.

 -  `What is the expected behavior?`
md-menu should follow html rules of inheriting z-indexes so that the menu appears above the trigger

**CodePen** (or steps to reproduce the issue): *
http://codepen.io/sebakerckhof/pen/dpJxzr (click on the menu)

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 53.0.2785.143 (64-bit)
 -  `OS: *` Ubuntu 16.04

**Comment by gvillenave** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'deprecated' category. We deprecate issues for one or more of the following reasons:

*  Issue has a reasonable workaround
*  Issue doesn't have a demo or reproducible case available
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  **Issue is real, but only affects a very small use case**
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests are welcomed to resolve this issue. But note that **not** all community PRs will be merged into master. Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
