### ISSUE TITLE
Form Layout Issues

### ISSUE THREAD

**Issue by mattpawson** [angular/material#9798]
**Actual Behavior**:
 -  `What is the issue? 

When attempting to build a form that utilises a number of different components the layout doesn't appear to render correctly.

The datepicker doesn't fill the whole of the row in the same manner as select and text boxes do, while the autocomplete's height is larger than that normal textbox / select box.

 -  `What is the expected behavior?`

I expected all the input elements to be of equal width / height when building the form.

**CodePen** (or steps to reproduce the issue): *
http://codepen.io/mattpawson/pen/ALybpq/

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Version: *` Firefox 49.0.1, Chrome: 53.0.2785
 -  `OS: *` Windows 10

**Comment by crisbeto** [comment]
The datepicker isn't meant to stretch the full width, because it changes the background on the input, in order to make the calendar masking work. That being said, if you know that your form won't stretch too much, you can get it working by adding the following to your CSS (note that I haven't included any vendor prefixes):

```css
md-datepicker {
    display: flex;
    align-items: center;
}

.md-datepicker-input-container {
    flex: 1;
}
```

[Here's a forked codepen.](http://codepen.io/crisbeto/pen/rrdROO) Also it seems like the arrow isn't quite aligned, I'll try to fix that one.

**Comment by mattpawson** [comment]
Thanks for your response. I like the calendar icon, it gives the user a good indicator of the type of input, so I'll probably aim to leave it there. I did manage to achieve something similar, but it wasn't as elegant as yours:

	.md-datepicker-input-container {
	  width: calc(100% - 64px);
	  margin-left: 0px;
	}

Any news on the autocomplete's, and why their height is so much taller than the other elements?

**Comment by crisbeto** [comment]
I'm not too sure about the autocomplete since I'm not responsible for it, but @DevVersion should know more about it.

**Comment by crisbeto** [comment]
I'll close the issue for now, but we can continue the discussion.
