### ISSUE TITLE
Export Theming logic

### ISSUE THREAD

**Issue by Sandreu** [angular/material#980]
Hello,

I used to be angular, but I'm starting playing with react. I like it and I would like to use angular-material markup to build a [react version of angular-material](https://github.com/Sandreu/react-angular-material).

I just met the new ThemeProvider... This is much nicer than the previous theme handling. 

But I ask myself how to extract the theme building logic from the angular module to be able to do a gulp task and/or a react mixin using the same code... I can do pull request, but I just want to be agree on how to do that.

What do you think about it ?

**Comment by sscovil** [comment]
I would love to see the theming logic in a separate package as well, as a node module that can be run in a grunt/gulp task. I'll take a swing at it and share my progress here.

**Comment by sscovil** [comment]
I've been giving this some thought, and wanted to share my observations and ideas in case anyone else is interested...

## Problem

Right now, theme-specific CSS is generated at runtime and added to the `<head>` section of the application in several `<style>` tags. This is fine for themes that are created on the fly by the end user, but is not ideal for themes that ship with the application and could be served as static CSS files.

## Observations

Looking at the underlying code, here is how the theme generation currently works:

1. During the Angular Material build process, the [themeBuildStream](https://github.com/angular/material/blob/f60b5e5a7713af9058f9a29966f6e324cae901b9/gulp/util.js#L187) function compiles all `*-theme.scss` files from components into a single CSS string that is injected into the `material.core` module as a constant called `$MD_THEME_CSS`.

1. The module `angular.core` appears to only consist of the `$MD_THEME_CSS` constant definition. (See the end of the [unminified angular-material.js](https://cdnjs.cloudflare.com/ajax/libs/angular-material/0.10.1/angular-material.js) file.)

1. In [theming.js](https://github.com/angular/material/blob/master/src/core/services/theming/theming.js#L450) there is a function called `generateThemes` that utilizes `$MD_THEME_CSS` to generate the `<style>` tags that get added to the `<head>` section at runtime.

1. For each of the four (4) palettes in each registered theme (including the default theme), there are four (4) `<style>` tags added to the `<head>` section (e.g. `.md-primary`, `.md-primary.md-hue-1`, `.md-primary.md-hue-2`, `.md-primary.md-hue-3`). That means each registered theme results in 16 `<style>` tags being generated and added to the `<head>` section at runtime.

1. In [theming.js](https://github.com/angular/material/blob/master/src/core/services/theming/theming.js#L53), a closure variable called `GENERATED` is used to keep track of the themes that have had their CSS added to the `<head>` section.

## Requirements

1. If one were able to pre-compile theme CSS, they would also need to be able to notify `ngMaterial` so it does not attempt to generate CSS for the themes that already have it. This would require a new service, or a new method in an existing service (`$mdThemingProvider` seems like a good candidate) where developers can register theme CSS as generated.

1. The `generateThemes` function would need to check for any themes that have been registered as CSS-generated. It [already checks](https://github.com/angular/material/blob/master/src/core/services/theming/theming.js#L506) a `GENERATED` closure variable, so that variable should probably be moved into a service (see above).

1. The `$MD_THEME_CSS` string should be exported to a file that can be `require`d in a Node.js app like gulp. Same goes for the `generateThemes` function. If something like [Browserify](http://browserify.org/) were used in the Angular Material build process, this would be pretty easy to accomplish.

Does anyone else have any thoughts? Hopefully this can spark a discussion that will result in an improved theming system.

**Comment by ThomasBurleson** [comment]
@sscovil - Perhaps you would like to blend these notes above into our [Configuring a Theme](https://github.com/angular/material/blob/master/docs/content/Theming/03_configuring_a_theme.md) document?  Your Pull Request would be welcomed.

**Comment by sscovil** [comment]
@ThomasBurleson I'd be happy to. Will take a look at it tonight.

**Comment by sscovil** [comment]
@ThomasBurleson there you go. Let me know if I can be of any further assistance.

**Comment by ThomasBurleson** [comment]
@rschmukler - can you review the https://github.com/angular/material/pull/4448 and merge if ok?

**Comment by rschmukler** [comment]
Reviewed #4448 - moving this into a post-1.0 effort / consideration for 2.0

**Comment by pames** [comment]
One other issue related to injecting <style> tags - this hinders an application's ability to use Content Security Policy (e.g. those that use ng-csp).  This requires adding 'unsafe-inline' to the style-src directive, which isn't particularly ideal.

**Comment by stu-co** [comment]
I'm wondering if there has been any update to this?

I do not wish to use inject style tags due to security concerns as detailed on [this stack overflow post.](https://stackoverflow.com/a/18428346)

**Comment by Splaktar** [comment]
@stu-co as you found and as mentioned in https://github.com/angular/material/issues/7959#issuecomment-400220734, you can use `$mdThemingProvider.disableTheming()` which is documented [here](https://material.angularjs.org/latest/api/service/$mdThemingProvider#mdthemingprovider-disabletheming-isdisabled).
