### ISSUE TITLE
update(css): update ngM1 CSS to avoid conflicts with ngM2 stylesheets

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#9824]
Teams migrating ngM1 applications to ng2 + ngM2 may experience css style collisions when both ngM1 + ngM2 stylesheets are loaded.
### ngM2 CSS Changes

Styles will be updated to support concepts/approaches described in  [BEM - Block Element Modifiers](http://getbem.com/naming/).
- In material2, change all our css classes to be prefixed either as `md--` or `md-card--`
- stop using **element selectors** in material2, and always use classes
-  add a css class called `md2` to each material1 component (elements only)
### ngM1 CSS Changes
- Change any ngM1 styles that use an **element selector**  to also have `:not(.md2)`
-  These changes are needed in both ngMaterial 1.0.9 and 1.1.x 

> Using `:not` doesn't increase specificity when the given expression doesn't match anything. So that shouldn't break any existing consumption based on specificity. This will prevent material1 css from affecting anything in material2, and then we can both use the `md-` prefix for elements.

**Comment by mckenzielong** [comment]
@ThomasBurleson will this be hidden behind a build option? do you know if the `:not()` pseudo class will noticeably hurt performance (looking at you ie11...)

**Comment by clshortfuse** [comment]
Alternatively, instead of using an opt-out pseudo class (`:not(.md2)`) we can use an opt-in class (`.md1`).

One caveat is that the element needs to have an `md1` class add to it. If an element has a directive, it's easy. If it doesn't, we may inject the class if we use it in the template. If neither of these apply, we would have to create a directive just for that element. 

If the number of directives we need to create is small (or none), it may be more efficient to use an opt-in approach. 

Also, we can mix both solutions and only use `:not(.md2)` on elements that do not have directives and/or template.

Here's a partial example list of all CSS rules that need to be modified and if they have a directive or template

| Component | Selector | Directive or Template |
| :-: |:-:| :-: |
| autocomplete.scss | md-autocomplete | Directive |
| autocomplete.scss | md-input-container | Directive |
| autocomplete.scss | md-autocomplete-wrap | Template |
| autocomplete.scss | md-progress-linear | Template |
| autocomplete.scss | md-icon | Directive |
| autocomplete-theme.scss | md-autocomplete | Directive |
| autocomplete-theme.scss | md-icon | Directive |
| backdrop.scss | md-backdrop | Directive |
| backdrop-theme.scss | md-backdrop | Directive |
| bottom-sheet.scss | md-bottom-sheet | Directive |
| bottom-sheet.scss | md-inline-icon |  |
| bottom-sheet.scss | md-list-item | Directive  |
| bottom-sheet-theme.scss | md-bottom-sheet | Directive |
| bottom-sheet-theme.scss | md-list-item | Directive |

**Comment by ThomasBurleson** [comment]
Closed as Material2 has identified an alternate solution.
