### ISSUE TITLE
md-nav-bar stretch

### ISSUE THREAD

**Issue by Jeevanaawara** [angular/material#9828]
-  `how to stretch md-nav-bar? *`
 -  `just like stretch md-tabs by adding attribute md-stretch-tabs?`

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'deprecated' category. We deprecate issues for one or more of the following reasons:

*  Issue was filed a long time ago
*  Issue has a reasonable workaround
*  Issue doesn't have a repro case available
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests are welcomed to resolve this issue. But note that **not** all community PRs will be merged into master. Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].

**Comment by shamilus** [comment]
Is this issue  has a reasonable workaround?

**Comment by dremie** [comment]
My workaround: 
```
<md-nav-bar md-selected-nav-item="$ctrl.selectedTabName" 
              nav-bar-aria-label="tab links" >
    
    <div flex layout="row" layout-align="space-around center">
      <md-nav-item  ng-repeat="tab in $ctrl.tabs"
                    md-nav-sref="{{tab.sref}}" 
                    name="{{tab.name}}" aria-label="{{tab.name}}">
        {{tab.name}}
      </md-nav-item>
    </div>
  </md-nav-bar>
```
