### ISSUE TITLE
long tooltips are repeatedly displayed/hidden on Firefox

### ISSUE THREAD

**Issue by fcrwx** [angular/material#9832]
**Actual Behavior**:
With Firefox, when specifying left or right direction for tooltips with a large amount of text, the tooltip is repeatedly displayed and hidden.
The tooltip should be displayed on hover and should remain displayed until navigating away.

**CodePen**:
http://codepen.io/fcrwx/pen/GjBgRP
Using Firefox, hover over the first icon to see the left tooltip flash repeatedly. Hover over the second icon to see the bottom tooltip behave correctly.

**Angular Versions**:
 Angular Version: 1.5.8
 Angular Material Version: 1.1.0

**Additional Information**:
 Browser Type: Firefox
 Browser Version: 47.0.1
 OS: *
 Stack Traces: n/a

**Comment by Reddemonfox** [comment]
this is because when you create such large text then on hover tool-tip is triggered and it will show the tool-tip and that tool tip comes over the reload icon that means the mouse cursor will now hovering the tool tip(not that reload icon directly) that is why that tool-tip closes, and when it does again mouse will hover on the reload icon(as that layer of tool-tip goes from the top of that icon). 
So that is why this process keeps going on
To solve this, you just need to place tool tip in the direction where it will not cover the actual icon.

**Comment by ThomasBurleson** [comment]
Fixed with ^.
