### ISSUE TITLE
Menu / Sub Menu navigation with Left/Right keys doesn't take into account Right-to-Left mode

### ISSUE THREAD

**Issue by ChrisNightingale** [angular/material#9859]
Hi everybody,

Been using the md-menu directives in both Left-to-Right (ltr) and Right-to-Left (rtl) modes and they work fine visually except when trying to navigate using the left / right arrows keys.  The right arrow key is used to open a sub menu and the left key used to close a sub menu and return to the parent menu.

But this doesn't get reversed when running in rtl, you still need to use the right arrow key to open a sub menu and the left arrow key to close it where I think this should be reversed in rtl mode.  I did a quick check of Windows running in rtl mode and it does reverse the keys.  So I assume this is just something that has been overlooked in Angular Material Design's implementation of the menu navigation.

Looking at the keyboard handling code in the source code ("activateInteraction" method of the MenuProvider) it doesn't appear to have any switch based on ltr / rtl mode.

**Angular Versions**: *
 -  Angular Version: 1.5.8
 -  Angular Material Version: 1.1.1

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'deprecated' category. We deprecate issues for one or more of the following reasons:

*  Issue has a reasonable workaround
*  Issue doesn't have a demo or reproducible case available
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  **Issue is real, but only affects a very small use case**
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests are welcomed to resolve this issue. But note that **not** all community PRs will be merged into master. Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].

**Comment by ChrisNightingale** [comment]
Hi Thomas

Thanks for the response and verifying the situation
