### ISSUE TITLE
progressCircular: spinner is too slow relative to spec

### ISSUE THREAD

**Issue by naomiblack** [angular/material#9879]
feedback from the core design team -- ProgressCircular is about 3x too slow.

have shared a better example with @ThomasBurleson. Can we get this updated?

See https://material.angularjs.org/latest/demo/progressCircular

**Comment by ThomasBurleson** [comment]
@clshortfuse  - see attached SVG/HTML samples for speed, etc.

[export.zip](https://github.com/angular/material/files/543180/export.zip)

> This is for comparison only... not for re-implementation of the ngM1 spinners.

**Comment by crisbeto** [comment]
FYI the animation can be tweaked from here https://github.com/angular/material/blob/master/src/components/progressCircular/js/progressCircularProvider.js#L49

**Comment by clshortfuse** [comment]
It seems that the current implementation is incomplete. Just accelerating the animation might not be enough. 

I see the animation having two cycles that I call `extend` and `contract`. The `extend` cycle pushes the "head" clockwise and extends at a faster rate. The `contract` cycle shortens the "tail" clockwise at a faster rate.

Our animation only has the the `contract` cycle and is completely missing the `extend` cycle. This is why is appears "slower" than spec.

**Comment by crisbeto** [comment]
Tweaking the animation so it accelerates in one phase should be pretty simple, we can either:

* Pass in a different duration - may end up causing overlapping animations.
* Pass in a different easing function that accelerates at a different rate.

We can pair up on this, if you need help @clshortfuse

**Comment by clshortfuse** [comment]
@crisbeto The problem is not the duration, but our current actual animation logic is too simplified. There are 4 pieces of logic that should be done in other to match spec 100%.

1. Increase the distance from ~0% to 75% using an ease-in function.
2. Decrease the distance from 75% to ~0% from the opposite end, using an then ease-out function
3. Rotate the object 90 degrees clockwise and start again. 

** Repeat 3 more times (for a total of 4 iterations), optionally changing color each iteration ** 

4. We need to do all this, all the while the entire object rotates counter-clockwise 360 degrees each of 4 iterations. 

(My use of ~0% means it can't be as close to 0% without actually being 0)

I've done all this already with pure CSS. The only issue is *requestAnimationFrame* has to be used for compatibility with IE, but luckily we are already using this in our current implementation.  I'm not 100% sure about the easing function though.

http://codepen.io/shortfuse/pen/jVNqyV?editors=1100

**Comment by crisbeto** [comment]
What I'm trying to say is that it's not complicated to pass in a different easing function, depending on the state of the animation.
