### ISSUE TITLE
Dirty Multiple mdSelect

### ISSUE THREAD

**Issue by BAByrne** [angular/material#9884]
**Actual Behavior**:
 -  `Forms with mdSelect and the mdSelect has multiple option is set to true, angular sees the form as dirty.`
 -  `multiple flag should not effect initial form state`

**CodePen** (or steps to reproduce the issue): *
 -  `http://codepen.io/bbyrne/pen/Kgboyv?editors=1010`
 -  `Details: When page is first loaded, the state of the form is automatically set to dirty. If the select is loaded with multiple false, the state is pristine.`

**Angular Versions**: *
 -  `Angular Version: <= 1.5.x`
 -  `Angular Material Version: 1.1.1`

**Additional Information**:
 -  `Browser Type: chrome`
 -  `Browser Version: 53.x`
 -  `OS: macOS Sierra`
 -  `Stack Traces: n/a`

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'deprecated' category. We deprecate issues for one or more of the following reasons:

*  Issue has a reasonable workaround
*  Issue doesn't have a demo or reproducible case available
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  **Issue is real, but only affects a very small use case**
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests are welcomed to resolve this issue. But note that **not** all community PRs will be merged into master. Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].

**Comment by deepak342** [comment]
@BAByrne, I ran into the same issue. Can you post the workaround snippet?
