### ISSUE TITLE
Keyboard Button Interaction Bug

### ISSUE THREAD

**Issue by SimeonC** [angular/material#991]
I found an odd bug to do with the mdButton directive and keyboard interaction.

Example here: http://plnkr.co/edit/6QhhohD5fwYtIkb8GDT3?p=preview

Steps:

1. Click into input.
2. Tab to normal button.
3. Press Enter/Spacebar - count increments by 2!
4. Tab to md-button
5. Press Enter/Spacebar - count decrements by 2!
6. Comment out the angular-material.min.js script and the DI in the module definition.
7. Repeat steps 1 - 3 - count increments by 1!!!

**Comment by marcysutton** [comment]
This is still dependent on angular/angular.js#10388.

**Comment by marcysutton** [comment]
@SimeonC the fix for ngAria has been merged to Angular.js master and should go out in the 1.4 release, so I'm going to close this issue. I forked your Plunker to use angular-aria version 1.3.5 (the last version without the bug), and it appears to work fine. So I'm pretty sure the 1.4 release will solve your issue. http://plnkr.co/edit/x5T3fM6xj0JWlKXYPhdv?p=preview

**Comment by SimeonC** [comment]
Cool beans! Thanks for letting me know. :+1:
