### ISSUE TITLE
Bottom Sheet on Dialog does not remove div.md-scroll-mask after losing focus

### ISSUE THREAD

**Issue by BenjaminBatman** [angular/material#9938]
**Actual Behavior**:
-  `What is the issue? *` When a bottom sheet is opened on a dialog and the dialog is closed by clicking out side of it, the overlay div with the class "md-scroll-mask" does not get removed from the page. This causes the entire application to become unusable.

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` http://codepen.io/benjaminbatman/pen/gwJBGm
-  `Details:` First open the dialog by clicking on the button. Then click on the "Open Bottom Sheet" button inside of the dialog. Next, close the dialog by clicking outside of it. The dialog button should no longer function because there is a div left on top of it. If the bottom sheet is closed before clicking outside of the dialog the overlay div is removed correctly.

**Angular Versions**: *
-  `Angular Version:` v1.5.8
-  `Angular Material Version:` v1.1.1

**Additional Information**:
-  `Browser Type: *` Chrome
-  `Browser Version: *` 54.0.2840.71 m
-  `OS: *`  Windows 10
-  `Stack Traces:`
---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by DevVersion** [comment]
After looking at this issue it took me a while to figure out why the scopes will be not destroyed.

Since you don't specify any explicit scope for the `dialog` and `bottom-sheet` the elements can not know from each other.

| --- | --- |
| --- | --- |
| Dialog | **Isolated Scope** |
| Bottom-Sheet | **Child Scope of Root** |

To automatically close the bottom-sheet when the dialog is hiding, you need to connect those scopes

- `Root Scope` -> `Dialog Scope` -> `Bottom Sheet Scope`

```js
$mdBottomSheet.show({
  scope: $scope,
  preserveScope: true,
});
```

> http://codepen.io/DevVersion/pen/dpxyjW

Please let me know if you have any other problems.
