### ISSUE TITLE
mdDatepicker scroll up on calendar view

### ISSUE THREAD

**Issue by wizzzet** [angular/material#9956]
**Actual Behavior**: Please watch this screencast: https://drive.google.com/file/d/0Byf3Jfa0xtHeaTRhQlA3aVdfVTg/view?usp=sharing
 -  `What is the issue? *` while mouse is over current month and today is 1st day of month and future days are disabled (current day is maxDate) I try to scroll up to previous month. Datepicker firstly scrolls to next month beginning. It scrolls up to previous month only after second mouse scroll attempt. 
 -  `What is the expected behavior?` datepicker should scroll up to previous month.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/wizzzet/pen/KgOmeZ
 -  `Details:` This bug was detected today, 1st Nov 2016. Maybe this bug only works on first day of month.

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 54.0.2840.71 (64-bit)
 -  `OS: *` Ubuntu 16.04
 -  `Stack Traces:`

**Comment by mde17** [comment]
i also have this problem, anyone fixed this?

**Comment by Phr33d0m** [comment]
Hi, also having this issue prior updating to 1.1.3. With the latest 1.1.3 when I open my datepicker instead of displaying February it's showing me April so I have to scroll up to February. This happens if above the datepicker I have some kind of ng-repeat.

Please have a look at this codepen: http://codepen.io/anon/pen/LxmNjK

Scroll down and open the datepicker. Sometimes on the first try it shows correctly. Click a second, third, etc... time and it shows incorrectly another month.

**Comment by ernsheong** [comment]
Related to https://github.com/angular/material/issues/10144, still not fixed in some scenarios.

**Comment by Splaktar** [comment]
This appears to be fixed. [Updated CodePen](https://codepen.io/Splaktar/pen/YarabQ) does not show this scrolling issue after updating to 1.1.8. I believe that this was fixed in 1.1.5 though.
