### ISSUE TITLE
Question : Is it possible to add chip options to contact chip

### ISSUE THREAD

**Issue by gwenael-louandre** [angular/material#9987]
Several options of the simple chip would be fine to be implemented in the contact chip : 
md-require-match : possibility add email which is not in the address book
md-transform-chip : to check if the entered value is an email
md-max-chips : to limit the number of people

Are these options already avalaible (and I didn't understand how it works) or is this forseen in the road map?

Thanks.

**Comment by topherfangio** [comment]
There are a handful of PRs out there that add some or all of this functionality. I need to review them and see what can be added.

**Comment by Splaktar** [comment]
- Our [contact chips demo](https://material.angularjs.org/1.1.22/demo/chips#contact-chips) uses `md-require-match` now. However, it's not really practical to set it to `false` because a contact chip cannot be created just by adding some text or an email address. It needs a name, email address, and image.
- `md-max-chips` is not supported by contact chips at this time.
- `md-transform-chip` is not supported by contact chips at this time.
